# Generated by Django 5.2.1 on 2026-05-19 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0031_rename_ent_notif_evt_entity_evt_idx_entity_noti_entity__bd0b29_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstImportedReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('gst_registration_gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('return_type', models.CharField(choices=[('GSTR2B', 'GSTR-2B'), ('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B')], max_length=16)),
                ('return_period', models.CharField(db_index=True, max_length=7)),
                ('source', models.CharField(choices=[('JSON_UPLOAD', 'JSON Upload'), ('EXCEL_UPLOAD', 'Excel Upload'), ('CSV_UPLOAD', 'CSV Upload'), ('PORTAL_API', 'Portal API'), ('MANUAL_ENTRY', 'Manual Entry'), ('ADAPTER', 'Adapter')], default='MANUAL_ENTRY', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CONSUMED', 'Consumed')], db_index=True, default='UPLOADED', max_length=16)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('normalized_payload_json', models.JSONField(blank=True, default=dict)),
                ('validation_summary_json', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entity', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entityfin', to='entity.entityfinancialyear')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_imported_returns', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_SubEntity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GstReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('item_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note'), ('SECTION_BUCKET', 'Section Bucket'), ('SUMMARY_BUCKET', 'Summary Bucket')], default='INVOICE', max_length=20)),
                ('direction', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('OUTPUT', 'Output'), ('INPUT', 'Input')], default='PURCHASE', max_length=16)),
                ('match_key', models.CharField(db_index=True, max_length=255)),
                ('source_document_type', models.CharField(max_length=64)),
                ('source_document_id', models.CharField(max_length=64)),
                ('linked_document_type', models.CharField(blank=True, max_length=64, null=True)),
                ('linked_document_id', models.CharField(blank=True, max_length=64, null=True)),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('counterparty_gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('doc_type_code', models.CharField(blank=True, max_length=20, null=True)),
                ('taxable_value_books', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_books', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_books', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_books', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess_books', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_value_imported', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_imported', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_imported', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_imported', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess_imported', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('match_status', models.CharField(choices=[('NOT_CHECKED', 'Not Checked'), ('MATCHED', 'Matched'), ('PARTIAL', 'Partial'), ('MISMATCHED', 'Mismatched'), ('MISSING_IN_BOOKS', 'Missing In Books'), ('MISSING_IN_RETURN', 'Missing In Return'), ('DUPLICATE', 'Duplicate'), ('IGNORED', 'Ignored'), ('MANUALLY_RESOLVED', 'Manually Resolved')], db_index=True, default='NOT_CHECKED', max_length=24)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('mismatch_summary', models.JSONField(blank=True, default=list)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entity', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entityfin', to='entity.entityfinancialyear')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_items_resolved', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_SubEntity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GstMismatchReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=16)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatch_reasons', to='gst_reconciliation.gstreconciliationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GstReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('gst_registration_gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('reconciliation_type', models.CharField(choices=[('GSTR2B_PURCHASE', 'GSTR-2B vs Purchase Register'), ('GSTR1_SALES', 'GSTR-1 vs Sales Register'), ('GSTR3B_BOOKS', 'GSTR-3B vs Books')], db_index=True, max_length=32)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=16)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('return_period', models.CharField(db_index=True, max_length=7)),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('source_mode', models.CharField(choices=[('BOOKS_VS_IMPORTED', 'Books vs Imported'), ('BOOKS_ONLY', 'Books Only'), ('IMPORTED_ONLY', 'Imported Only')], default='BOOKS_VS_IMPORTED', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IMPORTED', 'Imported'), ('MATCHING', 'Matching'), ('READY_FOR_REVIEW', 'Ready For Review'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=24)),
                ('match_strategy_code', models.CharField(default='default', max_length=64)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('close_comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_runs_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entity', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entityfin', to='entity.entityfinancialyear')),
                ('imported_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to='gst_reconciliation.gstimportedreturn')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_runs_reviewed', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_SubEntity', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_runs_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gst_reconciliation.gstreconciliationrun'),
        ),
        migrations.CreateModel(
            name='GstReconciliationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('IMPORTED', 'Imported'), ('MATCH_STARTED', 'Match Started'), ('MATCH_COMPLETED', 'Match Completed'), ('SUBMITTED', 'Submitted'), ('REVIEW_STARTED', 'Review Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('ITEM_RESOLVED', 'Item Resolved'), ('NOTE', 'Note')], db_index=True, max_length=24)),
                ('from_status', models.CharField(blank=True, max_length=24, null=True)),
                ('to_status', models.CharField(blank=True, max_length=24, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_reconciliation_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entity', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entityfin', to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_SubEntity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='gst_reconciliation.gstreconciliationitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='gst_reconciliation.gstreconciliationrun')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='gstimportedreturn',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_gstimportedreturn_scope'),
        ),
        migrations.AddIndex(
            model_name='gstimportedreturn',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'return_type', 'return_period'], name='ix_gst_imp_scope_type_period'),
        ),
        migrations.AddIndex(
            model_name='gstimportedreturn',
            index=models.Index(fields=['gst_registration_gstin', 'return_type', 'return_period'], name='ix_gst_imp_gstin_type_period'),
        ),
        migrations.AddIndex(
            model_name='gstimportedreturn',
            index=models.Index(fields=['status', 'return_type', 'return_period'], name='ix_gst_imp_status_type_period'),
        ),
        migrations.AddConstraint(
            model_name='gstimportedreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference__isnull', False)), fields=('entity', 'entityfinid', 'subentity', 'return_type', 'return_period', 'source', 'source_reference'), name='uq_gst_imp_scope_type_period_source_ref'),
        ),
        migrations.AddIndex(
            model_name='gstmismatchreason',
            index=models.Index(fields=['item', 'severity'], name='ix_gst_reason_item_severity'),
        ),
        migrations.AddIndex(
            model_name='gstmismatchreason',
            index=models.Index(fields=['code', 'severity'], name='ix_gst_reason_code_severity'),
        ),
        migrations.AddConstraint(
            model_name='gstmismatchreason',
            constraint=models.UniqueConstraint(fields=('item', 'code'), name='uq_gst_reason_item_code'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationrun',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_gstreconciliationrun_scope'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationrun',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'reconciliation_type', 'return_period'], name='ix_gst_run_scope_type_period'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationrun',
            index=models.Index(fields=['status', 'reconciliation_type', 'return_period'], name='ix_gst_run_status_type_period'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationrun',
            index=models.Index(fields=['gst_registration_gstin', 'reconciliation_type', 'return_period'], name='ix_gst_run_gstin_type_period'),
        ),
        migrations.AddConstraint(
            model_name='gstreconciliationrun',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfinid', 'subentity', 'gst_registration_gstin', 'reconciliation_type', 'return_period', 'revision_no', 'is_active'), name='uq_gst_run_scope_type_period_revision'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationitem',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_gstreconciliationitem_scope'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationitem',
            index=models.Index(fields=['run', 'match_status'], name='ix_gst_item_run_status'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationitem',
            index=models.Index(fields=['run', 'match_key'], name='ix_gst_item_run_key'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationitem',
            index=models.Index(fields=['run', 'item_type'], name='ix_gst_item_run_type'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationitem',
            index=models.Index(fields=['gstin', 'counterparty_gstin'], name='ix_gst_item_gstin_pair'),
        ),
        migrations.AddConstraint(
            model_name='gstreconciliationitem',
            constraint=models.UniqueConstraint(fields=('run', 'source_document_type', 'source_document_id'), name='uq_gst_item_run_source_doc'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationactionlog',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_gst_log_scope'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationactionlog',
            index=models.Index(fields=['run', 'action_type', 'created_at'], name='ix_gst_log_run_action_created'),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationactionlog',
            index=models.Index(fields=['actor', 'created_at'], name='ix_gst_log_actor_created'),
        ),
    ]
