# Generated by Django 5.2.1 on 2026-05-19 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0031_rename_ent_notif_evt_entity_evt_idx_entity_noti_entity__bd0b29_idx_and_more'),
        ('gst_reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='match_confidence_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='gstreconciliationrun',
            name='tolerance_config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='GstImportedReturnRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('row_no', models.PositiveIntegerField()),
                ('source_section', models.CharField(blank=True, max_length=50, null=True)),
                ('source_row_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('doc_type_code', models.CharField(blank=True, max_length=20, null=True)),
                ('counterparty_gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('counterparty_gstin_normalized', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number_normalized', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pos_state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_row_json', models.JSONField(blank=True, default=dict)),
                ('normalized_row_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entity', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entityfin', to='entity.entityfinancialyear')),
                ('imported_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='gst_reconciliation.gstimportedreturn')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_SubEntity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_gstimportedreturnrow_scope'), models.Index(fields=['imported_return', 'row_no'], name='ix_gst_imp_row_return_row'), models.Index(fields=['imported_return', 'counterparty_gstin_normalized', 'invoice_number_normalized'], name='ix_gst_imp_row_match'), models.Index(fields=['imported_return', 'doc_type_code'], name='ix_gst_imp_row_doctype')],
                'constraints': [models.UniqueConstraint(fields=('imported_return', 'row_no'), name='uq_gst_imp_row_return_row'), models.UniqueConstraint(fields=('imported_return', 'row_hash'), name='uq_gst_imp_row_return_hash')],
            },
        ),
    ]
