# Generated by Django 5.2.1 on 2026-05-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0031_rename_ent_notif_evt_entity_evt_idx_entity_noti_entity__bd0b29_idx_and_more'),
        ('gst_reconciliation', '0002_gstreconciliationitem_match_confidence_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='accepted_mismatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='accepted_mismatch_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_items_accepted_mismatch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_items_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='resolution_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('ACCEPTED_MISMATCH', 'Accepted Mismatch'), ('IGNORED', 'Ignored'), ('REOPENED', 'Reopened')], db_index=True, default='OPEN', max_length=24),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='reviewer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gstreconciliationactionlog',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IMPORTED', 'Imported'), ('MATCH_STARTED', 'Match Started'), ('MATCH_COMPLETED', 'Match Completed'), ('SUBMITTED', 'Submitted'), ('REVIEW_STARTED', 'Review Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('ITEM_RESOLVED', 'Item Resolved'), ('ITEM_ASSIGNED', 'Item Assigned'), ('ITEM_MANUAL_MATCHED', 'Item Manually Matched'), ('ITEM_UNMATCHED', 'Item Unmatched'), ('ITEM_IGNORED', 'Item Ignored'), ('ITEM_REOPENED', 'Item Reopened'), ('ITEM_ACCEPTED_MISMATCH', 'Item Accepted Mismatch'), ('BULK_ACTION', 'Bulk Action'), ('NOTE', 'Note')], db_index=True, max_length=24),
        ),
        migrations.AddIndex(
            model_name='gstreconciliationitem',
            index=models.Index(fields=['run', 'resolution_status'], name='ix_gst_item_run_resolution'),
        ),
    ]
