# Generated by Django 5.2.1 on 2026-05-19 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reconciliation', '0003_gstreconciliationitem_accepted_mismatch_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_items_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstreconciliationitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gst_recon_items_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gstreconciliationitem',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('ASSIGNED', 'Assigned'), ('AUTO_MATCHED', 'Auto Matched'), ('MANUAL_MATCHED', 'Manual Matched'), ('PARTIAL_MATCH', 'Partial Match'), ('MISMATCH', 'Mismatch'), ('ACCEPTED_MISMATCH', 'Accepted Mismatch'), ('IGNORED', 'Ignored'), ('REOPENED', 'Reopened'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING_REVIEW', max_length=24),
        ),
    ]
