# Generated by Django 5.2.1 on 2026-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_currency_base_amount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucherheader',
            name='workflow_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
