# Generated by Codex on 2026-03-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_invoice_payment_modes(apps, schema_editor):
    PaymentMode = apps.get_model("payments", "PaymentMode")
    InvoicePaymentMode = apps.get_model("invoice", "Paymentmodes")

    db_alias = schema_editor.connection.alias
    if PaymentMode.objects.using(db_alias).exists():
        return

    rows = []
    for old in InvoicePaymentMode.objects.using(db_alias).all().order_by("id"):
        rows.append(
            PaymentMode(
                id=old.id,
                paymentmode=old.paymentmode,
                paymentmodecode=old.paymentmodecode,
                iscash=old.iscash,
                createdby_id=old.createdby_id,
                created_at=getattr(old, "created_at", None),
                updated_at=getattr(old, "updated_at", None),
            )
        )
    if rows:
        PaymentMode.objects.using(db_alias).bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoice", "0001_initial"),
        ("payments", "0004_paymentvoucherheader_workflow_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paymentmode", models.CharField(max_length=200, verbose_name="Payment Mode")),
                ("paymentmodecode", models.CharField(max_length=20, verbose_name="Payment Mode Code")),
                ("iscash", models.BooleanField(default=True, verbose_name="IsCash Transaction")),
                ("createdby", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("paymentmode", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="paymentmode",
            constraint=models.UniqueConstraint(fields=("paymentmodecode",), name="uq_pay_mode_code"),
        ),
        migrations.RunPython(copy_invoice_payment_modes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="paymentvoucherheader",
            name="payment_mode",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="payments.paymentmode"),
        ),
    ]
