# Generated by Codex on 2026-03-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_invoice_payment_modes(apps, schema_editor):
    # Invoice app was retired; keep this migration as a no-op data step so
    # fresh installs and existing databases share the same migration chain.
    return


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0004_paymentvoucherheader_workflow_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paymentmode", models.CharField(max_length=200, verbose_name="Payment Mode")),
                ("paymentmodecode", models.CharField(max_length=20, verbose_name="Payment Mode Code")),
                ("iscash", models.BooleanField(default=True, verbose_name="IsCash Transaction")),
                ("createdby", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("paymentmode", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="paymentmode",
            constraint=models.UniqueConstraint(fields=("paymentmodecode",), name="uq_pay_mode_code"),
        ),
        migrations.RunPython(copy_invoice_payment_modes, migrations.RunPython.noop),
        migrations.AddField(
            model_name="paymentvoucherheader",
            name="payment_mode",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="payments.paymentmode"),
        ),
    ]
