# Generated by Django 4.2.28 on 2026-03-07 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentmode_and_repoint_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
