# Generated by Django 5.2.1 on 2026-03-07 10:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentmode_created_at'),
        ('purchase', '0020_vendoradvancebalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucherAdvanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('advance_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_advance_adjustments', to='purchase.vendoradvancebalance')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_adjustments', to='payments.paymentvoucherallocation')),
                ('ap_settlement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_advance_adjustment', to='purchase.vendorsettlement')),
                ('open_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_advance_adjustments', to='purchase.vendorbillopenitem')),
                ('payment_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_adjustments', to='payments.paymentvoucherheader')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_voucher'], name='ix_payment_adv_adj_voucher'), models.Index(fields=['advance_balance'], name='ix_payment_adv_adj_balance'), models.Index(fields=['open_item'], name='ix_payment_adv_adj_openitem')],
                'constraints': [models.CheckConstraint(check=models.Q(('adjusted_amount__gte', 0)), name='ck_payment_adv_adj_amt_nonneg')],
            },
        ),
    ]
