# Generated by Django 5.2.1 on 2026-08-02 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('geography', '0004_geography_runtime_indexes'),
        ('payments', '0014_seed_payment_modes'),
        ('purchase', '0052_purchaseinvoiceheader_ix_pur_lookup_sub_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentvoucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'paid_to', 'subentity', 'reference_number'], name='ix_pay_ref_warn_scope'),
        ),
    ]
