# Generated by Django 4.2.28 on 2026-02-27 06:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20)),
                ('txn_id', models.IntegerField(db_index=True)),
                ('voucher_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('voucher_date', models.DateField(blank=True, db_index=True, null=True)),
                ('posting_date', models.DateField(db_index=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Posted'), (9, 'Reversed')], db_index=True, default=1)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_entries_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_entries_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaticAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('CASH_BANK', 'Cash/Bank'), ('ROUND_OFF', 'Round-off'), ('GST_OUTPUT', 'GST Output'), ('GST_INPUT', 'GST Input'), ('RCM_PAYABLE', 'RCM Payable'), ('TDS', 'TDS'), ('TCS', 'TCS'), ('PURCHASE', 'Purchase Defaults'), ('SALES', 'Sales Defaults'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('txn_type', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20)),
                ('txn_id', models.IntegerField(db_index=True)),
                ('voucher_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20)),
                ('txn_id', models.IntegerField(db_index=True)),
                ('detail_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('voucher_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('drcr', models.BooleanField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('posting_date', models.DateField(db_index=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account')),
                ('accounthead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.accounthead')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_journal_lines', to='posting.entry')),
                ('posting_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='posting.postingbatch')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('S', 'Sales'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20)),
                ('txn_id', models.IntegerField(db_index=True)),
                ('detail_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('voucher_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_factor', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('base_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('ext_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cost_source', models.CharField(choices=[('PURCHASE', 'Purchase'), ('FIFO', 'FIFO'), ('AVG', 'Average'), ('MANUAL', 'Manual')], db_index=True, default='PURCHASE', max_length=20)),
                ('cost_meta', models.JSONField(blank=True, null=True)),
                ('move_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJ', 'Adjustment'), ('REV', 'Reversal')], db_index=True, max_length=10)),
                ('posting_date', models.DateField(db_index=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_moves_base_uom', to='catalog.unitofmeasure')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_inventory_moves', to='posting.entry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.godown')),
                ('posting_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_moves_posting', to='posting.postingbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inv_moves_uom', to='catalog.unitofmeasure')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='posting_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='posting.postingbatch'),
        ),
        migrations.AddField(
            model_name='entry',
            name='subentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity'),
        ),
        migrations.CreateModel(
            name='EntityStaticAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_static_account_maps', to='entity.entity')),
                ('static_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_maps', to='posting.staticaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='postingbatch',
            index=models.Index(fields=['entity', 'txn_type', 'txn_id'], name='ix_pb_locator'),
        ),
        migrations.AddIndex(
            model_name='postingbatch',
            index=models.Index(fields=['entity', 'entityfin', 'subentity', 'txn_type', 'txn_id'], name='ix_pb_locator_scope'),
        ),
        migrations.AddIndex(
            model_name='postingbatch',
            index=models.Index(fields=['entity', 'voucher_no'], name='ix_pb_vno'),
        ),
        migrations.AddIndex(
            model_name='postingbatch',
            index=models.Index(fields=['is_active', 'created_at'], name='ix_pb_active_time'),
        ),
        migrations.AddConstraint(
            model_name='postingbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('entity', 'entityfin', 'subentity', 'txn_type', 'txn_id'), name='uq_pb_one_active_per_txn'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['entity', 'txn_type', 'txn_id'], name='ix_jl_locator'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['entity', 'txn_type', 'txn_id', 'detail_id'], name='ix_jl_locator_line'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['entity', 'posting_date'], name='ix_jl_entity_postdate'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account'], name='ix_jl_posting_account'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['accounthead'], name='ix_jl_head'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['posting_batch'], name='ix_jl_batch'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ck_jl_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('account__isnull', False), ('accounthead__isnull', True)), models.Q(('account__isnull', True), ('accounthead__isnull', False)), _connector='OR'), name='ck_jl_account_xor_head'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['entity', 'txn_type', 'txn_id'], name='ix_im_locator'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['entity', 'txn_type', 'txn_id', 'detail_id'], name='ix_im_locator_line'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['entity', 'product', 'posting_date'], name='ix_im_p_entity_product_date'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['posting_batch'], name='ix_im_batch'),
        ),
        migrations.AddIndex(
            model_name='inventorymove',
            index=models.Index(fields=['location', 'product', 'posting_date'], name='ix_im_loc_product_date'),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(check=models.Q(('qty', 0), _negated=True), name='ck_im_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='inventorymove',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost__gte', 0), ('ext_cost__gte', 0)), name='ck_im_cost_nonneg'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entity', 'posting_date'], name='ix_entry_entity_postdate'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entity', 'txn_type', 'txn_id'], name='ix_entry_txn'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entity', 'voucher_no'], name='ix_entry_vno'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['status', 'posted_at'], name='ix_entry_status_time'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfin', 'subentity', 'txn_type', 'txn_id'), name='uq_entry_one_per_txn_scope'),
        ),
        migrations.AddIndex(
            model_name='entitystaticaccountmap',
            index=models.Index(fields=['entity', 'static_account'], name='ix_esam_entity_static'),
        ),
        migrations.AddIndex(
            model_name='entitystaticaccountmap',
            index=models.Index(fields=['entity', 'account'], name='ix_esam_entity_account'),
        ),
        migrations.AddIndex(
            model_name='entitystaticaccountmap',
            index=models.Index(fields=['static_account'], name='ix_esam_static'),
        ),
        migrations.AddConstraint(
            model_name='entitystaticaccountmap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('entity', 'static_account'), name='uq_esam_entity_static_active'),
        ),
    ]
