# Generated by Django 4.2.28 on 2026-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postingbatch',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
    ]
