# Generated by Django 5.2.1 on 2026-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_journalline_entitystaticaccountmap_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postingbatch',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher')], db_index=True, max_length=20),
        ),
    ]
