# Generated by Django 4.2.28 on 2026-03-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_remove_role_entity_remove_roleprivilege_entity_and_more'),
        ('posting', '0006_alter_entry_txn_type_alter_inventorymove_txn_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitystaticaccountmap',
            name='sub_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity'),
        ),
        migrations.AddField(
            model_name='staticaccount',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
