# Generated by Django 4.2.28 on 2026-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_entitystaticaccountmap_sub_entity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitystaticaccountmap',
            name='uq_esam_entity_static_active',
        ),
        migrations.AddConstraint(
            model_name='entitystaticaccountmap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('entity', 'sub_entity', 'static_account'), name='uq_esam_entity_subentity_static_active'),
        ),
    ]
