# Generated by Django 5.2.1 on 2026-04-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('posting', '0008_remove_entitystaticaccountmap_uq_esam_entity_static_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitystaticaccountmap',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account'),
        ),
    ]
