# Generated by Django 4.2.28 on 2026-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0013_inventorymove_batch_number_inventorymove_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postingbatch',
            name='txn_type',
            field=models.CharField(choices=[('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staticaccount',
            name='group',
            field=models.CharField(choices=[('CASH_BANK', 'Cash/Bank'), ('ROUND_OFF', 'Round-off'), ('GST_OUTPUT', 'GST Output'), ('GST_INPUT', 'GST Input'), ('RCM_PAYABLE', 'RCM Payable'), ('TDS', 'TDS'), ('TCS', 'TCS'), ('PURCHASE', 'Purchase Defaults'), ('SALES', 'Sales Defaults'), ('EQUITY', 'Equity / Opening'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
    ]
