# Generated by Django 5.2.1 on 2026-04-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0014_alter_entry_txn_type_alter_inventorymove_txn_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='txn_type',
            field=models.CharField(choices=[('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='movement_nature',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('OPENING', 'Opening Stock'), ('RETURN', 'Return'), ('REVERSAL', 'Reversal'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='txn_type',
            field=models.CharField(choices=[('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='txn_type',
            field=models.CharField(choices=[('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postingbatch',
            name='txn_type',
            field=models.CharField(choices=[('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance')], db_index=True, max_length=20),
        ),
    ]
