# Generated by Django 5.2.1 on 2026-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0020_seed_manufacturing_additional_cost_expense_static_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticaccount',
            name='group',
            field=models.CharField(choices=[('CASH_BANK', 'Cash/Bank'), ('ROUND_OFF', 'Round-off'), ('GST_OUTPUT', 'GST Output'), ('GST_INPUT', 'GST Input'), ('RCM_PAYABLE', 'RCM Payable'), ('TDS', 'TDS'), ('TCS', 'TCS'), ('PURCHASE', 'Purchase Defaults'), ('SALES', 'Sales Defaults'), ('MANUFACTURING', 'Manufacturing'), ('EQUITY', 'Equity / Opening'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
    ]
