# Generated by Django 5.2.1 on 2026-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0027_inventory_balance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='txn_type',
            field=models.CharField(choices=[('CAPDIST', 'Capital Distribution'), ('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('PRLFNF', 'Payroll FnF'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance'), ('YEC', 'Year-End Close')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='txn_type',
            field=models.CharField(choices=[('CAPDIST', 'Capital Distribution'), ('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('PRLFNF', 'Payroll FnF'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance'), ('YEC', 'Year-End Close')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='txn_type',
            field=models.CharField(choices=[('CAPDIST', 'Capital Distribution'), ('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('PRLFNF', 'Payroll FnF'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance'), ('YEC', 'Year-End Close')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='postingbatch',
            name='txn_type',
            field=models.CharField(choices=[('CAPDIST', 'Capital Distribution'), ('MWO', 'Manufacturing Work Order'), ('S', 'Sales'), ('SCN', 'Sales Credit Note'), ('SDN', 'Sales Debit Note'), ('P', 'Purchase'), ('PRL', 'Payroll'), ('PRLFNF', 'Payroll FnF'), ('FAC', 'Fixed Asset Capitalization'), ('FADP', 'Fixed Asset Depreciation'), ('FAI', 'Fixed Asset Impairment'), ('FADS', 'Fixed Asset Disposal'), ('J', 'Journal'), ('SR', 'Sales Return'), ('PR', 'Purchase Return'), ('PCN', 'Purchase Credit Note'), ('PDN', 'Purchase Debit Note'), ('C', 'Journal (Cash)'), ('B', 'Journal (Bank)'), ('IT', 'Inventory Transfer'), ('IA', 'Inventory Adjustment'), ('RV', 'Receipt Voucher'), ('PV', 'Payment Voucher'), ('OB', 'Opening Balance'), ('YEC', 'Year-End Close')], db_index=True, max_length=20),
        ),
    ]
