# Generated by Django 5.2.1 on 2026-05-24 14:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0031_rename_ent_notif_evt_entity_evt_idx_entity_noti_entity__bd0b29_idx_and_more'),
        ('posting', '0024_alter_entry_txn_type_alter_inventorymove_txn_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('run_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('matching', 'Matching'), ('review', 'Review'), ('reconciled', 'Reconciled'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20)),
                ('as_of_date', models.DateField(blank=True, db_index=True, null=True)),
                ('statement_opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('statement_closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('book_opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('book_closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unmatched_bank_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unmatched_book_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('statement_line_count', models.PositiveIntegerField(default=0)),
                ('matched_line_count', models.PositiveIntegerField(default=0)),
                ('suggested_line_count', models.PositiveIntegerField(default=0)),
                ('exception_line_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliation_runs', to='entity.entitybankaccountv2')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation_runs', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entityfinancialyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('match_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('unmatched', 'Unmatched'), ('reversed', 'Reversed')], db_index=True, default='suggested', max_length=20)),
                ('match_kind', models.CharField(choices=[('one_to_one', 'One To One'), ('one_to_many', 'One To Many'), ('many_to_one', 'Many To One'), ('many_to_many', 'Many To Many'), ('partial', 'Partial'), ('auto', 'Auto'), ('manual', 'Manual')], db_index=True, default='auto', max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('bank_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('book_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rule_code', models.CharField(blank=True, default='', max_length=80)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='bank_reco.bankreconciliationrun')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('import_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='uploaded', max_length=20)),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF'), ('mt940', 'MT940'), ('camt053', 'CAMT053'), ('json', 'JSON')], db_index=True, default='csv', max_length=20)),
                ('source_file_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('parser_key', models.CharField(blank=True, default='csv', max_length=50)),
                ('statement_from', models.DateField(blank=True, db_index=True, null=True)),
                ('statement_to', models.DateField(blank=True, db_index=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('imported_line_count', models.PositiveIntegerField(default=0)),
                ('duplicate_line_count', models.PositiveIntegerField(default=0)),
                ('invalid_line_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to='entity.entitybankaccountv2')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_imports', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='bankreconciliationrun',
            name='statement_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='bank_reco.bankstatementimport'),
        ),
        migrations.CreateModel(
            name='BankReconciliationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(blank=True, default='', max_length=40)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bank_reco.bankreconciliationmatch')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bank_reco.bankreconciliationrun')),
                ('statement_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bank_reco.bankstatementimport')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('line_no', models.PositiveIntegerField()),
                ('txn_date', models.DateField(blank=True, db_index=True, null=True)),
                ('value_date', models.DateField(blank=True, db_index=True, null=True)),
                ('narration', models.CharField(blank=True, default='', max_length=500)),
                ('reference_no', models.CharField(blank=True, default='', max_length=120)),
                ('cheque_no', models.CharField(blank=True, default='', max_length=80)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_hash', models.CharField(db_index=True, max_length=64)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('warning', 'Warning'), ('invalid', 'Invalid')], db_index=True, default='pending', max_length=20)),
                ('reconciliation_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('suggested', 'Suggested'), ('partial', 'Partial'), ('matched', 'Matched'), ('ignored', 'Ignored'), ('voucher_created', 'Voucher Created')], db_index=True, default='unmatched', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bank_reco.bankstatementimport')),
            ],
            options={
                'ordering': ('line_no', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationMatchBankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('allocation_order', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_lines', to='bank_reco.bankreconciliationmatch')),
                ('statement_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bank_reco.bankstatementline')),
            ],
            options={
                'ordering': ('allocation_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationMatchBookLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('allocation_order', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='posting.entry')),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='posting.journalline')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_lines', to='bank_reco.bankreconciliationmatch')),
            ],
            options={
                'ordering': ('allocation_order', 'id'),
                'indexes': [models.Index(fields=['match', 'allocation_order'], name='ix_brm_jl_order'), models.Index(fields=['journal_line'], name='ix_bank_reco_match_bookline_jl')],
                'constraints': [models.UniqueConstraint(fields=('match', 'journal_line'), name='uq_bank_reco_match_bookline')],
            },
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmatch',
            index=models.Index(fields=['run', 'status'], name='ix_bank_reco_match_run_status'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmatch',
            index=models.Index(fields=['run', 'match_kind'], name='ix_bank_reco_match_run_kind'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['entity', 'entityfin', 'subentity', 'bank_account'], name='ix_bank_stmt_import_scope'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['entity', 'status', 'statement_from', 'statement_to'], name='ix_bsi_status_period'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_file_sha256', ''), _negated=True), fields=('entity', 'bank_account', 'source_file_sha256'), name='uq_bank_statement_import_entity_bank_filehash'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationrun',
            index=models.Index(fields=['entity', 'entityfin', 'subentity', 'bank_account'], name='ix_bank_reco_run_scope'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationrun',
            index=models.Index(fields=['entity', 'status', 'as_of_date'], name='ix_bank_reco_run_status'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationauditlog',
            index=models.Index(fields=['run', 'action'], name='ix_bank_reco_audit_run_action'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationauditlog',
            index=models.Index(fields=['statement_import', 'action'], name='ix_br_audit_imp_act'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement_import', 'reconciliation_status'], name='ix_bank_stmt_line_reco'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['txn_date', 'reference_no'], name='ix_bank_stmt_line_txn_ref'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(fields=('statement_import', 'line_no'), name='uq_bank_stmt_line_import_lineno'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmatchbankline',
            index=models.Index(fields=['match', 'allocation_order'], name='ix_brm_bl_order'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmatchbankline',
            index=models.Index(fields=['statement_line'], name='ix_brm_bl_stmt'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliationmatchbankline',
            constraint=models.UniqueConstraint(fields=('match', 'statement_line'), name='uq_bank_reco_match_bankline'),
        ),
    ]
