# Generated by Django 5.2.1 on 2026-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliationmatch',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('suggested', 'Suggested'), ('possible', 'Possible')], db_index=True, default='suggested', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankreconciliationmatch',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('partially_matched', 'Partially Matched'), ('unmatched', 'Unmatched'), ('cancelled', 'Cancelled')], db_index=True, default='suggested', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='reconciliation_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('partially_matched', 'Partially Matched'), ('cancelled', 'Cancelled')], db_index=True, default='unmatched', max_length=20),
        ),
    ]
