# Generated by Django 5.2.1 on 2026-05-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reco', '0002_bankreconciliationmatch_match_type_and_more'),
        ('vouchers', '0005_remove_voucherheader_uq_voucher_entity_fin_code_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='created_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vouchers.voucherheader'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='exception_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='exception_status',
            field=models.CharField(choices=[('none', 'None'), ('bank_error', 'Bank Error'), ('book_error', 'Book Error'), ('ignored', 'Ignored'), ('hold_for_review', 'Hold For Review'), ('pending_clearance', 'Pending Clearance')], db_index=True, default='none', max_length=30),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement_import', 'exception_status'], name='ix_bank_stmt_line_exc'),
        ),
    ]
