# Generated by Django 5.2.1 on 2026-06-19 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reco', '0004_bank_reco_runtime_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankreconciliationauditlog',
            index=models.Index(fields=['run', 'created_at'], name='ix_bank_reco_audit_run_dt'),
        ),
    ]
