# Generated by Django 4.2.28 on 2026-02-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizedStringKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('default_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizedStringValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localization.language')),
                ('string_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.localizedstringkey')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'entity'], name='localizatio_languag_ca6d2f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='localizedstringvalue',
            constraint=models.UniqueConstraint(fields=('string_key', 'language', 'entity'), name='uq_localized_value_key_lang_entity'),
        ),
    ]
