# Generated by Django 5.2.1 on 2026-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='localizedstringkey',
            index=models.Index(fields=['is_active', 'module'], name='ix_l10n_key_active_mod'),
        ),
        migrations.AddIndex(
            model_name='localizedstringvalue',
            index=models.Index(fields=['language', 'is_approved', 'entity', 'string_key'], name='ix_l10n_val_lang_appr'),
        ),
    ]
