from __future__ import annotations

import json
import random
import time
from dataclasses import asdict, dataclass
from datetime import date, datetime, timedelta
from decimal import Decimal
from io import StringIO

from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction
from django.db.models import Count, Sum
from django.utils import timezone

from Authentication.models import User
from catalog.models import Product, ProductCategory, ProductPurchaseBehavior, UnitOfMeasure
from entity.models import Entity, EntityAddress, EntityFinancialYear, EntityGstRegistration, GstRegistrationType, SubEntity
from financial.models import AccountCommercialProfile, AccountComplianceProfile, Ledger, accountHead, accounttype
from financial.services import create_account_with_synced_ledger
from geography.models import City, Country, District, State
from numbering.models import DocumentNumberSeries, DocumentType
from payments.models import PaymentMode
from posting.models import Entry, EntryStatus, JournalLine, PostingBatch, TxnType
from purchase.models.purchase_ap import VendorBillOpenItem, VendorSettlement, VendorSettlementLine
from purchase.models.purchase_core import PurchaseInvoiceHeader, PurchaseInvoiceLine, PurchaseTaxSummary
from sales.models import CustomerBillOpenItem, CustomerSettlement, CustomerSettlementLine, SalesInvoiceHeader, SalesInvoiceLine, SalesTaxSummary


ZERO = Decimal("0.00")
TAXABLE = Decimal("500.00")
GST = Decimal("90.00")
TOTAL = Decimal("590.00")


@dataclass
class TenantTarget:
    code: str
    label: str
    sales: int
    purchase: int


class Command(BaseCommand):
    help = "Seed deterministic, isolated multi-tenant performance fixtures after staging safety gates pass."

    def add_arguments(self, parser):
        parser.add_argument("--profile", choices=["tiny", "small", "medium", "large"], default="tiny")
        parser.add_argument("--sales", type=int, default=None, help="Override sales invoice count per tenant.")
        parser.add_argument("--purchase", type=int, default=None, help="Override purchase invoice count per tenant.")
        parser.add_argument("--batch-size", type=int, default=500)
        parser.add_argument("--seed", type=int, default=20261010)
        parser.add_argument("--payment-ratio", type=float, default=0.20)
        parser.add_argument("--json", action="store_true")
        parser.add_argument("--dry-run", action="store_true")
        parser.add_argument("--reset-fixture", action="store_true", help="Delete only rows generated by this command after safety audit passes.")
        parser.add_argument("--allow-db-name", action="append", default=[])
        parser.add_argument("--allow-db-host", action="append", default=[])

    def handle(self, *args, **options):
        started = time.perf_counter()
        self._assert_safety(options)
        targets = self._targets(options)
        rng = random.Random(int(options["seed"]))

        if options["reset_fixture"]:
            reset = self._reset_fixture(dry_run=options["dry_run"])
            self._write({"dry_run": options["dry_run"], "reset": reset}, options)
            return

        before = self._database_snapshot()
        if options["dry_run"]:
            payload = {
                "dry_run": True,
                "targets": [asdict(target) for target in targets],
                "database": before,
                "message": "Safety audit passed. No rows were written.",
            }
            self._write(payload, options)
            return

        results = []
        for target in targets:
            with transaction.atomic():
                tenant = self._ensure_tenant(target)
            result = self._seed_tenant(tenant=tenant, target=target, batch_size=options["batch_size"], rng=rng, payment_ratio=Decimal(str(options["payment_ratio"])))
            validation = self._validate_tenant(tenant)
            results.append({**result, "validation": validation})

        after = self._database_snapshot()
        payload = {
            "dry_run": False,
            "elapsed_seconds": round(time.perf_counter() - started, 3),
            "database_before": before,
            "database_after": after,
            "targets": [asdict(target) for target in targets],
            "results": results,
        }
        self._write(payload, options)

    def _assert_safety(self, options):
        out = StringIO()
        args = ["--json", "--strict"]
        for name in options["allow_db_name"]:
            args.extend(["--allow-db-name", name])
        for host in options["allow_db_host"]:
            args.extend(["--allow-db-host", host])
        try:
            call_command("audit_performance_staging", *args, stdout=out)
        except CommandError as exc:
            raise CommandError(f"Performance fixture seeding blocked by safety audit: {exc}") from exc
        payload = json.loads(out.getvalue())
        if not payload.get("ready"):
            raise CommandError("Performance fixture seeding blocked because staging audit is not ready.")

    def _targets(self, options) -> list[TenantTarget]:
        defaults = {
            "tiny": (4, 3),
            "small": (1000, 500),
            "medium": (10000, 5000),
            "large": (50000, 25000),
        }
        sales, purchase = defaults[options["profile"]]
        sales = int(options["sales"] if options["sales"] is not None else sales)
        purchase = int(options["purchase"] if options["purchase"] is not None else purchase)
        if sales < 0 or purchase < 0:
            raise CommandError("Sales and purchase counts must be non-negative.")
        return [
            TenantTarget(code=f"P2B3B-{options['profile'].upper()}-S", label=f"Phase2B3B {options['profile']} Small Tenant", sales=sales, purchase=purchase),
            TenantTarget(code=f"P2B3B-{options['profile'].upper()}-M", label=f"Phase2B3B {options['profile']} Medium Tenant", sales=sales, purchase=purchase),
            TenantTarget(code=f"P2B3B-{options['profile'].upper()}-L", label=f"Phase2B3B {options['profile']} Large Tenant", sales=sales, purchase=purchase),
        ]

    def _ensure_user(self):
        return User.objects.get_or_create(
            email="perf-fixture@local.invalid",
            defaults={"username": "perf-fixture", "is_active": True},
        )[0]

    def _ensure_tenant(self, target: TenantTarget) -> dict:
        actor = self._ensure_user()
        country, _ = Country.objects.get_or_create(countrycode=f"I{target.code[-1]}", defaults={"countryname": f"{target.label} India"})
        state_home, _ = State.objects.get_or_create(country=country, statecode="27", defaults={"statename": f"{target.label} Maharashtra"})
        state_other, _ = State.objects.get_or_create(country=country, statecode="29", defaults={"statename": f"{target.label} Karnataka"})
        district, _ = District.objects.get_or_create(state=state_home, districtcode=f"{target.code[-1]}D", defaults={"districtname": f"{target.label} District"})
        city, _ = City.objects.get_or_create(distt=district, citycode=f"{target.code[-1]}C", defaults={"cityname": f"{target.label} City", "pincode": "400001"})
        gst_type, _ = GstRegistrationType.objects.get_or_create(Name=f"{target.code} Regular", defaults={"Description": "Regular"})
        entity, _ = Entity.objects.get_or_create(
            entityname=target.label,
            defaults={"legalname": f"{target.label} Pvt Ltd", "business_type": Entity.BusinessType.MIXED, "GstRegitrationType": gst_type, "createdby": actor},
        )
        subentity, _ = SubEntity.objects.get_or_create(entity=entity, subentityname="Head Office")
        entityfin, _ = EntityFinancialYear.objects.get_or_create(
            entity=entity,
            desc="FY 2026-27",
            defaults={
                "finstartyear": timezone.make_aware(datetime(2026, 4, 1)),
                "finendyear": timezone.make_aware(datetime(2027, 3, 31)),
                "createdby": actor,
            },
        )
        EntityAddress.objects.get_or_create(
            entity=entity,
            address_type=EntityAddress.AddressType.REGISTERED,
            line1=f"{target.label} Address",
            defaults={"country": country, "state": state_home, "district": district, "city": city, "pincode": "400001", "is_primary": True, "createdby": actor},
        )
        entity_gstin = self._gstin_for_target(target)
        EntityGstRegistration.objects.get_or_create(
            entity=entity,
            gstin=entity_gstin,
            defaults={"registration_type": gst_type, "state": state_home, "is_primary": True, "createdby": actor},
        )
        acc_type, _ = accounttype.objects.get_or_create(entity=entity, accounttypecode=f"{target.code[-1]}CUR", defaults={"accounttypename": "Current", "createdby": actor})
        debit_head, _ = accountHead.objects.get_or_create(entity=entity, code=1000, defaults={"name": "Assets/Expense", "balanceType": "Debit", "drcreffect": "Debit", "accounttype": acc_type, "createdby": actor})
        credit_head, _ = accountHead.objects.get_or_create(entity=entity, code=7000, defaults={"name": "Income/Liability", "balanceType": "Credit", "drcreffect": "Credit", "accounttype": acc_type, "createdby": actor})

        vendor = self._account(entity, credit_head, 9001, "Vendor", actor, "Vendor", "27ABCDE1234F1Z5")
        customer = self._account(entity, debit_head, 9101, "Customer", actor, "Customer", "27VWXYZ1234F1Z5")
        expense = self._account(entity, debit_head, 5001, "Service Expense", actor, "", "")
        sales = self._account(entity, credit_head, 9502, "Sales Revenue", actor, "", "")
        cash = self._account(entity, debit_head, 1002, "Cash", actor, "", "")
        input_igst = self._account(entity, debit_head, 6503, "Input IGST", actor, "", "")
        output_igst = self._account(entity, credit_head, 6603, "Output IGST", actor, "", "")

        PaymentMode.objects.get_or_create(paymentmodecode=f"{target.code[-1]}CASH", defaults={"paymentmode": f"{target.label} Cash", "iscash": True, "createdby": actor})
        uom, _ = UnitOfMeasure.objects.get_or_create(entity=entity, code=f"{target.code[-1]}EA", defaults={"description": "Each"})
        category, _ = ProductCategory.objects.get_or_create(entity=entity, pcategoryname=f"{target.label} Services")
        Product.objects.get_or_create(
            entity=entity,
            sku=f"{target.code}-SERVICE",
            defaults={"productname": "Performance Service", "productdesc": "Performance Service", "productcategory": category, "base_uom": uom, "is_service": True, "purchase_behavior": ProductPurchaseBehavior.EXPENSE, "purchase_account": expense},
        )
        self._numbering(entity, entityfin, subentity, "sales", "sales_invoice", "SINV", f"{target.code[-1]}SI", actor)
        self._numbering(entity, entityfin, subentity, "purchase", f"{target.code}_purchase_invoice", "PINV", f"{target.code[-1]}PI", actor)
        return {
            "target": target,
            "actor": actor,
            "entity": entity,
            "subentity": subentity,
            "entityfin": entityfin,
            "state_home": state_home,
            "state_other": state_other,
            "vendor": vendor,
            "customer": customer,
            "expense": expense,
            "sales": sales,
            "cash": cash,
            "input_igst": input_igst,
            "output_igst": output_igst,
        }

    @staticmethod
    def _gstin_for_target(target: TenantTarget) -> str:
        number = sum((idx + 1) * ord(ch) for idx, ch in enumerate(target.code)) % 10000
        suffix = target.code[-1] if target.code[-1].isalpha() else "X"
        pan = f"PF{suffix}AB{number:04d}C"
        return f"27{pan}1Z5"

    def _account(self, entity, head, code, suffix, actor, partytype, gstin):
        ledger, _ = Ledger.objects.get_or_create(entity=entity, ledger_code=code, defaults={"name": suffix, "accounthead": head, "createdby": actor})
        acc = getattr(ledger, "account_profile", None)
        if acc is None:
            acc = create_account_with_synced_ledger(
                account_data={"entity": entity, "ledger": ledger, "accountname": suffix, "createdby": actor},
                ledger_overrides={"ledger_code": code, "accounthead": head, "is_party": bool(partytype)},
            )
        if partytype:
            AccountCommercialProfile.objects.update_or_create(account=acc, defaults={"entity": entity, "partytype": partytype, "createdby": actor})
            AccountComplianceProfile.objects.update_or_create(account=acc, defaults={"entity": entity, "gstno": gstin, "pan": gstin[2:12], "createdby": actor})
        return acc

    def _numbering(self, entity, entityfin, subentity, module, doc_key, doc_code, prefix, actor):
        doc_type, _ = DocumentType.objects.get_or_create(module=module, doc_key=doc_key, defaults={"name": doc_key, "default_code": doc_code, "is_active": True})
        DocumentNumberSeries.objects.get_or_create(
            entity=entity,
            entityfinid=entityfin,
            subentity=subentity,
            doc_type=doc_type,
            doc_code=doc_code,
            defaults={"prefix": prefix, "starting_number": 1, "current_number": 1, "is_active": True, "created_by": actor},
        )

    def _seed_tenant(self, *, tenant, target: TenantTarget, batch_size: int, rng: random.Random, payment_ratio: Decimal) -> dict:
        sales_inserted = self._seed_sales(tenant, target.sales, batch_size, rng, payment_ratio)
        purchase_inserted = self._seed_purchase(tenant, target.purchase, batch_size, rng, payment_ratio)
        return {"tenant": target.code, "entity_id": tenant["entity"].id, "sales_inserted": sales_inserted, "purchase_inserted": purchase_inserted}

    def _seed_sales(self, tenant, total: int, batch_size: int, rng: random.Random, payment_ratio: Decimal) -> int:
        inserted = 0
        existing = SalesInvoiceHeader.objects.filter(entity=tenant["entity"], legacy_source_system="phase2b3b").count()
        for start in range(existing + 1, total + 1, batch_size):
            end = min(start + batch_size - 1, total)
            with transaction.atomic():
                for n in range(start, end + 1):
                    bill_date = date(2026, 4, 1) + timedelta(days=rng.randrange(180))
                    due_date = bill_date + timedelta(days=30)
                    paid = TOTAL if Decimal(n % 10) / Decimal("10") < payment_ratio else ZERO
                    header = SalesInvoiceHeader.objects.create(
                        entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"],
                        doc_type=SalesInvoiceHeader.DocType.TAX_INVOICE, status=SalesInvoiceHeader.Status.POSTED,
                        bill_date=bill_date, posting_date=bill_date, due_date=due_date, credit_days=30,
                        doc_code="SINV", doc_no=n, invoice_number=f"{tenant['target'].code}-SINV-{n:06d}",
                        customer=tenant["customer"], customer_ledger=tenant["customer"].ledger,
                        customer_name=tenant["customer"].accountname, customer_gstin="27VWXYZ1234F1Z5",
                        customer_state_code="27", seller_gstin="27AAAAA1234A1Z5", seller_state_code="27",
                        place_of_supply_state_code="29", supply_category=SalesInvoiceHeader.SupplyCategory.DOMESTIC_B2B,
                        taxability=SalesInvoiceHeader.Taxability.TAXABLE, tax_regime=SalesInvoiceHeader.TaxRegime.INTER_STATE,
                        is_igst=True, total_taxable_value=TAXABLE, total_igst=GST, grand_total=TOTAL,
                        settled_amount=paid, outstanding_amount=TOTAL - paid,
                        settlement_status=SalesInvoiceHeader.SettlementStatus.SETTLED if paid == TOTAL else SalesInvoiceHeader.SettlementStatus.OPEN,
                        reference=f"P2B3B-S-{n}", posted_at=timezone.now(), posted_by=tenant["actor"],
                        legacy_source_system="phase2b3b", legacy_source_key=f"{tenant['target'].code}:sales:{n}",
                    )
                    SalesInvoiceLine.objects.create(entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"], header=header, line_no=1, productDesc="Performance service", hsn_sac_code="998311", is_service=True, qty=1, rate=TAXABLE, taxability=SalesInvoiceHeader.Taxability.TAXABLE, gst_rate=18, igst_amount=GST, taxable_value=TAXABLE, line_total=TOTAL, sales_account=tenant["sales"])
                    SalesTaxSummary.objects.create(entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"], header=header, taxability=SalesInvoiceHeader.Taxability.TAXABLE, hsn_sac_code="998311", is_service=True, gst_rate=18, taxable_value=TAXABLE, igst_amount=GST)
                    CustomerBillOpenItem.objects.create(header=header, entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"], customer=tenant["customer"], customer_ledger=tenant["customer"].ledger, doc_type=header.doc_type, bill_date=bill_date, due_date=due_date, invoice_number=header.invoice_number, original_amount=TOTAL, gross_amount=TOTAL, net_receivable_amount=TOTAL, settled_amount=paid, outstanding_amount=TOTAL - paid, is_open=paid < TOTAL)
                    if paid:
                        settlement = CustomerSettlement.objects.create(entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"], customer=tenant["customer"], customer_ledger=tenant["customer"].ledger, settlement_type=CustomerSettlement.SettlementType.RECEIPT, settlement_date=bill_date, reference_no=f"RCPT-{header.doc_no}", total_amount=paid, status=CustomerSettlement.Status.POSTED, posted_at=timezone.now(), posted_by=tenant["actor"])
                        CustomerSettlementLine.objects.create(settlement=settlement, open_item=header.ap_open_item, amount=paid, applied_amount_signed=paid)
                    self._post_entry(tenant, TxnType.SALES, header.id, header.invoice_number, bill_date, [(tenant["customer"], True, TOTAL), (tenant["sales"], False, TAXABLE), (tenant["output_igst"], False, GST)])
                    inserted += 1
        return inserted

    def _seed_purchase(self, tenant, total: int, batch_size: int, rng: random.Random, payment_ratio: Decimal) -> int:
        inserted = 0
        existing = PurchaseInvoiceHeader.objects.filter(entity=tenant["entity"], legacy_source_system="phase2b3b").count()
        for start in range(existing + 1, total + 1, batch_size):
            end = min(start + batch_size - 1, total)
            with transaction.atomic():
                for n in range(start, end + 1):
                    bill_date = date(2026, 4, 1) + timedelta(days=rng.randrange(180))
                    due_date = bill_date + timedelta(days=30)
                    paid = TOTAL if Decimal(n % 10) / Decimal("10") < payment_ratio else ZERO
                    header = PurchaseInvoiceHeader.objects.create(
                        entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"],
                        doc_type=PurchaseInvoiceHeader.DocType.TAX_INVOICE, status=PurchaseInvoiceHeader.Status.POSTED,
                        bill_date=bill_date, posting_date=bill_date, due_date=due_date, credit_days=30,
                        doc_code="PINV", doc_no=n, purchase_number=f"{tenant['target'].code}-PINV-{n:06d}",
                        supplier_invoice_number=f"SUP-{n:06d}", supplier_invoice_date=bill_date,
                        vendor=tenant["vendor"], vendor_ledger=tenant["vendor"].ledger, vendor_name=tenant["vendor"].accountname,
                        vendor_gstin="27ABCDE1234F1Z5", vendor_state=tenant["state_home"], supplier_state=tenant["state_home"], place_of_supply_state=tenant["state_other"],
                        supply_category=PurchaseInvoiceHeader.SupplyCategory.DOMESTIC, default_taxability=PurchaseInvoiceHeader.Taxability.TAXABLE,
                        tax_regime=PurchaseInvoiceHeader.TaxRegime.INTER, is_igst=True, total_taxable=TAXABLE, total_igst=GST, total_gst=GST, grand_total=TOTAL, grand_total_base_currency=TOTAL,
                        posted_at=timezone.now(), posted_by=tenant["actor"], created_by=tenant["actor"],
                        legacy_source_system="phase2b3b", legacy_source_key=f"{tenant['target'].code}:purchase:{n}",
                    )
                    PurchaseInvoiceLine.objects.create(header=header, line_no=1, purchase_account=tenant["expense"], product_desc="Performance service", is_service=True, hsn_sac="998311", qty=1, rate=TAXABLE, taxability=PurchaseInvoiceHeader.Taxability.TAXABLE, gst_rate=18, igst_percent=18, igst_amount=GST, taxable_value=TAXABLE, line_total=TOTAL)
                    PurchaseTaxSummary.objects.create(header=header, taxability=PurchaseInvoiceHeader.Taxability.TAXABLE, hsn_sac="998311", is_service=True, gst_rate=18, taxable_value=TAXABLE, igst_amount=GST, total_value=TOTAL, itc_eligible_tax=GST)
                    open_item = VendorBillOpenItem.objects.create(header=header, entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"], vendor=tenant["vendor"], vendor_ledger=tenant["vendor"].ledger, doc_type=header.doc_type, bill_date=bill_date, due_date=due_date, purchase_number=header.purchase_number, supplier_invoice_number=header.supplier_invoice_number, original_amount=TOTAL, gross_amount=TOTAL, net_payable_amount=TOTAL, settled_amount=paid, outstanding_amount=TOTAL - paid, is_open=paid < TOTAL)
                    if paid:
                        settlement = VendorSettlement.objects.create(entity=tenant["entity"], entityfinid=tenant["entityfin"], subentity=tenant["subentity"], vendor=tenant["vendor"], vendor_ledger=tenant["vendor"].ledger, settlement_type=VendorSettlement.SettlementType.PAYMENT, settlement_date=bill_date, reference_no=f"PAY-{header.doc_no}", total_amount=paid, status=VendorSettlement.Status.POSTED, posted_at=timezone.now(), posted_by=tenant["actor"])
                        VendorSettlementLine.objects.create(settlement=settlement, open_item=open_item, amount=paid, applied_amount_signed=paid)
                    self._post_entry(tenant, TxnType.PURCHASE, header.id, header.purchase_number, bill_date, [(tenant["expense"], True, TAXABLE), (tenant["input_igst"], True, GST), (tenant["vendor"], False, TOTAL)])
                    inserted += 1
        return inserted

    def _post_entry(self, tenant, txn_type, txn_id, voucher_no, posting_date, lines):
        batch = PostingBatch.objects.create(entity=tenant["entity"], entityfin=tenant["entityfin"], subentity=tenant["subentity"], txn_type=txn_type, txn_id=txn_id, voucher_no=voucher_no, created_by=tenant["actor"])
        entry = Entry.objects.create(entity=tenant["entity"], entityfin=tenant["entityfin"], subentity=tenant["subentity"], txn_type=txn_type, txn_id=txn_id, voucher_no=voucher_no, voucher_date=posting_date, posting_date=posting_date, status=EntryStatus.POSTED, posted_at=timezone.now(), posted_by=tenant["actor"], posting_batch=batch, created_by=tenant["actor"])
        for acc, drcr, amount in lines:
            JournalLine.objects.create(entry=entry, posting_batch=batch, entity=tenant["entity"], entityfin=tenant["entityfin"], subentity=tenant["subentity"], txn_type=txn_type, txn_id=txn_id, voucher_no=voucher_no, account=acc, ledger=acc.ledger, drcr=drcr, amount=amount, posting_date=posting_date, posted_at=timezone.now(), created_by=tenant["actor"])

    def _validate_tenant(self, tenant) -> dict:
        entity = tenant["entity"]
        sales = SalesInvoiceHeader.objects.filter(entity=entity, legacy_source_system="phase2b3b")
        purchase = PurchaseInvoiceHeader.objects.filter(entity=entity, legacy_source_system="phase2b3b")
        lines = JournalLine.objects.filter(entity=entity, txn_id__in=Entry.objects.filter(entity=entity).values("txn_id"))
        debit = lines.filter(drcr=True).aggregate(v=Sum("amount"))["v"] or ZERO
        credit = lines.filter(drcr=False).aggregate(v=Sum("amount"))["v"] or ZERO
        duplicate_sales = sales.values("doc_code", "doc_no").annotate(c=Count("id")).filter(c__gt=1).count()
        duplicate_purchase = purchase.values("doc_code", "doc_no").annotate(c=Count("id")).filter(c__gt=1).count()
        return {
            "sales_count": sales.count(),
            "purchase_count": purchase.count(),
            "ar_open_total": str(CustomerBillOpenItem.objects.filter(entity=entity).aggregate(v=Sum("outstanding_amount"))["v"] or ZERO),
            "ap_open_total": str(VendorBillOpenItem.objects.filter(entity=entity).aggregate(v=Sum("outstanding_amount"))["v"] or ZERO),
            "journal_debit": str(debit),
            "journal_credit": str(credit),
            "balanced": debit == credit,
            "duplicate_sales_doc_numbers": duplicate_sales,
            "duplicate_purchase_doc_numbers": duplicate_purchase,
        }

    def _reset_fixture(self, *, dry_run: bool) -> dict:
        sales = SalesInvoiceHeader.objects.filter(legacy_source_system="phase2b3b")
        purchase = PurchaseInvoiceHeader.objects.filter(legacy_source_system="phase2b3b")
        entity_ids = set(sales.values_list("entity_id", flat=True)) | set(purchase.values_list("entity_id", flat=True))
        preview = {"sales_headers": sales.count(), "purchase_headers": purchase.count(), "entities": len(entity_ids)}
        if dry_run:
            return preview
        with transaction.atomic():
            Entry.objects.filter(entity_id__in=entity_ids).delete()
            purchase.delete()
            sales.delete()
            Entity.objects.filter(id__in=entity_ids, entityname__startswith="Phase2B3B").delete()
        return preview

    def _database_snapshot(self):
        with connection.cursor() as cursor:
            cursor.execute("select current_database(), current_user")
            db_name, db_user = cursor.fetchone()
            cursor.execute("select pg_database_size(current_database())")
            size = cursor.fetchone()[0]
        return {"database": db_name, "user": db_user, "size_bytes": size}

    def _write(self, payload, options):
        if options["json"]:
            self.stdout.write(json.dumps(payload, indent=2, sort_keys=True, default=str))
        else:
            self.stdout.write(json.dumps(payload, indent=2, sort_keys=True, default=str))
