# Generated by Django 5.2.1 on 2026-05-18 03:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('hrms', '0002_globalattendancepolicytemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLeaveBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payroll_period_code', models.CharField(blank=True, default='', max_length=40)),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('snapshot_source', models.CharField(choices=[('opening', 'Opening'), ('accrual', 'Accrual'), ('consumption', 'Consumption'), ('carry_forward', 'Carry Forward'), ('lapse', 'Lapse'), ('encashment', 'Encashment'), ('adjustment', 'Adjustment')], default='adjustment', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accrued_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('consumed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lapsed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('encashed_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('trace_json', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_balance_snapshots', to='hrms.hremploymentcontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='hrms.leavepolicy')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='hrms.leavetype')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract_id', 'leave_type_id', '-snapshot_date', '-created_at'],
                'indexes': [models.Index(fields=['entity', 'contract', 'leave_type'], name='ix_hr_leave_bal_contract'), models.Index(fields=['entity', 'snapshot_date', 'snapshot_source'], name='ix_hr_leave_bal_date')],
            },
        ),
        migrations.CreateModel(
            name='ContractLeaveLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('entry_type', models.CharField(choices=[('opening', 'Opening'), ('accrual', 'Accrual'), ('consumption', 'Consumption'), ('carry_forward', 'Carry Forward'), ('lapse', 'Lapse'), ('encashment', 'Encashment'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=20)),
                ('quantity_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_after_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference_type', models.CharField(blank=True, default='', max_length=40)),
                ('reference_id', models.CharField(blank=True, default='', max_length=80)),
                ('payroll_period_code', models.CharField(blank=True, default='', max_length=40)),
                ('trace_json', models.JSONField(blank=True, default=dict)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_ledger_entries', to='hrms.hremploymentcontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='hrms.leavepolicy')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='hrms.leavetype')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract_id', 'leave_type_id', 'effective_date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['entity', 'contract', 'leave_type', 'effective_date'], name='ix_hr_leave_led_contract'), models.Index(fields=['entity', 'entry_type', 'effective_date'], name='ix_hr_leave_led_type')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('requested_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approved_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unpaid_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('attendance_percentage_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('manager_note', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('application_trace_json', models.JSONField(blank=True, default=dict)),
                ('payroll_impact_json', models.JSONField(blank=True, default=dict)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to='hrms.hremploymentcontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to='hrms.leavepolicy')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hrms.leavetype')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['entity', 'contract', 'status'], name='ix_hr_leave_app_contract'), models.Index(fields=['entity', 'leave_type', 'status'], name='ix_hr_leave_app_type'), models.Index(fields=['entity', 'start_date', 'end_date'], name='ix_hr_leave_app_dates')],
            },
        ),
    ]
