# Generated by Django 5.2.1 on 2026-05-18 04:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('hrms', '0003_contractleavebalancesnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('batch_code', models.CharField(max_length=60)),
                ('import_mode', models.CharField(choices=[('placeholder', 'Placeholder'), ('csv', 'CSV'), ('xlsx', 'XLSX'), ('api', 'API'), ('device', 'Device')], default='placeholder', max_length=20)),
                ('import_status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMonthlyClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payroll_period_code', models.CharField(max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='draft', max_length=20)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('close_note', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_attendance_monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('attendance_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closes', to='hrms.attendancepolicy')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_attendance_monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_attendance_monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_attendance_monthly_closes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payroll_period_code', models.CharField(max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_attendance_approvals', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_approvals', to='hrms.hremploymentcontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_attendance_approvals', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_attendance_approvals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
                ('monthly_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='hrms.attendancemonthlyclose')),
            ],
            options={
                'ordering': ['-period_start', 'contract__contract_code'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('weekly_off', 'Weekly Off'), ('holiday', 'Holiday'), ('leave', 'Leave')], default='present', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('leave_sync', 'Leave Sync'), ('device', 'Device'), ('system', 'System')], default='manual', max_length=20)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_mark', models.BooleanField(default=False)),
                ('attendance_fraction', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('payable_fraction', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('lop_fraction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('trace_json', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_entries', to='hrms.hremploymentcontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='hrms.attendanceimportbatch')),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance_entries', to='hrms.leaveapplication')),
                ('monthly_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='hrms.attendancemonthlyclose')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract_id', 'attendance_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDeviceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attendance_date', models.DateField()),
                ('punch_time', models.DateTimeField()),
                ('device_employee_code', models.CharField(blank=True, default='', max_length=60)),
                ('device_identifier', models.CharField(blank=True, default='', max_length=80)),
                ('punch_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('raw', 'Raw')], default='raw', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_device_logs', to='hrms.hremploymentcontract')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_deleted', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_entity', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_subentity', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_hrms_updated', to=settings.AUTH_USER_MODEL)),
                ('linked_daily_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_logs', to='hrms.dailyattendance')),
            ],
            options={
                'ordering': ['-punch_time', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceimportbatch',
            index=models.Index(fields=['entity', 'import_status', 'uploaded_at'], name='ix_hr_att_import_status'),
        ),
        migrations.AddConstraint(
            model_name='attendanceimportbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity', 'batch_code'), name='uq_hrms_att_import_batch_code'),
        ),
        migrations.AddIndex(
            model_name='attendancemonthlyclose',
            index=models.Index(fields=['entity', 'status'], name='ix_hr_att_close_status'),
        ),
        migrations.AddIndex(
            model_name='attendancemonthlyclose',
            index=models.Index(fields=['entity', 'payroll_period_code'], name='ix_hr_att_close_period'),
        ),
        migrations.AddConstraint(
            model_name='attendancemonthlyclose',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entity', 'subentity', 'payroll_period_code'), name='uq_hrms_att_monthly_close_scope_period'),
        ),
        migrations.AddIndex(
            model_name='attendanceapproval',
            index=models.Index(fields=['entity', 'status'], name='ix_hr_att_approval_status'),
        ),
        migrations.AddIndex(
            model_name='attendanceapproval',
            index=models.Index(fields=['entity', 'payroll_period_code'], name='ix_hr_att_approval_period'),
        ),
        migrations.AddConstraint(
            model_name='attendanceapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('contract', 'payroll_period_code'), name='uq_hrms_att_approval_contract_period'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['entity', 'attendance_date', 'status'], name='ix_hr_daily_att_status'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['entity', 'contract', 'attendance_date'], name='ix_hr_daily_att_contract'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('contract', 'attendance_date'), name='uq_hrms_daily_attendance_contract_date'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicelog',
            index=models.Index(fields=['entity', 'attendance_date'], name='ix_hr_att_device_date'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicelog',
            index=models.Index(fields=['entity', 'device_employee_code'], name='ix_hr_att_device_emp'),
        ),
    ]
