from django.urls import path

from withholding.views import (
    TcsEntityConfigListCreateAPIView,
    TcsEntityConfigRetrieveUpdateDestroyAPIView,
    GstTcsComputationListCreateAPIView,
    GstTcsEcoProfileListCreateAPIView,
    TcsDepositAllocationListAPIView,
    TcsCollectionRetrieveUpdateDestroyAPIView,
    TcsCollectionListCreateAPIView,
    TcsComputationListAPIView,
    TcsDepositRetrieveUpdateDestroyAPIView,
    TcsComputeConfirmAPIView,
    TcsComputePreviewAPIView,
    TcsComputeRecomputeAPIView,
    TcsDepositAllocateAPIView,
    TcsDepositListCreateAPIView,
    TcsPartyProfileListCreateAPIView,
    TcsPartyProfileRetrieveUpdateDestroyAPIView,
    TcsReportLedgerAPIView,
    TcsReturn27EqRetrieveUpdateDestroyAPIView,
    TcsReturn27EqPrefillAPIView,
    TcsSectionRetrieveUpdateDestroyAPIView,
    TcsReturn27EqListCreateAPIView,
    TcsReportFilingPackAPIView,
    TcsSectionListCreateAPIView,
)
from withholding.views_bulk_statutory import (
    TcsSectionsBulkTemplateAPIView,
    TcsSectionsBulkExportAPIView,
    TcsSectionsBulkImportValidateAPIView,
    TcsSectionsBulkImportCommitAPIView,
    TcsConfigsBulkTemplateAPIView,
    TcsConfigsBulkExportAPIView,
    TcsConfigsBulkImportValidateAPIView,
    TcsConfigsBulkImportCommitAPIView,
    TcsBulkJobDetailAPIView,
    TcsBulkJobErrorsExportAPIView,
)

urlpatterns = [
    path("tcs/sections/", TcsSectionListCreateAPIView.as_view(), name="tcs-sections"),
    path("tcs/sections/<int:pk>/", TcsSectionRetrieveUpdateDestroyAPIView.as_view(), name="tcs-section-detail"),
    path("tcs/sections/bulk/template/", TcsSectionsBulkTemplateAPIView.as_view(), name="tcs-sections-bulk-template"),
    path("tcs/sections/bulk/export/", TcsSectionsBulkExportAPIView.as_view(), name="tcs-sections-bulk-export"),
    path("tcs/sections/bulk/import/validate/", TcsSectionsBulkImportValidateAPIView.as_view(), name="tcs-sections-bulk-import-validate"),
    path("tcs/sections/bulk/import/commit/", TcsSectionsBulkImportCommitAPIView.as_view(), name="tcs-sections-bulk-import-commit"),
    path("tcs/rules/", TcsSectionListCreateAPIView.as_view(), name="tcs-rules"),
    path("tcs/rules/<int:pk>/", TcsSectionRetrieveUpdateDestroyAPIView.as_view(), name="tcs-rule-detail"),
    path("tcs/configs/", TcsEntityConfigListCreateAPIView.as_view(), name="tcs-configs"),
    path("tcs/configs/<int:pk>/", TcsEntityConfigRetrieveUpdateDestroyAPIView.as_view(), name="tcs-config-detail"),
    path("tcs/configs/bulk/template/", TcsConfigsBulkTemplateAPIView.as_view(), name="tcs-configs-bulk-template"),
    path("tcs/configs/bulk/export/", TcsConfigsBulkExportAPIView.as_view(), name="tcs-configs-bulk-export"),
    path("tcs/configs/bulk/import/validate/", TcsConfigsBulkImportValidateAPIView.as_view(), name="tcs-configs-bulk-import-validate"),
    path("tcs/configs/bulk/import/commit/", TcsConfigsBulkImportCommitAPIView.as_view(), name="tcs-configs-bulk-import-commit"),
    path("tcs/bulk/jobs/<int:job_id>/", TcsBulkJobDetailAPIView.as_view(), name="tcs-bulk-job-detail"),
    path("tcs/bulk/jobs/<int:job_id>/errors/", TcsBulkJobErrorsExportAPIView.as_view(), name="tcs-bulk-job-errors"),
    path("tcs/party-profiles/", TcsPartyProfileListCreateAPIView.as_view(), name="tcs-party-profiles"),
    path("tcs/party-profiles/<int:pk>/", TcsPartyProfileRetrieveUpdateDestroyAPIView.as_view(), name="tcs-party-profile-detail"),
    path("tcs/compute/preview/", TcsComputePreviewAPIView.as_view(), name="tcs-compute-preview"),
    path("tcs/compute/confirm/", TcsComputeConfirmAPIView.as_view(), name="tcs-compute-confirm"),
    path("tcs/compute/recompute/", TcsComputeRecomputeAPIView.as_view(), name="tcs-compute-recompute"),
    path("tcs/computations/", TcsComputationListAPIView.as_view(), name="tcs-computations"),
    path("tcs/collections/", TcsCollectionListCreateAPIView.as_view(), name="tcs-collections"),
    path("tcs/collections/<int:pk>/", TcsCollectionRetrieveUpdateDestroyAPIView.as_view(), name="tcs-collection-detail"),
    path("tcs/deposits/", TcsDepositListCreateAPIView.as_view(), name="tcs-deposits"),
    path("tcs/deposits/<int:pk>/", TcsDepositRetrieveUpdateDestroyAPIView.as_view(), name="tcs-deposit-detail"),
    path("tcs/deposits/<int:pk>/allocations/", TcsDepositAllocationListAPIView.as_view(), name="tcs-deposit-allocations"),
    path("tcs/deposits/<int:pk>/allocate/", TcsDepositAllocateAPIView.as_view(), name="tcs-deposit-allocate"),
    path("tcs/returns/27eq/", TcsReturn27EqListCreateAPIView.as_view(), name="tcs-return-27eq"),
    path("tcs/returns/27eq/prefill/", TcsReturn27EqPrefillAPIView.as_view(), name="tcs-return-27eq-prefill"),
    path("tcs/returns/27eq/<int:pk>/", TcsReturn27EqRetrieveUpdateDestroyAPIView.as_view(), name="tcs-return-27eq-detail"),
    path("tcs/reports/ledger/", TcsReportLedgerAPIView.as_view(), name="tcs-report-ledger"),
    path("tcs/reports/filing-pack/", TcsReportFilingPackAPIView.as_view(), name="tcs-report-filing-pack"),
    path("gst-tcs/eco-profiles/", GstTcsEcoProfileListCreateAPIView.as_view(), name="gst-tcs-eco-profiles"),
    path("gst-tcs/computations/", GstTcsComputationListCreateAPIView.as_view(), name="gst-tcs-computations"),
]
