from financial.models import Credit, Debit


# Ledger/account head/account code values below intentionally preserve the key
# legacy financial identifiers already used in invoice/reporting code today.
# This keeps onboarding compatible while the rest of the system gradually moves
# toward Ledger-first accounting.
STANDARD_TRADING_TEMPLATE = {
    "account_types": [
        {"code": "1001", "name": "Receivable", "normal_balance": Debit},
        {"code": "1002", "name": "Current Assets", "normal_balance": Debit},
        {"code": "1003", "name": "Bank and Cash", "normal_balance": Debit},
        {"code": "1008", "name": "Payable", "normal_balance": Credit},
        {"code": "1012", "name": "Equity", "normal_balance": Credit},
        {"code": "1014", "name": "Income", "normal_balance": Credit},
        {"code": "1015", "name": "Other Income", "normal_balance": Credit},
        {"code": "1016", "name": "Expenses", "normal_balance": Debit},
    ],
    "account_heads": [
        {
            "code": 200,
            "name": "Closing Stock",
            "type_code": "1002",
            "detailsingroup": 1,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 1000,
            "name": "Purchase",
            "type_code": "1016",
            "detailsingroup": 1,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 2000,
            "name": "Bank",
            "type_code": "1003",
            "detailsingroup": 3,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 3000,
            "name": "Sale",
            "type_code": "1014",
            "detailsingroup": 1,
            "balance_type": Credit,
            "drcreffect": Credit,
        },
        {
            "code": 4000,
            "name": "Cash",
            "type_code": "1003",
            "detailsingroup": 3,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 6000,
            "name": "Advance Payable",
            "type_code": "1008",
            "detailsingroup": 3,
            "balance_type": Credit,
            "drcreffect": Credit,
        },
        {
            "code": 6100,
            "name": "Advance Recoverable",
            "type_code": "1002",
            "detailsingroup": 3,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 6200,
            "name": "Proprietor Capital",
            "type_code": "1012",
            "detailsingroup": 3,
            "balance_type": Credit,
            "drcreffect": Credit,
        },
        {
            "code": 6300,
            "name": "Partner Capital",
            "type_code": "1012",
            "detailsingroup": 3,
            "balance_type": Credit,
            "drcreffect": Credit,
        },
        {
            "code": 7000,
            "name": "Sundry Creditors",
            "type_code": "1008",
            "detailsingroup": 3,
            "balance_type": Credit,
            "drcreffect": Credit,
        },
        {
            "code": 7088,
            "name": "Indirect Income",
            "type_code": "1015",
            "detailsingroup": 2,
            "balance_type": Credit,
            "drcreffect": Credit,
        },
        {
            "code": 8000,
            "name": "Sundry Debtors",
            "type_code": "1001",
            "detailsingroup": 3,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 8300,
            "name": "Direct Expenses",
            "type_code": "1016",
            "detailsingroup": 2,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 8350,
            "name": "Indirect Expenses",
            "type_code": "1016",
            "detailsingroup": 2,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
        {
            "code": 9000,
            "name": "Opening Stock",
            "type_code": "1002",
            "detailsingroup": 1,
            "balance_type": Debit,
            "drcreffect": Debit,
        },
    ],
    "default_accounts": [
        {"code": 200, "name": "Closing Stock", "head_code": 200, "party_type": "Other"},
        {"code": 1000, "name": "Purchase", "head_code": 1000, "credit_head_code": 3000, "party_type": "Other"},
        {"code": 2000, "name": "Bank", "head_code": 2000, "party_type": "Bank"},
        {"code": 3000, "name": "Sale", "head_code": 3000, "party_type": "Other"},
        {"code": 4000, "name": "Cash", "head_code": 4000, "party_type": "Other"},
        {"code": 6000, "name": "Advance Payable", "head_code": 6000, "credit_head_code": 6100, "party_type": "Other"},
        {"code": 6001, "name": "GST(CGST)", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6002, "name": "GST(SGST)", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6003, "name": "GST(IGST)", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6004, "name": "CESS", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6005, "name": "GST(CGST) Reverse", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6006, "name": "GST(SGST) Reverse", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6007, "name": "GST(IGST) Reverse", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 6100, "name": "Advance Recoverable", "head_code": 6100, "party_type": "Other"},
        {"code": 7000, "name": "Sundry Creditors Control", "head_code": 7000, "party_type": "Vendor"},
        {"code": 8000, "name": "Sundry Debtors Control", "head_code": 8000, "credit_head_code": 7000, "party_type": "Customer"},
        {"code": 8050, "name": "TCS206C1H", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 8051, "name": "TCS206C", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 8100, "name": "TDS194Q", "head_code": 6000, "credit_head_code": 6100, "party_type": "Government"},
        {"code": 8400, "name": "Discounts", "head_code": 8350, "party_type": "Other"},
        {"code": 8500, "name": "Bank Charges", "head_code": 8350, "party_type": "Other"},
        {"code": 8504, "name": "Round Off", "head_code": 8350, "party_type": "Other"},
        {"code": 9000, "name": "Opening Stock", "head_code": 9000, "party_type": "Other"},
    ],
}


FINANCIAL_TEMPLATES = {
    "standard_trading": STANDARD_TRADING_TEMPLATE,
}
