# Generated by Django 5.2.1 on 2026-04-18 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_expiry_warning_days_and_more'),
        ('entity', '0020_remove_entity_unittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('promotion_type', models.CharField(choices=[('SAME_ITEM_SLAB', 'Same Item Slab')], default='SAME_ITEM_SLAB', max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommercePromotionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productbarcode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='commerce.commercepromotion')),
            ],
        ),
        migrations.CreateModel(
            name='CommercePromotionSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('min_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('free_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='commerce.commercepromotion')),
            ],
            options={
                'ordering': ['sequence_no', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='commercepromotion',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity__isnull', False)), fields=('entity', 'subentity', 'code'), name='uq_commerce_promotion_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='commercepromotion',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity__isnull', True)), fields=('entity', 'code'), name='uq_commerce_promotion_root_code'),
        ),
        migrations.AddConstraint(
            model_name='commercepromotionscope',
            constraint=models.UniqueConstraint(fields=('promotion', 'product', 'barcode'), name='uq_commerce_promotion_scope_product_barcode'),
        ),
        migrations.AddConstraint(
            model_name='commercepromotionslab',
            constraint=models.UniqueConstraint(fields=('promotion', 'sequence_no'), name='uq_commerce_promotion_slab_sequence'),
        ),
    ]
