# Generated by Django 5.2.1 on 2026-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('entity', '0034_entity_lookup_runtime_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commercepromotion',
            index=models.Index(fields=['entity', 'subentity', 'is_active', 'code'], name='ix_commerce_promo_scope'),
        ),
    ]
