# Generated by Django 5.2.1 on 2026-05-14 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0024_alter_entitygstregistration_gstin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], db_index=True, max_length=20)),
                ('mode', models.CharField(choices=[('outstanding_only', 'Outstanding only'), ('full_history', 'Full history')], db_index=True, max_length=30)),
                ('detail_level', models.CharField(choices=[('header_only', 'Header only'), ('header_plus_lines', 'Header + lines')], default='header_only', max_length=30)),
                ('compliance_mode', models.CharField(choices=[('passive', 'Passive'), ('live', 'Live')], default='passive', max_length=20)),
                ('withholding_mode', models.CharField(choices=[('preserve_legacy', 'Preserve legacy'), ('recompute_finacc', 'Recompute Finacc')], default='preserve_legacy', max_length=30)),
                ('file_format', models.CharField(choices=[('xlsx', 'XLSX'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('failed', 'Failed'), ('committed', 'Committed'), ('partial', 'Partial')], db_index=True, default='pending', max_length=20)),
                ('stock_replay', models.BooleanField(default=False)),
                ('input_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_system', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('reconciliation_summary', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_import_jobs', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('row_no', models.PositiveIntegerField()),
                ('group_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('error', 'Error'), ('imported', 'Imported'), ('skipped', 'Skipped')], db_index=True, default='valid', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('committed_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='invoice_import.importjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['entity', 'module', 'status'], name='ix_invimp_job_scope'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status'], name='ix_invimp_row_job_status'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'group_key'], name='ix_invimp_row_job_group'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('job', 'row_no'), name='uq_invimp_row_job_rowno'),
        ),
    ]
