# Generated by Django 5.2.1 on 2026-05-14 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0024_alter_entitygstregistration_gstin_and_more'),
        ('invoice_import', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='profile_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('source_system', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_import_profiles', to='entity.entity')),
            ],
        ),
        migrations.AddField(
            model_name='importjob',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='invoice_import.importprofile'),
        ),
        migrations.AddIndex(
            model_name='importprofile',
            index=models.Index(fields=['entity', 'module', 'is_default'], name='ix_invimp_profile_default'),
        ),
        migrations.AddConstraint(
            model_name='importprofile',
            constraint=models.UniqueConstraint(fields=('entity', 'module', 'name'), name='uq_invimp_profile_entity_module_name'),
        ),
    ]
