# Generated by Django 5.2.1 on 2026-06-19 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0034_entity_lookup_runtime_indexes'),
        ('invoice_import', '0003_importjob_review_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['entity', 'module', 'created_at'], name='ix_invimp_job_recent'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status', 'row_no'], name='ix_invimp_row_status_ord'),
        ),
    ]
