ENTITY_MASTER_CATALOG = {
    "gst_registration_types": [
        {"name": "Regular", "description": "Regular GST registration."},
        {"name": "Composition", "description": "Composition taxpayer."},
        {"name": "Casual Taxable Person", "description": "Temporary taxable registration."},
        {"name": "Input Service Distributor", "description": "ISD registration."},
        {"name": "SEZ Unit", "description": "Special Economic Zone unit."},
        {"name": "SEZ Developer", "description": "Special Economic Zone developer."},
        {"name": "Non Resident Taxable Person", "description": "Non-resident taxable registration."},
        {"name": "Tax Deductor", "description": "GST TDS deductor registration."},
        {"name": "Tax Collector", "description": "GST TCS collector registration."},
        {"name": "UIN Holder", "description": "Unique Identification Number holder."},
        {"name": "Unregistered", "description": "Entity not registered under GST."},
    ],
    "constitutions": [
        {"code": "PROP", "name": "Proprietorship", "description": "Sole proprietorship business."},
        {"code": "PART", "name": "Partnership Firm", "description": "Traditional partnership firm."},
        {"code": "LLP", "name": "Limited Liability Partnership", "description": "LLP registered under LLP Act."},
        {"code": "PVT", "name": "Private Limited Company", "description": "Private company under Companies Act."},
        {"code": "PUB", "name": "Public Limited Company", "description": "Public company under Companies Act."},
        {"code": "OPC", "name": "One Person Company", "description": "Single-owner corporate entity."},
        {"code": "HUF", "name": "Hindu Undivided Family", "description": "HUF legal structure."},
        {"code": "TRUST", "name": "Trust", "description": "Public or private trust."},
        {"code": "SOC", "name": "Society", "description": "Registered society."},
        {"code": "AOP", "name": "Association of Persons", "description": "Association of persons."},
        {"code": "BOI", "name": "Body of Individuals", "description": "Body of individuals."},
        {"code": "COOP", "name": "Co-operative Society", "description": "Co-operative entity."},
        {"code": "GOV", "name": "Government Department", "description": "Government department or office."},
        {"code": "PSU", "name": "PSU / Government Undertaking", "description": "Public sector undertaking."},
        {"code": "LA", "name": "Local Authority", "description": "Municipality, panchayat, or local body."},
        {"code": "SB", "name": "Statutory Body", "description": "Body created under statute."},
        {"code": "SEC8", "name": "Section 8 Company", "description": "Not-for-profit company."},
        {"code": "EDU", "name": "Educational Institution", "description": "School, college, university, or training institution."},
        {"code": "HOSP", "name": "Hospital / Healthcare Institution", "description": "Hospital, clinic, or healthcare organization."},
        {"code": "FOREIGN", "name": "Foreign Company", "description": "Foreign company or liaison/project office."},
    ],
    "ownership_types": [
        {"name": "Proprietor", "description": "Primary proprietor."},
        {"name": "Partner", "description": "Partner in a firm."},
        {"name": "Designated Partner", "description": "Designated partner in an LLP."},
        {"name": "Director", "description": "Director of a company."},
        {"name": "Managing Director", "description": "Managing director or whole-time director."},
        {"name": "Chairperson", "description": "Chairperson or board head."},
        {"name": "Trustee", "description": "Trustee in a trust."},
        {"name": "Karta", "description": "Karta of an HUF."},
        {"name": "Board Member", "description": "Board or governing body member."},
        {"name": "Authorized Signatory", "description": "Authorized signatory for GST and banking."},
        {"name": "CEO", "description": "Chief executive officer."},
        {"name": "CFO", "description": "Chief financial officer."},
        {"name": "Compliance Officer", "description": "Compliance or statutory officer."},
    ],
}
