# Generated by Django 5.2.1 on 2026-03-11 16:23

import assets.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0004_account_uq_account_entity_accountcode_present'),
        ('posting', '0003_journalline_entitystaticaccountmap_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('nature', models.CharField(choices=[('TANGIBLE', 'Tangible'), ('INTANGIBLE', 'Intangible'), ('ROU', 'Right-of-Use'), ('CWIP', 'Capital Work In Progress')], db_index=True, default='TANGIBLE', max_length=12)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], default='SLM', max_length=10)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
                ('residual_value_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('capitalization_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('accumulated_depreciation_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_acc_dep_ledgers', to='financial.ledger')),
                ('asset_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_asset_ledgers', to='financial.ledger')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cwip_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_cwip_ledgers', to='financial.ledger')),
                ('depreciation_expense_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_dep_expense_ledgers', to='financial.ledger')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='entity.entity')),
                ('gain_on_sale_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_gain_ledgers', to='financial.ledger')),
                ('loss_on_sale_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_loss_ledgers', to='financial.ledger')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_scope', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('default_doc_code_asset', models.CharField(default='FA', max_length=10)),
                ('default_doc_code_disposal', models.CharField(default='FAD', max_length=10)),
                ('default_workflow_action', models.CharField(choices=[('draft', 'Save as Draft'), ('confirm', 'Auto Confirm on Save'), ('post', 'Auto Post on Save')], db_index=True, default='draft', max_length=10)),
                ('default_depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], default='SLM', max_length=10)),
                ('default_useful_life_months', models.PositiveIntegerField(default=60)),
                ('default_residual_value_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('depreciation_posting_day', models.PositiveSmallIntegerField(default=30)),
                ('allow_multiple_asset_books', models.BooleanField(default=False)),
                ('auto_post_depreciation', models.BooleanField(default=False)),
                ('auto_number_assets', models.BooleanField(default=True)),
                ('require_asset_tag', models.BooleanField(default=False)),
                ('enable_component_accounting', models.BooleanField(default=False)),
                ('enable_impairment_tracking', models.BooleanField(default=True)),
                ('capitalization_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('policy_controls', models.JSONField(blank=True, default=assets.models.default_asset_policy_controls)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_settings', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_settings_scope', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('run_code', models.CharField(max_length=50)),
                ('period_from', models.DateField(db_index=True)),
                ('period_to', models.DateField(db_index=True)),
                ('posting_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('depreciation_method', models.CharField(default='SLM', max_length=10)),
                ('total_assets', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_runs', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_runs', to='entity.entityfinancialyear')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciation_runs_posted', to=settings.AUTH_USER_MODEL)),
                ('posting_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciation_runs', to='posting.postingbatch')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_runs_scope', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('asset_code', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CAPITAL_WIP', 'Capital WIP'), ('ACTIVE', 'Active'), ('HELD_FOR_SALE', 'Held for Sale'), ('DISPOSED', 'Disposed'), ('SCRAPPED', 'Scrapped'), ('TRANSFERRED', 'Transferred')], db_index=True, default='DRAFT', max_length=20)),
                ('acquisition_date', models.DateField()),
                ('capitalization_date', models.DateField(blank=True, db_index=True, null=True)),
                ('put_to_use_date', models.DateField(blank=True, null=True)),
                ('depreciation_start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('disposal_date', models.DateField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14)),
                ('gross_block', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], default='SLM', max_length=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('impairment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custodian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='entity.entity')),
                ('entityfinid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_opened', to='entity.entityfinancialyear')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='financial.ledger')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_scope', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_vendors', to='financial.account')),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('opening_gross_block', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('closing_net_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('calculation_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.depreciationrun')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_lines', to='assets.fixedasset')),
            ],
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['entity', 'subentity', 'code'], name='ix_asset_category_scope_code'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['entity', 'subentity', 'nature'], name='ix_asset_category_scope_nature'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity', 'code'), name='uq_asset_category_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity', 'name'), name='uq_asset_category_scope_name'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(check=models.Q(('useful_life_months__gt', 0)), name='ck_asset_category_life_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='assetsettings',
            index=models.Index(fields=['entity'], name='ix_asset_settings_entity'),
        ),
        migrations.AddIndex(
            model_name='assetsettings',
            index=models.Index(fields=['entity', 'subentity'], name='ix_asset_settings_scope'),
        ),
        migrations.AddConstraint(
            model_name='assetsettings',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity'), name='uq_asset_settings_entity_subentity'),
        ),
        migrations.AddIndex(
            model_name='depreciationrun',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'posting_date'], name='ix_fa_dep_scope_dt'),
        ),
        migrations.AddConstraint(
            model_name='depreciationrun',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfinid', 'subentity', 'run_code'), name='uq_asset_dep_run_scope_code'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['entity', 'status'], name='ix_fixed_asset_entity_status'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['entity', 'category', 'status'], name='ix_fa_ent_cat_stat'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['entity', 'capitalization_date'], name='ix_fa_ent_capdate'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['entity', 'depreciation_start_date'], name='ix_fa_ent_depstart'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('entity', 'asset_code'), name='uq_fixed_asset_entity_code'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_tag__isnull', False)), fields=('entity', 'asset_tag'), name='uq_fixed_asset_entity_tag'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(check=models.Q(('gross_block__gte', 0)), name='ck_fixed_asset_gross_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(check=models.Q(('accumulated_depreciation__gte', 0)), name='ck_fixed_asset_accdep_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(check=models.Q(('impairment_amount__gte', 0)), name='ck_fixed_asset_impairment_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(check=models.Q(('useful_life_months__gt', 0)), name='ck_fixed_asset_life_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='depreciationrunline',
            index=models.Index(fields=['asset', 'period_to'], name='ix_fa_depline_ast_dt'),
        ),
        migrations.AddConstraint(
            model_name='depreciationrunline',
            constraint=models.UniqueConstraint(fields=('run', 'asset'), name='uq_asset_dep_run_asset'),
        ),
    ]
