# Generated by Django 5.2.1 on 2026-03-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('posting', '0004_alter_entry_txn_type_alter_inventorymove_txn_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='capitalization_posting_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalized_assets', to='posting.postingbatch'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_posting_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_assets', to='posting.postingbatch'),
        ),
    ]
