# Generated by Django 5.2.1 on 2026-03-11 16:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_fixedasset_capitalization_posting_batch_and_more'),
        ('financial', '0004_account_uq_account_entity_accountcode_present'),
        ('posting', '0005_alter_entry_txn_type_alter_inventorymove_txn_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='impairment_expense_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_impairment_expense_ledgers', to='financial.ledger'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='impairment_reserve_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_category_impairment_reserve_ledgers', to='financial.ledger'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_gain_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_proceeds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='impairment_posting_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impaired_assets', to='posting.postingbatch'),
        ),
    ]
