# Generated by Django 5.2.1 on 2026-04-19 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcategory_impairment_expense_ledger_and_more'),
        ('entity', '0021_alter_entitygstregistration_gstin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scope_type', models.CharField(choices=[('CATEGORY', 'Category'), ('ASSET', 'Fixed Asset')], db_index=True, max_length=20)),
                ('job_type', models.CharField(choices=[('validate', 'Validate'), ('import', 'Import'), ('template', 'Template'), ('export', 'Export')], db_index=True, default='validate', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file_format', models.CharField(choices=[('xlsx', 'XLSX'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('upsert_mode', models.CharField(choices=[('create_only', 'Create only'), ('update_only', 'Update only'), ('upsert', 'Upsert')], default='upsert', max_length=20)),
                ('duplicate_strategy', models.CharField(choices=[('fail', 'Fail'), ('skip', 'Skip'), ('overwrite', 'Overwrite')], default='fail', max_length=20)),
                ('validation_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('input_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_bulk_jobs', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_bulk_jobs', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'scope_type', 'job_type', 'status'], name='ix_asset_bulk_entity_scope_job'), models.Index(fields=['entity', 'validation_token'], name='ix_asset_bulk_entity_token')],
            },
        ),
    ]
