# Generated by Django 5.2.1 on 2026-06-03 04:51

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetcategory_policy_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='accounting_controls',
            field=models.JSONField(blank=True, default=assets.models.default_asset_category_accounting_controls),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='traceability_controls',
            field=models.JSONField(blank=True, default=assets.models.default_asset_category_traceability_controls),
        ),
    ]
