# Generated by Django 5.2.1 on 2026-06-19 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assetcategory_accounting_controls_and_more'),
        ('entity', '0034_entity_lookup_runtime_indexes'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('posting', '0027_inventory_balance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['entity', 'is_active', 'name'], name='ix_asset_cat_ent_act_nm'),
        ),
        migrations.AddIndex(
            model_name='depreciationrun',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'status', 'period_to'], name='ix_fa_dep_scope_stat_to'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['entity', 'subentity', 'is_active', 'id'], name='ix_fa_ent_sub_act_id'),
        ),
    ]
