# Generated by Django 5.2.1 on 2026-04-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0002_split_allocations_and_exceptions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankreconciliationauditlog',
            new_name='bank_reconc_session_04587c_idx',
            old_name='ix_bral_session_action',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationexceptionitem',
            new_name='bank_reconc_session_f6ea63_idx',
            old_name='ix_br_ex_session_type_status',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationmatch',
            new_name='bank_reconc_session_55267e_idx',
            old_name='ix_brm_session_kind',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationmatch',
            new_name='bank_reconc_entry_i_fbc4e3_idx',
            old_name='ix_brm_entry',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationmatch',
            new_name='bank_reconc_journal_c38ee9_idx',
            old_name='ix_brm_journal_line',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationmatchallocation',
            new_name='bank_reconc_match_i_abffd5_idx',
            old_name='ix_bram_match_order',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationmatchallocation',
            new_name='bank_reconc_journal_b50125_idx',
            old_name='ix_bram_journal_line',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationrule',
            new_name='bank_reconc_entity__1078bf_idx',
            old_name='ix_brr_entity_rule_active',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationrule',
            new_name='bank_reconc_entity__1a325c_idx',
            old_name='ix_brr_entity_priority',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationsession',
            new_name='bank_reconc_entity__3a9f46_idx',
            old_name='ix_brs_entity_status',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationsession',
            new_name='bank_reconc_entity__cdfb72_idx',
            old_name='ix_brs_entity_fy_bank',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliationsession',
            new_name='bank_reconc_date_fr_24e0bf_idx',
            old_name='ix_brs_date_range',
        ),
        migrations.RenameIndex(
            model_name='bankstatementbatch',
            new_name='bank_reconc_session_9bd986_idx',
            old_name='ix_bsb_session_format',
        ),
        migrations.RenameIndex(
            model_name='bankstatementbatch',
            new_name='bank_reconc_batch_c_b9da68_idx',
            old_name='ix_bsb_batch_code',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_reconc_batch_i_fdf454_idx',
            old_name='ix_bsl_batch_status',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_reconc_transac_05e4ea_idx',
            old_name='ix_bsl_txn_ref',
        ),
    ]
