# Generated by Django 5.2.1 on 2026-04-19 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0003_rename_ix_bral_session_action_bank_reconc_session_04587c_idx_and_more'),
        ('entity', '0021_alter_entitygstregistration_gstin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], db_index=True, default='csv', max_length=20)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('date_format', models.CharField(blank=True, default='', max_length=40)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entity.entitybankaccountv2')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_import_profiles', to='entity.entity')),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['entity', 'source_format', 'is_active'], name='bank_reconc_entity__cd01c5_idx'), models.Index(fields=['entity', 'bank_account'], name='bank_reconc_entity__7c67a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'name'), name='uq_bank_statement_import_profile_entity_name')],
            },
        ),
    ]
