# Generated by Django 5.2.1 on 2026-06-19 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0004_bankstatementimportprofile'),
        ('entity', '0034_entity_lookup_runtime_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankreconciliationauditlog',
            index=models.Index(fields=['session', 'created_at'], name='ix_bral_sess_created'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationexceptionitem',
            index=models.Index(fields=['session', 'status', 'created_at'], name='ix_brex_sess_stat_ct'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationsession',
            index=models.Index(fields=['entity', 'entityfin', 'subentity', 'bank_account', 'status', 'created_at'], name='ix_brs_scope_bank_stat_ct'),
        ),
        migrations.AddIndex(
            model_name='bankstatementbatch',
            index=models.Index(fields=['session', 'created_at'], name='ix_bsb_sess_created'),
        ),
    ]
