from django.urls import path

from reports.api.financial import (
    BalanceSheetAPIView,
    TradingAccountCSVAPIView,
    TradingAccountExcelAPIView,
    TradingAccountExcelLandscapeAPIView,
    TradingAccountExcelPortraitAPIView,
    LedgerBookCSVAPIView,
    LedgerBookExcelAPIView,
    TrialBalanceCSVAPIView,
    FinancialReportsMetaAPIView,
    LedgerBookAPIView,
    LedgerBookPDFAPIView,
    LedgerBookPrintAPIView,
    ProfitAndLossCSVAPIView,
    ProfitAndLossExcelAPIView,
    ProfitAndLossExcelLandscapeAPIView,
    ProfitAndLossExcelPortraitAPIView,
    ProfitAndLossPDFAPIView,
    ProfitAndLossPDFLandscapeAPIView,
    ProfitAndLossPDFPortraitAPIView,
    ProfitAndLossPrintAPIView,
    TrialBalanceExcelAPIView,
    TrialBalancePDFAPIView,
    ProfitAndLossAPIView,
    TrialBalancePrintAPIView,
    TradingAccountPDFAPIView,
    TradingAccountPDFLandscapeAPIView,
    TradingAccountPDFPortraitAPIView,
    TradingAccountPrintAPIView,
    TradingAccountAPIView,
    TrialBalanceAPIView,
)
from reports.api.assets_views import (
    AssetEventCSVAPIView,
    AssetEventExcelAPIView,
    AssetEventPDFAPIView,
    AssetEventPrintAPIView,
    AssetEventReportAPIView,
    AssetHistoryAPIView,
    DepreciationScheduleAPIView,
    DepreciationScheduleCSVAPIView,
    DepreciationScheduleExcelAPIView,
    DepreciationSchedulePDFAPIView,
    DepreciationSchedulePrintAPIView,
    FixedAssetRegisterAPIView,
    FixedAssetRegisterCSVAPIView,
    FixedAssetRegisterExcelAPIView,
    FixedAssetRegisterPDFAPIView,
    FixedAssetRegisterPrintAPIView,
)
from reports.api.book_views import CashbookAPIView, DaybookAPIView, DaybookEntryDetailAPIView
from reports.api.purchase_register_view import (
    PurchaseRegisterAPIView,
    PurchaseRegisterCSVAPIView,
    PurchaseRegisterExcelAPIView,
    PurchaseRegisterPDFAPIView,
    PurchaseRegisterPrintAPIView,
)
from reports.api.sales_register_view import (
    SalesRegisterAPIView,
    SalesRegisterCSVAPIView,
    SalesRegisterExcelAPIView,
    SalesRegisterPDFAPIView,
    SalesRegisterPrintAPIView,
)
from reports.api.sales_gstin_view import SalesGstinAPIView
from reports.api.ping import ReportsPingAPIView
from reports.gstr1.views import (
    Gstr1ExportAPIView,
    Gstr1InvoiceDetailAPIView,
    Gstr1MetaAPIView,
    Gstr1SectionAPIView,
    Gstr1SummaryAPIView,
    Gstr1TableAPIView,
    Gstr1ValidationAPIView,
)
from reports.gstr3b.views import Gstr3bExportAPIView, Gstr3bMetaAPIView, Gstr3bSummaryAPIView, Gstr3bValidationAPIView
from reports.api.statutory import Gstr1ReportAPIView
from reports.api.receivables_views import (
    CustomerOutstandingReportAPIView,
    CustomerOutstandingCSVAPIView,
    CustomerOutstandingExcelAPIView,
    CustomerOutstandingPDFAPIView,
    CustomerOutstandingPrintAPIView,
    ReceivableAgingReportAPIView,
    ReceivableAgingCSVAPIView,
    ReceivableAgingExcelAPIView,
    ReceivableAgingPDFAPIView,
    ReceivableAgingPrintAPIView,
)
from reports.api.payables_views import (
    VendorOutstandingReportAPIView,
    VendorOutstandingCSVAPIView,
    VendorOutstandingExcelAPIView,
    VendorOutstandingPDFAPIView,
    VendorOutstandingPrintAPIView,
    ApAgingReportAPIView,
    ApAgingCSVAPIView,
    ApAgingExcelAPIView,
    ApAgingPDFAPIView,
    ApAgingPrintAPIView,
    PayablesDashboardSummaryAPIView,
    PayablesReportsMetaAPIView,
)
from reports.api.inventory_views import (
    InventoryReportsMetaAPIView,
    InventoryNonMovingStockAPIView,
    InventoryNonMovingStockCSVAPIView,
    InventoryNonMovingStockExcelAPIView,
    InventoryNonMovingStockPDFAPIView,
    InventoryNonMovingStockPrintAPIView,
    InventoryStockBookDetailAPIView,
    InventoryStockBookDetailCSVAPIView,
    InventoryStockBookDetailExcelAPIView,
    InventoryStockBookDetailPDFAPIView,
    InventoryStockBookDetailPrintAPIView,
    InventoryStockBookSummaryAPIView,
    InventoryStockBookSummaryCSVAPIView,
    InventoryStockBookSummaryExcelAPIView,
    InventoryStockBookSummaryPDFAPIView,
    InventoryStockBookSummaryPrintAPIView,
    InventoryStockDayBookAPIView,
    InventoryStockDayBookCSVAPIView,
    InventoryStockDayBookExcelAPIView,
    InventoryStockDayBookPDFAPIView,
    InventoryStockDayBookPrintAPIView,
    InventoryStockLedgerAPIView,
    InventoryStockLedgerCSVAPIView,
    InventoryStockLedgerExcelAPIView,
    InventoryStockLedgerPDFAPIView,
    InventoryStockLedgerPrintAPIView,
    InventoryStockMovementAPIView,
    InventoryStockMovementCSVAPIView,
    InventoryStockMovementExcelAPIView,
    InventoryStockMovementPDFAPIView,
    InventoryStockMovementPrintAPIView,
    InventoryStockAgingAPIView,
    InventoryStockAgingCSVAPIView,
    InventoryStockAgingExcelAPIView,
    InventoryStockAgingPDFAPIView,
    InventoryStockAgingPrintAPIView,
    InventoryLocationStockAPIView,
    InventoryLocationStockCSVAPIView,
    InventoryLocationStockExcelAPIView,
    InventoryLocationStockPDFAPIView,
    InventoryLocationStockPrintAPIView,
    InventoryReorderStatusAPIView,
    InventoryReorderStatusCSVAPIView,
    InventoryReorderStatusExcelAPIView,
    InventoryReorderStatusPDFAPIView,
    InventoryReorderStatusPrintAPIView,
    InventoryStockSummaryAPIView,
    InventoryStockSummaryCSVAPIView,
    InventoryStockSummaryExcelAPIView,
    InventoryStockSummaryPDFAPIView,
    InventoryStockSummaryPrintAPIView,
)
from reports.api.report_preferences_view import ReportPreferenceAPIView
from reports.api.payables_operational_views import (
    PayablesClosePackAPIView,
    PayablesClosePackCSVAPIView,
    PayablesClosePackExcelAPIView,
    PayablesClosePackPDFAPIView,
    PayablesClosePackPrintAPIView,
    VendorLedgerStatementAPIView,
    VendorLedgerStatementCSVAPIView,
    VendorLedgerStatementExcelAPIView,
    VendorLedgerStatementPDFAPIView,
    VendorLedgerStatementPrintAPIView,
    VendorNoteRegisterAPIView,
    VendorNoteRegisterCSVAPIView,
    VendorNoteRegisterExcelAPIView,
    VendorNoteRegisterPDFAPIView,
    VendorNoteRegisterPrintAPIView,
    VendorSettlementHistoryAPIView,
    VendorSettlementHistoryCSVAPIView,
    VendorSettlementHistoryExcelAPIView,
    VendorSettlementHistoryPDFAPIView,
    VendorSettlementHistoryPrintAPIView,
)
from reports.api.payables_control_views import (
    ApGlReconciliationCSVAPIView,
    ApGlReconciliationExcelAPIView,
    ApGlReconciliationPDFAPIView,
    ApGlReconciliationPrintAPIView,
    ApGlReconciliationReportAPIView,
    PayablesCloseReadinessSummaryAPIView,
    PayablesCloseValidationAPIView,
    VendorBalanceExceptionCSVAPIView,
    VendorBalanceExceptionExcelAPIView,
    VendorBalanceExceptionPDFAPIView,
    VendorBalanceExceptionPrintAPIView,
    VendorBalanceExceptionReportAPIView,
)


app_name = "reports"


urlpatterns = [
    path("ping/", ReportsPingAPIView.as_view(), name="reports-ping"),
    path("financial/meta/", FinancialReportsMetaAPIView.as_view(), name="financial-meta"),
    path("financial/daybook/", DaybookAPIView.as_view(), name="financial-daybook"),
    path("financial/daybook/<int:entry_id>/", DaybookEntryDetailAPIView.as_view(), name="financial-daybook-detail"),
    path("financial/cashbook/", CashbookAPIView.as_view(), name="financial-cashbook"),
    path("purchases/register/", PurchaseRegisterAPIView.as_view(), name="purchase-register"),
    path("purchases/register/excel/", PurchaseRegisterExcelAPIView.as_view(), name="purchase-register-excel"),
    path("purchases/register/pdf/", PurchaseRegisterPDFAPIView.as_view(), name="purchase-register-pdf"),
    path("purchases/register/csv/", PurchaseRegisterCSVAPIView.as_view(), name="purchase-register-csv"),
    path("purchases/register/print/", PurchaseRegisterPrintAPIView.as_view(), name="purchase-register-print"),
    path("sales/register/", SalesRegisterAPIView.as_view(), name="sales-register"),
    path("sales/register/excel/", SalesRegisterExcelAPIView.as_view(), name="sales-register-excel"),
    path("sales/register/pdf/", SalesRegisterPDFAPIView.as_view(), name="sales-register-pdf"),
    path("sales/register/csv/", SalesRegisterCSVAPIView.as_view(), name="sales-register-csv"),
    path("sales/register/print/", SalesRegisterPrintAPIView.as_view(), name="sales-register-print"),
    path("sales/gstin/", SalesGstinAPIView.as_view(), name="sales-gstin"),
    path("inventory/meta/", InventoryReportsMetaAPIView.as_view(), name="inventory-meta"),
    path("inventory/stock-summary/", InventoryStockSummaryAPIView.as_view(), name="inventory-stock-summary"),
    path("inventory/stock-summary/excel/", InventoryStockSummaryExcelAPIView.as_view(), name="inventory-stock-summary-excel"),
    path("inventory/stock-summary/pdf/", InventoryStockSummaryPDFAPIView.as_view(), name="inventory-stock-summary-pdf"),
    path("inventory/stock-summary/csv/", InventoryStockSummaryCSVAPIView.as_view(), name="inventory-stock-summary-csv"),
    path("inventory/stock-summary/print/", InventoryStockSummaryPrintAPIView.as_view(), name="inventory-stock-summary-print"),
    path("inventory/stock-ledger/", InventoryStockLedgerAPIView.as_view(), name="inventory-stock-ledger"),
    path("inventory/stock-ledger/excel/", InventoryStockLedgerExcelAPIView.as_view(), name="inventory-stock-ledger-excel"),
    path("inventory/stock-ledger/pdf/", InventoryStockLedgerPDFAPIView.as_view(), name="inventory-stock-ledger-pdf"),
    path("inventory/stock-ledger/csv/", InventoryStockLedgerCSVAPIView.as_view(), name="inventory-stock-ledger-csv"),
    path("inventory/stock-ledger/print/", InventoryStockLedgerPrintAPIView.as_view(), name="inventory-stock-ledger-print"),
    path("inventory/stock-aging/", InventoryStockAgingAPIView.as_view(), name="inventory-stock-aging"),
    path("inventory/stock-aging/excel/", InventoryStockAgingExcelAPIView.as_view(), name="inventory-stock-aging-excel"),
    path("inventory/stock-aging/pdf/", InventoryStockAgingPDFAPIView.as_view(), name="inventory-stock-aging-pdf"),
    path("inventory/stock-aging/csv/", InventoryStockAgingCSVAPIView.as_view(), name="inventory-stock-aging-csv"),
    path("inventory/stock-aging/print/", InventoryStockAgingPrintAPIView.as_view(), name="inventory-stock-aging-print"),
    path("inventory/location-stock/", InventoryLocationStockAPIView.as_view(), name="inventory-location-stock"),
    path("inventory/location-stock/excel/", InventoryLocationStockExcelAPIView.as_view(), name="inventory-location-stock-excel"),
    path("inventory/location-stock/pdf/", InventoryLocationStockPDFAPIView.as_view(), name="inventory-location-stock-pdf"),
    path("inventory/location-stock/csv/", InventoryLocationStockCSVAPIView.as_view(), name="inventory-location-stock-csv"),
    path("inventory/location-stock/print/", InventoryLocationStockPrintAPIView.as_view(), name="inventory-location-stock-print"),
    path("inventory/non-moving-stock/", InventoryNonMovingStockAPIView.as_view(), name="inventory-non-moving-stock"),
    path("inventory/non-moving-stock/excel/", InventoryNonMovingStockExcelAPIView.as_view(), name="inventory-non-moving-stock-excel"),
    path("inventory/non-moving-stock/pdf/", InventoryNonMovingStockPDFAPIView.as_view(), name="inventory-non-moving-stock-pdf"),
    path("inventory/non-moving-stock/csv/", InventoryNonMovingStockCSVAPIView.as_view(), name="inventory-non-moving-stock-csv"),
    path("inventory/non-moving-stock/print/", InventoryNonMovingStockPrintAPIView.as_view(), name="inventory-non-moving-stock-print"),
    path("inventory/reorder-status/", InventoryReorderStatusAPIView.as_view(), name="inventory-reorder-status"),
    path("inventory/reorder-status/excel/", InventoryReorderStatusExcelAPIView.as_view(), name="inventory-reorder-status-excel"),
    path("inventory/reorder-status/pdf/", InventoryReorderStatusPDFAPIView.as_view(), name="inventory-reorder-status-pdf"),
    path("inventory/reorder-status/csv/", InventoryReorderStatusCSVAPIView.as_view(), name="inventory-reorder-status-csv"),
    path("inventory/reorder-status/print/", InventoryReorderStatusPrintAPIView.as_view(), name="inventory-reorder-status-print"),
    path("inventory/stock-movement/", InventoryStockMovementAPIView.as_view(), name="inventory-stock-movement"),
    path("inventory/stock-movement/excel/", InventoryStockMovementExcelAPIView.as_view(), name="inventory-stock-movement-excel"),
    path("inventory/stock-movement/pdf/", InventoryStockMovementPDFAPIView.as_view(), name="inventory-stock-movement-pdf"),
    path("inventory/stock-movement/csv/", InventoryStockMovementCSVAPIView.as_view(), name="inventory-stock-movement-csv"),
    path("inventory/stock-movement/print/", InventoryStockMovementPrintAPIView.as_view(), name="inventory-stock-movement-print"),
    path("inventory/stock-day-book/", InventoryStockDayBookAPIView.as_view(), name="inventory-stock-day-book"),
    path("inventory/stock-day-book/excel/", InventoryStockDayBookExcelAPIView.as_view(), name="inventory-stock-day-book-excel"),
    path("inventory/stock-day-book/pdf/", InventoryStockDayBookPDFAPIView.as_view(), name="inventory-stock-day-book-pdf"),
    path("inventory/stock-day-book/csv/", InventoryStockDayBookCSVAPIView.as_view(), name="inventory-stock-day-book-csv"),
    path("inventory/stock-day-book/print/", InventoryStockDayBookPrintAPIView.as_view(), name="inventory-stock-day-book-print"),
    path("inventory/stock-book-summary/", InventoryStockBookSummaryAPIView.as_view(), name="inventory-stock-book-summary"),
    path("inventory/stock-book-summary/excel/", InventoryStockBookSummaryExcelAPIView.as_view(), name="inventory-stock-book-summary-excel"),
    path("inventory/stock-book-summary/pdf/", InventoryStockBookSummaryPDFAPIView.as_view(), name="inventory-stock-book-summary-pdf"),
    path("inventory/stock-book-summary/csv/", InventoryStockBookSummaryCSVAPIView.as_view(), name="inventory-stock-book-summary-csv"),
    path("inventory/stock-book-summary/print/", InventoryStockBookSummaryPrintAPIView.as_view(), name="inventory-stock-book-summary-print"),
    path("inventory/stock-book-detail/", InventoryStockBookDetailAPIView.as_view(), name="inventory-stock-book-detail"),
    path("inventory/stock-book-detail/excel/", InventoryStockBookDetailExcelAPIView.as_view(), name="inventory-stock-book-detail-excel"),
    path("inventory/stock-book-detail/pdf/", InventoryStockBookDetailPDFAPIView.as_view(), name="inventory-stock-book-detail-pdf"),
    path("inventory/stock-book-detail/csv/", InventoryStockBookDetailCSVAPIView.as_view(), name="inventory-stock-book-detail-csv"),
    path("inventory/stock-book-detail/print/", InventoryStockBookDetailPrintAPIView.as_view(), name="inventory-stock-book-detail-print"),
    path("gstr1/summary/", Gstr1SummaryAPIView.as_view(), name="gstr1-summary"),
    path("gstr1/meta/", Gstr1MetaAPIView.as_view(), name="gstr1-meta"),
    path("gstr1/section/<str:section_name>/", Gstr1SectionAPIView.as_view(), name="gstr1-section"),
    path("gstr1/table/<str:table_code>/", Gstr1TableAPIView.as_view(), name="gstr1-table"),
    path("gstr1/validations/", Gstr1ValidationAPIView.as_view(), name="gstr1-validations"),
    path("gstr1/export/", Gstr1ExportAPIView.as_view(), name="gstr1-export"),
    path("gstr1/invoice/<int:invoice_id>/", Gstr1InvoiceDetailAPIView.as_view(), name="gstr1-invoice-detail"),
    path("gstr3b/summary/", Gstr3bSummaryAPIView.as_view(), name="gstr3b-summary"),
    path("gstr3b/meta/", Gstr3bMetaAPIView.as_view(), name="gstr3b-meta"),
    path("gstr3b/validations/", Gstr3bValidationAPIView.as_view(), name="gstr3b-validations"),
    path("gstr3b/export/", Gstr3bExportAPIView.as_view(), name="gstr3b-export"),
    path("gstr3b/export", Gstr3bExportAPIView.as_view(), name="gstr3b-export-noslash"),
    # Backward-compatible aliases for older frontend routes.
    path("gstr3b1/summary/", Gstr3bSummaryAPIView.as_view(), name="gstr3b1-summary"),
    path("gstr3b1/meta/", Gstr3bMetaAPIView.as_view(), name="gstr3b1-meta"),
    path("gstr3b1/validations/", Gstr3bValidationAPIView.as_view(), name="gstr3b1-validations"),
    path("gstr3b1/export/", Gstr3bExportAPIView.as_view(), name="gstr3b1-export"),
    path("gstr3b1/export", Gstr3bExportAPIView.as_view(), name="gstr3b1-export-noslash"),
    path("statutory/gstr1/", Gstr1ReportAPIView.as_view(), name="gstr1-register"),
    path("financial/trial-balance/", TrialBalanceAPIView.as_view(), name="financial-trial-balance"),
    path("financial/trial-balance/excel/", TrialBalanceExcelAPIView.as_view(), name="financial-trial-balance-excel"),
    path("financial/trial-balance/pdf/", TrialBalancePDFAPIView.as_view(), name="financial-trial-balance-pdf"),
    path("financial/trial-balance/csv/", TrialBalanceCSVAPIView.as_view(), name="financial-trial-balance-csv"),
    path("financial/trial-balance/print/", TrialBalancePrintAPIView.as_view(), name="financial-trial-balance-print"),
    path("financial/ledger-book/", LedgerBookAPIView.as_view(), name="financial-ledger-book"),
    path("financial/ledger-book/excel/", LedgerBookExcelAPIView.as_view(), name="financial-ledger-book-excel"),
    path("financial/ledger-book/pdf/", LedgerBookPDFAPIView.as_view(), name="financial-ledger-book-pdf"),
    path("financial/ledger-book/csv/", LedgerBookCSVAPIView.as_view(), name="financial-ledger-book-csv"),
    path("financial/ledger-book/print/", LedgerBookPrintAPIView.as_view(), name="financial-ledger-book-print"),
    path("financial/profit-loss/", ProfitAndLossAPIView.as_view(), name="financial-profit-loss"),
    path("financial/profit-loss/excel/", ProfitAndLossExcelAPIView.as_view(), name="financial-profit-loss-excel"),
    path("financial/profit-loss/excel/landscape/", ProfitAndLossExcelLandscapeAPIView.as_view(), name="financial-profit-loss-excel-landscape"),
    path("financial/profit-loss/excel/portrait/", ProfitAndLossExcelPortraitAPIView.as_view(), name="financial-profit-loss-excel-portrait"),
    path("financial/profit-loss/pdf/", ProfitAndLossPDFAPIView.as_view(), name="financial-profit-loss-pdf"),
    path("financial/profit-loss/pdf/landscape/", ProfitAndLossPDFLandscapeAPIView.as_view(), name="financial-profit-loss-pdf-landscape"),
    path("financial/profit-loss/pdf/portrait/", ProfitAndLossPDFPortraitAPIView.as_view(), name="financial-profit-loss-pdf-portrait"),
    path("financial/profit-loss/csv/", ProfitAndLossCSVAPIView.as_view(), name="financial-profit-loss-csv"),
    path("financial/profit-loss/print/", ProfitAndLossPrintAPIView.as_view(), name="financial-profit-loss-print"),
    path("financial/balance-sheet/", BalanceSheetAPIView.as_view(), name="financial-balance-sheet"),
    path("financial/trading-account/", TradingAccountAPIView.as_view(), name="financial-trading-account"),
    path("financial/trading-account/excel/", TradingAccountExcelAPIView.as_view(), name="financial-trading-account-excel"),
    path("financial/trading-account/excel/landscape/", TradingAccountExcelLandscapeAPIView.as_view(), name="financial-trading-account-excel-landscape"),
    path("financial/trading-account/excel/portrait/", TradingAccountExcelPortraitAPIView.as_view(), name="financial-trading-account-excel-portrait"),
    path("financial/trading-account/pdf/", TradingAccountPDFAPIView.as_view(), name="financial-trading-account-pdf"),
    path("financial/trading-account/pdf/landscape/", TradingAccountPDFLandscapeAPIView.as_view(), name="financial-trading-account-pdf-landscape"),
    path("financial/trading-account/pdf/portrait/", TradingAccountPDFPortraitAPIView.as_view(), name="financial-trading-account-pdf-portrait"),
    path("financial/trading-account/csv/", TradingAccountCSVAPIView.as_view(), name="financial-trading-account-csv"),
    path("financial/trading-account/print/", TradingAccountPrintAPIView.as_view(), name="financial-trading-account-print"),
    path("trading-account", TradingAccountAPIView.as_view(), name="trading-account-noslash"),
    path("trading-account/", TradingAccountAPIView.as_view(), name="trading-account"),
    path("fixed-assets/register/", FixedAssetRegisterAPIView.as_view(), name="fixed-asset-register"),
    path("fixed-assets/register/excel/", FixedAssetRegisterExcelAPIView.as_view(), name="fixed-asset-register-excel"),
    path("fixed-assets/register/pdf/", FixedAssetRegisterPDFAPIView.as_view(), name="fixed-asset-register-pdf"),
    path("fixed-assets/register/csv/", FixedAssetRegisterCSVAPIView.as_view(), name="fixed-asset-register-csv"),
    path("fixed-assets/register/print/", FixedAssetRegisterPrintAPIView.as_view(), name="fixed-asset-register-print"),
    path("fixed-assets/depreciation-schedule/", DepreciationScheduleAPIView.as_view(), name="depreciation-schedule"),
    path("fixed-assets/depreciation-schedule/excel/", DepreciationScheduleExcelAPIView.as_view(), name="depreciation-schedule-excel"),
    path("fixed-assets/depreciation-schedule/pdf/", DepreciationSchedulePDFAPIView.as_view(), name="depreciation-schedule-pdf"),
    path("fixed-assets/depreciation-schedule/csv/", DepreciationScheduleCSVAPIView.as_view(), name="depreciation-schedule-csv"),
    path("fixed-assets/depreciation-schedule/print/", DepreciationSchedulePrintAPIView.as_view(), name="depreciation-schedule-print"),
    path("fixed-assets/events/", AssetEventReportAPIView.as_view(), name="fixed-asset-events"),
    path("fixed-assets/events/excel/", AssetEventExcelAPIView.as_view(), name="fixed-asset-events-excel"),
    path("fixed-assets/events/pdf/", AssetEventPDFAPIView.as_view(), name="fixed-asset-events-pdf"),
    path("fixed-assets/events/csv/", AssetEventCSVAPIView.as_view(), name="fixed-asset-events-csv"),
    path("fixed-assets/events/print/", AssetEventPrintAPIView.as_view(), name="fixed-asset-events-print"),
    path("fixed-assets/history/", AssetHistoryAPIView.as_view(), name="fixed-asset-history"),
    path("receivables/customer-outstanding/", CustomerOutstandingReportAPIView.as_view(), name="customer-outstanding-report"),
    path("receivables/customer-outstanding/excel/", CustomerOutstandingExcelAPIView.as_view(), name="customer-outstanding-report-excel"),
    path("receivables/customer-outstanding/pdf/", CustomerOutstandingPDFAPIView.as_view(), name="customer-outstanding-report-pdf"),
    path("receivables/customer-outstanding/csv/", CustomerOutstandingCSVAPIView.as_view(), name="customer-outstanding-report-csv"),
    path("receivables/customer-outstanding/print/", CustomerOutstandingPrintAPIView.as_view(), name="customer-outstanding-report-print"),
    path("receivables/aging/", ReceivableAgingReportAPIView.as_view(), name="receivable-aging-report"),
    path("receivables/aging/excel/", ReceivableAgingExcelAPIView.as_view(), name="receivable-aging-report-excel"),
    path("receivables/aging/pdf/", ReceivableAgingPDFAPIView.as_view(), name="receivable-aging-report-pdf"),
    path("receivables/aging/csv/", ReceivableAgingCSVAPIView.as_view(), name="receivable-aging-report-csv"),
    path("receivables/aging/print/", ReceivableAgingPrintAPIView.as_view(), name="receivable-aging-report-print"),
    path("payables/meta/", PayablesReportsMetaAPIView.as_view(), name="payables-meta"),
    path("payables/dashboard-summary/", PayablesDashboardSummaryAPIView.as_view(), name="payables-dashboard-summary"),
    path("payables/reconciliation/", ApGlReconciliationReportAPIView.as_view(), name="ap-gl-reconciliation-report"),
    path("payables/reconciliation/excel/", ApGlReconciliationExcelAPIView.as_view(), name="ap-gl-reconciliation-report-excel"),
    path("payables/reconciliation/pdf/", ApGlReconciliationPDFAPIView.as_view(), name="ap-gl-reconciliation-report-pdf"),
    path("payables/reconciliation/csv/", ApGlReconciliationCSVAPIView.as_view(), name="ap-gl-reconciliation-report-csv"),
    path("payables/reconciliation/print/", ApGlReconciliationPrintAPIView.as_view(), name="ap-gl-reconciliation-report-print"),
    path("payables/exceptions/", VendorBalanceExceptionReportAPIView.as_view(), name="vendor-balance-exception-report"),
    path("payables/exceptions/excel/", VendorBalanceExceptionExcelAPIView.as_view(), name="vendor-balance-exception-report-excel"),
    path("payables/exceptions/pdf/", VendorBalanceExceptionPDFAPIView.as_view(), name="vendor-balance-exception-report-pdf"),
    path("payables/exceptions/csv/", VendorBalanceExceptionCSVAPIView.as_view(), name="vendor-balance-exception-report-csv"),
    path("payables/exceptions/print/", VendorBalanceExceptionPrintAPIView.as_view(), name="vendor-balance-exception-report-print"),
    path("payables/close-validation/", PayablesCloseValidationAPIView.as_view(), name="payables-close-validation"),
    path("payables/close-readiness-summary/", PayablesCloseReadinessSummaryAPIView.as_view(), name="payables-close-readiness-summary"),
    path("payables/vendor-ledger/", VendorLedgerStatementAPIView.as_view(), name="vendor-ledger-statement"),
    path("payables/vendor-ledger/excel/", VendorLedgerStatementExcelAPIView.as_view(), name="vendor-ledger-statement-excel"),
    path("payables/vendor-ledger/pdf/", VendorLedgerStatementPDFAPIView.as_view(), name="vendor-ledger-statement-pdf"),
    path("payables/vendor-ledger/csv/", VendorLedgerStatementCSVAPIView.as_view(), name="vendor-ledger-statement-csv"),
    path("payables/vendor-ledger/print/", VendorLedgerStatementPrintAPIView.as_view(), name="vendor-ledger-statement-print"),
    path("payables/settlement-history/", VendorSettlementHistoryAPIView.as_view(), name="vendor-settlement-history"),
    path("payables/settlement-history/excel/", VendorSettlementHistoryExcelAPIView.as_view(), name="vendor-settlement-history-excel"),
    path("payables/settlement-history/pdf/", VendorSettlementHistoryPDFAPIView.as_view(), name="vendor-settlement-history-pdf"),
    path("payables/settlement-history/csv/", VendorSettlementHistoryCSVAPIView.as_view(), name="vendor-settlement-history-csv"),
    path("payables/settlement-history/print/", VendorSettlementHistoryPrintAPIView.as_view(), name="vendor-settlement-history-print"),
    path("payables/note-register/", VendorNoteRegisterAPIView.as_view(), name="vendor-note-register"),
    path("payables/note-register/excel/", VendorNoteRegisterExcelAPIView.as_view(), name="vendor-note-register-excel"),
    path("payables/note-register/pdf/", VendorNoteRegisterPDFAPIView.as_view(), name="vendor-note-register-pdf"),
    path("payables/note-register/csv/", VendorNoteRegisterCSVAPIView.as_view(), name="vendor-note-register-csv"),
    path("payables/note-register/print/", VendorNoteRegisterPrintAPIView.as_view(), name="vendor-note-register-print"),
    path("payables/close-pack/", PayablesClosePackAPIView.as_view(), name="payables-close-pack"),
    path("payables/close-pack/excel/", PayablesClosePackExcelAPIView.as_view(), name="payables-close-pack-excel"),
    path("payables/close-pack/pdf/", PayablesClosePackPDFAPIView.as_view(), name="payables-close-pack-pdf"),
    path("payables/close-pack/csv/", PayablesClosePackCSVAPIView.as_view(), name="payables-close-pack-csv"),
    path("payables/close-pack/print/", PayablesClosePackPrintAPIView.as_view(), name="payables-close-pack-print"),
    path("payables/vendor-outstanding/", VendorOutstandingReportAPIView.as_view(), name="vendor-outstanding-report"),
    path("payables/vendor-outstanding/excel/", VendorOutstandingExcelAPIView.as_view(), name="vendor-outstanding-report-excel"),
    path("payables/vendor-outstanding/pdf/", VendorOutstandingPDFAPIView.as_view(), name="vendor-outstanding-report-pdf"),
    path("payables/vendor-outstanding/csv/", VendorOutstandingCSVAPIView.as_view(), name="vendor-outstanding-report-csv"),
    path("payables/vendor-outstanding/print/", VendorOutstandingPrintAPIView.as_view(), name="vendor-outstanding-report-print"),
    path("payables/aging/", ApAgingReportAPIView.as_view(), name="ap-aging-report"),
    path("payables/accountspayableaging/", ApAgingReportAPIView.as_view(), name="accountspayableaging-report"),
    path("accounts-payable-aging/", ApAgingReportAPIView.as_view(), name="accounts-payable-aging-report"),
    path("payables/aging/excel/", ApAgingExcelAPIView.as_view(), name="ap-aging-report-excel"),
    path("payables/accountspayableaging/excel/", ApAgingExcelAPIView.as_view(), name="accountspayableaging-report-excel"),
    path("accounts-payable-aging/excel/", ApAgingExcelAPIView.as_view(), name="accounts-payable-aging-report-excel"),
    path("payables/aging/pdf/", ApAgingPDFAPIView.as_view(), name="ap-aging-report-pdf"),
    path("payables/accountspayableaging/pdf/", ApAgingPDFAPIView.as_view(), name="accountspayableaging-report-pdf"),
    path("accounts-payable-aging/pdf/", ApAgingPDFAPIView.as_view(), name="accounts-payable-aging-report-pdf"),
    path("payables/aging/csv/", ApAgingCSVAPIView.as_view(), name="ap-aging-report-csv"),
    path("payables/accountspayableaging/csv/", ApAgingCSVAPIView.as_view(), name="accountspayableaging-report-csv"),
    path("accounts-payable-aging/csv/", ApAgingCSVAPIView.as_view(), name="accounts-payable-aging-report-csv"),
    path("payables/aging/print/", ApAgingPrintAPIView.as_view(), name="ap-aging-report-print"),
    path("payables/accountspayableaging/print/", ApAgingPrintAPIView.as_view(), name="accountspayableaging-report-print"),
    path("accounts-payable-aging/print/", ApAgingPrintAPIView.as_view(), name="accounts-payable-aging-report-print"),
    path("preferences/", ReportPreferenceAPIView.as_view(), name="report-preferences"),
]

