# Generated by Django 5.2.1 on 2026-03-07 13:30

import django.db.models.deletion
import django.utils.timezone
import receipts.models.receipt_config
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucherAdvanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_full_settlement', models.BooleanField(default=False)),
                ('is_advance_adjustment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('doc_code', models.CharField(default='RV', max_length=10)),
                ('doc_no', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(db_index=True, default='INR', max_length=3)),
                ('base_currency_code', models.CharField(default='INR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18)),
                ('receipt_type', models.CharField(choices=[('AGAINST_INVOICE', 'Against Invoice'), ('ADVANCE', 'Advance Receipt'), ('ON_ACCOUNT', 'On Account')], default='AGAINST_INVOICE', max_length=20)),
                ('supply_type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services'), ('MIXED', 'Mixed/Unknown')], default='SERVICES', max_length=10)),
                ('cash_received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_effective_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_effective_amount_base_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('instrument_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_no', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument_date', models.DateField(blank=True, null=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('advance_taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('advance_cess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Confirmed'), (3, 'Posted'), (9, 'Cancelled')], db_index=True, default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_payload', models.JSONField(blank=True, default=dict)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paymentmode', models.CharField(max_length=200, verbose_name='Receipt Mode')),
                ('paymentmodecode', models.CharField(max_length=20, verbose_name='Receipt Mode Code')),
                ('iscash', models.BooleanField(default=True, verbose_name='IsCash Transaction')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('paymentmode', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_doc_code_receipt', models.CharField(default='RV', max_length=10)),
                ('default_workflow_action', models.CharField(choices=[('draft', 'Save as Draft'), ('confirm', 'Auto Confirm on Save'), ('post', 'Auto Post on Save')], db_index=True, default='draft', max_length=10)),
                ('policy_controls', models.JSONField(blank=True, default=receipts.models.receipt_config.default_receipt_policy_controls)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_settings', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_settings', to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adj_type', models.CharField(choices=[('TDS', 'TDS'), ('TCS', 'TCS'), ('DISCOUNT_ALLOWED', 'Discount Allowed'), ('BANK_CHARGES', 'Bank Charges'), ('ROUND_OFF', 'Round Off'), ('WRITE_OFF', 'Write Off'), ('FX_DIFF', 'Forex Difference'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_effect', models.CharField(choices=[('PLUS', 'Plus'), ('MINUS', 'Minus')], default='PLUS', max_length=5)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_receipt_adjustment_ledgers', to='financial.account')),
            ],
        ),
    ]
