# Generated by Django 5.2.1 on 2026-03-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('geography', '0001_initial'),
        ('receipts', '0001_initial'),
        ('sales', '0022_customeradvancebalance_customerbillopenitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucheradvanceadjustment',
            name='advance_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_advance_adjustments', to='sales.customeradvancebalance'),
        ),
        migrations.AddField(
            model_name='receiptvoucheradvanceadjustment',
            name='ap_settlement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_advance_adjustment', to='sales.customersettlement'),
        ),
        migrations.AddField(
            model_name='receiptvoucheradvanceadjustment',
            name='open_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_advance_adjustments', to='sales.customerbillopenitem'),
        ),
        migrations.AddField(
            model_name='receiptvoucherallocation',
            name='open_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='sales.customerbillopenitem'),
        ),
        migrations.AddField(
            model_name='receiptvoucheradvanceadjustment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_adjustments', to='receipts.receiptvoucherallocation'),
        ),
        migrations.AddField(
            model_name='receiptvoucheradjustment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='receipts.receiptvoucherallocation'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='ap_settlement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_voucher', to='sales.customersettlement'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_rv_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_receipt_vouchers_cancelled', related_query_name='new_receipt_voucher_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_rv_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='entityfinid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='place_of_supply_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.state'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='receipt_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receipts.receiptmode'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='received_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_rv_received_from', to='financial.account'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='received_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_rv_received_in', to='financial.account'),
        ),
        migrations.AddField(
            model_name='receiptvoucherheader',
            name='subentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity'),
        ),
        migrations.AddField(
            model_name='receiptvoucherallocation',
            name='receipt_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receipts.receiptvoucherheader'),
        ),
        migrations.AddField(
            model_name='receiptvoucheradvanceadjustment',
            name='receipt_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_adjustments', to='receipts.receiptvoucherheader'),
        ),
        migrations.AddField(
            model_name='receiptvoucheradjustment',
            name='receipt_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='receipts.receiptvoucherheader'),
        ),
        migrations.AddConstraint(
            model_name='receiptmode',
            constraint=models.UniqueConstraint(fields=('paymentmodecode',), name='uq_receipt_mode_code'),
        ),
        migrations.AddIndex(
            model_name='receiptsettings',
            index=models.Index(fields=['entity'], name='ix_receipt_settings_entity'),
        ),
        migrations.AddConstraint(
            model_name='receiptsettings',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity'), name='uq_receipt_settings_entity_subentity'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'voucher_date'], name='ix_receipt_ent_fin_date'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'received_from'], name='ix_receipt_ent_fin_customer'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'status'], name='ix_receipt_ent_fin_status'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucherheader',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfinid', 'doc_code', 'doc_no'), name='uq_receipt_voucher_entity_fin_code_no'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucherheader',
            constraint=models.CheckConstraint(check=models.Q(('cash_received_amount__gte', 0)), name='ck_receipt_cash_nonneg'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucherallocation',
            index=models.Index(fields=['receipt_voucher'], name='ix_receipt_alloc_voucher'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucherallocation',
            index=models.Index(fields=['open_item'], name='ix_receipt_alloc_openitem'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucherallocation',
            constraint=models.CheckConstraint(check=models.Q(('settled_amount__gte', 0)), name='ck_receipt_alloc_amt_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucherallocation',
            constraint=models.UniqueConstraint(fields=('receipt_voucher', 'open_item'), name='uq_receipt_alloc_voucher_openitem'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucheradvanceadjustment',
            index=models.Index(fields=['receipt_voucher'], name='ix_receipt_adv_adj_voucher'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucheradvanceadjustment',
            index=models.Index(fields=['advance_balance'], name='ix_receipt_adv_adj_balance'),
        ),
        migrations.AddIndex(
            model_name='receiptvoucheradvanceadjustment',
            index=models.Index(fields=['open_item'], name='ix_receipt_adv_adj_openitem'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucheradvanceadjustment',
            constraint=models.CheckConstraint(check=models.Q(('adjusted_amount__gte', 0)), name='ck_receipt_adv_adj_amt_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucheradjustment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='ck_receipt_adj_amt_nonneg'),
        ),
    ]
