# Generated by Django 5.2.1 on 2026-08-02 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('geography', '0004_geography_runtime_indexes'),
        ('receipts', '0010_seed_receipt_modes'),
        ('sales', '0047_sales_invoice_list_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='receiptvoucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'received_from', 'subentity', 'reference_number'], name='ix_rec_ref_warn_scope'),
        ),
    ]
