# Generated by Django 4.2.28 on 2026-02-28 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='tds_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='tds_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='tds_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
