# Generated by Django 4.2.28 on 2026-03-02 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseinvoiceheader_tds_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_contract_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='gst_tds_status',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Eligible'), (2, 'Deducted'), (3, 'Deposited'), (4, 'Reported (GSTR-7)')], db_index=True, default=0),
        ),
    ]
