# Generated by Django 4.2.28 on 2026-03-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseinvoiceheader_gst_tds_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasechargeline',
            name='charge_type',
            field=models.CharField(choices=[('FREIGHT', 'Freight'), ('PACKING', 'Packing'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasechargeline',
            name='hsn_sac_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='purchasechargeline',
            name='is_rate_inclusive_of_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasechargeline',
            name='is_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchasechargeline',
            name='itc_block_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='purchasechargeline',
            name='itc_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchasechargeline',
            name='taxability',
            field=models.CharField(choices=[('TAXABLE', 'Taxable'), ('EXEMPT', 'Exempt'), ('NIL', 'Nil Rated'), ('NON_GST', 'Non-GST')], default='TAXABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasechargeline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='purchasechargeline',
            index=models.Index(fields=['header', 'charge_type'], name='ix_purchase_charge_hdr_type'),
        ),
        migrations.AddIndex(
            model_name='purchasechargeline',
            index=models.Index(fields=['header', 'taxability', 'gst_rate'], name='ix_purchase_charge_hdr_tax'),
        ),
        migrations.AddConstraint(
            model_name='purchasechargeline',
            constraint=models.CheckConstraint(check=models.Q(('gst_rate', 0), ('taxable_value', 0), models.Q(('hsn_sac_code', ''), _negated=True), _connector='OR'), name='ck_purchase_charge_hsn_required_when_gst'),
        ),
    ]
