# Generated by Django 4.2.28 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_purchasechargeline_charge_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoiceheader",
            name="gst_tds_is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseinvoiceheader",
            name="tds_is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
