# Generated by Django 4.2.28 on 2026-03-03 16:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('purchase', '0006_purchaseinvoiceheader_gst_tds_is_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('base_category', models.CharField(choices=[('FREIGHT', 'Freight'), ('PACKING', 'Packing'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=True)),
                ('hsn_sac_code_default', models.CharField(blank=True, default='', max_length=16)),
                ('gst_rate_default', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('itc_eligible_default', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_charge_types', to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'is_active'], name='ix_charge_type_entity_active'), models.Index(fields=['entity', 'base_category'], name='ix_charge_type_entity_cat')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchasechargetype',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='uq_purchase_charge_type_entity_code'),
        ),
        migrations.AddConstraint(
            model_name='purchasechargetype',
            constraint=models.CheckConstraint(check=models.Q(('gst_rate_default__gte', 0), ('gst_rate_default__lte', 100)), name='ck_purchase_charge_type_gst_rate_bounds'),
        ),
    ]
