# Generated by Django 4.2.28 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_purchasechargetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasesettings",
            name="post_gst_tds_on_invoice",
            field=models.BooleanField(default=False),
        ),
    ]
