# Generated by Django 4.2.28 on 2026-03-04 05:25

from django.db import migrations, models
import purchase.models.purchase_config


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_vendor_ap_models_and_policy_settlement_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesettings',
            name='policy_controls',
            field=models.JSONField(blank=True, default=purchase.models.purchase_config.default_policy_controls),
        ),
    ]
