# Generated by Django 5.2.1 on 2026-03-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('purchase', '0017_purchase_reporting_foundation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasestatutoryreturnline',
            name='deductee_country_code_snapshot',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasestatutoryreturnline',
            name='deductee_country_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasestatutoryreturnline',
            name='deductee_country_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_statutory_return_lines', to='geography.country'),
        ),
        migrations.AddField(
            model_name='purchasestatutoryreturnline',
            name='deductee_residency_snapshot',
            field=models.CharField(blank=True, choices=[('RESIDENT', 'Resident'), ('NON_RESIDENT', 'Non-Resident')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasestatutoryreturnline',
            name='deductee_tax_id_snapshot',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
