# Generated by Django 5.2.1 on 2026-03-06 16:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('payments', '0004_paymentvoucherheader_workflow_payload'),
        ('purchase', '0019_purchase_statutory_return_unique_original_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAdvanceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('payment_advance', 'Payment Advance'), ('on_account', 'On Account'), ('manual', 'Manual')], db_index=True, default='payment_advance', max_length=30)),
                ('credit_date', models.DateField(db_index=True)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding_amount', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('last_adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear')),
                ('payment_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_advance_balance', to='payments.paymentvoucherheader')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
            ],
        ),
        migrations.AddField(
            model_name='vendorsettlement',
            name='advance_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='purchase.vendoradvancebalance'),
        ),
        migrations.AddIndex(
            model_name='vendoradvancebalance',
            index=models.Index(fields=['entity', 'entityfinid', 'vendor', 'is_open'], name='ix_pur_adv_scope'),
        ),
        migrations.AddIndex(
            model_name='vendoradvancebalance',
            index=models.Index(fields=['entity', 'entityfinid', 'credit_date'], name='ix_pur_adv_creditdt'),
        ),
    ]
