# Generated by Django 5.2.1 on 2026-03-25 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0010_remove_account_address1_remove_account_address2_and_more'),
        ('geography', '0001_initial'),
        ('purchase', '0022_remove_purchaseinvoiceheader_uq_purchase_doc_entity_fin_type_code_no_and_more'),
        ('withholding', '0002_withholdingsection_law_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseinvoiceheader',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_no__isnull', False), ('subentity__isnull', True)), fields=('entity', 'entityfinid', 'doc_type', 'doc_code', 'doc_no'), name='uq_purchase_doc_root_type_code_no'),
        ),
    ]
