# Generated by Django 5.2.1 on 2026-03-29 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_invoicecustomfielddefault_options_and_more'),
        ('purchase', '0024_purchaseinvoiceheader_custom_fields_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='financial.account'),
        ),
    ]
