# Generated by Django 4.2.28 on 2026-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0026_purchasestatutoryform16aofficialdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='affects_inventory',
            field=models.BooleanField(default=False, help_text='If True, posting will reverse/add inventory movement for this CN/DN'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceheader',
            name='note_reason',
            field=models.CharField(blank=True, choices=[('qty_return', 'Quantity Return'), ('price_diff', 'Price Difference'), ('other', 'Other')], help_text='Applicable for Credit Note / Debit Note only', max_length=20, null=True),
        ),
    ]
