# Generated by Django 5.2.1 on 2026-04-06 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_add_note_reason_affects_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStatutoryForm16ACertificateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='TRACES', max_length=20)),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(upload_to='purchase/statutory/form16a/certificates/')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16a_certificate_documents', to='purchase.purchasestatutoryreturn')),
                ('return_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form16a_certificate_document', to='purchase.purchasestatutoryreturnline')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_statutory_form16a_certificate_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['filing'], name='ix_pur_form16a_cert_filing'), models.Index(fields=['return_line'], name='ix_pur_form16a_cert_line')],
                'constraints': [models.UniqueConstraint(fields=('filing', 'return_line'), name='uq_pur_form16a_certificate_filing_line')],
            },
        ),
    ]
