# Generated by Django 5.2.1 on 2026-04-06 05:44

import purchase.models.purchase_addons
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_purchasestatutoryform16acertificatedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseattachment',
            name='file',
            field=models.FileField(upload_to=purchase.models.purchase_addons._purchase_attachment_upload_to),
        ),
    ]
