# Generated by Django 5.2.1 on 2026-04-06 06:02

import django.db.models.deletion
import django.utils.timezone
import purchase.models.purchase_statutory
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_alter_purchaseattachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStatutoryForm16ADeducteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deductee_key', models.CharField(db_index=True, max_length=40)),
                ('deductee_pan', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('deductee_tax_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('deductee_gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('source', models.CharField(default='TRACES', max_length=20)),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('line_ids_json', models.JSONField(blank=True, default=list)),
                ('document', models.FileField(upload_to=purchase.models.purchase_statutory._purchase_form16a_deductee_upload_to)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form16a_deductee_documents', to='purchase.purchasestatutoryreturn')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_statutory_form16a_deductee_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['filing'], name='ix_pur_form16a_deductee_filing'), models.Index(fields=['deductee_key'], name='ix_pur_form16a_deductee_key')],
                'constraints': [models.UniqueConstraint(fields=('filing', 'deductee_key'), name='uq_pur_form16a_deductee_filing_key')],
            },
        ),
    ]
