# Generated by Django 5.2.1 on 2026-04-06 06:23

import purchase.models.purchase_statutory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_purchasestatutoryform16adeducteedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatutoryform16acertificatedocument',
            name='document',
            field=models.FileField(max_length=255, upload_to='purchase/statutory/form16a/certificates/'),
        ),
        migrations.AlterField(
            model_name='purchasestatutoryform16adeducteedocument',
            name='document',
            field=models.FileField(max_length=255, upload_to=purchase.models.purchase_statutory._purchase_form16a_deductee_upload_to),
        ),
        migrations.AlterField(
            model_name='purchasestatutoryform16aofficialdocument',
            name='document',
            field=models.FileField(max_length=255, upload_to='purchase/statutory/form16a/'),
        ),
    ]
