# Generated by Django 5.2.1 on 2026-04-06 06:35

import purchase.models.purchase_addons
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0031_alter_purchasestatutoryform16acertificatedocument_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=purchase.models.purchase_addons._purchase_attachment_upload_to),
        ),
    ]
