# Generated by Django 4.2.28 on 2026-04-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0034_purchaseinvoiceheader_itc_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceheader',
            name='itc_review_comment',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceheader',
            name='itc_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceheader',
            name='itc_reviewed_by',
        ),
    ]
