# Generated by Django 5.2.1 on 2026-04-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_expiry_warning_days_and_more'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('purchase', '0037_purchaseinvoiceheader_location_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['product', 'batch_number'], name='ix_pur_line_product_batch'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['product', 'expiry_date'], name='ix_pur_line_product_expiry'),
        ),
    ]
