# Generated by Django 5.2.1 on 2026-04-23 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productbarcode_barcode_image_and_more'),
        ('entity', '0021_alter_entitygstregistration_gstin_and_more'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('geography', '0003_city_uq_city_active_district_code_and_more'),
        ('purchase', '0038_purchaseinvoiceline_batch_number_and_more'),
        ('withholding', '0014_remove_tcsquarterlyreturn_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'bill_date'], name='ix_pur_hdr_billdt'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'status'], name='ix_pur_hdr_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'doc_type'], name='ix_pur_hdr_doctyp'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'doc_type', 'doc_code', 'doc_no'], name='ix_pur_hdr_nav'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['header', 'is_service'], name='ix_pur_line_hdr_srv'),
        ),
    ]
