# Generated by Django 5.2.1 on 2026-05-08 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0041_purchasestatutoryreviewnoteevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatutoryreviewnote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='purchasestatutoryreviewnoteevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
