# Generated by Django 5.2.1 on 2026-05-09 11:34

from django.db import migrations, models


def backfill_service_line_purchase_behavior(apps, schema_editor):
    PurchaseInvoiceLine = apps.get_model("purchase", "PurchaseInvoiceLine")
    PurchaseInvoiceLine.objects.filter(is_service=True).update(purchase_behavior="expense")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_purchase_behavior'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('purchase', '0042_alter_purchasestatutoryreviewnote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='purchase_behavior',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('expense', 'Expense'), ('asset', 'Asset')], db_index=True, default='inventory', max_length=20),
        ),
        migrations.RunPython(backfill_service_line_purchase_behavior, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='purchaseinvoiceline',
            index=models.Index(fields=['header', 'purchase_behavior'], name='ix_pur_line_hdr_pbeh'),
        ),
    ]
