# Generated by Django 5.2.1 on 2026-06-19 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0048_purchase_gstr2b_runtime_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseattachment',
            index=models.Index(fields=['header', 'created_at'], name='ix_purchase_attach_hdr_dt'),
        ),
    ]
