# Generated by Django 5.2.1 on 2026-08-02 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('geography', '0004_geography_runtime_indexes'),
        ('invoice_import', '0004_importjob_ix_invimp_job_recent_and_more'),
        ('purchase', '0050_purchaseinvoiceline_cess_type_and_specific_amount'),
        ('withholding', '0017_seed_withholding_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'doc_no', 'id'], name='ix_pur_lookup_sort'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'doc_type', 'status', 'doc_no', 'id'], name='ix_pur_nav_scope'),
        ),
    ]
