# Generated by Django 5.2.1 on 2026-08-03 08:27

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('geography', '0004_geography_runtime_indexes'),
        ('invoice_import', '0004_importjob_ix_invimp_job_recent_and_more'),
        ('purchase', '0052_purchaseinvoiceheader_ix_pur_lookup_sub_and_more'),
        ('withholding', '0017_seed_withholding_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseinvoiceheader',
            index=models.Index(models.F('entity'), models.F('vendor'), models.F('supplier_invoice_date'), models.F('grand_total'), django.db.models.functions.text.Upper('supplier_invoice_number'), condition=models.Q(('status', 9), _negated=True), name='ix_pur_dup_guard'),
        ),
    ]
