# Generated by Django 5.2.1 on 2026-08-03 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('payments', '0015_paymentvoucherheader_ix_pay_ref_warn_scope'),
        ('purchase', '0053_purchaseinvoiceheader_ix_pur_dup_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendoradvancebalance',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'vendor', 'credit_date'], name='ix_pur_adv_hist_scope'),
        ),
        migrations.AddIndex(
            model_name='vendorbillopenitem',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'vendor', 'bill_date'], name='ix_pur_ap_hist_scope'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'status', 'settlement_date'], name='ix_pur_settle_hist_scope'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['advance_balance', 'status', 'settlement_date'], name='ix_pur_settle_adv_statdt'),
        ),
    ]
