from __future__ import annotations

from catalog.models import HsnSac, ProductCategory
from entity.models import EntityFinancialYear, Godown, SubEntity


INVENTORY_REPORT_DEFAULTS = {
    'default_page_size': 100,
    'decimal_places': 2,
    'show_zero_balances_default': False,
    'show_opening_balance_default': False,
    'default_scope_mode': 'as_of',
    'default_valuation_method': 'fifo',
    'enable_drilldown': False,
    'default_export_format': 'excel',
}


def _report_registry() -> list[dict]:
    return [
        {
            'code': 'inventory_stock_summary',
            'name': 'Stock Summary',
            'path': '/api/reports/inventory/stock-summary/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_summary.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': INVENTORY_REPORT_DEFAULTS['show_zero_balances_default'],
            'default_include_negative': True,
        },
        {
            'code': 'inventory_stock_ledger',
            'name': 'Stock Ledger',
            'path': '/api/reports/inventory/stock-ledger/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_ledger.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': True,
            'default_include_negative': True,
        },
        {
            'code': 'inventory_stock_aging',
            'name': 'Stock Aging',
            'path': '/api/reports/inventory/stock-aging/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_aging.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
                'aging_buckets': True,
                'group_by_location': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': INVENTORY_REPORT_DEFAULTS['show_zero_balances_default'],
            'default_include_negative': True,
        },
        {
            'code': 'inventory_stock_movement',
            'name': 'Stock Movement',
            'path': '/api/reports/inventory/stock-movement/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_movement.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
                'group_by_location': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': True,
            'default_include_negative': True,
        },
        {
            'code': 'inventory_stock_day_book',
            'name': 'Stock Day Book',
            'path': '/api/reports/inventory/stock-day-book/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_day_book.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': True,
            'default_include_negative': True,
        },
        {
            'code': 'inventory_stock_book_summary',
            'name': 'Stock Book Summary',
            'path': '/api/reports/inventory/stock-book-summary/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_book_summary.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': True,
            'default_include_negative': True,
        },
        {
            'code': 'inventory_stock_book_detail',
            'name': 'Stock Book Detail',
            'path': '/api/reports/inventory/stock-book-detail/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.stock_book_detail.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': False,
                'valuation_method': True,
                'sort': True,
                'group_by_location': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': True,
            'default_include_negative': True,
        },
        {
            'code': 'inventory_non_moving_stock',
            'name': 'Non-Moving Stock',
            'path': '/api/reports/inventory/non-moving-stock/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.non_moving_stock.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': True,
                'valuation_method': True,
                'sort': True,
                'non_moving_days': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': INVENTORY_REPORT_DEFAULTS['show_zero_balances_default'],
            'default_include_negative': True,
        },
        {
            'code': 'inventory_reorder_status',
            'name': 'Reorder Status',
            'path': '/api/reports/inventory/reorder-status/',
            'category': 'inventory',
            'required_permission': 'reports.inventory.reorder_status.view',
            'scope_modes': ['financial_year', 'month', 'quarter', 'year', 'custom', 'as_of'],
            'supports': {
                'entityfinid': True,
                'subentity': True,
                'date_range': True,
                'as_of_date': True,
                'product_filters': True,
                'category_filters': True,
                'hsn_filters': True,
                'location_filters': True,
                'search': True,
                'pagination': True,
                'drilldown': True,
                'valuation_method': True,
                'sort': True,
            },
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'default_valuation_method': INVENTORY_REPORT_DEFAULTS['default_valuation_method'],
            'default_include_zero': True,
            'default_include_negative': True,
        },
    ]


def build_inventory_report_meta(entity_id: int) -> dict:
    financial_years = list(
        EntityFinancialYear.objects.filter(entity_id=entity_id, isactive=1)
        .order_by('-finstartyear')
        .values('id', 'desc', 'finstartyear', 'finendyear')
    )
    subentities = list(
        SubEntity.objects.filter(entity_id=entity_id, isactive=1)
        .order_by('-is_head_office', 'subentityname', 'id')
        .values('id', 'subentityname', 'is_head_office')
    )
    for row in subentities:
        row['ismainentity'] = row['is_head_office']

    categories = list(
        ProductCategory.objects.filter(entity_id=entity_id)
        .order_by('pcategoryname', 'id')
        .values('id', 'pcategoryname', 'level')
    )
    hsns = list(
        HsnSac.objects.filter(entity_id=entity_id)
        .order_by('code', 'id')
        .values('id', 'code', 'description', 'is_service')
    )
    locations = list(
        Godown.objects.filter(is_active=True)
        .order_by('name', 'id')
        .values('id', 'name', 'code', 'city', 'state')
    )

    return {
        'entity_id': entity_id,
        'defaults': INVENTORY_REPORT_DEFAULTS,
        'choices': {
            'scope_mode': [
                {'value': 'financial_year', 'label': 'Financial Year'},
                {'value': 'month', 'label': 'This Month'},
                {'value': 'quarter', 'label': 'This Quarter'},
                {'value': 'year', 'label': 'This Year'},
                {'value': 'custom', 'label': 'Custom Range'},
                {'value': 'as_of', 'label': 'As of Date'},
            ],
            'valuation_method': [
                {'value': 'fifo', 'label': 'FIFO'},
                {'value': 'lifo', 'label': 'LIFO'},
                {'value': 'mwa', 'label': 'Moving Average'},
                {'value': 'wac', 'label': 'Weighted Average'},
                {'value': 'latest', 'label': 'Latest Cost'},
            ],
            'sort_order': [
                {'value': 'asc', 'label': 'Ascending'},
                {'value': 'desc', 'label': 'Descending'},
            ],
            'export': [
                {'value': 'excel', 'label': 'Excel'},
                {'value': 'pdf', 'label': 'PDF'},
                {'value': 'csv', 'label': 'CSV'},
            ],
        },
        'financial_years': financial_years,
        'subentities': subentities,
        'categories': categories,
        'hsns': hsns,
        'locations': locations,
        'reports': _report_registry(),
        'required_permission_codes': [
            'reports.inventory.view',
            'reports.inventory.stock_summary.view',
            'reports.inventory.stock_ledger.view',
            'reports.inventory.stock_aging.view',
            'reports.inventory.stock_movement.view',
            'reports.inventory.stock_day_book.view',
            'reports.inventory.stock_book_summary.view',
            'reports.inventory.stock_book_detail.view',
        ],
        'actions': {
            'can_view': True,
            'can_export_excel': True,
            'can_export_pdf': True,
            'can_export_csv': True,
            'can_drilldown': False,
        },
        'scope_contract': {
            'version': '2026-04',
            'default_scope_mode': INVENTORY_REPORT_DEFAULTS['default_scope_mode'],
            'primary_fields': [
                'entity',
                'subentity',
                'entityfinid',
                'scope_mode',
                'as_on_date',
                'from_date',
                'to_date',
                'as_of_date',
                'valuation_method',
                'group_by_location',
                'bucket_ends',
                'product',
                'product_ids',
                'category',
                'category_ids',
                'hsn',
                'hsn_ids',
                'location',
                'location_ids',
                'include_zero',
                'include_negative',
                'search',
                'sort_by',
                'sort_order',
                'page',
                'page_size',
                'export',
            ],
        },
    }
