# Generated by Django 4.2.28 on 2026-02-28 12:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.PositiveSmallIntegerField(choices=[(1, 'TDS'), (2, 'TCS')], db_index=True)),
                ('section_code', models.CharField(db_index=True, max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('base_rule', models.PositiveSmallIntegerField(choices=[(1, 'Invoice value excl GST'), (2, 'Invoice value incl GST'), (3, 'Receipt value'), (4, 'Payment value')], default=1)),
                ('rate_default', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('threshold_default', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('requires_pan', models.BooleanField(default=False)),
                ('higher_rate_no_pan', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('applicability_json', models.JSONField(blank=True, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tax_type', 'section_code'], name='withholding_tax_typ_bc3057_idx'), models.Index(fields=['tax_type', 'is_active'], name='withholding_tax_typ_24ad52_idx')],
                'unique_together': {('tax_type', 'section_code', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='PartyTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(blank=True, max_length=16, null=True)),
                ('is_pan_available', models.BooleanField(default=False)),
                ('is_exempt_withholding', models.BooleanField(default=False)),
                ('lower_deduction_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('lower_deduction_valid_from', models.DateField(blank=True, null=True)),
                ('lower_deduction_valid_to', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='financial.account')),
            ],
        ),
        migrations.CreateModel(
            name='EntityWithholdingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_tds', models.BooleanField(default=True)),
                ('enable_tcs', models.BooleanField(default=True)),
                ('apply_194q', models.BooleanField(default=False)),
                ('apply_tcs_206c1h', models.BooleanField(default=False)),
                ('effective_from', models.DateField(db_index=True)),
                ('rounding_places', models.PositiveSmallIntegerField(default=2)),
                ('default_tcs_section', models.ForeignKey(blank=True, limit_choices_to={'tax_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tcs_configs', to='withholding.withholdingsection')),
                ('default_tds_section', models.ForeignKey(blank=True, limit_choices_to={'tax_type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tds_configs', to='withholding.withholdingsection')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('entityfin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entityfin', 'subentity'], name='withholding_entity__7de97f_idx'), models.Index(fields=['entity', 'effective_from'], name='withholding_entity__22d3a9_idx')],
                'unique_together': {('entity', 'entityfin', 'subentity', 'effective_from')},
            },
        ),
    ]
