# Generated by Django 5.2.1 on 2026-03-06 07:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('withholding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withholdingsection',
            name='law_type',
            field=models.CharField(choices=[('INCOME_TAX', 'Income Tax'), ('GST', 'GST')], db_index=True, default='INCOME_TAX', max_length=16),
        ),
        migrations.AddField(
            model_name='withholdingsection',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('206C_1', '206C(1)'), ('206C_1C', '206C(1C)'), ('206C_1F', '206C(1F)'), ('206C_1G', '206C(1G)'), ('206C_1H_LEGACY', '206C(1H) Legacy'), ('GST_SEC_52', 'GST Section 52')], db_index=True, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='GstTcsEcoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('is_eco', models.BooleanField(db_index=True, default=False)),
                ('section_code', models.CharField(default='52', max_length=16)),
                ('default_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
            ],
            options={
                'db_table': 'withholding_gst_tcs_eco_profile',
            },
        ),
        migrations.CreateModel(
            name='GstTcsComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateField(db_index=True)),
                ('document_type', models.CharField(db_index=True, max_length=20)),
                ('document_id', models.BigIntegerField(db_index=True)),
                ('document_no', models.CharField(blank=True, default='', max_length=60)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gst_tcs_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7)),
                ('gst_tcs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fy', models.CharField(db_index=True, max_length=9)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked'), ('FILED', 'Filed')], db_index=True, default='DRAFT', max_length=12)),
                ('snapshot_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('supplier_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
                ('eco_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='withholding.gsttcsecoprofile')),
            ],
            options={
                'db_table': 'withholding_gst_tcs_computation',
            },
        ),
        migrations.CreateModel(
            name='TcsComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=30)),
                ('document_type', models.CharField(db_index=True, max_length=30)),
                ('document_id', models.BigIntegerField(db_index=True)),
                ('document_no', models.CharField(blank=True, default='', max_length=60)),
                ('doc_date', models.DateField(db_index=True)),
                ('rule_snapshot_json', models.JSONField(blank=True, null=True)),
                ('applicability_status', models.CharField(db_index=True, default='APPLICABLE', max_length=24)),
                ('trigger_basis', models.CharField(blank=True, default='INVOICE', max_length=20)),
                ('taxable_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('excluded_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tcs_base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('no_pan_applied', models.BooleanField(default=False)),
                ('lower_rate_applied', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, default='', max_length=255)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_year', models.CharField(blank=True, default='', max_length=9)),
                ('quarter', models.CharField(blank=True, default='', max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=16)),
                ('computation_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('entityfin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcs_overridden', to=settings.AUTH_USER_MODEL)),
                ('party_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='withholding.withholdingsection')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity')),
            ],
            options={
                'db_table': 'withholding_tcs_computation',
            },
        ),
        migrations.CreateModel(
            name='TcsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(db_index=True)),
                ('receipt_voucher_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('tcs_collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('collection_reference', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ALLOCATED', 'Allocated'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='withholding.tcscomputation')),
            ],
            options={
                'db_table': 'withholding_tcs_collection',
            },
        ),
        migrations.CreateModel(
            name='TcsDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('challan_no', models.CharField(db_index=True, max_length=40)),
                ('challan_date', models.DateField(db_index=True)),
                ('bsr_code', models.CharField(blank=True, default='', max_length=20)),
                ('cin', models.CharField(blank=True, default='', max_length=40)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('total_deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('FILED', 'Filed')], db_index=True, default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcs_deposited', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
            ],
            options={
                'db_table': 'withholding_tcs_deposit',
            },
        ),
        migrations.CreateModel(
            name='TcsDepositAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_allocations', to='withholding.tcscollection')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='withholding.tcsdeposit')),
            ],
            options={
                'db_table': 'withholding_tcs_deposit_allocation',
            },
        ),
        migrations.CreateModel(
            name='TcsQuarterlyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(db_index=True, max_length=9)),
                ('quarter', models.CharField(db_index=True, max_length=2)),
                ('form_name', models.CharField(default='27EQ', max_length=10)),
                ('return_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('CORRECTION', 'Correction')], default='ORIGINAL', max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('FILED', 'Filed')], db_index=True, default='DRAFT', max_length=16)),
                ('ack_no', models.CharField(blank=True, default='', max_length=50)),
                ('filed_on', models.DateField(blank=True, null=True)),
                ('json_snapshot', models.JSONField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
            ],
            options={
                'db_table': 'withholding_tcs_quarterly_return',
            },
        ),
        migrations.CreateModel(
            name='TcsCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(db_index=True, max_length=50)),
                ('form_name', models.CharField(default='27D', max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
                ('quarterly_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='withholding.tcsquarterlyreturn')),
            ],
            options={
                'db_table': 'withholding_tcs_certificate',
            },
        ),
        migrations.AddConstraint(
            model_name='gsttcsecoprofile',
            constraint=models.UniqueConstraint(fields=('entity', 'gstin', 'effective_from'), name='uq_gst_tcs_eco_scope'),
        ),
        migrations.AddIndex(
            model_name='gsttcscomputation',
            index=models.Index(fields=['entity', 'fy', 'month'], name='ix_gst_tcs_fy_m'),
        ),
        migrations.AddIndex(
            model_name='gsttcscomputation',
            index=models.Index(fields=['document_type', 'document_id'], name='ix_gst_tcs_doc'),
        ),
        migrations.AddIndex(
            model_name='tcscomputation',
            index=models.Index(fields=['module_name', 'document_type', 'document_id'], name='ix_tcs_cmp_doc'),
        ),
        migrations.AddIndex(
            model_name='tcscomputation',
            index=models.Index(fields=['entity', 'fiscal_year', 'quarter'], name='ix_tcs_cmp_fy_qtr'),
        ),
        migrations.AddIndex(
            model_name='tcscomputation',
            index=models.Index(fields=['party_account', 'doc_date'], name='ix_tcs_cmp_party_dt'),
        ),
        migrations.AddIndex(
            model_name='tcscollection',
            index=models.Index(fields=['collection_date', 'status'], name='ix_tcs_col_dt_st'),
        ),
        migrations.AddIndex(
            model_name='tcsdeposit',
            index=models.Index(fields=['entity', 'financial_year', 'month'], name='ix_tcs_dep_fy_m'),
        ),
        migrations.AddConstraint(
            model_name='tcsdepositallocation',
            constraint=models.UniqueConstraint(fields=('deposit', 'collection'), name='uq_tcs_dep_alloc_once'),
        ),
        migrations.AddIndex(
            model_name='tcsquarterlyreturn',
            index=models.Index(fields=['entity', 'fy', 'quarter'], name='ix_tcs_ret_fy_q'),
        ),
        migrations.AddConstraint(
            model_name='tcscertificate',
            constraint=models.UniqueConstraint(fields=('quarterly_return', 'party_account'), name='uq_tcs_cert_party_once'),
        ),
    ]
