# Generated by Django 5.2.1 on 2026-04-04 08:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_entitygstregistration_state_scope_and_primary_fix'),
        ('financial', '0014_financialsettings_reporting_policy'),
        ('withholding', '0006_remove_withholdingsection_payable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPartyTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exempt_withholding', models.BooleanField(default=False)),
                ('is_specified_person_206ab', models.BooleanField(default=False)),
                ('specified_person_valid_from', models.DateField(blank=True, null=True)),
                ('specified_person_valid_to', models.DateField(blank=True, null=True)),
                ('lower_deduction_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('lower_deduction_valid_from', models.DateField(blank=True, null=True)),
                ('lower_deduction_valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('party_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'subentity', 'party_account', 'is_active'], name='ix_wh_ent_party_profile')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'subentity', 'party_account'), name='uq_wh_entity_party_profile')],
            },
        ),
    ]
