# Generated by Django 5.2.1 on 2026-04-04 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withholding', '0007_entitypartytaxprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingSectionPolicyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], db_index=True, max_length=16)),
                ('changed_fields_json', models.JSONField(blank=True, null=True)),
                ('before_snapshot_json', models.JSONField(blank=True, null=True)),
                ('after_snapshot_json', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(db_index=True, default='api', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholding_policy_audits', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_audits', to='withholding.withholdingsection')),
            ],
            options={
                'db_table': 'withholding_section_policy_audit',
                'indexes': [models.Index(fields=['section', 'created_at'], name='ix_wh_policy_audit_sec_dt'), models.Index(fields=['action', 'created_at'], name='ix_wh_policy_audit_action_dt')],
            },
        ),
    ]
