# Generated by Django 5.2.1 on 2026-04-04 11:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withholding', '0008_withholdingsectionpolicyaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='cess_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='declaration_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='residency_status',
            field=models.CharField(choices=[('resident', 'Resident'), ('non_resident', 'Non Resident'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='surcharge_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='tax_identifier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='treaty_article',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='treaty_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='treaty_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitypartytaxprofile',
            name='treaty_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
