# Generated by Django 5.2.1 on 2026-04-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withholding', '0009_entitypartytaxprofile_cess_rate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withholdingsection',
            unique_together={('tax_type', 'section_code', 'base_rule', 'effective_from')},
        ),
    ]
