# Generated by Django 5.2.1 on 2026-04-05 08:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_entitygstregistration_state_scope_and_primary_fix'),
        ('financial', '0014_financialsettings_reporting_policy'),
        ('withholding', '0010_alter_withholdingsection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitywithholdingconfig',
            name='tcs_206c1h_force_eligible',
            field=models.BooleanField(blank=True, help_text='Optional manual override for 206C(1H) turnover eligibility.', null=True),
        ),
        migrations.AddField(
            model_name='entitywithholdingconfig',
            name='tcs_206c1h_prev_fy_turnover',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='entitywithholdingconfig',
            name='tcs_206c1h_turnover_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000000.00'), max_digits=18),
        ),
        migrations.CreateModel(
            name='EntityTcsThresholdOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('entityfin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('party_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
                ('section', models.ForeignKey(limit_choices_to={'tax_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='withholding.withholdingsection')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entityfin', 'party_account', 'section', 'is_active'], name='ix_tcs_opening_lookup')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'entityfin', 'subentity', 'party_account', 'section', 'effective_from'), name='uq_tcs_opening_entity_fin_sub_party_sec_eff')],
            },
        ),
    ]
