# Generated by Django 5.2.1 on 2026-04-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('withholding', '0012_tcsquarterlyreturn_notes_original_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitypartytaxprofile',
            name='party_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account'),
        ),
        migrations.AlterField(
            model_name='entitytcsthresholdopening',
            name='party_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account'),
        ),
        migrations.AlterField(
            model_name='partytaxprofile',
            name='party_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_profile', to='financial.account'),
        ),
    ]
