# Generated by Django 4.2.28 on 2026-04-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withholding', '0013_remove_tcsquarterlyreturn_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcsquarterlyreturn',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tcsquarterlyreturn',
            name='original_return',
        ),
    ]
