from django.urls import path

from receipts.views import (
    ReceiptVoucherListCreateAPIView,
    ReceiptVoucherRetrieveUpdateDestroyAPIView,
    ReceiptVoucherConfirmAPIView,
    ReceiptVoucherPostAPIView,
    ReceiptVoucherApprovalAPIView,
    ReceiptVoucherCancelAPIView,
    ReceiptVoucherSettlementSummaryAPIView,
    ReceiptVoucherUnpostAPIView,
    ReceiptSettingsAPIView,
    ReceiptCompiledChoicesAPIView,
    ReceiptCustomerAdvanceBalanceListAPIView,
    ReceiptCustomerBillOpenItemListAPIView,
    ReceiptCustomerSettlementListAPIView,
    ReceiptCustomerStatementAPIView,
    ReceiptModeListAPIView,
    ReceiptVoucherPDFAPIView,
    ReceiptVoucherFormMetaAPIView,
    ReceiptVoucherDetailFormMetaAPIView,
    ReceiptVoucherSearchMetaAPIView,
    ReceiptArMetaAPIView,
    ReceiptArSettlementFormMetaAPIView,
    ReceiptSettingsMetaAPIView,
)


urlpatterns = [
    path("receipt-vouchers/", ReceiptVoucherListCreateAPIView.as_view(), name="receipt-voucher-list-create"),
    path("receipt-vouchers/<int:pk>/", ReceiptVoucherRetrieveUpdateDestroyAPIView.as_view(), name="receipt-voucher-rud"),
    path("receipt-vouchers/<int:pk>/confirm/", ReceiptVoucherConfirmAPIView.as_view(), name="receipt-voucher-confirm"),
    path("receipt-vouchers/<int:pk>/post/", ReceiptVoucherPostAPIView.as_view(), name="receipt-voucher-post"),
    path("receipt-vouchers/<int:pk>/approval/", ReceiptVoucherApprovalAPIView.as_view(), name="receipt-voucher-approval"),
    path("receipt-vouchers/<int:pk>/unpost/", ReceiptVoucherUnpostAPIView.as_view(), name="receipt-voucher-unpost"),
    path("receipt-vouchers/<int:pk>/cancel/", ReceiptVoucherCancelAPIView.as_view(), name="receipt-voucher-cancel"),
    path("receipt-vouchers/<int:pk>/settlement-summary/", ReceiptVoucherSettlementSummaryAPIView.as_view(), name="receipt-voucher-settlement-summary"),
    path("receipt-vouchers/<int:pk>/pdf/", ReceiptVoucherPDFAPIView.as_view(), name="receipt-voucher-pdf"),
    path("meta/voucher-form/", ReceiptVoucherFormMetaAPIView.as_view(), name="receipt-meta-voucher-form"),
    path("meta/voucher-detail-form/", ReceiptVoucherDetailFormMetaAPIView.as_view(), name="receipt-meta-voucher-detail-form"),
    path("meta/voucher-search/", ReceiptVoucherSearchMetaAPIView.as_view(), name="receipt-meta-voucher-search"),
    path("meta/settings/", ReceiptSettingsMetaAPIView.as_view(), name="receipt-meta-settings"),
    path("ar/meta/", ReceiptArMetaAPIView.as_view(), name="receipt-ar-meta"),
    path("ar/meta/settlement-form/", ReceiptArSettlementFormMetaAPIView.as_view(), name="receipt-ar-settlement-form-meta"),
    path("open-items/", ReceiptCustomerBillOpenItemListAPIView.as_view(), name="receipt-open-items-list"),
    path("open-advances/", ReceiptCustomerAdvanceBalanceListAPIView.as_view(), name="receipt-open-advances-list"),
    path("ar/settlements/", ReceiptCustomerSettlementListAPIView.as_view(), name="receipt-ar-settlement-list"),
    path("ar/customer-statement/", ReceiptCustomerStatementAPIView.as_view(), name="receipt-ar-customer-statement"),
    path("receipt-modes/", ReceiptModeListAPIView.as_view(), name="receipt-mode-list"),
    path("settings/", ReceiptSettingsAPIView.as_view(), name="receipt-settings"),
    path("choices/", ReceiptCompiledChoicesAPIView.as_view(), name="receipt-choices"),
]
