# Generated by Django 5.2.1 on 2026-09-10 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityFormationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('formation_type', models.CharField(choices=[('unconfigured', 'Unconfigured'), ('proprietorship', 'Proprietorship'), ('partnership', 'Partnership Firm'), ('llp', 'Limited Liability Partnership'), ('company', 'Company'), ('opc', 'One Person Company'), ('huf', 'Hindu Undivided Family'), ('trust', 'Trust'), ('society', 'Society'), ('ngo', 'NGO'), ('section_8', 'Section 8 Company'), ('cooperative', 'Cooperative'), ('government', 'Government Entity'), ('psu', 'Public Sector Undertaking')], db_index=True, default='unconfigured', max_length=30)),
                ('strategy_code', models.CharField(blank=True, default='', max_length=60)),
                ('policy_schema_version', models.PositiveIntegerField(default=1)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('contradictory', 'Contradictory'), ('unsupported', 'Unsupported'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, default='resolved', max_length=40)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('readiness_issues', models.JSONField(blank=True, default=list)),
                ('resolution_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_profiles', to='entity.entity')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_profiles_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('entity_id', '-version_number', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DistributionPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('formation_type', models.CharField(choices=[('unconfigured', 'Unconfigured'), ('proprietorship', 'Proprietorship'), ('partnership', 'Partnership Firm'), ('llp', 'Limited Liability Partnership'), ('company', 'Company'), ('opc', 'One Person Company'), ('huf', 'Hindu Undivided Family'), ('trust', 'Trust'), ('society', 'Society'), ('ngo', 'NGO'), ('section_8', 'Section 8 Company'), ('cooperative', 'Cooperative'), ('government', 'Government Entity'), ('psu', 'Public Sector Undertaking')], db_index=True, max_length=30)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('governing_document_reference', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_policies_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_policies', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_policies', to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_policies', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_policies_submitted', to=settings.AUTH_USER_MODEL)),
                ('formation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='capital_distribution.entityformationprofile')),
            ],
            options={
                'ordering': ('entity_id', '-version_number', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DistributionPolicyStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('target_type', models.CharField(choices=[('proprietor', 'Proprietor'), ('partner', 'Partner'), ('shareholder', 'Shareholder'), ('member', 'Member'), ('trustee', 'Trustee'), ('fund', 'Fund'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('target_name', models.CharField(max_length=150)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('loss_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('destination_account_preference', models.CharField(choices=[('capital', 'Capital'), ('current', 'Current'), ('auto', 'Auto')], default='current', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_policy_stakeholders_created', to=settings.AUTH_USER_MODEL)),
                ('ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_policy_rows', to='entity.entityownershipv2')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='capital_distribution.distributionpolicyversion')),
            ],
            options={
                'ordering': ('policy_id', 'sort_order', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('ownership__isnull', False)), fields=('policy', 'ownership'), name='uq_dist_policy_ownership'), models.CheckConstraint(condition=models.Q(('profit_percentage__isnull', True), models.Q(('profit_percentage__gte', 0), ('profit_percentage__lte', 100)), _connector='OR'), name='ck_dist_policy_profit_pct'), models.CheckConstraint(condition=models.Q(('loss_percentage__isnull', True), models.Q(('loss_percentage__gte', 0), ('loss_percentage__lte', 100)), _connector='OR'), name='ck_dist_policy_loss_pct')],
            },
        ),
        migrations.CreateModel(
            name='CapitalDistributionAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_audit_events', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_distribution_audit_events', to='entity.entity')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='capital_distribution.distributionpolicyversion')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['entity', 'action', 'created_at'], name='ix_cap_dist_audit_scope')],
            },
        ),
        migrations.AddIndex(
            model_name='entityformationprofile',
            index=models.Index(fields=['entity', 'status', 'effective_from'], name='ix_form_profile_scope_status'),
        ),
        migrations.AddConstraint(
            model_name='entityformationprofile',
            constraint=models.UniqueConstraint(fields=('entity', 'version_number'), name='uq_formation_profile_entity_version'),
        ),
        migrations.AddConstraint(
            model_name='entityformationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_formation_profile_date_range'),
        ),
        migrations.AddIndex(
            model_name='distributionpolicyversion',
            index=models.Index(fields=['entity', 'status', 'effective_from'], name='ix_dist_policy_scope_status'),
        ),
        migrations.AddIndex(
            model_name='distributionpolicyversion',
            index=models.Index(fields=['entity', 'formation_type', 'effective_from'], name='ix_dist_policy_form_date'),
        ),
        migrations.AddConstraint(
            model_name='distributionpolicyversion',
            constraint=models.UniqueConstraint(fields=('entity', 'version_number'), name='uq_distribution_policy_entity_version'),
        ),
        migrations.AddConstraint(
            model_name='distributionpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_distribution_policy_date_range'),
        ),
    ]
