# Generated by Django 5.2.1 on 2026-09-10 10:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_distribution', '0001_initial'),
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalDistributionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('period_from', models.DateField(db_index=True)),
                ('period_to', models.DateField(db_index=True)),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom'), ('annual', 'Annual')], default='custom', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('stale', 'Stale'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('profit_source', models.CharField(choices=[('posted_books', 'Posted books'), ('manual_approved', 'Approved manual amount'), ('day_weighted', 'Day-weighted annual result')], default='posted_books', max_length=20)),
                ('source_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('book_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('distributable_result', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('calculation_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, max_length=80)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_runs_calculated', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_runs_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_distribution_runs', to='entity.entity')),
                ('entityfin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_runs', to='entity.entityfinancialyear')),
                ('formation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='capital_distribution.entityformationprofile')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='capital_distribution.distributionpolicyversion')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_runs', to='entity.subentity')),
            ],
            options={
                'ordering': ('-period_to', '-id'),
            },
        ),
        migrations.AddField(
            model_name='capitaldistributionauditevent',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='capital_distribution.capitaldistributionrun'),
        ),
        migrations.CreateModel(
            name='CapitalDistributionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('source_profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocation_basis', models.CharField(default='actual_segment', max_length=30)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_segments', to='capital_distribution.distributionpolicyversion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='capital_distribution.capitaldistributionrun')),
            ],
            options={
                'ordering': ('run_id', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='CapitalDistributionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('component_type', models.CharField(choices=[('remuneration', 'Remuneration'), ('capital_interest', 'Interest on capital'), ('drawing_interest', 'Interest on drawings'), ('residual_profit', 'Residual profit'), ('residual_loss', 'Residual loss'), ('rounding', 'Rounding')], max_length=30)),
                ('basis_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('days', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('side', models.CharField(choices=[('credit', 'Credit stakeholder'), ('debit', 'Debit stakeholder')], max_length=10)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_lines', to='capital_distribution.distributionpolicystakeholder')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='capital_distribution.capitaldistributionrun')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='capital_distribution.capitaldistributionsegment')),
            ],
            options={
                'ordering': ('segment_id', 'stakeholder_id', 'component_type', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DistributionBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('cutoff_date', models.DateField()),
                ('capital_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('drawing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('movements', models.JSONField(blank=True, default=list)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='capital_distribution.capitaldistributionrun')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='capital_distribution.distributionpolicystakeholder')),
            ],
            options={
                'ordering': ('run_id', 'stakeholder_id'),
            },
        ),
        migrations.AddIndex(
            model_name='capitaldistributionrun',
            index=models.Index(fields=['entity', 'entityfin', 'status', 'period_from'], name='ix_cap_run_scope_status'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributionrun',
            constraint=models.UniqueConstraint(fields=('entity', 'idempotency_key'), name='uq_cap_dist_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributionrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_to__gte', models.F('period_from'))), name='ck_cap_dist_run_period'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributionsegment',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uq_cap_dist_segment_sequence'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributionsegment',
            constraint=models.CheckConstraint(condition=models.Q(('period_to__gte', models.F('period_from'))), name='ck_cap_dist_segment_period'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributionline',
            constraint=models.UniqueConstraint(fields=('segment', 'stakeholder', 'component_type'), name='uq_cap_dist_line_identity'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_cap_dist_line_amount'),
        ),
        migrations.AddConstraint(
            model_name='distributionbalancesnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'stakeholder'), name='uq_cap_dist_balance_snapshot'),
        ),
    ]
