# Generated by Django 5.2.1 on 2026-09-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_distribution', '0002_add_calculation_runs'),
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('posting', '0028_alter_entry_txn_type_alter_inventorymove_txn_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_runs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='lifecycle_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_runs_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='posting_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_original_runs', to='posting.postingbatch'),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='reversal_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_reversed_runs', to='posting.postingbatch'),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_runs_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitaldistributionrun',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_runs_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitaldistributionrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('stale', 'Stale'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CapitalDistributionAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('capital_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_capital_mappings', to='financial.account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_account_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('current_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_current_mappings', to='financial.account')),
                ('drawings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_drawings_mappings', to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_distribution_account_mappings', to='entity.entity')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_account_mappings', to='entity.entityownershipv2')),
            ],
            options={
                'ordering': ('entity_id', 'ownership_id', '-effective_from', '-id'),
                'indexes': [models.Index(fields=['entity', 'isactive', 'ownership'], name='ix_cap_dist_map_scope_owner')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('entity', 'ownership'), name='uq_cap_dist_active_owner_mapping'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_cap_dist_mapping_dates')],
            },
        ),
    ]
