# Generated by Django 5.2.1 on 2026-09-11 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_distribution', '0003_capitaldistributionrun_approved_at_and_more'),
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('formation_type', models.CharField(choices=[('unconfigured', 'Unconfigured'), ('proprietorship', 'Proprietorship'), ('partnership', 'Partnership Firm'), ('llp', 'Limited Liability Partnership'), ('company', 'Company'), ('opc', 'One Person Company'), ('huf', 'Hindu Undivided Family'), ('trust', 'Trust'), ('society', 'Society'), ('ngo', 'NGO'), ('section_8', 'Section 8 Company'), ('cooperative', 'Cooperative'), ('government', 'Government Entity'), ('psu', 'Public Sector Undertaking')], db_index=True, max_length=30)),
                ('tax_type', models.CharField(choices=[('income_tax', 'Income tax')], db_index=True, default='income_tax', max_length=30)),
                ('policy_code', models.CharField(db_index=True, max_length=80)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('jurisdiction_country', models.CharField(db_index=True, default='IN', max_length=2)),
                ('jurisdiction_state', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('statutory_reference', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_published_on', models.DateField(blank=True, null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_policies_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_distribution_tax_policies', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_tax_policies', to='entity.entityfinancialyear')),
                ('formation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_policies', to='capital_distribution.entityformationprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_policies_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('entity_id', 'policy_code', '-version_number', '-id'),
            },
        ),
        migrations.AddField(
            model_name='capitaldistributionauditevent',
            name='tax_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='capital_distribution.taxpolicyversion'),
        ),
        migrations.AddIndex(
            model_name='taxpolicyversion',
            index=models.Index(fields=['entity', 'tax_type', 'status', 'effective_from'], name='ix_cap_tax_policy_scope'),
        ),
        migrations.AddIndex(
            model_name='taxpolicyversion',
            index=models.Index(fields=['policy_code', 'jurisdiction_country', 'jurisdiction_state'], name='ix_cap_tax_policy_code'),
        ),
        migrations.AddConstraint(
            model_name='taxpolicyversion',
            constraint=models.UniqueConstraint(fields=('entity', 'policy_code', 'jurisdiction_country', 'jurisdiction_state', 'version_number'), name='uq_cap_tax_policy_scope_version'),
        ),
        migrations.AddConstraint(
            model_name='taxpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_cap_tax_policy_date_range'),
        ),
    ]
