# Generated by Django 5.2.1 on 2026-09-11 05:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_distribution', '0004_taxpolicyversion_and_more'),
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalDistributionTaxWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('period_from', models.DateField(db_index=True)),
                ('period_to', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('reversed', 'Reversed')], db_index=True, default='calculated', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=80)),
                ('calculation_hash', models.CharField(db_index=True, max_length=64)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('book_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('allowable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('disallowed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_reason', models.CharField(blank=True, default='', max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_workings_approved', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_workings_calculated', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_workings_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_distribution_tax_workings', to='entity.entity')),
                ('entityfin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_tax_workings', to='entity.entityfinancialyear')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_workings_reversed', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_workings', to='capital_distribution.capitaldistributionrun')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_distribution_tax_workings', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_workings_submitted', to=settings.AUTH_USER_MODEL)),
                ('tax_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_workings', to='capital_distribution.taxpolicyversion')),
            ],
            options={
                'ordering': ('-period_to', '-id'),
            },
        ),
        migrations.AddField(
            model_name='capitaldistributionauditevent',
            name='tax_working',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='capital_distribution.capitaldistributiontaxworking'),
        ),
        migrations.CreateModel(
            name='CapitalDistributionTaxWorkingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('component_type', models.CharField(choices=[('remuneration', 'Remuneration'), ('capital_interest', 'Interest on capital'), ('drawing_interest', 'Interest on drawings'), ('residual_profit', 'Residual profit'), ('residual_loss', 'Residual loss'), ('rounding', 'Rounding')], max_length=30)),
                ('stakeholder_name', models.CharField(max_length=150)),
                ('book_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('treatment', models.CharField(max_length=20)),
                ('calculated_allowable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('calculated_disallowed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('override_allowable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('allowable_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disallowed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rule_snapshot', models.JSONField(default=dict)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('override_reason', models.CharField(blank=True, default='', max_length=500)),
                ('evidence_references', models.JSONField(blank=True, default=list)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_tax_working_lines_overridden', to=settings.AUTH_USER_MODEL)),
                ('source_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_working_lines', to='capital_distribution.capitaldistributionline')),
                ('working', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='capital_distribution.capitaldistributiontaxworking')),
            ],
            options={
                'ordering': ('working_id', 'source_line_id'),
            },
        ),
        migrations.AddIndex(
            model_name='capitaldistributiontaxworking',
            index=models.Index(fields=['entity', 'entityfin', 'status', 'period_from'], name='ix_cap_tax_work_scope'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.UniqueConstraint(fields=('entity', 'idempotency_key'), name='uq_cap_tax_work_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.UniqueConstraint(fields=('run', 'tax_policy'), name='uq_cap_tax_work_run_policy'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.CheckConstraint(condition=models.Q(('period_to__gte', models.F('period_from'))), name='ck_cap_tax_work_period'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.CheckConstraint(condition=models.Q(('book_amount__gte', 0)), name='ck_cap_tax_work_book'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.CheckConstraint(condition=models.Q(('allowable_amount__gte', 0)), name='ck_cap_tax_work_allowable'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.CheckConstraint(condition=models.Q(('disallowed_amount__gte', 0)), name='ck_cap_tax_work_disallowed'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworking',
            constraint=models.CheckConstraint(condition=models.Q(('book_amount', models.F('allowable_amount') + models.F('disallowed_amount'))), name='ck_cap_tax_work_reconciled'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.UniqueConstraint(fields=('working', 'source_line'), name='uq_cap_tax_work_source_line'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('book_amount__gte', 0)), name='ck_cap_tax_line_book'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('allowable_amount__gte', 0)), name='ck_cap_tax_line_allowable'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('disallowed_amount__gte', 0)), name='ck_cap_tax_line_disallowed'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('calculated_allowable_amount__gte', 0)), name='ck_cap_tax_line_calc_allowable'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('calculated_disallowed_amount__gte', 0)), name='ck_cap_tax_line_calc_disallowed'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('book_amount', models.F('allowable_amount') + models.F('disallowed_amount'))), name='ck_cap_tax_line_reconciled'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('book_amount', models.F('calculated_allowable_amount') + models.F('calculated_disallowed_amount'))), name='ck_cap_tax_line_calc_reconciled'),
        ),
        migrations.AddConstraint(
            model_name='capitaldistributiontaxworkingline',
            constraint=models.CheckConstraint(condition=models.Q(('override_allowable_amount__isnull', True), models.Q(('override_allowable_amount__gte', 0), ('override_allowable_amount__lte', models.F('book_amount'))), _connector='OR'), name='ck_cap_tax_line_override_range'),
        ),
    ]
