# Generated by Django 5.2.1 on 2026-09-11 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_distribution', '0005_capitaldistributiontaxworking_and_more'),
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalDistributionActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('wave_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending setup'), ('ready', 'Ready to enable'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('readiness_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_activations_created', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_distribution_activations_enabled', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_distribution_activation', to='entity.entity')),
            ],
            options={
                'ordering': ('entity_id',),
            },
        ),
    ]
