# Generated by Django 5.2.1 on 2026-03-09 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ledgers(apps, schema_editor):
    Account = apps.get_model("financial", "account")
    Ledger = apps.get_model("financial", "Ledger")
    StaticAccountMapping = apps.get_model("financial", "staticacountsmapping")

    account_to_ledger = {}

    for acc in Account.objects.all().iterator():
        ledger = Ledger.objects.create(
            entity_id=acc.entity_id,
            ledger_code=acc.accountcode,
            name=acc.accountname or f"Account {acc.pk}",
            legal_name=acc.legalname,
            accounthead_id=acc.accounthead_id,
            creditaccounthead_id=acc.creditaccounthead_id,
            accounttype_id=acc.accounttype_id,
            is_party=True,
            is_system=False,
            canbedeleted=acc.canbedeleted,
            openingbcr=acc.openingbcr,
            openingbdr=acc.openingbdr,
            createdby_id=acc.createdby_id,
            isactive=acc.isactive,
        )
        Account.objects.filter(pk=acc.pk).update(ledger_id=ledger.pk)
        account_to_ledger[acc.pk] = ledger.pk

    for acc in Account.objects.exclude(contraaccount_id__isnull=True).iterator():
        ledger_id = account_to_ledger.get(acc.pk)
        contra_ledger_id = account_to_ledger.get(acc.contraaccount_id)
        if ledger_id and contra_ledger_id:
            Ledger.objects.filter(pk=ledger_id).update(contra_ledger_id=contra_ledger_id)

    for mapping in StaticAccountMapping.objects.exclude(account_id__isnull=True).iterator():
        ledger_id = account_to_ledger.get(mapping.account_id)
        if ledger_id:
            StaticAccountMapping.objects.filter(pk=mapping.pk).update(ledger_id=ledger_id)


def reverse_backfill_ledgers(apps, schema_editor):
    Account = apps.get_model("financial", "account")
    Ledger = apps.get_model("financial", "Ledger")
    StaticAccountMapping = apps.get_model("financial", "staticacountsmapping")

    StaticAccountMapping.objects.update(ledger_id=None)
    Account.objects.update(ledger_id=None)
    Ledger.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staticacounts',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticacounts',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staticacounts',
            name='mapping_scope',
            field=models.CharField(choices=[('posting', 'Posting'), ('reporting', 'Reporting'), ('system', 'System')], default='posting', max_length=20),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('ledger_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_party', models.BooleanField(db_index=True, default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('canbedeleted', models.BooleanField(default=True)),
                ('openingbcr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('openingbdr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('accounthead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accountheads', to='financial.accounthead')),
                ('accounttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='financial.accounttype')),
                ('contra_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contra_ledgers', to='financial.ledger')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creditaccounthead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_credit_accountheads', to='financial.accounthead')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_profile', to='financial.ledger'),
        ),
        migrations.AddField(
            model_name='staticacountsmapping',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_account_mappings', to='financial.ledger'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('gstno__isnull', False), models.Q(('gstno', ''), _negated=True)), fields=('entity', 'gstno'), name='uq_account_entity_gstno_present'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['entity', 'ledger_code'], name='ix_ledger_entity_code'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['entity', 'name'], name='ix_ledger_entity_name'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['entity', 'is_party'], name='ix_ledger_entity_party'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('entity', 'ledger_code'), name='uq_ledger_entity_ledger_code'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(check=models.Q(('ledger_code__gt', 0), ('ledger_code__isnull', True), _connector='OR'), name='ck_ledger_code_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(check=models.Q(('openingbcr__gte', 0), ('openingbcr__isnull', True), _connector='OR'), name='ck_ledger_openingbcr_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(check=models.Q(('openingbdr__gte', 0), ('openingbdr__isnull', True), _connector='OR'), name='ck_ledger_openingbdr_nonneg'),
        ),
        migrations.RunPython(backfill_ledgers, reverse_backfill_ledgers),
    ]
