# Generated by Django 5.2.1 on 2026-03-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0002_staticacounts_description_staticacounts_is_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('opening_balance_edit_mode', models.CharField(choices=[('always', 'Always Allow'), ('before_posting', 'Allow Before First Posting'), ('locked', 'Locked')], default='before_posting', max_length=20)),
                ('enforce_gst_uniqueness', models.BooleanField(default=True)),
                ('enforce_pan_uniqueness', models.BooleanField(default=True)),
                ('require_gst_for_registered_parties', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_settings', to='entity.entity')),
            ],
            options={
                'verbose_name': 'Financial Settings',
                'verbose_name_plural': 'Financial Settings',
            },
        ),
    ]
