# Generated by Django 5.2.1 on 2026-03-09 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0003_financialsettings'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('accountcode__isnull', False)), fields=('entity', 'accountcode'), name='uq_account_entity_accountcode_present'),
        ),
    ]
