# Generated by Django 5.2.1 on 2026-03-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0006_drop_legacy_invoice_inventory_tables'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountbankdetails',
            name='uq_bankdetails_one_primary_per_account',
        ),
        migrations.AlterField(
            model_name='account',
            name='accountcode',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.city'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.district'),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.city'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.country'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.district'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.city'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.country'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.district'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state'),
        ),
        migrations.AddConstraint(
            model_name='accountbankdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True), ('isprimary', True)), fields=('account',), name='uq_bankdetails_one_primary_per_account'),
        ),
        migrations.AddConstraint(
            model_name='contactdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('isprimary', True)), fields=('account',), name='uq_contactdetails_one_primary_per_account'),
        ),
    ]
