# Generated by Django 5.2.1 on 2026-03-21 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_account_normalized_profiles(apps, schema_editor):
    Account = apps.get_model("financial", "account")
    AccountAddress = apps.get_model("financial", "AccountAddress")
    AccountComplianceProfile = apps.get_model("financial", "AccountComplianceProfile")
    AccountCommercialProfile = apps.get_model("financial", "AccountCommercialProfile")

    for acc in Account.objects.all().iterator():
        AccountComplianceProfile.objects.get_or_create(
            account_id=acc.id,
            defaults={
                "entity_id": acc.entity_id,
                "createdby_id": acc.createdby_id,
                "gstno": acc.gstno,
                "pan": acc.pan,
                "gstintype": acc.gstintype,
                "gstregtype": acc.gstregtype,
                "is_sez": bool(acc.is_sez),
                "cin": acc.cin,
                "msme": acc.msme,
                "gsttdsno": acc.gsttdsno,
                "tdsno": acc.tdsno,
                "tdsrate": acc.tdsrate,
                "tdssection": acc.tdssection,
                "tds_threshold": acc.tds_threshold,
                "istcsapplicable": bool(acc.istcsapplicable),
                "tcscode": acc.tcscode,
                "isactive": bool(acc.isactive),
            },
        )

        AccountCommercialProfile.objects.get_or_create(
            account_id=acc.id,
            defaults={
                "entity_id": acc.entity_id,
                "createdby_id": acc.createdby_id,
                "partytype": acc.partytype,
                "creditlimit": acc.creditlimit,
                "creditdays": acc.creditdays,
                "paymentterms": acc.paymentterms,
                "currency": acc.currency,
                "blockstatus": acc.blockstatus,
                "blockedreason": acc.blockedreason,
                "approved": bool(acc.approved),
                "agent": acc.agent,
                "reminders": acc.reminders,
                "isactive": bool(acc.isactive),
            },
        )

        has_any_address = any(
            [
                acc.address1,
                acc.address2,
                acc.addressfloorno,
                acc.addressstreet,
                acc.country_id,
                acc.state_id,
                acc.district_id,
                acc.city_id,
                acc.pincode,
            ]
        )
        if has_any_address and not AccountAddress.objects.filter(account_id=acc.id).exists():
            AccountAddress.objects.create(
                account_id=acc.id,
                entity_id=acc.entity_id,
                createdby_id=acc.createdby_id,
                address_type="billing",
                line1=acc.address1,
                line2=acc.address2,
                floor_no=acc.addressfloorno,
                street=acc.addressstreet,
                country_id=acc.country_id,
                state_id=acc.state_id,
                district_id=acc.district_id,
                city_id=acc.city_id,
                pincode=acc.pincode,
                isprimary=True,
                isactive=bool(acc.isactive),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0007_remove_accountbankdetails_uq_bankdetails_one_primary_per_account_and_more'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('address_type', models.CharField(choices=[('registered', 'Registered'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('correspondence', 'Correspondence')], default='billing', max_length=20)),
                ('line1', models.CharField(blank=True, max_length=255, null=True)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('isprimary', models.BooleanField(db_index=True, default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='financial.account')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.country')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.district')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'account'], name='ix_accaddr_ent_acc'), models.Index(fields=['account', 'address_type'], name='ix_accaddr_acc_type')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isactive', True), ('isprimary', True)), fields=('account',), name='uq_accaddr_primary')],
            },
        ),
        migrations.CreateModel(
            name='AccountCommercialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('partytype', models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Both', 'Customer & Vendor'), ('Bank', 'Bank'), ('Employee', 'Employee'), ('Government', 'Government'), ('Other', 'Other')], max_length=20, null=True)),
                ('creditlimit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creditdays', models.IntegerField(blank=True, null=True)),
                ('paymentterms', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('Net7', 'Net 7'), ('Net15', 'Net 15'), ('Net30', 'Net 30'), ('Net45', 'Net 45'), ('Net60', 'Net 60')], max_length=100, null=True)),
                ('currency', models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD')], max_length=10, null=True)),
                ('blockstatus', models.CharField(blank=True, choices=[('Active', 'Active'), ('Blocked', 'Blocked'), ('OnHold', 'On Hold')], max_length=10, null=True)),
                ('blockedreason', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('agent', models.CharField(blank=True, max_length=50, null=True)),
                ('reminders', models.IntegerField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='financial.account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'partytype'], name='ix_acccom_ent_party'), models.Index(fields=['entity', 'currency'], name='ix_acccom_ent_curr')],
                'constraints': [models.CheckConstraint(check=models.Q(('creditdays__gte', 0), ('creditdays__isnull', True), _connector='OR'), name='ck_acccom_crdays_nn'), models.CheckConstraint(check=models.Q(('creditlimit__gte', 0), ('creditlimit__isnull', True), _connector='OR'), name='ck_acccom_crlimit_nn')],
            },
        ),
        migrations.CreateModel(
            name='AccountComplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gstno', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('gstintype', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Composition', 'Composition'), ('Unregistered', 'Unregistered'), ('Consumer', 'Consumer'), ('SEZ', 'SEZ'), ('DeemedExport', 'Deemed Export'), ('Export', 'Export')], max_length=255, null=True)),
                ('gstregtype', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Composition', 'Composition'), ('UIN', 'UIN'), ('SEZ', 'SEZ'), ('Unregistered', 'Unregistered')], max_length=30, null=True)),
                ('is_sez', models.BooleanField(default=False)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('msme', models.CharField(blank=True, max_length=50, null=True)),
                ('gsttdsno', models.CharField(blank=True, max_length=50, null=True)),
                ('tdsno', models.CharField(blank=True, max_length=50, null=True)),
                ('tdsrate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tdssection', models.CharField(blank=True, max_length=20, null=True)),
                ('tds_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('istcsapplicable', models.BooleanField(default=False)),
                ('tcscode', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profile', to='financial.account')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'gstno'], name='ix_acccomp_ent_gst'), models.Index(fields=['entity', 'pan'], name='ix_acccomp_ent_pan')],
            },
        ),
        migrations.RunPython(backfill_account_normalized_profiles, migrations.RunPython.noop),
    ]
