# Generated by Django 5.2.1 on 2026-03-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_accountaddress_accountcommercialprofile_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='ck_account_creditdays_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='ck_account_creditlimit_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='uq_account_entity_gstno_present',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ix_account_entity_gstno',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ix_account_entity_pan',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='ix_account_entity_partytype',
        ),
    ]
