# Generated by Django 4.2.28 on 2026-03-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_invoicecustomfielddefinition_invoicecustomfielddefault'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicecustomfielddefault',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoicecustomfielddefinition',
            options={},
        ),
    ]
