# Generated by Django 4.2.28 on 2026-04-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_invoicecustomfielddefault_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountname',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contraaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.account', verbose_name='contra account'),
        ),
    ]
