# Generated by Django 5.2.1 on 2026-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_financial_governance_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialcodeseries',
            options={},
        ),
        migrations.AlterModelOptions(
            name='financialmasterrule',
            options={},
        ),
    ]
