# Generated by Django 5.2.1 on 2026-09-07 04:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0003_add_sensitive_customer_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOperationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation_type', models.CharField(choices=[('onboard_customer', 'Onboard customer')], db_index=True, max_length=50)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retry_queued', 'Retry queued'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='validated', max_length=30)),
                ('reason', models.CharField(max_length=500)),
                ('ticket_reference', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('payload_hash', models.CharField(max_length=64)),
                ('request_snapshot', models.JSONField()),
                ('validation_snapshot', models.JSONField(default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('customer_account_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=120)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_operations_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformProvisioningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=80)),
                ('completed_stages', models.JSONField(blank=True, default=list)),
                ('stage_results', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_job', to='platform_ops.platformoperationrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='platformoperationrequest',
            index=models.Index(fields=['operation_type', 'status', 'created_at'], name='ix_platform_operation_queue'),
        ),
        migrations.AddConstraint(
            model_name='platformoperationrequest',
            constraint=models.UniqueConstraint(fields=('requested_by', 'idempotency_key'), name='uq_platform_operation_idempotency'),
        ),
    ]
