# Generated by Django 5.2.1 on 2026-09-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0004_platformoperationrequest_platformprovisioningjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationrequest',
            name='expected_target_version',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformoperationrequest',
            name='operation_type',
            field=models.CharField(choices=[('onboard_customer', 'Onboard customer'), ('customer_contact_update', 'Update customer contacts')], db_index=True, max_length=50),
        ),
    ]
