# Generated by Django 5.2.1 on 2026-09-07 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0005_platformoperationrequest_expected_target_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformoperationrequest',
            name='operation_type',
            field=models.CharField(choices=[('onboard_customer', 'Onboard customer'), ('customer_contact_update', 'Update customer contacts'), ('customer_status_update', 'Update customer status')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PlatformOperationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comment', models.CharField(max_length=500)),
                ('target_version', models.DateTimeField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_operation_decisions', to=settings.AUTH_USER_MODEL)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='platform_ops.platformoperationrequest')),
            ],
            options={
                'ordering': ('-decided_at',),
            },
        ),
    ]
