# Generated by Django 5.2.1 on 2026-09-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0007_alter_platformoperationrequest_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformoperationrequest',
            name='operation_type',
            field=models.CharField(choices=[('onboard_customer', 'Onboard customer'), ('customer_contact_update', 'Update customer contacts'), ('customer_status_update', 'Update customer status'), ('add_entity_branch', 'Add entity branch'), ('add_entity_financial_year', 'Add entity financial year'), ('update_entity_gst_registration', 'Update entity GST registration')], db_index=True, max_length=50),
        ),
    ]
