# Generated by Django 5.2.1 on 2026-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0011_alter_platformoperationrequest_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformoperationrequest',
            name='operation_type',
            field=models.CharField(choices=[('onboard_customer', 'Onboard customer'), ('customer_contact_update', 'Update customer contacts'), ('customer_status_update', 'Update customer status'), ('add_entity_branch', 'Add entity branch'), ('add_entity_financial_year', 'Add entity financial year'), ('update_entity_gst_registration', 'Update entity GST registration'), ('change_subscription_plan', 'Change subscription plan'), ('update_tenant_membership', 'Update tenant membership'), ('invite_tenant_user', 'Invite tenant user'), ('resend_tenant_invitation', 'Resend tenant invitation')], db_index=True, max_length=50),
        ),
    ]
