# Generated by Django 5.2.1 on 2026-09-07 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_cancel_permission(apps, schema_editor):
    Permission = apps.get_model('platform_ops', 'PlatformPermission')
    Role = apps.get_model('platform_ops', 'PlatformRole')
    permission, _ = Permission.objects.update_or_create(
        code='platform.operation.cancel',
        defaults={'name': 'Cancel operations', 'is_active': True},
    )
    for code in ('onboarding-operator', 'billing-operator', 'compliance-operator', 'platform-security-admin'):
        role = Role.objects.filter(code=code).first()
        if role:
            role.permissions.add(permission)


def remove_cancel_permission(apps, schema_editor):
    apps.get_model('platform_ops', 'PlatformPermission').objects.filter(code='platform.operation.cancel').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0013_alter_platformoperationrequest_operation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformoperationrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='platformoperationrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformoperationrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_operations_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_cancel_permission, remove_cancel_permission),
    ]
