# Generated by Django 5.2.1 on 2026-09-07 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def add_support_manage_permission(apps, schema_editor):
    Permission = apps.get_model('platform_ops', 'PlatformPermission')
    Role = apps.get_model('platform_ops', 'PlatformRole')
    permission, _ = Permission.objects.update_or_create(
        code='platform.support.manage',
        defaults={'name': 'Manage customer requests', 'is_active': True},
    )
    for code in ('support-operator', 'onboarding-operator', 'platform-approver'):
        role = Role.objects.filter(code=code).first()
        if role:
            role.permissions.add(permission)


def remove_support_manage_permission(apps, schema_editor):
    apps.get_model('platform_ops', 'PlatformPermission').objects.filter(code='platform.support.manage').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('platform_ops', '0024_alter_platformoperationrequest_operation_type'),
        ('subscriptions', '0006_subscriptionplan_is_selectable_for_signup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('account_change', 'Account change'), ('entity_change', 'Entity change'), ('subscription_change', 'Subscription change'), ('user_access', 'User access'), ('compliance_setup', 'Compliance setup'), ('technical_support', 'Technical support'), ('other', 'Other')], db_index=True, max_length=40)),
                ('subject', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], db_index=True, default='new', max_length=20)),
                ('operator_note', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='subscriptions.customeraccount')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_requests', to='entity.entity')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_ops.customerservicerequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='customerservicerequest',
            index=models.Index(fields=['customer_account', 'status', 'created_at'], name='ix_service_request_customer'),
        ),
        migrations.AddIndex(
            model_name='customerservicerequest',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='ix_service_request_queue'),
        ),
        migrations.RunPython(add_support_manage_permission, remove_support_manage_permission),
    ]
