from django.urls import path

from hrms.views import (
    AttendanceApprovalApproveAPIView,
    AttendanceApprovalListAPIView,
    AttendanceApprovalRejectAPIView,
    AttendanceApprovalSubmitAPIView,
    AttendanceImportBatchListCreateAPIView,
    AttendanceMonthlyCloseApproveAPIView,
    AttendanceMonthlyCloseCloseAPIView,
    AttendanceMonthlyCloseListCreateAPIView,
    AttendanceMonthlyCloseSubmitAPIView,
    AttendanceMonthlySummaryAPIView,
    AttendancePayrollPeriodListAPIView,
    DailyAttendanceBulkUpsertAPIView,
    DailyAttendanceListCreateAPIView,
    HrEmployeeDetailAPIView,
    HrEmployeeListCreateAPIView,
    HrEmploymentContractDetailAPIView,
    HrEmploymentContractListCreateAPIView,
    HrHolidayDetailAPIView,
    HrHolidayListCreateAPIView,
    HrHolidayCalendarDetailAPIView,
    HrHolidayCalendarListCreateAPIView,
    HrmsEntitySetupPatchAPIView,
    HrmsEntitySetupSummaryAPIView,
    HrmsGlobalAdoptTemplatesAPIView,
    HrmsGlobalAdoptionPreviewAPIView,
    HrmsGlobalTemplateCatalogAPIView,
    HrmsMetaAPIView,
    HrOrganizationUnitDetailAPIView,
    HrOrganizationUnitListCreateAPIView,
    HrShiftDetailAPIView,
    HrShiftListCreateAPIView,
    LeaveApplicationApprovalAPIView,
    LeaveApplicationCancelAPIView,
    LeaveApplicationListCreateAPIView,
    LeaveApplicationRejectAPIView,
    LeaveBalanceAccrualAPIView,
    LeaveBalanceListAPIView,
    LeaveBalanceBootstrapAPIView,
    LeaveLedgerListAPIView,
    LeavePolicyListAPIView,
    LeavePolicyRuleDetailAPIView,
)

app_name = "hrms"

urlpatterns = [
    path("meta/", HrmsMetaAPIView.as_view(), name="meta"),
    path("organization-units/", HrOrganizationUnitListCreateAPIView.as_view(), name="organization-unit-list"),
    path("organization-units/<uuid:pk>/", HrOrganizationUnitDetailAPIView.as_view(), name="organization-unit-detail"),
    path("employees/", HrEmployeeListCreateAPIView.as_view(), name="employee-list"),
    path("employees/<uuid:pk>/", HrEmployeeDetailAPIView.as_view(), name="employee-detail"),
    path("contracts/", HrEmploymentContractListCreateAPIView.as_view(), name="contract-list"),
    path("contracts/<uuid:pk>/", HrEmploymentContractDetailAPIView.as_view(), name="contract-detail"),
    path("shifts/", HrShiftListCreateAPIView.as_view(), name="shift-list"),
    path("shifts/<uuid:pk>/", HrShiftDetailAPIView.as_view(), name="shift-detail"),
    path("holiday-calendars/", HrHolidayCalendarListCreateAPIView.as_view(), name="holiday-calendar-list"),
    path("holiday-calendars/<uuid:pk>/", HrHolidayCalendarDetailAPIView.as_view(), name="holiday-calendar-detail"),
    path("holiday-calendars/<uuid:calendar_pk>/holidays/", HrHolidayListCreateAPIView.as_view(), name="holiday-list"),
    path("holidays/<uuid:pk>/", HrHolidayDetailAPIView.as_view(), name="holiday-detail"),
    path("global-templates/", HrmsGlobalTemplateCatalogAPIView.as_view(), name="global-template-catalog"),
    path("onboarding/adoption-preview/", HrmsGlobalAdoptionPreviewAPIView.as_view(), name="global-adoption-preview"),
    path("onboarding/adopt/", HrmsGlobalAdoptTemplatesAPIView.as_view(), name="global-adopt"),
    path("onboarding/entity-setup-summary/", HrmsEntitySetupSummaryAPIView.as_view(), name="entity-setup-summary"),
    path("onboarding/entity-setup/<str:setup_type>/<uuid:pk>/", HrmsEntitySetupPatchAPIView.as_view(), name="entity-setup-patch"),
    path("daily-attendance/", DailyAttendanceListCreateAPIView.as_view(), name="daily-attendance-list"),
    path("daily-attendance/bulk-upsert/", DailyAttendanceBulkUpsertAPIView.as_view(), name="daily-attendance-bulk-upsert"),
    path("attendance-import-batches/", AttendanceImportBatchListCreateAPIView.as_view(), name="attendance-import-batch-list"),
    path("attendance-payroll-periods/", AttendancePayrollPeriodListAPIView.as_view(), name="attendance-payroll-period-list"),
    path("attendance-monthly-summaries/", AttendanceMonthlySummaryAPIView.as_view(), name="attendance-monthly-summary"),
    path("attendance-approvals/", AttendanceApprovalListAPIView.as_view(), name="attendance-approval-list"),
    path("attendance-approvals/contracts/<uuid:pk>/submit/", AttendanceApprovalSubmitAPIView.as_view(), name="attendance-approval-submit"),
    path("attendance-approvals/<uuid:pk>/approve/", AttendanceApprovalApproveAPIView.as_view(), name="attendance-approval-approve"),
    path("attendance-approvals/<uuid:pk>/reject/", AttendanceApprovalRejectAPIView.as_view(), name="attendance-approval-reject"),
    path("attendance-monthly-closes/", AttendanceMonthlyCloseListCreateAPIView.as_view(), name="attendance-monthly-close-list"),
    path("attendance-monthly-closes/<uuid:pk>/submit/", AttendanceMonthlyCloseSubmitAPIView.as_view(), name="attendance-monthly-close-submit"),
    path("attendance-monthly-closes/<uuid:pk>/approve/", AttendanceMonthlyCloseApproveAPIView.as_view(), name="attendance-monthly-close-approve"),
    path("attendance-monthly-closes/<uuid:pk>/close/", AttendanceMonthlyCloseCloseAPIView.as_view(), name="attendance-monthly-close-close"),
    path("leave-policies/", LeavePolicyListAPIView.as_view(), name="leave-policy-list"),
    path("leave-policy-rules/<uuid:pk>/", LeavePolicyRuleDetailAPIView.as_view(), name="leave-policy-rule-detail"),
    path("leave-balances/", LeaveBalanceListAPIView.as_view(), name="leave-balance-list"),
    path("leave-balances/contracts/<uuid:pk>/bootstrap/", LeaveBalanceBootstrapAPIView.as_view(), name="leave-balance-bootstrap"),
    path("leave-balances/contracts/<uuid:pk>/accrue/", LeaveBalanceAccrualAPIView.as_view(), name="leave-balance-accrue"),
    path("leave-ledger/", LeaveLedgerListAPIView.as_view(), name="leave-ledger-list"),
    path("leave-applications/", LeaveApplicationListCreateAPIView.as_view(), name="leave-application-list"),
    path("leave-applications/<uuid:pk>/approve/", LeaveApplicationApprovalAPIView.as_view(), name="leave-application-approve"),
    path("leave-applications/<uuid:pk>/reject/", LeaveApplicationRejectAPIView.as_view(), name="leave-application-reject"),
    path("leave-applications/<uuid:pk>/cancel/", LeaveApplicationCancelAPIView.as_view(), name="leave-application-cancel"),
]
