# Generated by Django 4.2.28 on 2026-02-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('cityname', models.CharField(max_length=255)),
                ('citycode', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=25)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('countryname', models.CharField(max_length=255)),
                ('countrycode', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('statename', models.CharField(max_length=255)),
                ('statecode', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state', to='geography.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('districtname', models.CharField(max_length=255)),
                ('districtcode', models.CharField(max_length=25)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geography.state')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['countrycode', 'countryname'], name='geography_c_country_b10b19_idx'),
        ),
        migrations.AddField(
            model_name='city',
            name='distt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='geography.district'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['statecode', 'statename'], name='geography_s_stateco_bc84be_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['districtcode', 'districtname'], name='geography_d_distric_866045_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['citycode', 'pincode'], name='geography_c_citycod_6c0232_idx'),
        ),
    ]
