# Generated by Django 5.2.1 on 2026-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='statecode',
            field=models.CharField(max_length=2),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('countrycode',), name='uq_country_active_code'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('country', 'statecode'), name='uq_state_active_country_code'),
        ),
    ]
