# Generated by Django 5.2.1 on 2026-04-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_state_statecode_country_uq_country_active_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('distt', 'citycode'), name='uq_city_active_district_code'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('distt', 'cityname', 'pincode'), name='uq_city_active_district_name_pin'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('state', 'districtcode'), name='uq_district_active_state_code'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('state', 'districtname'), name='uq_district_active_state_name'),
        ),
    ]
