# Generated by Django 5.2.1 on 2026-04-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_godown_entity_godown_subentity_alter_godown_code_and_more'),
        ('inventory_ops', '0002_inventoryadjustment_inventoryadjustmentline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown'),
        ),
        migrations.AlterField(
            model_name='inventorytransfer',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown'),
        ),
        migrations.AlterField(
            model_name='inventorytransfer',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown'),
        ),
    ]
