# Generated by Django 4.2.28 on 2026-04-17 16:48

from django.db import migrations, models
import inventory_ops.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_ops', '0005_inventoryopssettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryopssettings',
            options={},
        ),
        migrations.AlterField(
            model_name='inventoryopssettings',
            name='policy_controls',
            field=models.JSONField(blank=True, default=inventory_ops.models.default_inventory_ops_policy_controls),
        ),
    ]
