# Generated by Django 4.2.28 on 2026-02-27 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='gsttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gsttypename', models.CharField(max_length=255, verbose_name='Gst type Name')),
                ('gsttypecode', models.CharField(max_length=255, verbose_name='Gst Type Code')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HsnChaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('Chapter', models.CharField(max_length=255, verbose_name='Chapter')),
                ('Description', models.CharField(max_length=2000, verbose_name='Chapter Description')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HsnCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('hsnCode', models.CharField(max_length=255, verbose_name='Hsn code')),
                ('Hsndescription', models.CharField(max_length=2000, verbose_name='Hsn Description')),
                ('GSTRate', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=14)),
                ('Chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.hsnchaper')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('productname', models.CharField(max_length=50, verbose_name='Product Name')),
                ('productcode', models.IntegerField(blank=True, null=True, verbose_name='Product Code')),
                ('productdesc', models.CharField(max_length=100, null=True, verbose_name='product desc')),
                ('is_pieces', models.BooleanField(default=True)),
                ('openingstockqty', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('openingstockboxqty', models.IntegerField(blank=True, null=True, verbose_name='Box/Pcs')),
                ('openingstockvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchaserate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Purchase Rate')),
                ('prlesspercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mrpless', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salesprice', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('totalgst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cesstype', models.BooleanField(default=True)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True)),
                ('is_product', models.BooleanField(default=True)),
                ('barcode_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barcode Number')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Barcode Image')),
                ('isbarcoderequired', models.BooleanField(default=True, verbose_name='Is Barcode Required')),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('gsttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.gsttype', verbose_name='Gst Type')),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.hsncode', verbose_name='Hsn Code')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherdate', models.DateField(auto_now_add=True, null=True, verbose_name='Vocucher Date')),
                ('voucherno', models.IntegerField(default=1, verbose_name='Voucher No')),
                ('quantity_to_produce', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveIntegerField(default=1)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.billofmaterial')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('entityfinid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear', verbose_name='entity Financial year')),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_production_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='inventory.productionorder')),
            ],
        ),
        migrations.CreateModel(
            name='UnitofMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('unitname', models.CharField(max_length=255, verbose_name='UOM calculate')),
                ('unitcode', models.CharField(max_length=255, verbose_name='UOM calculate')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='typeofgoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('goodstype', models.CharField(max_length=255, null=True, verbose_name='Goods Type')),
                ('goodscode', models.CharField(max_length=255, null=True, verbose_name='Goods Code')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='stkvaluationby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('valuationby', models.CharField(max_length=255, verbose_name='Valuation By')),
                ('valuationcode', models.CharField(max_length=255, verbose_name='valuation code')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='stkcalculateby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('unitname', models.CharField(max_length=255, verbose_name='UOM calculate')),
                ('unitcode', models.CharField(max_length=255, verbose_name='UOM calculate')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ratecalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('rname', models.CharField(max_length=255, verbose_name='Rate calc Name')),
                ('rcode', models.CharField(max_length=255, verbose_name='Rate Calc Code')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=True)),
                ('production_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productionoutput')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrap_or_wastage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.productionorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('wastage_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_skus', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('pcategoryname', models.CharField(max_length=50, verbose_name='Product Category')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('maincategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='Main category')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseaccount', to='financial.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='ratecalculate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ratecalculate', verbose_name='Rate calculate'),
        ),
        migrations.AddField(
            model_name='product',
            name='saleaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='stkcalculateby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stkcalculateby', verbose_name='Stock Calculated By'),
        ),
        migrations.AddField(
            model_name='product',
            name='stkvaluationby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stkvaluationby', verbose_name='Stock valuation by'),
        ),
        migrations.AddField(
            model_name='product',
            name='typeofgoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.typeofgoods', verbose_name='Type of goods'),
        ),
        migrations.AddField(
            model_name='product',
            name='unitofmeasurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement', verbose_name='Unit of Measurement'),
        ),
        migrations.CreateModel(
            name='GstRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('CSGT', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=14)),
                ('SGST', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=14)),
                ('IGST', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=14)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_percentage', models.BooleanField(default=True)),
                ('quantity_required_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_produced_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.billofmaterial')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_raw_materials', to='inventory.product')),
                ('wastage_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_wastage_materials', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='finished_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_versions', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='BarcodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salesprice', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('barcode_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barcode Number')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Barcode Image')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_detail', to='inventory.product', verbose_name='Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together={('finished_good', 'version')},
        ),
    ]
