# Generated by Django 4.2.28 on 2026-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_user_report_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('transactiontype', models.CharField(max_length=255, verbose_name='Transaction Type')),
                ('transactioncode', models.CharField(max_length=2000, verbose_name='Transaction Code')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='userreportpreference',
            new_name='reports_use_user_id_ad64f3_idx',
            old_name='rep_usr_ent_rep_idx',
        ),
        migrations.AlterField(
            model_name='userreportpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
