# Generated by Django 5.2.1 on 2026-04-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0021_alter_entitygstregistration_gstin_and_more'),
        ('reports', '0002_transactiontype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFreezeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('report_code', models.CharField(db_index=True, max_length=50)),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_freeze_snapshots', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_freeze_snapshots', to='entity.entityfinancialyear')),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_freeze_snapshots', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_freeze_snapshots', to='entity.subentity')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report_code', 'entity', 'entityfinid', 'subentity', 'version'], name='reports_rep_report__299905_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_code', 'entity', 'entityfinid', 'subentity', 'version'), name='reports_freeze_scope_version_unique')],
            },
        ),
    ]
