# Generated by Django 5.2.1 on 2026-04-27 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0021_alter_entitygstregistration_gstin_and_more'),
        ('reports', '0003_reportfreezesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFilingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('report_code', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='prepared', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('portal_reference', models.CharField(blank=True, default='', max_length=120)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filing_runs', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filing_runs', to='entity.entityfinancialyear')),
                ('freeze_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filing_runs', to='reports.reportfreezesnapshot')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_report_filing_runs', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_filing_runs', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_report_filing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report_code', 'entity', 'entityfinid', 'subentity', 'status'], name='reports_rep_report__08c31e_idx')],
            },
        ),
    ]
