# Generated by Django 5.2.1 on 2026-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportfilingrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfilingrun',
            name='portal_provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
