# Generated by Django 5.2.1 on 2026-09-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('reports', '0006_report_runtime_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstPortalFilingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, default='whitebox', max_length=40)),
                ('return_type', models.CharField(choices=[('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('gstr2b', 'GSTR-2B')], db_index=True, max_length=12)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('state_cd', models.CharField(blank=True, default='', max_length=2)),
                ('ret_period', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('saved', 'Saved'), ('summary_fetched', 'Summary Fetched'), ('offset', 'Offset'), ('evc_requested', 'EVC Requested'), ('filed', 'Filed'), ('failed', 'Failed')], db_index=True, default='prepared', max_length=24)),
                ('stage', models.CharField(blank=True, default='prepared', max_length=40)),
                ('txn', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('portal_reference', models.CharField(blank=True, default='', max_length=120)),
                ('scope_payload', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('portal_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_portal_filing_runs', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_portal_filing_runs', to='entity.entityfinancialyear')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_gst_portal_filing_runs', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_portal_filing_runs', to='entity.subentity')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_gst_portal_filing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['provider', 'return_type', 'entity', 'entityfinid', 'gstin', 'ret_period'], name='reports_gst_provide_bb0290_idx'), models.Index(fields=['return_type', 'entity', 'entityfinid', 'subentity', 'status'], name='ix_gst_portal_filing_scope')],
            },
        ),
        migrations.CreateModel(
            name='GstPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, default='whitebox', max_length=40)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('state_cd', models.CharField(blank=True, default='', max_length=2)),
                ('gst_username', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('txn', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('otp_requested', 'OTP Requested'), ('authenticated', 'Authenticated'), ('logged_out', 'Logged Out'), ('failed', 'Failed')], db_index=True, default='otp_requested', max_length=24)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('otp_requested_at', models.DateTimeField(blank=True, null=True)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('authenticated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticated_gst_portal_sessions', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_portal_sessions', to='entity.entity')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_gst_portal_sessions', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_portal_sessions', to='entity.subentity')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['provider', 'entity', 'gstin', 'status'], name='reports_gst_provide_b09c24_idx'), models.Index(fields=['provider', 'entity', 'subentity', 'gstin'], name='ix_gst_portal_session_scope')],
            },
        ),
    ]
