# Generated by Codex on 2026-09-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_gst_portal_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GstPortalProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=True)),
                ("provider", models.CharField(db_index=True, default="whitebox", max_length=40)),
                ("gstin", models.CharField(db_index=True, max_length=15)),
                ("state_cd", models.CharField(blank=True, default="", max_length=2)),
                ("gst_username", models.CharField(blank=True, default="", max_length=128)),
                ("registered_mobile_masked", models.CharField(blank=True, default="", max_length=32)),
                ("registered_email_masked", models.EmailField(blank=True, default="", max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_portal_profiles",
                        to="entity.entity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_gst_portal_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("entity_id", "gstin", "provider"),
                "indexes": [
                    models.Index(fields=["provider", "entity", "gstin", "isactive"], name="ix_gst_portal_profile_scope"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "entity", "gstin"), name="reports_gst_portal_profile_unique"),
                ],
            },
        ),
    ]
