# Generated by Django 5.2.1 on 2026-09-18 06:31

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('reports', '0009_gst_portal_proceeded_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstComplianceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('return_period', models.CharField(db_index=True, max_length=7)),
                ('return_type', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('source_code', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('blocked', 'Blocked'), ('closed', 'Closed')], db_index=True, default='open', max_length=24)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='warning', max_length=16)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_note', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_gst_compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gst_compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_compliance_tasks', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_compliance_tasks', to='entity.entityfinancialyear')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_gst_compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_compliance_tasks', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gst_compliance_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'due_date', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GstComplianceTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('file', models.FileField(max_length=255, upload_to=reports.models._gst_compliance_task_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.gstcompliancetask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_compliance_task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GstComplianceTaskAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_compliance_task_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reports.gstcompliancetask')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GstComplianceTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_compliance_task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.gstcompliancetask')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='gstcompliancetask',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'gstin', 'return_period', 'status'], name='ix_gst_task_scope_status'),
        ),
        migrations.AddIndex(
            model_name='gstcompliancetask',
            index=models.Index(fields=['entity', 'owner', 'status', 'due_date'], name='ix_gst_task_owner_due'),
        ),
        migrations.AddIndex(
            model_name='gstcompliancetaskattachment',
            index=models.Index(fields=['task', 'created_at'], name='ix_gst_task_attach_task_dt'),
        ),
        migrations.AddIndex(
            model_name='gstcompliancetaskaudit',
            index=models.Index(fields=['task', 'action', 'created_at'], name='ix_gst_task_audit_task_action'),
        ),
        migrations.AddIndex(
            model_name='gstcompliancetaskaudit',
            index=models.Index(fields=['actor', 'created_at'], name='ix_gst_task_audit_actor_dt'),
        ),
        migrations.AddIndex(
            model_name='gstcompliancetaskcomment',
            index=models.Index(fields=['task', 'created_at'], name='ix_gst_task_comment_task_dt'),
        ),
    ]
