# Generated by Django 5.2.1 on 2026-09-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('reports', '0010_gstcompliancetask_gstcompliancetaskattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstCompliancePeriodLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('return_period', models.CharField(db_index=True, max_length=7)),
                ('portal_return_period', models.CharField(blank=True, db_index=True, default='', max_length=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('prepared', 'Prepared'), ('in_review', 'In Review'), ('frozen', 'Frozen'), ('filed', 'Filed'), ('amendment_open', 'Amendment Open')], db_index=True, default='open', max_length=24)),
                ('locked', models.BooleanField(db_index=True, default=False)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('portal_reference', models.CharField(blank=True, default='', max_length=120)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_compliance_period_lifecycles', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_compliance_period_lifecycles', to='entity.entityfinancialyear')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_gst_period_lifecycles', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_gst_period_lifecycles', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_gst_period_lifecycles', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_gst_period_lifecycles', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gst_period_lifecycles', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gst_compliance_period_lifecycles', to='entity.subentity')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='GstCompliancePeriodLifecycleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_period_lifecycle_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reports.gstcomplianceperiodlifecycle')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='gstcomplianceperiodlifecycle',
            index=models.Index(fields=['entity', 'entityfinid', 'gstin', 'return_period', 'status'], name='ix_gst_period_life_scope'),
        ),
        migrations.AddIndex(
            model_name='gstcomplianceperiodlifecycle',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'locked'], name='ix_gst_period_life_locked'),
        ),
        migrations.AddConstraint(
            model_name='gstcomplianceperiodlifecycle',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfinid', 'subentity', 'gstin', 'return_period'), name='reports_gst_period_lifecycle_unique'),
        ),
        migrations.AddIndex(
            model_name='gstcomplianceperiodlifecycleaudit',
            index=models.Index(fields=['lifecycle', 'action', 'created_at'], name='ix_gst_life_audit_action'),
        ),
        migrations.AddIndex(
            model_name='gstcomplianceperiodlifecycleaudit',
            index=models.Index(fields=['actor', 'created_at'], name='ix_gst_life_audit_actor'),
        ),
    ]
