from django.urls import path

from .views import PlatformMeAPIView
from .discovery_views import (
    PlatformCustomerDetailAPIView,
    PlatformCustomerListAPIView,
    PlatformSubscriptionPlanListAPIView,
    PlatformConfigurationHealthAPIView,
    PlatformDashboardAPIView,
    PlatformEntityDetailAPIView,
    PlatformEntityListAPIView,
    PlatformOperatorListAPIView,
    PlatformRoleListAPIView,
    PlatformOperatorCandidateListAPIView,
    PlatformSecuritySummaryAPIView,
    PlatformAuditEventListAPIView,
)
from .onboarding_views import PlatformOnboardingValidationAPIView
from .customer_request_views import (
    PlatformCustomerServiceRequestDetailAPIView,
    PlatformCustomerServiceRequestListAPIView,
)
from .operation_views import (
    PlatformOnboardingRequestAPIView,
    PlatformOperationDetailAPIView,
    PlatformOperationExecuteAPIView,
    PlatformOperationListAPIView,
    PlatformCustomerContactUpdateAPIView,
    PlatformCustomerStatusUpdateAPIView,
    PlatformOperationDecisionAPIView,
    PlatformAddBranchRequestAPIView,
    PlatformAddFinancialYearRequestAPIView,
    PlatformEntityGstUpdateAPIView,
    PlatformSubscriptionPlanChangeAPIView,
    PlatformTenantMembershipUpdateAPIView,
    PlatformTenantUserInviteAPIView,
    PlatformTenantInvitationResendAPIView,
    PlatformCustomerOwnershipTransferAPIView,
    PlatformOperationCancelAPIView,
    PlatformOnboardingRepairPreviewAPIView,
    PlatformOnboardingRepairExecuteAPIView,
    PlatformEntityNumberingRepairPreviewAPIView,
    PlatformEntityNumberingRepairRequestAPIView,
    PlatformEntityPostingMappingRepairPreviewAPIView,
    PlatformEntityPostingMappingRepairRequestAPIView,
    PlatformEntityRbacRoleRepairPreviewAPIView,
    PlatformEntityRbacRoleRepairRequestAPIView,
    PlatformEntityCatalogRepairPreviewAPIView,
    PlatformEntityCatalogRepairRequestAPIView,
    PlatformEntityAssetRepairPreviewAPIView,
    PlatformEntityAssetRepairRequestAPIView,
    PlatformEntityTradeSettingsRepairPreviewAPIView,
    PlatformEntityTradeSettingsRepairRequestAPIView,
    PlatformEntityChoiceOverrideAuditAPIView,
    PlatformRoleChangeRequestAPIView,
    PlatformSessionRevocationRequestAPIView,
)


app_name = "platform_ops"

urlpatterns = [
    path("me/", PlatformMeAPIView.as_view(), name="me"),
    path("customer-requests/", PlatformCustomerServiceRequestListAPIView.as_view(), name="customer-request-list"),
    path("customer-requests/<int:pk>/", PlatformCustomerServiceRequestDetailAPIView.as_view(), name="customer-request-detail"),
    path("dashboard/", PlatformDashboardAPIView.as_view(), name="dashboard"),
    path("configuration-health/", PlatformConfigurationHealthAPIView.as_view(), name="configuration-health"),
    path("operators/", PlatformOperatorListAPIView.as_view(), name="operator-list"),
    path("roles/", PlatformRoleListAPIView.as_view(), name="role-list"),
    path("operator-candidates/", PlatformOperatorCandidateListAPIView.as_view(), name="operator-candidate-list"),
    path("security-summary/", PlatformSecuritySummaryAPIView.as_view(), name="security-summary"),
    path("operators/role-change-requests/", PlatformRoleChangeRequestAPIView.as_view(), name="operator-role-change-request"),
    path("operators/session-revocation-requests/", PlatformSessionRevocationRequestAPIView.as_view(), name="operator-session-revocation-request"),
    path("audit-events/", PlatformAuditEventListAPIView.as_view(), name="audit-event-list"),
    path("customers/", PlatformCustomerListAPIView.as_view(), name="customer-list"),
    path("subscription-plans/", PlatformSubscriptionPlanListAPIView.as_view(), name="subscription-plan-list"),
    path("customers/<int:pk>/", PlatformCustomerDetailAPIView.as_view(), name="customer-detail"),
    path("customers/<int:pk>/contact-change-requests/", PlatformCustomerContactUpdateAPIView.as_view(), name="customer-contact-change-request"),
    path("customers/<int:pk>/status-change-requests/", PlatformCustomerStatusUpdateAPIView.as_view(), name="customer-status-change-request"),
    path("customers/<int:pk>/subscription-change-requests/", PlatformSubscriptionPlanChangeAPIView.as_view(), name="customer-subscription-change-request"),
    path("customers/<int:pk>/memberships/<int:membership_id>/change-requests/", PlatformTenantMembershipUpdateAPIView.as_view(), name="customer-membership-change-request"),
    path("customers/<int:pk>/membership-invite-requests/", PlatformTenantUserInviteAPIView.as_view(), name="customer-membership-invite-request"),
    path("customers/<int:pk>/memberships/<int:membership_id>/invitation-resend-requests/", PlatformTenantInvitationResendAPIView.as_view(), name="customer-membership-invitation-resend-request"),
    path("customers/<int:pk>/ownership-transfer-requests/", PlatformCustomerOwnershipTransferAPIView.as_view(), name="customer-ownership-transfer-request"),
    path("entities/", PlatformEntityListAPIView.as_view(), name="entity-list"),
    path("entities/<int:pk>/", PlatformEntityDetailAPIView.as_view(), name="entity-detail"),
    path("entities/<int:pk>/branch-change-requests/", PlatformAddBranchRequestAPIView.as_view(), name="entity-branch-change-request"),
    path("entities/<int:pk>/financial-year-change-requests/", PlatformAddFinancialYearRequestAPIView.as_view(), name="entity-financial-year-change-request"),
    path("entities/<int:pk>/gst-change-requests/", PlatformEntityGstUpdateAPIView.as_view(), name="entity-gst-change-request"),
    path("entities/<int:pk>/numbering-repair-preview/", PlatformEntityNumberingRepairPreviewAPIView.as_view(), name="entity-numbering-repair-preview"),
    path("entities/<int:pk>/numbering-repair-requests/", PlatformEntityNumberingRepairRequestAPIView.as_view(), name="entity-numbering-repair-request"),
    path("entities/<int:pk>/posting-mapping-repair-preview/", PlatformEntityPostingMappingRepairPreviewAPIView.as_view(), name="entity-posting-mapping-repair-preview"),
    path("entities/<int:pk>/posting-mapping-repair-requests/", PlatformEntityPostingMappingRepairRequestAPIView.as_view(), name="entity-posting-mapping-repair-request"),
    path("entities/<int:pk>/rbac-role-repair-preview/", PlatformEntityRbacRoleRepairPreviewAPIView.as_view(), name="entity-rbac-role-repair-preview"),
    path("entities/<int:pk>/rbac-role-repair-requests/", PlatformEntityRbacRoleRepairRequestAPIView.as_view(), name="entity-rbac-role-repair-request"),
    path("entities/<int:pk>/catalog-repair-preview/", PlatformEntityCatalogRepairPreviewAPIView.as_view(), name="entity-catalog-repair-preview"),
    path("entities/<int:pk>/catalog-repair-requests/", PlatformEntityCatalogRepairRequestAPIView.as_view(), name="entity-catalog-repair-request"),
    path("entities/<int:pk>/asset-repair-preview/", PlatformEntityAssetRepairPreviewAPIView.as_view(), name="entity-asset-repair-preview"),
    path("entities/<int:pk>/asset-repair-requests/", PlatformEntityAssetRepairRequestAPIView.as_view(), name="entity-asset-repair-request"),
    path("entities/<int:pk>/trade-settings-repair-preview/", PlatformEntityTradeSettingsRepairPreviewAPIView.as_view(), name="entity-trade-settings-repair-preview"),
    path("entities/<int:pk>/trade-settings-repair-requests/", PlatformEntityTradeSettingsRepairRequestAPIView.as_view(), name="entity-trade-settings-repair-request"),
    path("entities/<int:pk>/choice-override-audit/", PlatformEntityChoiceOverrideAuditAPIView.as_view(), name="entity-choice-override-audit"),
    path("onboarding/validate/", PlatformOnboardingValidationAPIView.as_view(), name="onboarding-validate"),
    path("onboarding/preview/", PlatformOnboardingValidationAPIView.as_view(), name="onboarding-preview"),
    path("onboarding/requests/", PlatformOnboardingRequestAPIView.as_view(), name="onboarding-request"),
    path("operations/", PlatformOperationListAPIView.as_view(), name="operation-list"),
    path("operations/<uuid:pk>/", PlatformOperationDetailAPIView.as_view(), name="operation-detail"),
    path("operations/<uuid:pk>/execute/", PlatformOperationExecuteAPIView.as_view(), name="operation-execute"),
    path(
        "operations/<uuid:pk>/retry/",
        PlatformOperationExecuteAPIView.as_view(
            retry=True,
            required_platform_permissions=("platform.operation.execute", "platform.repair.execute"),
        ),
        name="operation-retry",
    ),
    path("operations/<uuid:pk>/cancel/", PlatformOperationCancelAPIView.as_view(), name="operation-cancel"),
    path("operations/<uuid:pk>/repair-preview/", PlatformOnboardingRepairPreviewAPIView.as_view(), name="operation-repair-preview"),
    path("operations/<uuid:pk>/repair/", PlatformOnboardingRepairExecuteAPIView.as_view(), name="operation-repair"),
    path("operations/<uuid:pk>/decision/", PlatformOperationDecisionAPIView.as_view(), name="operation-decision"),
]
