# Generated by Django 4.1 on 2022-09-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
