# Generated by Django 4.2.28 on 2026-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_remove_role_entity_remove_roleprivilege_entity_and_more'),
        ('Authentication', '0003_authotp_authsession_refresh_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='mainmenu',
        ),
        migrations.RemoveField(
            model_name='authotp',
            name='code',
        ),
        migrations.AddField(
            model_name='authotp',
            name='code_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='event',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('email_verified', 'Email Verified'), ('session_revoked', 'Session Revoked'), ('account_locked', 'Account Locked')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the email address has been verified.', verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Display username. Email is used for login.', max_length=150, verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['user', 'event', 'created_at'], name='Authenticat_user_id_415939_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['email', 'created_at'], name='Authenticat_email_44eb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['email', 'purpose', 'expires_at'], name='Authenticat_email_e9fe19_idx'),
        ),
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['user', 'purpose', 'consumed_at'], name='Authenticat_user_id_bf5a21_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'revoked_at'], name='Authenticat_user_id_79eb74_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'expires_at'], name='Authenticat_user_id_5ad3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'last_used_at'], name='Authenticat_user_id_027b04_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='Authenticat_email_896583_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified'], name='Authenticat_email_v_eab504_idx'),
        ),
        migrations.DeleteModel(
            name='MainMenu',
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
