# Generated by Django 5.2.1 on 2026-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_remove_submenu_mainmenu_remove_authotp_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authotp',
            index=models.Index(fields=['email', 'purpose', 'consumed_at', 'created_at'], name='ix_auth_otp_email_act_dt'),
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'revoked_at', 'issued_at'], name='ix_auth_sess_user_rev_dt'),
        ),
    ]
