# Generated by Django 4.1 on 2022-09-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('Authentication', '0005_rename_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity'),
        ),
    ]
