from django.urls import path

from assets.views import (
    AssetCategoryBulkImportCommitAPIView,
    AssetCategoryBulkImportValidateAPIView,
    AssetCategoryBulkJobDetailAPIView,
    AssetCategoryBulkJobErrorsExportAPIView,
    AssetCategoryBulkTemplateAPIView,
    AssetCategoryListCreateAPIView,
    AssetCategoryRetrieveUpdateAPIView,
    AssetMetaAPIView,
    AssetSettingsAPIView,
    AssetCategoryDestroyAPIView,
    DepreciationRunCalculateAPIView,
    DepreciationRunListCreateAPIView,
    DepreciationRunCancelAPIView,
    DepreciationRunPostAPIView,
    FixedAssetBulkImportCommitAPIView,
    FixedAssetBulkImportValidateAPIView,
    FixedAssetBulkJobDetailAPIView,
    FixedAssetBulkJobErrorsExportAPIView,
    FixedAssetBulkTemplateAPIView,
    DepreciationRunRetrieveAPIView,
    FixedAssetCapitalizeAPIView,
    FixedAssetDestroyAPIView,
    FixedAssetDisposeAPIView,
    FixedAssetImpairAPIView,
    FixedAssetListCreateAPIView,
    FixedAssetRetrieveUpdateAPIView,
    FixedAssetTransferAPIView,
)

app_name = "assets_api"

urlpatterns = [
    path("settings/", AssetSettingsAPIView.as_view(), name="asset-settings"),
    path("meta/", AssetMetaAPIView.as_view(), name="asset-meta"),
    path("categories/", AssetCategoryListCreateAPIView.as_view(), name="asset-category-list-create"),
    path("categories/<int:pk>/", AssetCategoryRetrieveUpdateAPIView.as_view(), name="asset-category-detail"),
    path("categories/<int:pk>/archive/", AssetCategoryDestroyAPIView.as_view(), name="asset-category-archive"),
    path("categories/bulk/template/", AssetCategoryBulkTemplateAPIView.as_view(), name="asset-category-bulk-template"),
    path("categories/bulk/import/validate/", AssetCategoryBulkImportValidateAPIView.as_view(), name="asset-category-bulk-import-validate"),
    path("categories/bulk/import/commit/", AssetCategoryBulkImportCommitAPIView.as_view(), name="asset-category-bulk-import-commit"),
    path("categories/bulk/jobs/<int:job_id>/", AssetCategoryBulkJobDetailAPIView.as_view(), name="asset-category-bulk-job-detail"),
    path("categories/bulk/jobs/<int:job_id>/errors/", AssetCategoryBulkJobErrorsExportAPIView.as_view(), name="asset-category-bulk-job-errors"),
    path("fixed-assets/", FixedAssetListCreateAPIView.as_view(), name="fixed-asset-list-create"),
    path("fixed-assets/<int:pk>/", FixedAssetRetrieveUpdateAPIView.as_view(), name="fixed-asset-detail"),
    path("fixed-assets/<int:pk>/archive/", FixedAssetDestroyAPIView.as_view(), name="fixed-asset-archive"),
    path("fixed-assets/<int:pk>/capitalize/", FixedAssetCapitalizeAPIView.as_view(), name="fixed-asset-capitalize"),
    path("fixed-assets/<int:pk>/impair/", FixedAssetImpairAPIView.as_view(), name="fixed-asset-impair"),
    path("fixed-assets/<int:pk>/transfer/", FixedAssetTransferAPIView.as_view(), name="fixed-asset-transfer"),
    path("fixed-assets/<int:pk>/dispose/", FixedAssetDisposeAPIView.as_view(), name="fixed-asset-dispose"),
    path("fixed-assets/bulk/template/", FixedAssetBulkTemplateAPIView.as_view(), name="fixed-asset-bulk-template"),
    path("fixed-assets/bulk/import/validate/", FixedAssetBulkImportValidateAPIView.as_view(), name="fixed-asset-bulk-import-validate"),
    path("fixed-assets/bulk/import/commit/", FixedAssetBulkImportCommitAPIView.as_view(), name="fixed-asset-bulk-import-commit"),
    path("fixed-assets/bulk/jobs/<int:job_id>/", FixedAssetBulkJobDetailAPIView.as_view(), name="fixed-asset-bulk-job-detail"),
    path("fixed-assets/bulk/jobs/<int:job_id>/errors/", FixedAssetBulkJobErrorsExportAPIView.as_view(), name="fixed-asset-bulk-job-errors"),
    path("depreciation-runs/", DepreciationRunListCreateAPIView.as_view(), name="depreciation-run-list-create"),
    path("depreciation-runs/<int:pk>/", DepreciationRunRetrieveAPIView.as_view(), name="depreciation-run-detail"),
    path("depreciation-runs/<int:pk>/calculate/", DepreciationRunCalculateAPIView.as_view(), name="depreciation-run-calculate"),
    path("depreciation-runs/<int:pk>/post/", DepreciationRunPostAPIView.as_view(), name="depreciation-run-post"),
    path("depreciation-runs/<int:pk>/cancel/", DepreciationRunCancelAPIView.as_view(), name="depreciation-run-cancel"),
]
