# Generated by Django 5.2.1 on 2026-04-18 09:43

import django.db.models.deletion
import django.utils.timezone
import manufacturing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_expiry_warning_days_and_more'),
        ('entity', '0020_remove_entity_unittype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('output_qty', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=18)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entity')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('output_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingBOMMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('waste_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='manufacturing.manufacturingbom')),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_doc_code_work_order', models.CharField(default='MWO', max_length=10)),
                ('default_workflow_action', models.CharField(choices=[('draft', 'Save as Draft'), ('post', 'Auto Post on Save')], db_index=True, default='draft', max_length=10)),
                ('policy_controls', models.JSONField(blank=True, default=manufacturing.models.default_manufacturing_policy_controls)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_settings', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_settings', to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('production_date', models.DateField(db_index=True)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('posting_entry_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='manufacturing.manufacturingbom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entityfinancialyear')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingWorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, default='', max_length=80)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('required_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('actual_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('waste_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='manufacturing.manufacturingworkorder')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingWorkOrderOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, default='', max_length=80)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('planned_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('actual_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='manufacturing.manufacturingworkorder')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='manufacturingbom',
            index=models.Index(fields=['entity', 'subentity', 'finished_product'], name='ix_mfg_bom_scope_product'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingbom',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity__isnull', False)), fields=('entity', 'subentity', 'code'), name='uq_mfg_bom_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingbom',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity__isnull', True)), fields=('entity', 'code'), name='uq_mfg_bom_root_code'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingbommaterial',
            constraint=models.UniqueConstraint(fields=('bom', 'line_no'), name='uq_mfg_bom_line_no'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingsettings',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity'), name='uq_mfg_settings_entity_subentity'),
        ),
        migrations.AddIndex(
            model_name='manufacturingworkorder',
            index=models.Index(fields=['entity', 'production_date'], name='ix_mfg_wo_entity_date'),
        ),
        migrations.AddIndex(
            model_name='manufacturingworkorder',
            index=models.Index(fields=['entity', 'work_order_no'], name='ix_mfg_wo_entity_no'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingworkordermaterial',
            constraint=models.UniqueConstraint(fields=('work_order', 'line_no'), name='uq_mfg_wo_material_line_no'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingworkorderoutput',
            constraint=models.UniqueConstraint(fields=('work_order', 'line_no'), name='uq_mfg_wo_output_line_no'),
        ),
    ]
