# Generated by Django 5.2.1 on 2026-04-18 13:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_remove_entity_unittype'),
        ('manufacturing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='manufacturingbom',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='manufacturing.manufacturingroute'),
        ),
        migrations.CreateModel(
            name='ManufacturingRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('step_code', models.CharField(blank=True, default='', max_length=40)),
                ('step_name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('default_duration_mins', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_qc', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manufacturing.manufacturingroute')),
            ],
            options={
                'ordering': ['sequence_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingWorkOrderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(default=1)),
                ('step_code', models.CharField(blank=True, default='', max_length=40)),
                ('step_name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('requires_qc', models.BooleanField(default=False)),
                ('input_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('output_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('scrap_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('route_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='manufacturing.manufacturingroutestep')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='manufacturing.manufacturingworkorder')),
            ],
            options={
                'ordering': ['sequence_no', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='manufacturingroute',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity__isnull', False)), fields=('entity', 'subentity', 'code'), name='uq_mfg_route_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingroute',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity__isnull', True)), fields=('entity', 'code'), name='uq_mfg_route_root_code'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingroutestep',
            constraint=models.UniqueConstraint(fields=('route', 'sequence_no'), name='uq_mfg_route_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingworkorderoperation',
            constraint=models.UniqueConstraint(fields=('work_order', 'sequence_no'), name='uq_mfg_wo_operation_sequence'),
        ),
    ]
