# Generated by Django 5.2.1 on 2026-04-18 14:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_expiry_warning_days_and_more'),
        ('manufacturing', '0002_manufacturingroute_manufacturingbom_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingBatchTraceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_batch_number', models.CharField(blank=True, default='', max_length=80)),
                ('input_manufacture_date', models.DateField(blank=True, null=True)),
                ('input_expiry_date', models.DateField(blank=True, null=True)),
                ('input_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('output_batch_number', models.CharField(blank=True, default='', max_length=80)),
                ('output_manufacture_date', models.DateField(blank=True, null=True)),
                ('output_expiry_date', models.DateField(blank=True, null=True)),
                ('output_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('input_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('material_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_links', to='manufacturing.manufacturingworkordermaterial')),
                ('output_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_links', to='manufacturing.manufacturingworkorderoutput')),
                ('output_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_links', to='manufacturing.manufacturingworkorder')),
            ],
            options={
                'ordering': ['material_line__line_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('work_order', 'material_line', 'output_line'), name='uq_mfg_trace_work_order_material_output')],
            },
        ),
    ]
