# Generated by Django 5.2.1 on 2026-04-18 15:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_manufacturingbatchtracelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingworkorderoutput',
            name='estimated_recovery_unit_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='manufacturingworkorderoutput',
            name='output_type',
            field=models.CharField(choices=[('MAIN', 'Main Output'), ('BYPRODUCT', 'Byproduct'), ('SALEABLE_SCRAP', 'Saleable Scrap')], db_index=True, default='MAIN', max_length=20),
        ),
    ]
