# Generated by Django 5.2.1 on 2026-04-18 15:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_manufacturingworkorderoutput_estimated_recovery_unit_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='actual_material_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='actual_output_qty_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='actual_recovery_value_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='actual_unit_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='material_variance_value_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='net_production_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='standard_material_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='standard_output_qty_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='standard_recovery_value_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='standard_unit_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='yield_variance_percent_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='yield_variance_qty_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
    ]
