# Generated by Django 5.2.1 on 2026-04-18 16:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_manufacturingworkorder_actual_material_cost_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingworkorder',
            name='total_additional_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.CreateModel(
            name='ManufacturingWorkOrderAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('cost_type', models.CharField(choices=[('LABOUR', 'Labour'), ('ELECTRICITY', 'Electricity'), ('FUEL', 'Fuel'), ('MACHINE', 'Machine'), ('OVERHEAD', 'Overhead'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='manufacturing.manufacturingworkorder')),
            ],
            options={
                'ordering': ['line_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('work_order', 'line_no'), name='uq_mfg_wo_additional_cost_line_no')],
            },
        ),
    ]
