# Generated by Django 5.2.1 on 2026-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_workorder_additional_cost_split_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingworkorderoperation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_QC', 'Awaiting QC'), ('QC_REJECTED', 'QC Rejected'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
