# Generated by Django 5.2.1 on 2026-06-19 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_opening_stock_branch_godown_and_planning_rules'),
        ('entity', '0034_entity_lookup_runtime_indexes'),
        ('manufacturing', '0010_alter_manufacturingworkorderoperation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='manufacturingbom',
            index=models.Index(fields=['entity', 'subentity', 'is_active', 'code'], name='ix_mfg_bom_scope_act_cd'),
        ),
        migrations.AddIndex(
            model_name='manufacturingroute',
            index=models.Index(fields=['entity', 'subentity', 'is_active', 'code'], name='ix_mfg_route_scope_act_cd'),
        ),
        migrations.AddIndex(
            model_name='manufacturingworkorder',
            index=models.Index(fields=['entity', 'entityfin', 'subentity', 'status', 'production_date'], name='ix_mfg_wo_scope_stat_dt'),
        ),
    ]
