from django.urls import path
from sales.views.eway_views import (
    SalesInvoiceEWayPrefillAPIView,
    SalesInvoiceGenerateEWayAPIView,
    SalesInvoiceEWayB2CPrefillAPIView,
    SalesInvoiceEWayB2CGenerateAPIView,
    SalesInvoiceCancelEWayAPIView,
    SalesInvoiceEWayUpdateVehicleAPIView,
    SalesInvoiceEWayUpdateTransporterAPIView,
    SalesInvoiceEWayExtendValidityAPIView,
)


from sales.views.sales_invoice_views import (
    SalesInvoiceListCreateAPIView,
    SalesInvoiceRetrieveUpdateAPIView,
    SalesServiceInvoiceListCreateAPIView,
    SalesServiceInvoiceRetrieveUpdateAPIView,
    SalesInvoiceConfirmAPIView,
    SalesInvoicePostAPIView,
    SalesInvoiceCancelAPIView,
    SalesInvoiceReverseAPIView,
    SalesInvoiceSettlementAPIView,
)

from sales.views.sales_invoice_compliance_api import (
    SalesInvoiceEnsureComplianceAPIView,
    SalesInvoiceComplianceStatusAPIView,
    SalesInvoiceGenerateIRNAPIView,
    SalesInvoiceGenerateIRNAndEWayAPIView,
    SalesInvoiceCancelIRNAPIView,
    SalesInvoiceGetIRNDetailsAPIView,
    SalesInvoiceGetEWayByIRNAPIView,
   # SalesInvoiceGenerateEWayAPIView,
)
from sales.views.sales_choices_views import SalesChoicesAPIView
from sales.views.sales_settings_views import SalesSettingsAPIView
from sales.views.sales_meta import (
    LegacyCombinedSalesMetaAPIView,
    SalesInvoiceFormMetaAPIView,
    SalesInvoiceDetailFormMetaAPIView,
    SalesInvoiceSearchMetaAPIView,
    SalesInvoiceLinesMetaAPIView,
    SalesAvailableBatchesAPIView,
    SalesStockBalanceHintAPIView,
    SalesInvoiceSummaryAPIView,
    SalesArMetaAPIView,
    SalesArSettlementFormMetaAPIView,
    SalesSettingsMetaAPIView,
    SalesComplianceMetaAPIView,
)
from sales.views.sales_charge_type_views import (
    SalesChargeTypeListCreateAPIView,
    SalesChargeTypeRetrieveUpdateAPIView,
)
from sales.views.sales_ar import (
    CustomerBillOpenItemListAPIView,
    CustomerAdvanceBalanceListAPIView,
    CustomerSettlementListCreateAPIView,
    CustomerSettlementPostAPIView,
    CustomerSettlementCancelAPIView,
    CustomerStatementAPIView,
)

urlpatterns = [
    path("invoices/", SalesInvoiceListCreateAPIView.as_view(), name="sales-invoice-list-create"),
    path("invoices/search/", SalesInvoiceListCreateAPIView.as_view(), name="sales-invoice-search"),
    path("invoices/<int:pk>/", SalesInvoiceRetrieveUpdateAPIView.as_view(), name="sales-invoice-detail"),
    path("service-invoices/", SalesServiceInvoiceListCreateAPIView.as_view(), name="sales-service-invoice-list-create"),
    path("service-invoices/search/", SalesServiceInvoiceListCreateAPIView.as_view(), name="sales-service-invoice-search"),
    path("service-invoices/<int:pk>/", SalesServiceInvoiceRetrieveUpdateAPIView.as_view(), name="sales-service-invoice-detail"),

    path("invoices/<int:pk>/confirm/", SalesInvoiceConfirmAPIView.as_view(), name="sales-invoice-confirm"),
    path("invoices/<int:pk>/post/", SalesInvoicePostAPIView.as_view(), name="sales-invoice-post"),
    path("invoices/<int:pk>/cancel/", SalesInvoiceCancelAPIView.as_view(), name="sales-invoice-cancel"),
    path("invoices/<int:pk>/reverse/", SalesInvoiceReverseAPIView.as_view(), name="sales-invoice-reverse"),
    path("invoices/<int:pk>/settlement/", SalesInvoiceSettlementAPIView.as_view(), name="sales-invoice-settlement"),
    path("service-invoices/<int:pk>/confirm/", SalesInvoiceConfirmAPIView.as_view(), name="sales-service-invoice-confirm"),
    path("service-invoices/<int:pk>/post/", SalesInvoicePostAPIView.as_view(), name="sales-service-invoice-post"),
    path("service-invoices/<int:pk>/cancel/", SalesInvoiceCancelAPIView.as_view(), name="sales-service-invoice-cancel"),
    path("service-invoices/<int:pk>/reverse/", SalesInvoiceReverseAPIView.as_view(), name="sales-service-invoice-reverse"),
    path("service-invoices/<int:pk>/settlement/", SalesInvoiceSettlementAPIView.as_view(), name="sales-service-invoice-settlement"),

    path("choices/", SalesChoicesAPIView.as_view(), name="sales-choices"),
    path("settings/", SalesSettingsAPIView.as_view(), name="sales-settings"),
    path("meta/invoice-form/", SalesInvoiceFormMetaAPIView.as_view(), name="sales-invoice-form-meta"),
    path("meta/invoice-detail-form/", SalesInvoiceDetailFormMetaAPIView.as_view(), name="sales-invoice-detail-form-meta"),
    path("meta/invoice-search/", SalesInvoiceSearchMetaAPIView.as_view(), name="sales-invoice-search-meta"),
    path("meta/invoice-lines/", SalesInvoiceLinesMetaAPIView.as_view(), name="sales-invoice-lines-meta"),
    path("meta/available-batches/", SalesAvailableBatchesAPIView.as_view(), name="sales-available-batches"),
    path("meta/stock-hint/", SalesStockBalanceHintAPIView.as_view(), name="sales-stock-hint"),
    path("meta/combined/", LegacyCombinedSalesMetaAPIView.as_view(), name="sales-legacy-combined-meta"),
    path("meta/settings/", SalesSettingsMetaAPIView.as_view(), name="sales-settings-meta"),
    path("meta/compliance/", SalesComplianceMetaAPIView.as_view(), name="sales-compliance-meta"),
    path("charge-types/", SalesChargeTypeListCreateAPIView.as_view(), name="sales-charge-type-list"),
    path("charge-types/<int:pk>/", SalesChargeTypeRetrieveUpdateAPIView.as_view(), name="sales-charge-type-detail"),
    path("invoices/<int:pk>/summary/", SalesInvoiceSummaryAPIView.as_view(), name="sales-invoice-summary"),
    path("ar/meta/", SalesArMetaAPIView.as_view(), name="sales-ar-meta"),
    path("ar/meta/settlement-form/", SalesArSettlementFormMetaAPIView.as_view(), name="sales-ar-settlement-form-meta"),
    path("ar/open-items/", CustomerBillOpenItemListAPIView.as_view(), name="sales-ar-open-items"),
    path("ar/open-advances/", CustomerAdvanceBalanceListAPIView.as_view(), name="sales-ar-open-advances"),
    path("ar/settlements/", CustomerSettlementListCreateAPIView.as_view(), name="sales-ar-settlements"),
    path("ar/settlements/<int:pk>/post/", CustomerSettlementPostAPIView.as_view(), name="sales-ar-settlement-post"),
    path("ar/settlements/<int:pk>/cancel/", CustomerSettlementCancelAPIView.as_view(), name="sales-ar-settlement-cancel"),
    path("ar/customer-statement/", CustomerStatementAPIView.as_view(), name="sales-ar-customer-statement"),
    path("sales-invoices/<int:pk>/compliance/ensure/", SalesInvoiceEnsureComplianceAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/status/", SalesInvoiceComplianceStatusAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/generate-irn/", SalesInvoiceGenerateIRNAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/generate-irn-and-eway/", SalesInvoiceGenerateIRNAndEWayAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/cancel-irn/", SalesInvoiceCancelIRNAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-irn-details/", SalesInvoiceGetIRNDetailsAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-eway-by-irn/", SalesInvoiceGetEWayByIRNAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/prefill/", SalesInvoiceEWayPrefillAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/generate-eway/", SalesInvoiceGenerateEWayAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway-b2c-prefill/", SalesInvoiceEWayB2CPrefillAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/generate-eway-b2c/", SalesInvoiceEWayB2CGenerateAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/cancel-eway/", SalesInvoiceCancelEWayAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/update-vehicle/", SalesInvoiceEWayUpdateVehicleAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/update-transporter/", SalesInvoiceEWayUpdateTransporterAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/extend-validity/", SalesInvoiceEWayExtendValidityAPIView.as_view()),
]
