from django.urls import path
from sales.views.eway_views import (
    SalesInvoiceEWayPrefillAPIView,
    SalesInvoiceGenerateEWayAPIView,
    SalesInvoiceEWayB2CPrefillAPIView,
    SalesInvoiceEWayB2CGenerateAPIView,
    SalesInvoiceGetEWayDetailsAPIView,
    SalesInvoiceGetEWayTransporterDetailsAPIView,
    SalesInvoiceGetEWayGSTINDetailsAPIView,
    SalesInvoiceGetEWayHSNDetailsAPIView,
    SalesInvoiceGetEWayErrorListAPIView,
    SalesInvoiceRejectEWayAPIView,
    SalesInvoiceGetTripSheetAPIView,
    SalesInvoiceGetEWayByDocumentAPIView,
    SalesInvoiceGetEWayBillsForTransporterAPIView,
    SalesInvoiceGetEWayBillReportByTransporterAssignedDateAPIView,
    SalesInvoiceGetEWayBillsByDateAPIView,
    SalesInvoiceGetEWayBillsRejectedByOthersAPIView,
    SalesInvoiceGetEWayBillsForTransporterByGSTINAPIView,
    SalesInvoiceGetEWayBillsForTransporterByStateAPIView,
    SalesInvoiceGetEWayBillsOfOtherPartyAPIView,
    SalesInvoiceGenerateConsolidatedEWayAPIView,
    SalesInvoiceRegenerateTripSheetAPIView,
    SalesInvoiceInitiateMultiVehicleAPIView,
    SalesInvoiceAddMultiVehicleAPIView,
    SalesInvoiceUpdateMultiVehicleAPIView,
    SalesInvoiceCancelEWayAPIView,
    SalesInvoiceEWayUpdateVehicleAPIView,
    SalesInvoiceEWayUpdateTransporterAPIView,
    SalesInvoiceEWayExtendValidityAPIView,
)


from sales.views.sales_invoice_views import (
    SalesInvoiceListCreateAPIView,
    SalesInvoiceCrossModeNavigationAPIView,
    SalesInvoiceLookupAPIView,
    SalesInvoiceRetrieveUpdateAPIView,
    SalesServiceInvoiceCrossModeNavigationAPIView,
    SalesServiceInvoiceListCreateAPIView,
    SalesServiceInvoiceLookupAPIView,
    SalesServiceInvoiceRetrieveUpdateAPIView,
    SalesInvoiceTransportAPIView,
    SalesInvoicePrintAPIView,
    SalesServiceInvoicePrintAPIView,
    SalesInvoiceConfirmAPIView,
    SalesInvoicePostAPIView,
    SalesInvoiceCancelAPIView,
    SalesInvoiceReverseAPIView,
    SalesInvoiceSettlementAPIView,
)
from sales.views.sales_attachment import (
    SalesInvoiceAttachmentDeleteAPIView,
    SalesInvoiceAttachmentDownloadAPIView,
    SalesInvoiceAttachmentListCreateAPIView,
)

from sales.views.sales_invoice_compliance_api import (
    SalesInvoiceEnsureComplianceAPIView,
    SalesInvoiceComplianceStatusAPIView,
    SalesInvoiceGenerateIRNAPIView,
    SalesInvoiceGenerateIRNAndEWayAPIView,
    SalesInvoiceCancelIRNAPIView,
    SalesInvoiceGetIRNDetailsAPIView,
    SalesInvoiceGetIRNByDocDetailsAPIView,
    SalesInvoiceGetGSTNDetailsAPIView,
    SalesInvoiceSyncGSTINFromCPAPIView,
    SalesInvoiceGetB2CQRCodeAPIView,
    SalesInvoiceGetEWayByIRNAPIView,
   # SalesInvoiceGenerateEWayAPIView,
)
from sales.views.sales_choices_views import SalesChoicesAPIView
from sales.views.sales_settings_views import SalesSettingsAPIView
from sales.views.sales_bulk_print_views import (
    SalesBulkPrintJobListCreateAPIView,
    SalesBulkPrintJobDetailAPIView,
    SalesBulkPrintJobDownloadAPIView,
)
from sales.views.sales_meta import (
    LegacyCombinedSalesMetaAPIView,
    SalesInvoiceCustomersMetaAPIView,
    SalesInvoiceFormMetaAPIView,
    SalesInvoiceDetailFormMetaAPIView,
    SalesInvoiceSearchMetaAPIView,
    SalesInvoiceLinesMetaAPIView,
    SalesAvailableBatchesAPIView,
    SalesStockBalanceHintAPIView,
    SalesInvoiceSummaryAPIView,
    SalesArMetaAPIView,
    SalesArSettlementFormMetaAPIView,
    SalesSettingsMetaAPIView,
    SalesComplianceMetaAPIView,
)
from sales.views.sales_charge_type_views import (
    SalesChargeTypeListCreateAPIView,
    SalesChargeTypeRetrieveUpdateAPIView,
)
from sales.views.sales_ar import (
    CustomerBillOpenItemListAPIView,
    CustomerAdvanceBalanceListAPIView,
    CustomerSettlementListCreateAPIView,
    CustomerSettlementPostAPIView,
    CustomerSettlementCancelAPIView,
    CustomerStatementAPIView,
)
from sales.views.sales_ar_exports import (
    CustomerStatementCSVAPIView,
    CustomerStatementExcelAPIView,
    CustomerStatementPDFAPIView,
    CustomerStatementPrintAPIView,
)
from invoice_import.views import (
    SalesInvoiceImportTemplateAPIView,
    SalesInvoiceImportProfileListCreateAPIView,
    SalesInvoiceImportProfileDetailAPIView,
    SalesInvoiceImportJobCreateAPIView,
    SalesInvoiceImportJobDetailAPIView,
    SalesInvoiceImportJobCommitAPIView,
    SalesInvoiceImportJobReviewAPIView,
    SalesInvoiceImportJobErrorsExportAPIView,
    SalesInvoiceImportJobReconciliationAPIView,
)

urlpatterns = [
    path("invoices/", SalesInvoiceListCreateAPIView.as_view(), name="sales-invoice-list-create"),
    path("invoices/lookup/", SalesInvoiceLookupAPIView.as_view(), name="sales-invoice-lookup"),
    path("invoices/search/", SalesInvoiceListCreateAPIView.as_view(), name="sales-invoice-search"),
    path("invoices/<int:pk>/cross-mode-nav/", SalesInvoiceCrossModeNavigationAPIView.as_view(), name="sales-invoice-cross-mode-nav"),
    path("invoices/<int:pk>/", SalesInvoiceRetrieveUpdateAPIView.as_view(), name="sales-invoice-detail"),
    path("invoices/<int:pk>/attachments/", SalesInvoiceAttachmentListCreateAPIView.as_view(), name="sales-invoice-attachments"),
    path("invoices/<int:pk>/attachments/<int:attachment_id>/", SalesInvoiceAttachmentDeleteAPIView.as_view(), name="sales-invoice-attachment-delete"),
    path("invoices/<int:pk>/attachments/<int:attachment_id>/download/", SalesInvoiceAttachmentDownloadAPIView.as_view(), name="sales-invoice-attachment-download"),
    path("invoices/<int:pk>/transport/", SalesInvoiceTransportAPIView.as_view(), name="sales-invoice-transport"),
    path("invoices/<int:pk>/print/", SalesInvoicePrintAPIView.as_view(), name="sales-invoice-print"),
    path("service-invoices/", SalesServiceInvoiceListCreateAPIView.as_view(), name="sales-service-invoice-list-create"),
    path("service-invoices/lookup/", SalesServiceInvoiceLookupAPIView.as_view(), name="sales-service-invoice-lookup"),
    path("service-invoices/search/", SalesServiceInvoiceListCreateAPIView.as_view(), name="sales-service-invoice-search"),
    path("service-invoices/<int:pk>/cross-mode-nav/", SalesServiceInvoiceCrossModeNavigationAPIView.as_view(), name="sales-service-invoice-cross-mode-nav"),
    path("service-invoices/<int:pk>/", SalesServiceInvoiceRetrieveUpdateAPIView.as_view(), name="sales-service-invoice-detail"),
    path("service-invoices/<int:pk>/attachments/", SalesInvoiceAttachmentListCreateAPIView.as_view(), name="sales-service-invoice-attachments"),
    path("service-invoices/<int:pk>/attachments/<int:attachment_id>/", SalesInvoiceAttachmentDeleteAPIView.as_view(), name="sales-service-invoice-attachment-delete"),
    path("service-invoices/<int:pk>/attachments/<int:attachment_id>/download/", SalesInvoiceAttachmentDownloadAPIView.as_view(), name="sales-service-invoice-attachment-download"),
    path("service-invoices/<int:pk>/transport/", SalesInvoiceTransportAPIView.as_view(), name="sales-service-invoice-transport"),
    path("service-invoices/<int:pk>/print/", SalesServiceInvoicePrintAPIView.as_view(), name="sales-service-invoice-print"),

    path("invoices/<int:pk>/confirm/", SalesInvoiceConfirmAPIView.as_view(), name="sales-invoice-confirm"),
    path("invoices/<int:pk>/post/", SalesInvoicePostAPIView.as_view(), name="sales-invoice-post"),
    path("invoices/<int:pk>/cancel/", SalesInvoiceCancelAPIView.as_view(), name="sales-invoice-cancel"),
    path("invoices/<int:pk>/reverse/", SalesInvoiceReverseAPIView.as_view(), name="sales-invoice-reverse"),
    path("invoices/<int:pk>/settlement/", SalesInvoiceSettlementAPIView.as_view(), name="sales-invoice-settlement"),
    path("service-invoices/<int:pk>/confirm/", SalesInvoiceConfirmAPIView.as_view(), name="sales-service-invoice-confirm"),
    path("service-invoices/<int:pk>/post/", SalesInvoicePostAPIView.as_view(), name="sales-service-invoice-post"),
    path("service-invoices/<int:pk>/cancel/", SalesInvoiceCancelAPIView.as_view(), name="sales-service-invoice-cancel"),
    path("service-invoices/<int:pk>/reverse/", SalesInvoiceReverseAPIView.as_view(), name="sales-service-invoice-reverse"),
    path("service-invoices/<int:pk>/settlement/", SalesInvoiceSettlementAPIView.as_view(), name="sales-service-invoice-settlement"),

    path("choices/", SalesChoicesAPIView.as_view(), name="sales-choices"),
    path("settings/", SalesSettingsAPIView.as_view(), name="sales-settings"),
    path("bulk-print/jobs/", SalesBulkPrintJobListCreateAPIView.as_view(), name="sales-bulk-print-job-list-create"),
    path("bulk-print/jobs/<int:job_id>/", SalesBulkPrintJobDetailAPIView.as_view(), name="sales-bulk-print-job-detail"),
    path("bulk-print/jobs/<int:job_id>/download/", SalesBulkPrintJobDownloadAPIView.as_view(), name="sales-bulk-print-job-download"),
    path("legacy-import/template/", SalesInvoiceImportTemplateAPIView.as_view(), name="sales-legacy-import-template"),
    path("legacy-import/profiles/", SalesInvoiceImportProfileListCreateAPIView.as_view(), name="sales-legacy-import-profile-list-create"),
    path("legacy-import/profiles/<int:profile_id>/", SalesInvoiceImportProfileDetailAPIView.as_view(), name="sales-legacy-import-profile-detail"),
    path("legacy-import/jobs/", SalesInvoiceImportJobCreateAPIView.as_view(), name="sales-legacy-import-job-create"),
    path("legacy-import/jobs/<int:job_id>/", SalesInvoiceImportJobDetailAPIView.as_view(), name="sales-legacy-import-job-detail"),
    path("legacy-import/jobs/<int:job_id>/review/", SalesInvoiceImportJobReviewAPIView.as_view(), name="sales-legacy-import-job-review"),
    path("legacy-import/jobs/<int:job_id>/commit/", SalesInvoiceImportJobCommitAPIView.as_view(), name="sales-legacy-import-job-commit"),
    path("legacy-import/jobs/<int:job_id>/errors/", SalesInvoiceImportJobErrorsExportAPIView.as_view(), name="sales-legacy-import-job-errors"),
    path("legacy-import/jobs/<int:job_id>/reconciliation/", SalesInvoiceImportJobReconciliationAPIView.as_view(), name="sales-legacy-import-job-reconciliation"),
    path("meta/invoice-form/", SalesInvoiceFormMetaAPIView.as_view(), name="sales-invoice-form-meta"),
    path("meta/customers/", SalesInvoiceCustomersMetaAPIView.as_view(), name="sales-invoice-customers-meta"),
    path("meta/invoice-detail-form/", SalesInvoiceDetailFormMetaAPIView.as_view(), name="sales-invoice-detail-form-meta"),
    path("meta/invoice-search/", SalesInvoiceSearchMetaAPIView.as_view(), name="sales-invoice-search-meta"),
    path("meta/invoice-lines/", SalesInvoiceLinesMetaAPIView.as_view(), name="sales-invoice-lines-meta"),
    path("meta/available-batches/", SalesAvailableBatchesAPIView.as_view(), name="sales-available-batches"),
    path("meta/stock-hint/", SalesStockBalanceHintAPIView.as_view(), name="sales-stock-hint"),
    path("meta/combined/", LegacyCombinedSalesMetaAPIView.as_view(), name="sales-legacy-combined-meta"),
    path("meta/settings/", SalesSettingsMetaAPIView.as_view(), name="sales-settings-meta"),
    path("meta/compliance/", SalesComplianceMetaAPIView.as_view(), name="sales-compliance-meta"),
    path("charge-types/", SalesChargeTypeListCreateAPIView.as_view(), name="sales-charge-type-list"),
    path("charge-types/<int:pk>/", SalesChargeTypeRetrieveUpdateAPIView.as_view(), name="sales-charge-type-detail"),
    path("invoices/<int:pk>/summary/", SalesInvoiceSummaryAPIView.as_view(), name="sales-invoice-summary"),
    path("ar/meta/", SalesArMetaAPIView.as_view(), name="sales-ar-meta"),
    path("ar/meta/settlement-form/", SalesArSettlementFormMetaAPIView.as_view(), name="sales-ar-settlement-form-meta"),
    path("ar/open-items/", CustomerBillOpenItemListAPIView.as_view(), name="sales-ar-open-items"),
    path("ar/open-advances/", CustomerAdvanceBalanceListAPIView.as_view(), name="sales-ar-open-advances"),
    path("ar/settlements/", CustomerSettlementListCreateAPIView.as_view(), name="sales-ar-settlements"),
    path("ar/settlements/<int:pk>/post/", CustomerSettlementPostAPIView.as_view(), name="sales-ar-settlement-post"),
    path("ar/settlements/<int:pk>/cancel/", CustomerSettlementCancelAPIView.as_view(), name="sales-ar-settlement-cancel"),
    path("ar/customer-statement/", CustomerStatementAPIView.as_view(), name="sales-ar-customer-statement"),
    path("ar/customer-statement/excel/", CustomerStatementExcelAPIView.as_view(), name="sales-ar-customer-statement-excel"),
    path("ar/customer-statement/csv/", CustomerStatementCSVAPIView.as_view(), name="sales-ar-customer-statement-csv"),
    path("ar/customer-statement/pdf/", CustomerStatementPDFAPIView.as_view(), name="sales-ar-customer-statement-pdf"),
    path("ar/customer-statement/print/", CustomerStatementPrintAPIView.as_view(), name="sales-ar-customer-statement-print"),
    path("sales-invoices/<int:pk>/compliance/ensure/", SalesInvoiceEnsureComplianceAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/status/", SalesInvoiceComplianceStatusAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/generate-irn/", SalesInvoiceGenerateIRNAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/generate-irn-and-eway/", SalesInvoiceGenerateIRNAndEWayAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/cancel-irn/", SalesInvoiceCancelIRNAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-irn-details/", SalesInvoiceGetIRNDetailsAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-irn-details-by-doc/", SalesInvoiceGetIRNByDocDetailsAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-gstn-details/", SalesInvoiceGetGSTNDetailsAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/sync-gstin-from-cp/", SalesInvoiceSyncGSTINFromCPAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-b2c-qrcode/", SalesInvoiceGetB2CQRCodeAPIView.as_view()),
    path("sales-invoices/<int:pk>/compliance/get-eway-by-irn/", SalesInvoiceGetEWayByIRNAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/prefill/", SalesInvoiceEWayPrefillAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/generate-eway/", SalesInvoiceGenerateEWayAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-details/", SalesInvoiceGetEWayDetailsAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-transporter-details/", SalesInvoiceGetEWayTransporterDetailsAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-gstin-details/", SalesInvoiceGetEWayGSTINDetailsAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-hsn-details/", SalesInvoiceGetEWayHSNDetailsAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-error-list/", SalesInvoiceGetEWayErrorListAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/reject-eway/", SalesInvoiceRejectEWayAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-trip-sheet/", SalesInvoiceGetTripSheetAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-by-document/", SalesInvoiceGetEWayByDocumentAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/get-eway-bills-for-transporter/", SalesInvoiceGetEWayBillsForTransporterAPIView.as_view()),
    path(
        "sales-invoices/<int:id>/compliance/get-eway-bill-report-by-transporter-assigned-date/",
        SalesInvoiceGetEWayBillReportByTransporterAssignedDateAPIView.as_view(),
    ),
    path("sales-invoices/<int:id>/compliance/get-eway-bills-by-date/", SalesInvoiceGetEWayBillsByDateAPIView.as_view()),
    path(
        "sales-invoices/<int:id>/compliance/get-eway-bills-rejected-by-others/",
        SalesInvoiceGetEWayBillsRejectedByOthersAPIView.as_view(),
    ),
    path(
        "sales-invoices/<int:id>/compliance/get-eway-bills-for-transporter-by-gstin/",
        SalesInvoiceGetEWayBillsForTransporterByGSTINAPIView.as_view(),
    ),
    path(
        "sales-invoices/<int:id>/compliance/get-eway-bills-for-transporter-by-state/",
        SalesInvoiceGetEWayBillsForTransporterByStateAPIView.as_view(),
    ),
    path("sales-invoices/<int:id>/compliance/get-eway-bills-of-other-party/", SalesInvoiceGetEWayBillsOfOtherPartyAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/generate-consolidated-eway/", SalesInvoiceGenerateConsolidatedEWayAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/regenerate-trip-sheet/", SalesInvoiceRegenerateTripSheetAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/initiate-multi-vehicle/", SalesInvoiceInitiateMultiVehicleAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/add-multi-vehicle/", SalesInvoiceAddMultiVehicleAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/update-multi-vehicle/", SalesInvoiceUpdateMultiVehicleAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway-b2c-prefill/", SalesInvoiceEWayB2CPrefillAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/generate-eway-b2c/", SalesInvoiceEWayB2CGenerateAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/cancel-eway/", SalesInvoiceCancelEWayAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/update-vehicle/", SalesInvoiceEWayUpdateVehicleAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/update-transporter/", SalesInvoiceEWayUpdateTransporterAPIView.as_view()),
    path("sales-invoices/<int:id>/compliance/eway/extend-validity/", SalesInvoiceEWayExtendValidityAPIView.as_view()),
]
