# Generated by Django 5.2.1 on 2026-05-17 07:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0027_entityapprovalpolicy'),
        ('payroll', '0005_contract_payroll_bridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPayrollPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('pay_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('BI_MONTHLY', 'Bi-Monthly')], default='MONTHLY', max_length=20)),
                ('payroll_month_start_day', models.PositiveSmallIntegerField(default=1)),
                ('payroll_month_end_day', models.PositiveSmallIntegerField(default=31)),
                ('attendance_cutoff_day', models.PositiveSmallIntegerField(default=31)),
                ('salary_disbursement_day', models.PositiveSmallIntegerField(default=1)),
                ('rounding_mode', models.CharField(choices=[('HALF_UP', 'Half Up'), ('HALF_DOWN', 'Half Down'), ('UP', 'Up'), ('DOWN', 'Down'), ('NONE', 'None')], default='HALF_UP', max_length=20)),
                ('net_pay_rounding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('component_rounding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('lop_calculation_method', models.CharField(choices=[('ATTENDANCE_DAYS', 'Attendance Days'), ('CALENDAR_DAYS', 'Calendar Days'), ('FIXED_DAILY_RATE', 'Fixed Daily Rate'), ('WORKING_DAYS', 'Working Days')], default='ATTENDANCE_DAYS', max_length=30)),
                ('arrear_calculation_method', models.CharField(choices=[('FULL_RECALCULATION', 'Full Recalculation'), ('DIFFERENTIAL_ONLY', 'Differential Only'), ('MANUAL_APPROVAL', 'Manual Approval')], default='DIFFERENTIAL_ONLY', max_length=30)),
                ('negative_salary_policy', models.CharField(choices=[('BLOCK', 'Block Processing'), ('CARRY_FORWARD', 'Carry Forward'), ('ALLOW_WITH_APPROVAL', 'Allow With Approval')], default='BLOCK', max_length=30)),
                ('payslip_publish_policy', models.CharField(choices=[('ON_APPROVAL', 'On Approval'), ('ON_POSTING', 'On Posting'), ('ON_PAYMENT', 'On Payment'), ('MANUAL', 'Manual')], default='ON_APPROVAL', max_length=20)),
                ('payroll_lock_policy', models.CharField(choices=[('ON_CALCULATION', 'On Calculation'), ('ON_APPROVAL', 'On Approval'), ('ON_POSTING', 'On Posting'), ('MANUAL', 'Manual')], default='ON_APPROVAL', max_length=20)),
                ('approval_required', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_policies', to='entity.entity')),
            ],
            options={
                'ordering': ['entity_id', 'pay_frequency', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicyRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(max_length=40)),
                ('rule_key', models.CharField(max_length=60)),
                ('rule_value_json', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.entitypayrollpolicy')),
            ],
            options={
                'ordering': ['policy_id', 'rule_type', 'rule_key', 'effective_from', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='entitypayrollpolicy',
            index=models.Index(fields=['entity', 'pay_frequency', 'is_active'], name='ix_payroll_policy_freq_active'),
        ),
        migrations.AddIndex(
            model_name='entitypayrollpolicy',
            index=models.Index(fields=['entity', 'is_default', 'is_active'], name='ix_payroll_policy_default'),
        ),
        migrations.AddConstraint(
            model_name='entitypayrollpolicy',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='uq_entity_payroll_policy_code'),
        ),
        migrations.AddConstraint(
            model_name='entitypayrollpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('entity', 'pay_frequency'), name='uq_entity_payroll_policy_default_frequency'),
        ),
        migrations.AddConstraint(
            model_name='entitypayrollpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_entity_payroll_policy_dates'),
        ),
        migrations.AddIndex(
            model_name='payrollpolicyrule',
            index=models.Index(fields=['policy', 'is_active'], name='ix_policy_rule_active'),
        ),
        migrations.AddIndex(
            model_name='payrollpolicyrule',
            index=models.Index(fields=['policy', 'rule_type', 'rule_key'], name='ix_policy_rule_type_key'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_payroll_policy_rule_dates'),
        ),
    ]
