# Generated by Django 5.2.1 on 2026-05-17 08:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0027_entityapprovalpolicy'),
        ('payroll', '0006_entitypayrollpolicy_payrollpolicyrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePayItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('REIMBURSEMENT', 'Reimbursement'), ('RECOVERY', 'Recovery')], max_length=20)),
                ('requested_date', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('ARREAR', 'Arrear'), ('INCENTIVE', 'Incentive'), ('REIMBURSEMENT', 'Reimbursement'), ('RECOVERY', 'Recovery'), ('ADJUSTMENT', 'Adjustment')], default='MANUAL', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_pay_items', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_pay_items', to='entity.entity')),
                ('payroll_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_pay_items', to='payroll.payrollcomponent')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='one_time_pay_items', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['contract_payroll_profile_id', '-effective_date', '-requested_date', '-id'],
                'indexes': [models.Index(fields=['entity', 'is_active'], name='ix_otpi_active'), models.Index(fields=['contract_payroll_profile', 'effective_date'], name='ix_otpi_prof_eff'), models.Index(fields=['payroll_period', 'approval_status'], name='ix_otpi_period_stat')],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('REIMBURSEMENT', 'Reimbursement'), ('RECOVERY', 'Recovery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('formula_override', models.TextField(blank=True, default='')),
                ('recurrence_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('BI_MONTHLY', 'Bi-Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_pay_items', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_pay_items', to='entity.entity')),
                ('payroll_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_pay_items', to='payroll.payrollcomponent')),
            ],
            options={
                'ordering': ['contract_payroll_profile_id', 'priority', 'effective_from', 'id'],
                'indexes': [models.Index(fields=['entity', 'is_active'], name='ix_rpi_active'), models.Index(fields=['contract_payroll_profile', 'effective_from'], name='ix_rpi_prof_eff'), models.Index(fields=['contract_payroll_profile', 'payroll_component'], name='ix_rpi_prof_comp')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_recurring_pay_item_dates')],
            },
        ),
    ]
