# Generated by Django 5.2.1 on 2026-05-17 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('payroll', '0007_onetimepayitem_recurringpayitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('scheme_type', models.CharField(choices=[('PF', 'PF'), ('ESI', 'ESI'), ('PT', 'Professional Tax'), ('TDS', 'TDS'), ('LWF', 'LWF'), ('BONUS', 'Bonus'), ('GRATUITY', 'Gratuity'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['country_code', 'state_code', 'scheme_type', 'code'],
                'indexes': [models.Index(fields=['scheme_type', 'is_active'], name='ix_stat_scheme_type'), models.Index(fields=['country_code', 'state_code', 'is_active'], name='ix_stat_scheme_geo')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state_code', '')), fields=('code', 'country_code'), name='uq_stat_scheme_country'), models.UniqueConstraint(condition=models.Q(('state_code', ''), _negated=True), fields=('code', 'country_code', 'state_code'), name='uq_stat_scheme_country_state')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(max_length=50)),
                ('rule_name', models.CharField(max_length=140)),
                ('rule_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('SLAB', 'Slab'), ('FIXED', 'Fixed'), ('FORMULA', 'Formula'), ('THRESHOLD', 'Threshold'), ('ELIGIBILITY', 'Eligibility')], max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rule_json', models.JSONField(blank=True, default=dict)),
                ('applicability_json', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statutory_rules', to='entity.entity')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='payroll.statutoryscheme')),
            ],
            options={
                'ordering': ['scheme_id', 'priority', 'effective_from', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='EntityStatutoryRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=80)),
                ('registration_state', models.CharField(blank=True, default='', max_length=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_registrations', to='entity.entity')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_registrations', to='payroll.statutoryscheme')),
            ],
            options={
                'ordering': ['entity_id', 'scheme_id', 'registration_state', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractStatutoryProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_applicable', models.BooleanField(default=True)),
                ('override_rule_json', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_profiles', to='payroll.contractpayrollprofile')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_profiles', to='payroll.statutoryscheme')),
            ],
            options={
                'ordering': ['contract_payroll_profile_id', 'scheme_id', '-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StatutorySlab',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slab_from', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('slab_to', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('formula', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='payroll.statutoryrule')),
            ],
            options={
                'ordering': ['rule_id', 'slab_from', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='statutoryrule',
            index=models.Index(fields=['scheme', 'is_active'], name='ix_stat_rule_scheme'),
        ),
        migrations.AddIndex(
            model_name='statutoryrule',
            index=models.Index(fields=['entity', 'scheme', 'effective_from'], name='ix_stat_rule_entity'),
        ),
        migrations.AddIndex(
            model_name='statutoryrule',
            index=models.Index(fields=['scheme', 'rule_type', 'priority'], name='ix_stat_rule_type_pri'),
        ),
        migrations.AddConstraint(
            model_name='statutoryrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_stat_rule_dates'),
        ),
        migrations.AddIndex(
            model_name='entitystatutoryregistration',
            index=models.Index(fields=['entity', 'scheme', 'is_active'], name='ix_stat_reg_active'),
        ),
        migrations.AddIndex(
            model_name='entitystatutoryregistration',
            index=models.Index(fields=['entity', 'registration_state'], name='ix_stat_reg_state'),
        ),
        migrations.AddConstraint(
            model_name='entitystatutoryregistration',
            constraint=models.UniqueConstraint(fields=('entity', 'scheme', 'registration_number'), name='uq_entity_stat_reg_number'),
        ),
        migrations.AddConstraint(
            model_name='entitystatutoryregistration',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_entity_stat_reg_dates'),
        ),
        migrations.AddIndex(
            model_name='contractstatutoryprofile',
            index=models.Index(fields=['contract_payroll_profile', 'scheme', 'is_active'], name='ix_csp_active'),
        ),
        migrations.AddIndex(
            model_name='contractstatutoryprofile',
            index=models.Index(fields=['contract_payroll_profile', 'effective_from'], name='ix_csp_eff'),
        ),
        migrations.AddConstraint(
            model_name='contractstatutoryprofile',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_contract_stat_prof_dates'),
        ),
        migrations.AddIndex(
            model_name='statutoryslab',
            index=models.Index(fields=['rule', 'is_active'], name='ix_stat_slab_rule'),
        ),
        migrations.AddIndex(
            model_name='statutoryslab',
            index=models.Index(fields=['rule', 'slab_from'], name='ix_stat_slab_from'),
        ),
        migrations.AddConstraint(
            model_name='statutoryslab',
            constraint=models.CheckConstraint(condition=models.Q(('slab_to__isnull', True), ('slab_to__gte', models.F('slab_from')), _connector='OR'), name='ck_stat_slab_range'),
        ),
    ]
