# Generated by Django 5.2.1 on 2026-05-17 10:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('payroll', '0008_statutory_configuration_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTaxDeclaration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_regime', models.CharField(blank=True, choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime'), ('', 'Not Set')], default='', max_length=20)),
                ('declaration_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('declared_annual_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('previous_employer_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('previous_employer_tds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('standard_deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('professional_tax_declared', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_tax_declarations', to='entity.entity')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_tax_declarations', to='entity.entityfinancialyear')),
            ],
            options={
                'ordering': ['entity_id', 'financial_year_id', 'contract_payroll_profile_id'],
            },
        ),
        migrations.CreateModel(
            name='ContractTaxDeclarationLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(choices=[('80C', '80C'), ('80D', '80D'), ('HRA', 'HRA'), ('LTA', 'LTA'), ('HOME_LOAN_INTEREST', 'Home Loan Interest'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('declared_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('evidence_required', models.BooleanField(default=False)),
                ('evidence_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.contracttaxdeclaration')),
            ],
            options={
                'ordering': ['declaration_id', 'section_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayrollInputSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('TAX_PROJECTION', 'Tax Projection'), ('ATTENDANCE_SUMMARY', 'Attendance Summary'), ('MANUAL_PAYROLL_INPUT', 'Manual Payroll Input')], max_length=30)),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import'), ('SYSTEM', 'System')], default='MANUAL', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_snapshots', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_payroll_input_snapshots', to='entity.entity')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_input_snapshots', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['contract_payroll_profile_id', 'input_type', '-effective_from', '-id'],
                'indexes': [models.Index(fields=['entity', 'input_type', 'is_active'], name='ix_cpis_entity_type'), models.Index(fields=['contract_payroll_profile', 'input_type', 'effective_from'], name='ix_cpis_prof_type'), models.Index(fields=['payroll_period', 'input_type'], name='ix_cpis_period_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_contract_input_snapshot_dates')],
            },
        ),
        migrations.AddIndex(
            model_name='contracttaxdeclaration',
            index=models.Index(fields=['entity', 'financial_year', 'is_active'], name='ix_ctd_entity_year'),
        ),
        migrations.AddIndex(
            model_name='contracttaxdeclaration',
            index=models.Index(fields=['contract_payroll_profile', 'declaration_status'], name='ix_ctd_prof_status'),
        ),
        migrations.AddConstraint(
            model_name='contracttaxdeclaration',
            constraint=models.UniqueConstraint(fields=('contract_payroll_profile', 'financial_year'), name='uq_contract_tax_declaration_contract_year'),
        ),
        migrations.AddIndex(
            model_name='contracttaxdeclarationline',
            index=models.Index(fields=['declaration', 'section_code', 'is_active'], name='ix_ctdl_decl_section'),
        ),
    ]
