# Generated by Django 5.2.1 on 2026-05-17 10:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('payroll', '0009_contracttaxdeclaration_contracttaxdeclarationline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAttendanceAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('PAYABLE_DAY', 'Payable Day'), ('LOP', 'LOP'), ('OVERTIME', 'Overtime'), ('LATE_DEDUCTION', 'Late Deduction'), ('HALF_DAY', 'Half Day')], max_length=30)),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_adjustments', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_attendance_adjustments', to='entity.entity')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_attendance_adjustments', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['entity_id', 'payroll_period_id', 'contract_payroll_profile_id', 'id'],
                'indexes': [models.Index(fields=['entity', 'payroll_period'], name='ix_cattadj_ent_period'), models.Index(fields=['contract_payroll_profile', 'is_active'], name='ix_cattadj_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('adjustment_value', Decimal('0.00')), _negated=True), name='ck_contract_att_adj_non_zero')],
            },
        ),
        migrations.CreateModel(
            name='ContractAttendanceSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('payable_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('weekly_off_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('holiday_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('half_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import'), ('ATTENDANCE_ENGINE', 'Attendance Engine')], default='MANUAL', max_length=30)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_attendance_summaries', to='entity.entity')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_attendance_summaries', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['entity_id', 'payroll_period_id', 'contract_payroll_profile_id'],
                'indexes': [models.Index(fields=['entity', 'payroll_period'], name='ix_cattsum_ent_period'), models.Index(fields=['contract_payroll_profile', 'is_active'], name='ix_cattsum_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contract_payroll_profile', 'payroll_period'), name='uq_contract_attendance_summary_active_period'), models.CheckConstraint(condition=models.Q(('attendance_days__gte', Decimal('0.00'))), name='ck_contract_att_sum_att_gte_zero'), models.CheckConstraint(condition=models.Q(('payable_days__gte', Decimal('0.00'))), name='ck_contract_att_sum_payable_gte_zero'), models.CheckConstraint(condition=models.Q(('lop_days__gte', Decimal('0.00'))), name='ck_contract_att_sum_lop_gte_zero'), models.CheckConstraint(condition=models.Q(('overtime_hours__gte', Decimal('0.00'))), name='ck_contract_att_sum_ot_gte_zero')],
            },
        ),
    ]
