# Generated by Django 5.2.1 on 2026-05-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_contractattendanceadjustment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrunemployee',
            options={'ordering': ['contract_payroll_profile__hrms_contract__employee__employee_number', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='payrollrunemployee',
            name='uq_payroll_run_employee',
        ),
        migrations.AddField(
            model_name='payrollrunemployee',
            name='contract_payroll_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_rows', to='payroll.contractpayrollprofile'),
        ),
        migrations.AddField(
            model_name='payrollrunemployeecomponent',
            name='one_time_pay_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_components', to='payroll.onetimepayitem'),
        ),
        migrations.AlterField(
            model_name='payrollrunemployee',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_rows', to='payroll.payrollemployeeprofile'),
        ),
        migrations.AddIndex(
            model_name='payrollrunemployee',
            index=models.Index(fields=['contract_payroll_profile', 'status'], name='ix_prun_emp_contract'),
        ),
        migrations.AddConstraint(
            model_name='payrollrunemployee',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'contract_payroll_profile'), name='uq_payroll_run_contract_employee'),
        ),
    ]
