# Generated by Django 5.2.1 on 2026-05-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_payrollrunemployee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrunemployeecomponent',
            name='payroll_adjustment',
        ),
        migrations.DeleteModel(
            name='PayrollAdjustment',
        ),
    ]
