# Generated by Django 5.2.1 on 2026-05-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_remove_payrollrunemployeecomponent_payroll_adjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrunemployee',
            name='employee_profile',
        ),
        migrations.DeleteModel(
            name='PayrollEmployeeProfile',
        ),
    ]
