# Generated by Django 5.2.1 on 2026-05-17 15:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('hrms', '0001_initial'),
        ('payroll', '0014_payrollcomponent_semantic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FnFSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('settlement_number', models.CharField(blank=True, default='', max_length=50)),
                ('separation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('settlement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('earned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_recoverable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('calculation_payload', models.JSONField(blank=True, default=dict)),
                ('settlement_snapshot', models.JSONField(blank=True, default=dict)),
                ('approval_note', models.CharField(blank=True, default='', max_length=255)),
                ('post_reference', models.CharField(blank=True, default='', max_length=100)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('is_recalculation_unlocked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fnf_settlements', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_fnf_settlements', to=settings.AUTH_USER_MODEL)),
                ('contract_payroll_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='payroll.contractpayrollprofile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='entity.entity')),
                ('entityfinid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='entity.entityfinancialyear')),
                ('hrms_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='hrms.hremploymentcontract')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_fnf_settlements', to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='payroll.payrollperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_fnf_settlements', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='payroll.salarystructure')),
                ('salary_structure_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='payroll.salarystructureversion')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_settlements', to='entity.subentity')),
            ],
            options={
                'ordering': ['-settlement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FnFSettlementComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_type', models.CharField(choices=[('SALARY_LINE', 'Salary Line'), ('NOTICE_PAY_RECOVERY', 'Notice Pay Recovery'), ('NOTICE_PAY_PAYOUT', 'Notice Pay Payout'), ('LEAVE_ENCASHMENT', 'Leave Encashment'), ('GRATUITY_HOOK', 'Gratuity Hook'), ('BONUS_PAYOUT', 'Bonus Payout'), ('INCENTIVE_PAYOUT', 'Incentive Payout'), ('REIMBURSEMENT_PAYABLE', 'Reimbursement Payable'), ('LOAN_RECOVERY', 'Loan Recovery'), ('ADVANCE_RECOVERY', 'Advance Recovery'), ('ASSET_RECOVERY', 'Asset Recovery'), ('STATUTORY', 'Statutory'), ('TDS_HOOK', 'TDS Hook'), ('MANUAL', 'Manual')], max_length=30)),
                ('component_code', models.CharField(blank=True, default='', max_length=40)),
                ('component_name', models.CharField(blank=True, default='', max_length=120)),
                ('component_type', models.CharField(blank=True, default='', max_length=30)),
                ('posting_behavior', models.CharField(blank=True, default='', max_length=30)),
                ('sequence', models.PositiveIntegerField(default=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculation_trace', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_components', to='payroll.payrollcomponent')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.fnfsettlement')),
                ('source_structure_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fnf_components', to='payroll.salarystructureline')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fnfsettlement',
            index=models.Index(fields=['entity', 'status'], name='ix_fnf_entity_status'),
        ),
        migrations.AddIndex(
            model_name='fnfsettlement',
            index=models.Index(fields=['contract_payroll_profile', 'status'], name='ix_fnf_profile_status'),
        ),
        migrations.AddIndex(
            model_name='fnfsettlement',
            index=models.Index(fields=['settlement_date'], name='ix_fnf_settlement_date'),
        ),
        migrations.AddConstraint(
            model_name='fnfsettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'CALCULATED', 'APPROVED', 'POSTED'])), fields=('hrms_contract',), name='uq_fnf_active_contract'),
        ),
        migrations.AddConstraint(
            model_name='fnfsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('last_working_day__gte', models.F('separation_date'))), name='ck_fnf_last_working_day_gte_separation'),
        ),
        migrations.AddIndex(
            model_name='fnfsettlementcomponent',
            index=models.Index(fields=['settlement', 'sequence'], name='ix_fnf_comp_settle_seq'),
        ),
        migrations.AddIndex(
            model_name='fnfsettlementcomponent',
            index=models.Index(fields=['source_type'], name='ix_fnf_comp_source'),
        ),
    ]
