# Generated by Django 5.2.1 on 2026-05-18 05:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('payroll', '0016_advanced_tds_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPaymentBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('PAYROLL_RUN', 'Payroll Run'), ('FNF_SETTLEMENT', 'FnF Settlement')], default='PAYROLL_RUN', max_length=30)),
                ('batch_number', models.CharField(max_length=60)),
                ('batch_name', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('EXPORTED', 'Exported'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('export_format', models.CharField(choices=[('GENERIC_CSV', 'Generic CSV'), ('BANK_UPLOAD_PLACEHOLDER', 'Bank Upload Placeholder')], default='GENERIC_CSV', max_length=40)),
                ('allow_non_positive_amounts', models.BooleanField(default=False)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('payable_line_count', models.PositiveIntegerField(default=0)),
                ('skipped_line_count', models.PositiveIntegerField(default=0)),
                ('invalid_line_count', models.PositiveIntegerField(default=0)),
                ('warning_line_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('validation_summary_json', models.JSONField(blank=True, default=dict)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('export_reference', models.CharField(blank=True, default='', max_length=80)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payroll_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_payroll_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_batches', to='entity.entity')),
                ('entityfinid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_batches', to='entity.entityfinancialyear')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exported_payroll_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('failed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='failed_payroll_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('fnf_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='payroll.fnfsettlement')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_payroll_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='payroll.payrollrun')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_batches', to='entity.subentity')),
            ],
            options={
                'ordering': ['-created_at', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentBatchLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=100)),
                ('employee_code', models.CharField(blank=True, default='', max_length=40)),
                ('employee_name', models.CharField(blank=True, default='', max_length=120)),
                ('employee_user_id', models.IntegerField(blank=True, null=True)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=140)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('branch_name', models.CharField(blank=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('line_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('has_duplicate_account_warning', models.BooleanField(default=False)),
                ('validation_errors_json', models.JSONField(blank=True, default=list)),
                ('validation_warnings_json', models.JSONField(blank=True, default=list)),
                ('source_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollpaymentbatch')),
                ('contract_payroll_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batch_lines', to='payroll.contractpayrollprofile')),
                ('fnf_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batch_lines', to='payroll.fnfsettlement')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_batch_lines', to='financial.account')),
                ('payroll_run_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batch_lines', to='payroll.payrollrunemployee')),
            ],
            options={
                'ordering': ['sequence', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentFileExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('GENERIC_CSV', 'Generic CSV'), ('BANK_UPLOAD_PLACEHOLDER', 'Bank Upload Placeholder')], max_length=40)),
                ('file_name', models.CharField(max_length=160)),
                ('content_type', models.CharField(default='text/csv', max_length=80)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('file_content', models.TextField(blank=True, default='')),
                ('export_metadata_json', models.JSONField(blank=True, default=dict)),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='payroll.payrollpaymentbatch')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_file_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payment_status_logs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='payroll.payrollpaymentbatch')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollpaymentbatch',
            index=models.Index(fields=['entity', 'status'], name='ix_pay_payment_batch_status'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentbatch',
            index=models.Index(fields=['entity', 'source_type'], name='ix_pay_payment_batch_source'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentbatch',
            index=models.Index(fields=['payroll_run', 'status'], name='ix_pay_payment_batch_run'),
        ),
        migrations.AddConstraint(
            model_name='payrollpaymentbatch',
            constraint=models.UniqueConstraint(fields=('entity', 'batch_number'), name='uq_payroll_payment_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='payrollpaymentbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll_run__isnull', False), ('status__in', ['DRAFT', 'VALIDATED', 'APPROVED', 'EXPORTED'])), fields=('payroll_run',), name='uq_payroll_payment_batch_active_run'),
        ),
        migrations.AddConstraint(
            model_name='payrollpaymentbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('fnf_settlement__isnull', False), ('status__in', ['DRAFT', 'VALIDATED', 'APPROVED', 'EXPORTED'])), fields=('fnf_settlement',), name='uq_payroll_payment_batch_active_fnf'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentbatchline',
            index=models.Index(fields=['batch', 'line_status'], name='ix_pay_payment_line_status'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentbatchline',
            index=models.Index(fields=['batch', 'sequence'], name='ix_pay_payment_line_seq'),
        ),
        migrations.AddConstraint(
            model_name='payrollpaymentbatchline',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll_run_employee__isnull', False)), fields=('batch', 'payroll_run_employee'), name='uq_payroll_payment_batch_line_run_employee'),
        ),
        migrations.AddConstraint(
            model_name='payrollpaymentbatchline',
            constraint=models.UniqueConstraint(condition=models.Q(('fnf_settlement__isnull', False)), fields=('batch', 'fnf_settlement'), name='uq_payroll_payment_batch_line_fnf'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentfileexport',
            index=models.Index(fields=['batch', 'exported_at'], name='ix_pay_payment_exported'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentstatuslog',
            index=models.Index(fields=['batch', 'created_at'], name='ix_pay_payment_log_batch'),
        ),
    ]
