# Generated by Django 5.2.1 on 2026-09-16 13:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('purchase', '0054_vendoradvancebalance_ix_pur_adv_hist_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryPaymentBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('VENDOR_PAYABLES', 'Vendor Payables'), ('PAYROLL', 'Payroll'), ('TAX', 'Tax'), ('MISC', 'Miscellaneous')], default='VENDOR_PAYABLES', max_length=30)),
                ('batch_number', models.CharField(max_length=70)),
                ('batch_name', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('EXPORTED', 'Exported'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('export_format', models.CharField(choices=[('GENERIC_CSV', 'Generic CSV'), ('BANK_UPLOAD_PLACEHOLDER', 'Bank Upload Placeholder')], default='GENERIC_CSV', max_length=40)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('payable_line_count', models.PositiveIntegerField(default=0)),
                ('invalid_line_count', models.PositiveIntegerField(default=0)),
                ('warning_line_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('validation_summary_json', models.JSONField(blank=True, default=dict)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('export_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_treasury_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_treasury_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_batches', to='entity.entity')),
                ('entityfinid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_batches', to='entity.entityfinancialyear')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exported_treasury_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('failed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='failed_treasury_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_treasury_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_treasury_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_batches', to='entity.subentity')),
            ],
            options={
                'ordering': ['-created_at', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryPaymentBatchLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=100)),
                ('party_name', models.CharField(blank=True, default='', max_length=200)),
                ('party_code', models.CharField(blank=True, default='', max_length=40)),
                ('source_doc_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_doc_number', models.CharField(blank=True, default='', max_length=80)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=160)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('branch_name', models.CharField(blank=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('line_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('has_duplicate_account_warning', models.BooleanField(default=False)),
                ('validation_errors_json', models.JSONField(blank=True, default=list)),
                ('validation_warnings_json', models.JSONField(blank=True, default=list)),
                ('source_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='treasury.treasurypaymentbatch')),
                ('party_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_batch_lines', to='financial.account')),
                ('vendor_open_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_batch_lines', to='purchase.vendorbillopenitem')),
            ],
            options={
                'ordering': ['sequence', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryPaymentFileExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('GENERIC_CSV', 'Generic CSV'), ('BANK_UPLOAD_PLACEHOLDER', 'Bank Upload Placeholder')], max_length=40)),
                ('file_name', models.CharField(max_length=180)),
                ('content_type', models.CharField(default='text/csv', max_length=80)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('file_content', models.TextField(blank=True, default='')),
                ('export_metadata_json', models.JSONField(blank=True, default=dict)),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='treasury.treasurypaymentbatch')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_file_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryPaymentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_payment_status_logs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='treasury.treasurypaymentbatch')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='treasurypaymentbatch',
            index=models.Index(fields=['entity', 'status'], name='ix_treas_batch_status'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentbatch',
            index=models.Index(fields=['entity', 'source_type'], name='ix_treas_batch_source'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentbatch',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_treas_batch_scope'),
        ),
        migrations.AddConstraint(
            model_name='treasurypaymentbatch',
            constraint=models.UniqueConstraint(fields=('entity', 'batch_number'), name='uq_treasury_payment_batch_number'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentbatchline',
            index=models.Index(fields=['batch', 'line_status'], name='ix_treas_line_status'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentbatchline',
            index=models.Index(fields=['vendor_open_item', 'line_status'], name='ix_treas_line_vendor_item'),
        ),
        migrations.AddConstraint(
            model_name='treasurypaymentbatchline',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_open_item__isnull', False)), fields=('batch', 'vendor_open_item'), name='uq_treas_batch_line_vendor_item'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentfileexport',
            index=models.Index(fields=['batch', 'exported_at'], name='ix_treas_exported'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentstatuslog',
            index=models.Index(fields=['batch', 'created_at'], name='ix_treas_log_batch'),
        ),
    ]
