# Generated by Django 5.2.1 on 2026-09-16 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('treasury', '0003_treasurypaymentinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryChequeBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_number', models.CharField(max_length=60)),
                ('start_leaf', models.CharField(max_length=30)),
                ('end_leaf', models.CharField(max_length=30)),
                ('total_leaves', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cheque_books', to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cheque_books', to='entity.entity')),
                ('entityfinid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cheque_books', to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cheque_books', to='entity.subentity')),
            ],
            options={
                'ordering': ['bank_account_id', 'book_number', 'start_leaf'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryChequeLeaf',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaf_no', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled'), ('STALE', 'Stale'), ('REISSUED', 'Reissued')], default='AVAILABLE', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cheque_leaves', to='financial.account')),
                ('cheque_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='treasury.treasurychequebook')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cheque_leaves', to='entity.entity')),
            ],
            options={
                'ordering': ['bank_account_id', 'leaf_no'],
            },
        ),
        migrations.AddField(
            model_name='treasurypaymentinstrument',
            name='cheque_leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_instruments', to='treasury.treasurychequeleaf'),
        ),
        migrations.AddIndex(
            model_name='treasurychequebook',
            index=models.Index(fields=['entity', 'bank_account', 'status'], name='ix_treas_chq_book_bank_status'),
        ),
        migrations.AddIndex(
            model_name='treasurychequebook',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_treas_chq_book_scope'),
        ),
        migrations.AddConstraint(
            model_name='treasurychequebook',
            constraint=models.UniqueConstraint(fields=('entity', 'bank_account', 'book_number'), name='uq_treas_cheque_book_bank_book'),
        ),
        migrations.AddIndex(
            model_name='treasurychequeleaf',
            index=models.Index(fields=['entity', 'bank_account', 'status'], name='ix_treas_chq_leaf_bank_status'),
        ),
        migrations.AddIndex(
            model_name='treasurychequeleaf',
            index=models.Index(fields=['leaf_no'], name='ix_treas_chq_leaf_no'),
        ),
        migrations.AddConstraint(
            model_name='treasurychequeleaf',
            constraint=models.UniqueConstraint(fields=('entity', 'bank_account', 'leaf_no'), name='uq_treas_cheque_leaf_bank_no'),
        ),
    ]
