# Generated by Django 5.2.1 on 2026-09-16 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reco', '0005_bankreconciliationauditlog_ix_bank_reco_audit_run_dt'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('payments', '0015_paymentvoucherheader_ix_pay_ref_warn_scope'),
        ('treasury', '0004_cheque_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurypaymentinstrument',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurypaymentinstrument',
            name='reconciled_bank_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_payment_instruments', to='bank_reco.bankstatementline'),
        ),
        migrations.AddField(
            model_name='treasurypaymentinstrument',
            name='reconciliation_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_payment_instruments', to='bank_reco.bankreconciliationmatch'),
        ),
        migrations.AddIndex(
            model_name='treasurypaymentinstrument',
            index=models.Index(fields=['reconciliation_match'], name='ix_treas_instr_reco_match'),
        ),
    ]
