# Generated by Django 5.2.1 on 2026-09-16 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0036_allow_shared_subentity_gstin_per_entity'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('payments', '0015_paymentvoucherheader_ix_pay_ref_warn_scope'),
        ('treasury', '0005_instrument_reconciliation_link'),
        ('vouchers', '0007_voucherattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryCashMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.CharField(max_length=70)),
                ('movement_type', models.CharField(choices=[('CASH_DEPOSIT', 'Cash Deposit'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('BANK_TO_BANK', 'Bank To Bank'), ('CASH_TO_BANK', 'Cash To Bank'), ('BANK_TO_CASH', 'Bank To Cash')], max_length=30)),
                ('movement_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference_no', models.CharField(blank=True, default='', max_length=120)),
                ('instrument_no', models.CharField(blank=True, default='', max_length=50)),
                ('instrument_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_treasury_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements_destination', to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements', to='entity.entityfinancialyear')),
                ('payment_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements', to='payments.paymentmode')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_treasury_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements_source', to='financial.account')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements', to='entity.subentity')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_movements', to='vouchers.voucherheader')),
            ],
            options={
                'ordering': ['-movement_date', '-created_at', 'movement_number'],
                'indexes': [models.Index(fields=['entity', 'entityfinid', 'subentity', 'movement_date'], name='ix_treas_cash_scope_dt'), models.Index(fields=['entity', 'status', 'movement_date'], name='ix_treas_cash_status_dt'), models.Index(fields=['source_account', 'movement_date'], name='ix_treas_cash_src_dt'), models.Index(fields=['destination_account', 'movement_date'], name='ix_treas_cash_dst_dt'), models.Index(fields=['voucher'], name='ix_treas_cash_voucher')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'movement_number'), name='uq_treas_cash_move_number'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_treas_cash_move_amt_pos'), models.CheckConstraint(condition=models.Q(('source_account', models.F('destination_account')), _negated=True), name='ck_treas_cash_move_accounts_diff')],
            },
        ),
    ]
