# Generated by Django 5.2.1 on 2026-03-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_menu_sort_order_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'rbac_menu_sort_order_check'
            ) THEN
                ALTER TABLE rbac_menu
                ADD CONSTRAINT rbac_menu_sort_order_check
                CHECK (sort_order >= 0);
            END IF;
        END
        $$;
        """
    )


def drop_menu_sort_order_constraint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        ALTER TABLE IF EXISTS rbac_menu
        DROP CONSTRAINT IF EXISTS rbac_menu_sort_order_check;
        """
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100)),
                ('policy_type', models.CharField(choices=[('branch', 'Branch'), ('department', 'Department'), ('warehouse', 'Warehouse'), ('financial_year', 'Financial Year'), ('custom', 'Custom')], max_length=30)),
                ('scope_mode', models.CharField(choices=[('allow_all', 'Allow All'), ('include', 'Include'), ('exclude', 'Exclude'), ('custom', 'Custom')], default='allow_all', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_system_defined', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_access_policies', to='entity.entity')),
            ],
            options={
                'ordering': ('policy_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('menu_type', models.CharField(choices=[('group', 'Group'), ('screen', 'Screen'), ('external', 'External'), ('action', 'Action')], default='screen', max_length=20)),
                ('route_path', models.CharField(blank=True, max_length=255)),
                ('route_name', models.CharField(blank=True, max_length=150)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('is_system_menu', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.menu')),
            ],
            options={
                'ordering': ('parent_id', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scope_type', models.CharField(choices=[('platform', 'Platform'), ('entity', 'Entity'), ('subentity', 'Sub Entity'), ('custom', 'Custom')], default='entity', max_length=20)),
                ('is_system_defined', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('module', 'resource', 'action', 'code'),
                'indexes': [models.Index(fields=['module', 'resource', 'action'], name='rbac_permis_module_aa18ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('relation_type', models.CharField(choices=[('visibility', 'Visibility'), ('action', 'Action')], default='visibility', max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='rbac.menu')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='rbac.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('role_level', models.CharField(choices=[('platform', 'Platform'), ('entity', 'Entity')], default='entity', max_length=20)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_assignable', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_roles_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to='entity.entity')),
            ],
            options={
                'ordering': ('role_level', 'priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RoleDataAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='rbac.dataaccesspolicy')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_policies', to='rbac.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
            ],
            options={
                'ordering': ('role', 'permission__code'),
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('scope_data', models.JSONField(blank=True, default=dict)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='entity.entity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.role')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbac_role_assignments', to='entity.subentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('entity', 'user', 'role'),
            },
        ),
        migrations.AddConstraint(
            model_name='dataaccesspolicy',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='rbac_policy_entity_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='dataaccesspolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('entity__isnull', True)), fields=('code',), name='rbac_policy_global_code_unique'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['parent', 'sort_order'], name='rbac_menu_parent__fc6f5b_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_menu_sort_order_constraint, drop_menu_sort_order_constraint),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='menu',
                    constraint=models.CheckConstraint(check=models.Q(('sort_order__gte', 0)), name='rbac_menu_sort_order_check'),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='menupermission',
            constraint=models.UniqueConstraint(fields=('menu', 'permission', 'relation_type'), name='rbac_menu_permission_unique'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['entity', 'isactive'], name='rbac_role_entity__8833cd_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_level', 'code'], name='rbac_role_role_le_174d03_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='rbac_role_entity_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('entity__isnull', True)), fields=('code',), name='rbac_role_global_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='roledataaccesspolicy',
            constraint=models.UniqueConstraint(fields=('role', 'policy'), name='rbac_role_data_policy_unique'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='rbac_role_permission_unique'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'entity', 'isactive'], name='rbac_userro_user_id_94c063_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['entity', 'role', 'isactive'], name='rbac_userro_entity__05d361_idx'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'entity', 'role', 'subentity'), name='rbac_user_entity_role_subentity_unique'),
        ),
    ]
