# Generated by Django 5.2.1 on 2026-03-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('rbac', '0006_drop_legacy_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('deactivate', 'Deactivate'), ('delete', 'Delete'), ('assign', 'Assign'), ('unassign', 'Unassign'), ('clone', 'Clone'), ('apply_template', 'Apply Template')], max_length=30)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to='entity.entity')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity', 'object_type'], name='rbac_rbacau_entity__49a180_idx'), models.Index(fields=['object_type', 'object_id'], name='rbac_rbacau_object__6d1530_idx'), models.Index(fields=['action', 'created_at'], name='rbac_rbacau_action_c7599e_idx')],
            },
        ),
    ]
