# Generated by Django 5.2.1 on 2026-06-19 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0034_entity_lookup_runtime_indexes'),
        ('rbac', '0128_add_asset_dashboard_menu_live'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rbacauditlog',
            index=models.Index(fields=['entity', 'created_at'], name='ix_rbac_audit_entity_dt'),
        ),
    ]
