# Generated by Django 4.2.28 on 2026-03-18 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customersubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='planlimit',
            options={'ordering': ['plan_id', 'key']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'price_amount', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='userentityaccess',
            options={'ordering': ['customer_account_id', 'user_id', 'role']},
        ),
        migrations.RemoveConstraint(
            model_name='planlimit',
            name='subscriptions_plan_limit_unique',
        ),
        migrations.RemoveConstraint(
            model_name='userentityaccess',
            name='subscriptions_user_entity_access_unique',
        ),
        migrations.RenameField(
            model_name='customeraccount',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customersubscription',
            old_name='ends_at',
            new_name='canceled_at',
        ),
        migrations.RenameField(
            model_name='customersubscription',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='planlimit',
            old_name='code',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userentityaccess',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='primary_user',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='planlimit',
            name='isactive',
        ),
        migrations.RemoveField(
            model_name='planlimit',
            name='value',
        ),
        migrations.RemoveField(
            model_name='userentityaccess',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='userentityaccess',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='userentityaccess',
            name='source',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='business', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='billing_provider',
            field=models.CharField(blank=True, help_text='Billing provider slug, e.g. stripe.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='external_customer_id',
            field=models.CharField(blank=True, help_text='External billing customer ID, e.g. Stripe customer ID.', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_customer_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='auto_renew',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='billing_provider',
            field=models.CharField(blank=True, help_text='Billing provider slug, e.g. stripe.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='external_subscription_id',
            field=models.CharField(blank=True, help_text='External billing subscription ID, e.g. Stripe subscription ID.', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='seats_purchased',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='started_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='int_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='limit_type',
            field=models.CharField(blank=True, choices=[('integer', 'Integer'), ('boolean', 'Boolean'), ('text', 'Text')], default='integer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='planlimit',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime'), ('custom', 'Custom')], default='monthly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_provider',
            field=models.CharField(blank=True, help_text='Billing provider slug, e.g. stripe.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='external_price_id',
            field=models.CharField(blank=True, help_text='External billing price ID, e.g. Stripe price ID.', max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userentityaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userentityaccess',
            name='granted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userentityaccess',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member'), ('viewer', 'Viewer'), ('billing', 'Billing')], default='member', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.customeraccount'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='status',
            field=models.CharField(blank=True, choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planlimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='userentityaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userentityaccess',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='subscriptions.customeraccount'),
        ),
        migrations.AlterField(
            model_name='userentityaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_customer_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userentityaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['slug'], name='customer_ac_slug_f2e020_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['status'], name='customer_ac_status_e67243_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['owner'], name='customer_ac_owner_i_714d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['customer_account', 'status'], name='customer_su_custome_67469a_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['plan'], name='customer_su_plan_id_ade5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['external_subscription_id'], name='customer_su_externa_b32b57_idx'),
        ),
        migrations.AddIndex(
            model_name='planlimit',
            index=models.Index(fields=['plan', 'key'], name='plan_limits_plan_id_b88a74_idx'),
        ),
        migrations.AddIndex(
            model_name='planlimit',
            index=models.Index(fields=['key'], name='plan_limits_key_6dee57_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['code'], name='subscriptio_code_e250fc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['tier'], name='subscriptio_tier_1ce992_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_public'], name='subscriptio_is_publ_b5ebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_default'], name='subscriptio_is_defa_29b486_idx'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['user', 'customer_account'], name='user_entity_user_id_de5f59_idx'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['customer_account', 'role'], name='user_entity_custome_d8ec58_idx'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['expires_at'], name='user_entity_expires_c002aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('is_active', True), ('status__in', ['trialing', 'active', 'past_due', 'paused'])), fields=('customer_account',), name='uq_one_current_subscription_per_account'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan', 'key'), name='uq_plan_limit_plan_key'),
        ),
        migrations.AddConstraint(
            model_name='userentityaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'customer_account'), name='uq_active_account_membership_per_user'),
        ),
        migrations.AlterModelTable(
            name='customeraccount',
            table='customer_accounts',
        ),
        migrations.AlterModelTable(
            name='customersubscription',
            table='customer_subscriptions',
        ),
        migrations.AlterModelTable(
            name='planlimit',
            table='plan_limits',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscription_plans',
        ),
        migrations.AlterModelTable(
            name='userentityaccess',
            table='user_entity_access',
        ),
    ]
