# Generated by Django 5.2.1 on 2026-06-19 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_customeraccount_tenant_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['customer_account', 'is_active', 'ended_at', 'status', 'started_at'], name='ix_sub_acct_active_cur'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['user', 'customer_account', 'is_active', 'expires_at'], name='ix_user_acc_active_usr'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['customer_account', 'is_active', 'expires_at'], name='ix_user_acc_active_acc'),
        ),
    ]
