# Generated by Django 5.2.1 on 2026-07-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_customersubscription_ix_sub_acct_active_cur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_selectable_for_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_selectable_for_signup'], name='subscriptio_is_sele_25f4ff_idx'),
        ),
    ]
