# Generated by Django 4.2.28 on 2026-02-27 06:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HsnSac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_service', models.BooleanField(default=False)),
                ('default_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_cess', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_exempt', models.BooleanField(default=False)),
                ('is_nil_rated', models.BooleanField(default=False)),
                ('is_non_gst', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('isdefault', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('productname', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('productdesc', models.CharField(blank=True, max_length=500)),
                ('is_pieces', models.BooleanField(default=True, help_text='If true, quantity is treated as pieces (integer). Otherwise, allows decimals.')),
                ('is_service', models.BooleanField(default=False)),
                ('is_batch_managed', models.BooleanField(default=False)),
                ('is_serialized', models.BooleanField(default=False)),
                ('is_ecomm_9_5_service', models.BooleanField(default=False)),
                ('default_is_rcm', models.BooleanField(default=False, help_text='Default reverse charge applicability for this product/service (optional helper).')),
                ('is_itc_eligible', models.BooleanField(default=True, help_text='Whether ITC is generally eligible for this product/service (optional helper).')),
                ('itc_block_reason', models.CharField(blank=True, max_length=500)),
                ('product_status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('blocked', 'Blocked'), ('upcoming', 'Upcoming')], default='active', max_length=20)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('discontinue_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('char', 'Text'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean')], max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('uqc', models.CharField(blank=True, help_text='NIC UQC code for e-invoice/e-waybill (e.g., KGS, NOS, MTR).', max_length=10, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductUomConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_conversions', to='catalog.unitofmeasure')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='catalog.product')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_conversions', to='catalog.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Base purchase rate', max_digits=18, null=True)),
                ('purchase_rate_less_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Discount % on purchase rate', max_digits=5, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('mrp_less_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Discount % on MRP', max_digits=5, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['product', 'pricelist', 'uom', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ProductPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reorder_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('abc_class', models.CharField(blank=True, max_length=1)),
                ('fsn_class', models.CharField(blank=True, max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGstRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('gst_type', models.CharField(choices=[('regular', 'Regular'), ('exempt', 'Exempt'), ('nil_rated', 'Nil Rated'), ('non_gst', 'Non-GST'), ('composition', 'Composition')], default='regular', max_length=20)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, help_text='Computed total GST rate (CGST+SGST).', max_digits=6)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess_type', models.CharField(choices=[('none', 'None'), ('ad_valorem', 'Ad valorem'), ('specific', 'Specific'), ('composite', 'Composite')], default='none', help_text='Type of CESS (if any).', max_length=20)),
                ('cess_specific_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Specific CESS amount per unit (used when cess_type is specific or composite).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('isdefault', models.BooleanField(default=False)),
                ('hsn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_gst_rates', to='catalog.hsnsac')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_rates', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('pcategoryname', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity')),
                ('maincategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['pcategoryname'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('isprimary', models.BooleanField(default=False)),
                ('pack_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('barcode_image', models.ImageField(blank=True, help_text='Auto-generated barcode image', null=True, upload_to='barcodes/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_details', to='catalog.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_uoms', to='catalog.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('value_char', models.CharField(blank=True, max_length=255)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='catalog.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productsCategory', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_%(class)s_set', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='product',
            name='productcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productsCategory', to='catalog.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='If null, use entity default purchase account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_account',
            field=models.ForeignKey(blank=True, help_text='If null, use entity default sales account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account'),
        ),
        migrations.CreateModel(
            name='OpeningStockByLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
                ('openingqty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('openingrate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('openingvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_opening_stocks', to='entity.entity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stocks', to='entity.subentity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_stocks', to='catalog.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='uq_uom_entity_code'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(condition=models.Q(('uqc__isnull', False), models.Q(('uqc', ''), _negated=True)), fields=('entity', 'uqc'), name='uq_uom_entity_uqc'),
        ),
        migrations.AddConstraint(
            model_name='productuomconversion',
            constraint=models.UniqueConstraint(fields=('product', 'from_uom', 'to_uom'), name='uq_product_uomconversion'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', '-effective_from', '-id'], name='ix_price_prod_eff'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'pricelist', 'uom', 'effective_from'), name='uq_productprice_key'),
        ),
        migrations.AddConstraint(
            model_name='productplanning',
            constraint=models.UniqueConstraint(fields=('product',), name='uq_productplanning_product'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uq_product_one_primary_image'),
        ),
        migrations.AddIndex(
            model_name='productgstrate',
            index=models.Index(fields=['product', '-isdefault', '-valid_from', '-id'], name='ix_gst_best_row'),
        ),
        migrations.AddIndex(
            model_name='productgstrate',
            index=models.Index(fields=['product', 'isdefault'], name='ix_gst_prod_default'),
        ),
        migrations.AddIndex(
            model_name='productgstrate',
            index=models.Index(fields=['product', 'valid_from'], name='ix_gst_prod_validfrom'),
        ),
        migrations.AddConstraint(
            model_name='productgstrate',
            constraint=models.UniqueConstraint(fields=('product', 'hsn', 'valid_from'), name='uq_product_hsn_validfrom'),
        ),
        migrations.AddConstraint(
            model_name='productgstrate',
            constraint=models.UniqueConstraint(condition=models.Q(('isdefault', True)), fields=('product',), name='uq_product_one_default_gst_rate'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('entity', 'pcategoryname'), name='uq_productcategory_entity_name'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'barcode'), name='uq_product_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'uom', 'pack_size'), name='uq_product_uom_packsize'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(condition=models.Q(('isprimary', True)), fields=('product',), name='uq_product_one_primary_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='uq_product_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='uq_productattribute_entity_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('entity', 'sku'), name='uq_product_entity_sku'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='uq_pricelist_entity_name'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('isdefault', True)), fields=('entity',), name='uq_pricelist_one_default_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='openingstockbylocation',
            constraint=models.UniqueConstraint(fields=('entity', 'product', 'location', 'as_of_date'), name='uq_openingstock_entity_product_location_date'),
        ),
        migrations.AddConstraint(
            model_name='hsnsac',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='uq_hsnsac_entity_code'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='uq_brand_entity_name'),
        ),
    ]
