# Generated by Django 4.2.28 on 2026-03-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productbulkjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productbulkjob',
            new_name='catalog_pro_entity__dc0560_idx',
            old_name='catalog_pro_entity__73af6c_idx',
        ),
        migrations.RenameIndex(
            model_name='productbulkjob',
            new_name='catalog_pro_entity__53ef2c_idx',
            old_name='catalog_pro_entity__db9f7a_idx',
        ),
        migrations.RemoveField(
            model_name='productbulkjob',
            name='isactive',
        ),
    ]
