# Generated by Django 5.2.1 on 2026-04-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_catalog_pro_entity__73af6c_idx_catalog_pro_entity__dc0560_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_warning_days',
            field=models.PositiveIntegerField(default=30, help_text='Warn when remaining shelf life reaches this many days.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_expiry_tracked',
            field=models.BooleanField(default=False, help_text='Mark items that need expiry tracking in future stock and batch reports.'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_classification',
            field=models.CharField(choices=[('trading_item', 'Trading Item'), ('raw_material', 'Raw Material'), ('wip', 'Work In Progress'), ('finished_good', 'Finished Good'), ('consumable', 'Consumable'), ('service_item', 'Service Item'), ('asset_spare', 'Asset Spare'), ('other', 'Other')], db_index=True, default='trading_item', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected shelf life in days for expiry-sensitive items.', null=True),
        ),
    ]
