# Generated by Django 5.2.1 on 2026-04-23 12:37

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productbarcode_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode_image',
            field=models.ImageField(blank=True, help_text='Auto-generated barcode image', null=True, upload_to=catalog.models.product_barcode_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_upload_to),
        ),
    ]
