# Generated by Django 5.2.1 on 2026-05-09 11:34

from django.db import migrations, models


def backfill_service_product_purchase_behavior(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(is_service=True).update(purchase_behavior="expense")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productbarcode_barcode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_behavior',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('expense', 'Expense'), ('asset', 'Asset')], db_index=True, default='inventory', help_text='Controls how purchase lines for this product should flow: inventory, expense, or asset.', max_length=20),
        ),
        migrations.RunPython(backfill_service_product_purchase_behavior, migrations.RunPython.noop),
    ]
