# Generated by Django 5.2.1 on 2026-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetcategory_ix_asset_cat_ent_act_nm_and_more'),
        ('catalog', '0011_opening_stock_branch_godown_and_planning_rules'),
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('financial', '0020_financial_master_runtime_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='barcodelabeltemplate',
            index=models.Index(fields=['entity', 'subentity', '-isdefault', 'name'], name='ix_cat_lbl_scope'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['entity', 'isactive', 'name'], name='ix_cat_brand_lookup'),
        ),
        migrations.AddIndex(
            model_name='hsnsac',
            index=models.Index(fields=['entity', 'isactive', 'code'], name='ix_cat_hsn_lookup'),
        ),
        migrations.AddIndex(
            model_name='openingstockbylocation',
            index=models.Index(fields=['product', '-as_of_date', 'id'], name='ix_cat_open_prod'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['entity', 'isactive', 'name'], name='ix_cat_prlist_lkp'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['entity', 'isactive', 'productname', 'id'], name='ix_cat_prod_list'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['entity', 'isactive', 'name'], name='ix_cat_attr_lookup'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['product', '-isprimary', 'id'], name='ix_cat_barcode_prod'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['entity', 'isactive', 'pcategoryname'], name='ix_cat_pcat_lookup'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', '-is_primary', 'id'], name='ix_cat_img_prod'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['entity', 'isactive', 'code'], name='ix_cat_uom_lookup'),
        ),
    ]
