# Generated by Django 5.2.1 on 2026-06-24 09:12

from django.db import migrations, models


def backfill_product_default_taxability(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductGstRate = apps.get_model("catalog", "ProductGstRate")

    product_ids = list(Product.objects.values_list("id", flat=True))
    for product_id in product_ids:
        gst_row = (
            ProductGstRate.objects.select_related("hsn")
            .filter(product_id=product_id)
            .order_by("-isdefault", "-valid_from", "-id")
            .first()
        )
        hsn = getattr(gst_row, "hsn", None)
        taxability = 1
        if hsn is not None:
            if getattr(hsn, "is_exempt", False):
                taxability = 2
            elif getattr(hsn, "is_nil_rated", False):
                taxability = 3
            elif getattr(hsn, "is_non_gst", False):
                taxability = 4
        Product.objects.filter(id=product_id).update(default_taxability=taxability)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_barcodelabeltemplate_ix_cat_lbl_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_taxability',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Taxable'), (2, 'Exempt'), (3, 'Nil-rated'), (4, 'Non-GST')], default=1, help_text='Default line-level taxability for purchase and sales invoices. Users can override it per invoice line.'),
        ),
        migrations.RunPython(backfill_product_default_taxability, migrations.RunPython.noop),
    ]
