# Generated by Django 4.2.28 on 2026-02-27 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_code', models.CharField(max_length=20)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('starting_number', models.PositiveIntegerField(default=1)),
                ('current_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveSmallIntegerField(default=0)),
                ('include_year', models.BooleanField(default=False)),
                ('include_month', models.BooleanField(default=False)),
                ('separator', models.CharField(default='-', max_length=5)),
                ('reset_frequency', models.CharField(choices=[('none', 'Do not reset'), ('monthly', 'Reset every month'), ('yearly', 'Reset every year')], default='none', max_length=10)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('custom_format', models.CharField(blank=True, default='', help_text='Placeholders: {prefix},{year},{month},{number},{suffix},{doc_code}', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_key', models.CharField(blank=True, max_length=50, null=True)),
                ('default_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'doc_key'], name='ix_doc_type_module_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('module', 'doc_key'), name='uq_doc_type_module_key'),
        ),
        migrations.AddField(
            model_name='documentnumberseries',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentnumberseries',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='numbering.documenttype'),
        ),
        migrations.AddField(
            model_name='documentnumberseries',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='documentnumberseries',
            name='entityfinid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear'),
        ),
        migrations.AddField(
            model_name='documentnumberseries',
            name='subentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity'),
        ),
        migrations.AddIndex(
            model_name='documentnumberseries',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_doc_series_scope'),
        ),
        migrations.AddIndex(
            model_name='documentnumberseries',
            index=models.Index(fields=['doc_type', 'doc_code'], name='ix_doc_series_type_code'),
        ),
        migrations.AddConstraint(
            model_name='documentnumberseries',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfinid', 'subentity', 'doc_type', 'doc_code'), name='uq_doc_series_scope_type_code'),
        ),
        migrations.AddConstraint(
            model_name='documentnumberseries',
            constraint=models.CheckConstraint(check=models.Q(('starting_number__gte', 1)), name='ck_doc_series_start_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='documentnumberseries',
            constraint=models.CheckConstraint(check=models.Q(('current_number__gte', 1)), name='ck_doc_series_current_gte_1'),
        ),
    ]
