# Generated by Django 5.2.1 on 2026-06-19 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0035_approvalrequest_ix_appr_req_entity_flow_and_more'),
        ('numbering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentnumberseries',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'doc_type', 'doc_code', 'is_active'], name='ix_doc_series_lookup'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['module', 'default_code', 'is_active'], name='ix_doc_type_mod_code_act'),
        ),
    ]
