from django.urls import path

from gst_reconciliation.views import (
    GstGstr2bExcelImportAPIView,
    GstGstr2bJsonImportAPIView,
    GstBulkAcceptMismatchAPIView,
    GstBulkAssignAPIView,
    GstBulkIgnoreAPIView,
    GstBulkMarkReviewedAPIView,
    GstBulkReopenAPIView,
    GstBulkUnmatchAPIView,
    GstLegacyRunBulkItemActionAPIView,
    GstImportedReturnDetailAPIView,
    GstImportedReturnListAPIView,
    GstImportedReturnRowListAPIView,
    GstReconciliationItemDetailAPIView,
    GstReconciliationItemGridAPIView,
    GstReconciliationItemAcceptMismatchAPIView,
    GstReconciliationItemAssignAPIView,
    GstReconciliationItemIgnoreAPIView,
    GstReconciliationItemManualMatchAPIView,
    GstReconciliationItemNotesAPIView,
    GstReconciliationItemReopenAPIView,
    GstReconciliationItemUnmatchAPIView,
    GstReconciliationRunApproveAPIView,
    GstReconciliationRunCloseAPIView,
    GstReconciliationRunDetailAPIView,
    GstReconciliationRunItemListAPIView,
    GstReconciliationRunListCreateAPIView,
    GstReconciliationRunMatchAPIView,
    GstReconciliationRunRejectAPIView,
    GstReconciliationRunReviewStartAPIView,
    GstReconciliationRunSummaryListAPIView,
    GstReconciliationRunSummaryAPIView,
    GstReconciliationRunSupplierAnalyticsAPIView,
    GstReconciliationRunSubmitAPIView,
    GstReconciliationReviewerQueueAPIView,
    GstSourceDocumentDetailAPIView,
    GstSourceDocumentSearchAPIView,
    PurchaseGstr2bBatchCreateRunAPIView,
)

app_name = "gst_reconciliation_api"

urlpatterns = [
    path("runs/", GstReconciliationRunListCreateAPIView.as_view(), name="run-list-create"),
    path("runs/summary-list/", GstReconciliationRunSummaryListAPIView.as_view(), name="run-summary-list"),
    path("runs/<int:pk>/", GstReconciliationRunDetailAPIView.as_view(), name="run-detail"),
    path("runs/<int:pk>/items/", GstReconciliationRunItemListAPIView.as_view(), name="run-items"),
    path("runs/<int:pk>/items/bulk-action/", GstLegacyRunBulkItemActionAPIView.as_view(), name="run-items-bulk-action-legacy"),
    path("runs/<int:pk>/summary/", GstReconciliationRunSummaryAPIView.as_view(), name="run-summary"),
    path("runs/<int:pk>/dashboard/", GstReconciliationRunSummaryAPIView.as_view(), name="run-dashboard"),
    path("runs/<int:pk>/supplier-analytics/", GstReconciliationRunSupplierAnalyticsAPIView.as_view(), name="run-supplier-analytics"),
    path("runs/<int:pk>/submit/", GstReconciliationRunSubmitAPIView.as_view(), name="run-submit"),
    path("runs/<int:pk>/review/start/", GstReconciliationRunReviewStartAPIView.as_view(), name="run-review-start"),
    path("runs/<int:pk>/approve/", GstReconciliationRunApproveAPIView.as_view(), name="run-approve"),
    path("runs/<int:pk>/reject/", GstReconciliationRunRejectAPIView.as_view(), name="run-reject"),
    path("runs/<int:pk>/close/", GstReconciliationRunCloseAPIView.as_view(), name="run-close"),
    path("runs/<int:pk>/match/", GstReconciliationRunMatchAPIView.as_view(), name="run-match"),
    path("imported-returns/", GstImportedReturnListAPIView.as_view(), name="imported-return-list"),
    path("imported-returns/<int:pk>/", GstImportedReturnDetailAPIView.as_view(), name="imported-return-detail"),
    path("imported-returns/<int:pk>/rows/", GstImportedReturnRowListAPIView.as_view(), name="imported-return-rows"),
    path("imported-returns/gstr2b/import-json/", GstGstr2bJsonImportAPIView.as_view(), name="gstr2b-import-json"),
    path("imported-returns/gstr2b/import-excel/", GstGstr2bExcelImportAPIView.as_view(), name="gstr2b-import-excel"),
    path("items/", GstReconciliationItemGridAPIView.as_view(), name="item-grid"),
    path("reviewer-queue/", GstReconciliationReviewerQueueAPIView.as_view(), name="reviewer-queue"),
    path("items/<int:pk>/detail/", GstReconciliationItemDetailAPIView.as_view(), name="item-detail"),
    path("items/<int:pk>/assign/", GstReconciliationItemAssignAPIView.as_view(), name="item-assign"),
    path("items/<int:pk>/manual-match/", GstReconciliationItemManualMatchAPIView.as_view(), name="item-manual-match"),
    path("items/<int:pk>/manual-unmatch/", GstReconciliationItemUnmatchAPIView.as_view(), name="item-manual-unmatch"),
    path("items/<int:pk>/unmatch/", GstReconciliationItemUnmatchAPIView.as_view(), name="item-unmatch"),
    path("items/<int:pk>/ignore/", GstReconciliationItemIgnoreAPIView.as_view(), name="item-ignore"),
    path("items/<int:pk>/reopen/", GstReconciliationItemReopenAPIView.as_view(), name="item-reopen"),
    path("items/<int:pk>/accept-mismatch/", GstReconciliationItemAcceptMismatchAPIView.as_view(), name="item-accept-mismatch"),
    path("items/<int:pk>/notes/", GstReconciliationItemNotesAPIView.as_view(), name="item-notes"),
    path("items/bulk/assign/", GstBulkAssignAPIView.as_view(), name="items-bulk-assign"),
    path("items/bulk/ignore/", GstBulkIgnoreAPIView.as_view(), name="items-bulk-ignore"),
    path("items/bulk/reopen/", GstBulkReopenAPIView.as_view(), name="items-bulk-reopen"),
    path("items/bulk/accept-mismatch/", GstBulkAcceptMismatchAPIView.as_view(), name="items-bulk-accept-mismatch"),
    path("items/bulk/unmatch/", GstBulkUnmatchAPIView.as_view(), name="items-bulk-unmatch"),
    path("items/bulk/mark-reviewed/", GstBulkMarkReviewedAPIView.as_view(), name="items-bulk-mark-reviewed"),
    path("source-documents/search/", GstSourceDocumentSearchAPIView.as_view(), name="source-document-search"),
    path(
        "source-documents/<str:source_document_type>/<str:document_id>/",
        GstSourceDocumentDetailAPIView.as_view(),
        name="source-document-detail",
    ),
    path(
        "adapters/purchase-gstr2b-batches/<int:batch_id>/create-run/",
        PurchaseGstr2bBatchCreateRunAPIView.as_view(),
        name="adapter-purchase-gstr2b-create-run",
    ),
]
