# Generated by Django 5.2.1 on 2026-03-07 15:35

import django.db.models.deletion
import django.utils.timezone
import vouchers.models.voucher_config
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('doc_code', models.CharField(default='JV', max_length=10)),
                ('doc_no', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_type', models.CharField(choices=[('CASH_PAYMENT', 'Cash Payment'), ('CASH_RECEIPT', 'Cash Receipt'), ('BANK_PAYMENT', 'Bank Payment'), ('BANK_RECEIPT', 'Bank Receipt'), ('JOURNAL', 'Journal')], db_index=True, default='JOURNAL', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('instrument_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_no', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument_date', models.DateField(blank=True, null=True)),
                ('total_debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Confirmed'), (3, 'Posted'), (9, 'Cancelled')], db_index=True, default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_payload', models.JSONField(blank=True, default=dict)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_vouchers', related_query_name='cancelled_voucher', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear')),
                ('primary_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_primary_accounts', to='financial.account')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('drcr', models.BooleanField(default=True, help_text='True=Debit, False=Credit')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vouchers.voucherheader')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='financial.account')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_doc_code_cash_payment', models.CharField(default='CPV', max_length=10)),
                ('default_doc_code_cash_receipt', models.CharField(default='CRV', max_length=10)),
                ('default_doc_code_bank_payment', models.CharField(default='BPV', max_length=10)),
                ('default_doc_code_bank_receipt', models.CharField(default='BRV', max_length=10)),
                ('default_doc_code_journal', models.CharField(default='JV', max_length=10)),
                ('default_workflow_action', models.CharField(choices=[('draft', 'Save as Draft'), ('confirm', 'Auto Confirm on Save'), ('post', 'Auto Post on Save')], db_index=True, default='draft', max_length=10)),
                ('policy_controls', models.JSONField(blank=True, default=vouchers.models.voucher_config.default_voucher_policy_controls)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_settings', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_settings', to='entity.subentity')),
            ],
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'voucher_date'], name='ix_voucher_ent_fin_date'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'voucher_type'], name='ix_voucher_ent_fin_type'),
        ),
        migrations.AddIndex(
            model_name='voucherheader',
            index=models.Index(fields=['entity', 'entityfinid', 'status'], name='ix_voucher_ent_fin_status'),
        ),
        migrations.AddConstraint(
            model_name='voucherheader',
            constraint=models.UniqueConstraint(fields=('entity', 'entityfinid', 'doc_code', 'doc_no'), name='uq_voucher_entity_fin_code_no'),
        ),
        migrations.AddConstraint(
            model_name='voucherheader',
            constraint=models.CheckConstraint(check=models.Q(('total_debit_amount__gte', 0)), name='ck_voucher_dr_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='voucherheader',
            constraint=models.CheckConstraint(check=models.Q(('total_credit_amount__gte', 0)), name='ck_voucher_cr_nonneg'),
        ),
        migrations.AddIndex(
            model_name='voucherline',
            index=models.Index(fields=['header'], name='ix_voucher_line_header'),
        ),
        migrations.AddIndex(
            model_name='voucherline',
            index=models.Index(fields=['ledger_account'], name='ix_voucher_line_ledger'),
        ),
        migrations.AddConstraint(
            model_name='voucherline',
            constraint=models.UniqueConstraint(fields=('header', 'line_no'), name='uq_voucher_line_header_lineno'),
        ),
        migrations.AddConstraint(
            model_name='voucherline',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='ck_voucher_line_amt_nonneg'),
        ),
        migrations.AddIndex(
            model_name='vouchersettings',
            index=models.Index(fields=['entity'], name='ix_voucher_settings_entity'),
        ),
        migrations.AddConstraint(
            model_name='vouchersettings',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity'), name='uq_voucher_settings_entity_subentity'),
        ),
    ]
