# Generated by Django 5.2.1 on 2026-03-25 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0010_remove_account_address1_remove_account_address2_and_more'),
        ('vouchers', '0004_voucherchoiceoverride_voucherlockperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voucherheader',
            name='uq_voucher_entity_fin_code_no',
        ),
        migrations.AddConstraint(
            model_name='voucherheader',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_no__isnull', False), ('subentity__isnull', False)), fields=('entity', 'entityfinid', 'subentity', 'doc_code', 'doc_no'), name='uq_voucher_scope_docno_sub'),
        ),
        migrations.AddConstraint(
            model_name='voucherheader',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_no__isnull', False), ('subentity__isnull', True)), fields=('entity', 'entityfinid', 'doc_code', 'doc_no'), name='uq_voucher_scope_docno_root'),
        ),
    ]
