from django.urls import path

from .views import (
    DistributionPolicyApproveAPIView,
    DistributionPolicyCompareAPIView,
    DistributionPolicyDetailAPIView,
    DistributionPolicyListCreateAPIView,
    DistributionPolicyRejectAPIView,
    DistributionPolicySeedAPIView,
    DistributionPolicySubmitAPIView,
    DistributionPolicySupersedeAPIView,
    FormationProfileAPIView,
    WaveOneActivationAPIView,
    WaveOneMigrationAPIView,
    CapitalDistributionRunDetailAPIView,
    CapitalDistributionOperationalHealthAPIView,
    CapitalDistributionRunListCalculateAPIView,
    CapitalDistributionAccountMappingAPIView,
    CapitalDistributionRunSubmitAPIView,
    CapitalDistributionRunApproveAPIView,
    CapitalDistributionRunPostAPIView,
    CapitalDistributionRunReverseAPIView,
    AppropriationStatementAPIView,
    TaxPolicyApproveAPIView,
    TaxPolicyDetailAPIView,
    TaxPolicyListCreateAPIView,
    TaxPolicyRejectAPIView,
    TaxPolicySubmitAPIView,
    TaxPolicySupersedeAPIView,
    TaxWorkingApproveAPIView,
    TaxWorkingDetailAPIView,
    TaxWorkingExportAPIView,
    TaxWorkingLineOverrideAPIView,
    TaxWorkingListCalculateAPIView,
    TaxWorkingReproduceAPIView,
    TaxWorkingReverseAPIView,
    TaxWorkingSubmitAPIView,
)


app_name = "capital_distribution_api"

urlpatterns = [
    path("formation/", FormationProfileAPIView.as_view(), name="formation-profile"),
    path("migration/", WaveOneMigrationAPIView.as_view(), name="wave-one-migration"),
    path("activation/", WaveOneActivationAPIView.as_view(), name="wave-one-activation"),
    path("policies/", DistributionPolicyListCreateAPIView.as_view(), name="policy-list"),
    path("policies/seed/", DistributionPolicySeedAPIView.as_view(), name="policy-seed"),
    path("policies/<int:policy_id>/", DistributionPolicyDetailAPIView.as_view(), name="policy-detail"),
    path("policies/<int:policy_id>/submit/", DistributionPolicySubmitAPIView.as_view(), name="policy-submit"),
    path("policies/<int:policy_id>/approve/", DistributionPolicyApproveAPIView.as_view(), name="policy-approve"),
    path("policies/<int:policy_id>/reject/", DistributionPolicyRejectAPIView.as_view(), name="policy-reject"),
    path("policies/<int:policy_id>/supersede/", DistributionPolicySupersedeAPIView.as_view(), name="policy-supersede"),
    path(
        "policies/<int:policy_id>/compare/<int:other_policy_id>/",
        DistributionPolicyCompareAPIView.as_view(),
        name="policy-compare",
    ),
    path("tax-policies/", TaxPolicyListCreateAPIView.as_view(), name="tax-policy-list"),
    path("tax-policies/<int:tax_policy_id>/", TaxPolicyDetailAPIView.as_view(), name="tax-policy-detail"),
    path("tax-policies/<int:tax_policy_id>/submit/", TaxPolicySubmitAPIView.as_view(), name="tax-policy-submit"),
    path("tax-policies/<int:tax_policy_id>/approve/", TaxPolicyApproveAPIView.as_view(), name="tax-policy-approve"),
    path("tax-policies/<int:tax_policy_id>/reject/", TaxPolicyRejectAPIView.as_view(), name="tax-policy-reject"),
    path(
        "tax-policies/<int:tax_policy_id>/supersede/",
        TaxPolicySupersedeAPIView.as_view(),
        name="tax-policy-supersede",
    ),
    path("tax-workings/", TaxWorkingListCalculateAPIView.as_view(), name="tax-working-list-calculate"),
    path("tax-workings/<int:tax_working_id>/", TaxWorkingDetailAPIView.as_view(), name="tax-working-detail"),
    path(
        "tax-workings/<int:tax_working_id>/export/",
        TaxWorkingExportAPIView.as_view(),
        name="tax-working-export",
    ),
    path(
        "tax-workings/<int:tax_working_id>/lines/<int:line_id>/override/",
        TaxWorkingLineOverrideAPIView.as_view(),
        name="tax-working-line-override",
    ),
    path(
        "tax-workings/<int:tax_working_id>/reproduce/",
        TaxWorkingReproduceAPIView.as_view(),
        name="tax-working-reproduce",
    ),
    path(
        "tax-workings/<int:tax_working_id>/submit/",
        TaxWorkingSubmitAPIView.as_view(),
        name="tax-working-submit",
    ),
    path(
        "tax-workings/<int:tax_working_id>/approve/",
        TaxWorkingApproveAPIView.as_view(),
        name="tax-working-approve",
    ),
    path(
        "tax-workings/<int:tax_working_id>/reverse/",
        TaxWorkingReverseAPIView.as_view(),
        name="tax-working-reverse",
    ),
    path("runs/", CapitalDistributionRunListCalculateAPIView.as_view(), name="run-list-calculate"),
    path("runs/<int:run_id>/", CapitalDistributionRunDetailAPIView.as_view(), name="run-detail"),
    path("operations/health/", CapitalDistributionOperationalHealthAPIView.as_view(), name="operational-health"),
    path("account-mappings/", CapitalDistributionAccountMappingAPIView.as_view(), name="account-mappings"),
    path("runs/<int:run_id>/submit/", CapitalDistributionRunSubmitAPIView.as_view(), name="run-submit"),
    path("runs/<int:run_id>/approve/", CapitalDistributionRunApproveAPIView.as_view(), name="run-approve"),
    path("runs/<int:run_id>/post/", CapitalDistributionRunPostAPIView.as_view(), name="run-post"),
    path("runs/<int:run_id>/reverse/", CapitalDistributionRunReverseAPIView.as_view(), name="run-reverse"),
    path("reports/appropriation-statement/", AppropriationStatementAPIView.as_view(), name="appropriation-statement"),
]
