# Generated by Django 4.2.28 on 2026-03-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_userrole_entity_user_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
    ]
