# Generated by Django 5.2.1 on 2026-03-14 06:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_modern_entity_fields(apps, schema_editor):
    Entity = apps.get_model("entity", "Entity")
    SubEntity = apps.get_model("entity", "SubEntity")
    EntityFinancialYear = apps.get_model("entity", "EntityFinancialYear")

    for entity in Entity.objects.all().iterator():
        changed = []
        if not entity.trade_name and entity.entityname:
            entity.trade_name = entity.entityname
            changed.append("trade_name")
        if not entity.short_name and entity.entityname:
            entity.short_name = entity.entityname[:50]
            changed.append("short_name")
        if not entity.contact_person_name and entity.ownername:
            entity.contact_person_name = entity.ownername
            changed.append("contact_person_name")
        if not entity.mobile_primary and entity.phoneoffice:
            entity.mobile_primary = entity.phoneoffice
            changed.append("mobile_primary")
        if not entity.mobile_secondary and entity.phoneresidence:
            entity.mobile_secondary = entity.phoneresidence
            changed.append("mobile_secondary")
        if not entity.email_primary and entity.email:
            entity.email_primary = entity.email.lower()
            changed.append("email_primary")
        if not entity.tan_no and entity.tds:
            entity.tan_no = entity.tds.upper()
            changed.append("tan_no")
        if entity.gstno and not entity.gst_effective_from and entity.dateofreg:
            entity.gst_effective_from = entity.dateofreg.date()
            changed.append("gst_effective_from")
        if entity.gstno and not entity.gst_cancelled_from and entity.dateofdreg:
            entity.gst_cancelled_from = entity.dateofdreg.date()
            changed.append("gst_cancelled_from")
        if not entity.entity_code and entity.entityname:
            generated = slugify(entity.entityname).replace("-", "_").upper()[:24]
            if not generated:
                generated = "ENTITY"
            generated = f"{generated}_{entity.id}"[:30]
            entity.entity_code = generated or f"ENTITY_{entity.id}"
            changed.append("entity_code")
        if changed:
            entity.save(update_fields=changed)

    for subentity in SubEntity.objects.all().iterator():
        changed = []
        if not subentity.subentity_code and subentity.subentityname:
            code = slugify(subentity.subentityname).replace("-", "_").upper()[:24]
            if not code:
                code = "SUBENTITY"
            code = f"{code}_{subentity.id}"[:30]
            subentity.subentity_code = code or f"SUB_{subentity.id}"
            changed.append("subentity_code")
        if not subentity.email_primary and subentity.email:
            subentity.email_primary = subentity.email.lower()
            changed.append("email_primary")
        if not subentity.mobile_primary and subentity.phoneoffice:
            subentity.mobile_primary = subentity.phoneoffice
            changed.append("mobile_primary")
        if not subentity.mobile_secondary and subentity.phoneresidence:
            subentity.mobile_secondary = subentity.phoneresidence
            changed.append("mobile_secondary")
        if not subentity.is_head_office and subentity.ismainentity:
            subentity.is_head_office = True
            changed.append("is_head_office")
        if subentity.is_head_office and subentity.branch_type != "head_office":
            subentity.branch_type = "head_office"
            changed.append("branch_type")
        if changed:
            subentity.save(update_fields=changed)

    for fy in EntityFinancialYear.objects.all().iterator():
        changed = []
        if fy.finstartyear and fy.finendyear:
            if not fy.year_code:
                fy.year_code = f"FY{fy.finstartyear.year}-{str(fy.finendyear.year)[-2:]}-{fy.id}"
                changed.append("year_code")
            if not fy.assessment_year_label:
                fy.assessment_year_label = f"AY{fy.finendyear.year}-{str(fy.finendyear.year + 1)[-2:]}"
                changed.append("assessment_year_label")
        if changed:
            fy.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entityfinancialyear',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subentity',
            options={'ordering': ['sort_order', 'subentityname']},
        ),
        migrations.AddField(
            model_name='entity',
            name='accounts_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='business_commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='business_type',
            field=models.CharField(choices=[('trader', 'Trader'), ('manufacturer', 'Manufacturer'), ('service', 'Service Provider'), ('mixed', 'Trading + Services'), ('ngo', 'NGO / Trust'), ('educational', 'Educational Institution'), ('healthcare', 'Healthcare'), ('government', 'Government / PSU'), ('other', 'Other')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='entity',
            name='cin_no',
            field=models.CharField(blank=True, max_length=21, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid CIN.', regex='^[A-Z0-9]{21}$')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_person_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='email_primary',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='gst_cancelled_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='gst_effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='gst_registration_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composition', 'Composition'), ('sez', 'SEZ'), ('tds', 'TDS Deductor'), ('tcs', 'TCS Collector'), ('uin', 'UIN Holder'), ('non_resident', 'Non Resident')], default='registered', max_length=20),
        ),
        migrations.AddField(
            model_name='entity',
            name='gst_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='iec_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IEC code.', regex='^[0-9A-Z]{10}$')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_einvoice_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_ewaybill_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_msme_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_tcs_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_tds_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='llpin_no',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid LLPIN.', regex='^[A-Z]{3}-[0-9]{4}$')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entity',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='mobile_secondary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='msme_category',
            field=models.CharField(blank=True, choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='organization_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='entity',
            name='parent_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entities', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='registered_address_same_as_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='support_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='tan_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid TAN.', regex='^[A-Z]{4}[0-9]{5}[A-Z]$')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='trade_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='udyam_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='ap_ar_locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='assessment_year_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='books_locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='gst_locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='inventory_locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='is_audit_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='is_year_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='period_status',
            field=models.CharField(choices=[('open', 'Open'), ('soft_locked', 'Soft Locked'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='entityfinancialyear',
            name='year_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='GstRegitrationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.gstregistrationtype'),
        ),
        migrations.AddField(
            model_name='subentity',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='addressfloorno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='addressstreet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='branch_type',
            field=models.CharField(choices=[('head_office', 'Head Office'), ('branch', 'Branch'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('depot', 'Depot'), ('showroom', 'Showroom'), ('office', 'Office')], default='branch', max_length=20),
        ),
        migrations.AddField(
            model_name='subentity',
            name='can_bank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='can_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='can_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='can_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='contact_person_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='email_primary',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subentity',
            name='gstno',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')]),
        ),
        migrations.AddField(
            model_name='subentity',
            name='is_head_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subentity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subentity',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AddField(
            model_name='subentity',
            name='mobile_secondary',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AddField(
            model_name='subentity',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subentity',
            name='subentity_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='gstno',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='panno',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phoneoffice',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phoneresidence',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pincode',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 6 digit pincode.', regex='^[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tds',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid TAN.', regex='^[A-Z]{4}[0-9]{5}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='subentity',
            name='phoneoffice',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AlterField(
            model_name='subentity',
            name='phoneresidence',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')]),
        ),
        migrations.AlterField(
            model_name='subentity',
            name='pincode',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 6 digit pincode.', regex='^[0-9]{6}$')]),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entityname'], name='entity_enti_entityn_e2f656_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['legalname'], name='entity_enti_legalna_fa440c_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['gstno'], name='entity_enti_gstno_ad8873_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['panno'], name='entity_enti_panno_803841_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['organization_status'], name='entity_enti_organiz_0e979a_idx'),
        ),
        migrations.AddIndex(
            model_name='entityfinancialyear',
            index=models.Index(fields=['entity', 'isactive'], name='entity_enti_entity__c34f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='entityfinancialyear',
            index=models.Index(fields=['entity', 'period_status'], name='entity_enti_entity__e59473_idx'),
        ),
        migrations.AddIndex(
            model_name='subentity',
            index=models.Index(fields=['entity', 'subentityname'], name='entity_sube_entity__fef3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='subentity',
            index=models.Index(fields=['entity', 'subentity_code'], name='entity_sube_entity__40df83_idx'),
        ),
        migrations.AddIndex(
            model_name='subentity',
            index=models.Index(fields=['gstno'], name='entity_sube_gstno_c6b86f_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_code__isnull', False)), fields=('entity_code',), name='uq_entity_code_when_present'),
        ),
        migrations.AddConstraint(
            model_name='entityfinancialyear',
            constraint=models.UniqueConstraint(condition=models.Q(('year_code__isnull', False)), fields=('entity', 'year_code'), name='uq_entity_year_code'),
        ),
        migrations.AddConstraint(
            model_name='subentity',
            constraint=models.UniqueConstraint(condition=models.Q(('subentity_code__isnull', False)), fields=('entity', 'subentity_code'), name='uq_subentity_code_per_entity'),
        ),
        migrations.RunPython(backfill_modern_entity_fields, migrations.RunPython.noop),
    ]
