# Generated by Django 4.2.28 on 2026-03-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_entity_customer_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='uq_entity_user_role_once',
        ),
        migrations.RemoveField(
            model_name='role',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='roleprivilege',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='roleprivilege',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roleprivilege',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='MasterGstDetail',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePrivilege',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
