# Generated by Django 5.2.1 on 2026-03-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_remove_role_entity_remove_roleprivilege_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityownership',
            name='OwnerShipType',
        ),
        migrations.RemoveField(
            model_name='entityownership',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='gstaccountdetail',
            name='addrLoc',
        ),
        migrations.RemoveField(
            model_name='gstaccountdetail',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gstaccountdetail',
            name='district',
        ),
        migrations.RemoveField(
            model_name='gstaccountdetail',
            name='stateCode',
        ),
        migrations.DeleteModel(
            name='OwnerShipTypes',
        ),
        migrations.DeleteModel(
            name='EntityOwnership',
        ),
        migrations.DeleteModel(
            name='GstAccountDetail',
        ),
    ]
