# Generated by Django 5.2.1 on 2026-03-21 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _to_clean(value, upper=False, lower=False, max_length=None):
    text = (value or "").strip()
    if not text:
        return None
    if upper:
        text = text.upper()
    if lower:
        text = text.lower()
    if max_length:
        return text[:max_length]
    return text


def _to_date(value):
    if value is None:
        return None
    if hasattr(value, "date"):
        return value.date()
    return value


def seed_normalized_profiles(apps, schema_editor):
    Entity = apps.get_model("entity", "Entity")
    Constitution = apps.get_model("entity", "Constitution")
    BankDetail = apps.get_model("entity", "BankDetail")
    BankAccount = apps.get_model("entity", "BankAccount")
    EntityConstitution = apps.get_model("entity", "EntityConstitution")
    SubEntity = apps.get_model("entity", "SubEntity")

    EntityAddress = apps.get_model("entity", "EntityAddress")
    EntityContact = apps.get_model("entity", "EntityContact")
    EntityTaxProfile = apps.get_model("entity", "EntityTaxProfile")
    EntityGstRegistration = apps.get_model("entity", "EntityGstRegistration")
    EntityBankAccountV2 = apps.get_model("entity", "EntityBankAccountV2")
    EntityComplianceProfile = apps.get_model("entity", "EntityComplianceProfile")
    EntityConstitutionV2 = apps.get_model("entity", "EntityConstitutionV2")

    SubEntityAddress = apps.get_model("entity", "SubEntityAddress")
    SubEntityContact = apps.get_model("entity", "SubEntityContact")
    SubEntityGstRegistration = apps.get_model("entity", "SubEntityGstRegistration")
    SubEntityCapability = apps.get_model("entity", "SubEntityCapability")

    constitutions = Constitution.objects.in_bulk(field_name="id")
    bank_details = BankDetail.objects.in_bulk(field_name="id")
    active_entity_gstin = set()
    active_subentity_gstin = set()

    entities = Entity.objects.all().order_by("id")
    for entity in entities:
        createdby_id = getattr(entity, "createdby_id", None)
        registration_date = _to_date(getattr(entity, "dateofreg", None))

        EntityTaxProfile.objects.update_or_create(
            entity_id=entity.id,
            defaults={
                "pan": _to_clean(entity.panno, upper=True, max_length=10),
                "tan": _to_clean(entity.tan_no or entity.tds, upper=True, max_length=10),
                "cin_no": _to_clean(entity.cin_no, upper=True, max_length=21),
                "llpin_no": _to_clean(entity.llpin_no, upper=True, max_length=8),
                "iec_code": _to_clean(entity.iec_code, upper=True, max_length=10),
                "udyam_no": _to_clean(entity.udyam_no, upper=True, max_length=30),
                "incorporation_date": entity.incorporation_date,
                "business_commencement_date": entity.business_commencement_date,
                "effective_from": registration_date,
                "createdby_id": createdby_id,
                "isactive": bool(entity.isactive),
            },
        )

        EntityComplianceProfile.objects.update_or_create(
            entity_id=entity.id,
            defaults={
                "is_tds_applicable": bool(entity.is_tds_applicable),
                "is_tcs_applicable": bool(entity.is_tcs_applicable),
                "is_einvoice_applicable": bool(entity.is_einvoice_applicable),
                "is_ewaybill_applicable": bool(entity.is_ewaybill_applicable),
                "is_msme_registered": bool(entity.is_msme_registered),
                "msme_category": entity.msme_category,
                "createdby_id": createdby_id,
                "isactive": bool(entity.isactive),
            },
        )

        if _to_clean(entity.address):
            EntityAddress.objects.update_or_create(
                entity_id=entity.id,
                address_type="registered",
                defaults={
                    "line1": _to_clean(entity.address, max_length=255) or "-",
                    "line2": _to_clean(entity.address2, max_length=255),
                    "floor_no": _to_clean(entity.addressfloorno, max_length=50),
                    "street": _to_clean(entity.addressstreet, max_length=100),
                    "country_id": entity.country_id,
                    "state_id": entity.state_id,
                    "district_id": entity.district_id,
                    "city_id": entity.city_id,
                    "pincode": _to_clean(entity.pincode, max_length=10),
                    "is_primary": True,
                    "effective_from": registration_date,
                    "createdby_id": createdby_id,
                    "isactive": bool(entity.isactive),
                },
            )

        owner_name = _to_clean(entity.contact_person_name) or _to_clean(entity.ownername)
        owner_mobile = _to_clean(entity.mobile_primary) or _to_clean(entity.phoneoffice)
        owner_email = _to_clean(entity.email_primary or entity.email, lower=True)
        if owner_name:
            EntityContact.objects.update_or_create(
                entity_id=entity.id,
                contact_type="owner",
                name=owner_name,
                defaults={
                    "designation": _to_clean(entity.contact_person_designation, max_length=100),
                    "mobile": _to_clean(owner_mobile, max_length=20),
                    "email": owner_email,
                    "is_primary": True,
                    "effective_from": registration_date,
                    "createdby_id": createdby_id,
                    "isactive": bool(entity.isactive),
                },
            )

        accounts_email = _to_clean(entity.accounts_email, lower=True)
        if accounts_email:
            EntityContact.objects.update_or_create(
                entity_id=entity.id,
                contact_type="accounts",
                name="Accounts",
                defaults={
                    "email": accounts_email,
                    "is_primary": False,
                    "effective_from": registration_date,
                    "createdby_id": createdby_id,
                    "isactive": bool(entity.isactive),
                },
            )

        support_email = _to_clean(entity.support_email, lower=True)
        if support_email:
            EntityContact.objects.update_or_create(
                entity_id=entity.id,
                contact_type="support",
                name="Support",
                defaults={
                    "email": support_email,
                    "is_primary": False,
                    "effective_from": registration_date,
                    "createdby_id": createdby_id,
                    "isactive": bool(entity.isactive),
                },
            )

        gstin = _to_clean(entity.gstno, upper=True)
        if gstin:
            is_active = gstin not in active_entity_gstin
            if is_active:
                active_entity_gstin.add(gstin)
            EntityGstRegistration.objects.update_or_create(
                entity_id=entity.id,
                gstin=gstin,
                defaults={
                    "registration_type_id": entity.GstRegitrationType_id,
                    "gst_status": entity.gst_registration_status or "registered",
                    "state_id": entity.state_id,
                    "nature_of_business": _to_clean(entity.nature_of_business, max_length=150),
                    "gst_effective_from": entity.gst_effective_from,
                    "gst_cancelled_from": entity.gst_cancelled_from,
                    "credential_ref": _to_clean(entity.gst_username, max_length=255),
                    "is_primary": is_active,
                    "createdby_id": createdby_id,
                    "isactive": bool(entity.isactive and is_active),
                },
            )

    for bank in BankAccount.objects.select_related("entity").order_by("entity_id", "-is_primary", "id"):
        current_primary = EntityBankAccountV2.objects.filter(entity_id=bank.entity_id, isactive=True, is_primary=True).exists()
        is_primary = bool(bank.is_primary) and not current_primary
        if not current_primary and not bank.is_primary:
            # Keep at least one primary account per entity for V2 rows.
            has_any = EntityBankAccountV2.objects.filter(entity_id=bank.entity_id, isactive=True).exists()
            if not has_any:
                is_primary = True

        EntityBankAccountV2.objects.create(
            entity_id=bank.entity_id,
            bank_name=_to_clean(bank.bank_name, max_length=100) or "Bank",
            branch=_to_clean(bank.branch, max_length=100),
            account_number=_to_clean(bank.account_number, max_length=32) or "UNKNOWN",
            ifsc_code=_to_clean(bank.ifsc_code, upper=True, max_length=11) or "UNKNOWN00000",
            account_type=bank.account_type or "current",
            is_primary=is_primary,
            effective_from=None,
            createdby_id=getattr(bank.entity, "createdby_id", None),
            isactive=bool(getattr(bank.entity, "isactive", True)),
        )

    entities_with_v2_bank = set(
        EntityBankAccountV2.objects.values_list("entity_id", flat=True).distinct()
    )
    for entity in Entity.objects.exclude(id__in=entities_with_v2_bank):
        account_number = _to_clean(entity.bankacno, max_length=32)
        ifsc_code = _to_clean(entity.ifsccode, upper=True, max_length=11)
        if not account_number or not ifsc_code:
            continue

        bank_name = None
        if entity.bank_id:
            bank_obj = bank_details.get(entity.bank_id)
            bank_name = getattr(bank_obj, "bankname", None)

        EntityBankAccountV2.objects.create(
            entity_id=entity.id,
            bank_name=_to_clean(bank_name, max_length=100) or "Bank",
            branch=None,
            account_number=account_number,
            ifsc_code=ifsc_code,
            account_type="current",
            is_primary=True,
            effective_from=_to_date(getattr(entity, "dateofreg", None)),
            createdby_id=getattr(entity, "createdby_id", None),
            isactive=bool(entity.isactive),
        )

    for legacy_constitution in EntityConstitution.objects.select_related("entity").order_by("id"):
        entity = legacy_constitution.entity
        constitution = constitutions.get(getattr(entity, "const_id", None))
        EntityConstitutionV2.objects.create(
            entity_id=legacy_constitution.entity_id,
            constitution_code=_to_clean(getattr(constitution, "constcode", None), upper=True, max_length=20) or "LEGACY",
            constitution_name=_to_clean(getattr(constitution, "constitutionname", None), max_length=255) or "Legacy",
            shareholder=_to_clean(legacy_constitution.shareholder, max_length=255),
            pan=_to_clean(legacy_constitution.pan, upper=True, max_length=10),
            share_percentage=legacy_constitution.sharepercentage,
            effective_from=None,
            createdby_id=getattr(legacy_constitution, "createdby_id", None) or getattr(entity, "createdby_id", None),
            isactive=bool(getattr(legacy_constitution, "isactive", True)),
        )

    for subentity in SubEntity.objects.select_related("entity").order_by("id"):
        if _to_clean(subentity.address):
            SubEntityAddress.objects.update_or_create(
                subentity_id=subentity.id,
                address_type="operations",
                defaults={
                    "line1": _to_clean(subentity.address, max_length=255) or "-",
                    "line2": _to_clean(subentity.address2, max_length=255),
                    "floor_no": _to_clean(subentity.addressfloorno, max_length=50),
                    "street": _to_clean(subentity.addressstreet, max_length=100),
                    "country_id": subentity.country_id,
                    "state_id": subentity.state_id,
                    "district_id": subentity.district_id,
                    "city_id": subentity.city_id,
                    "pincode": _to_clean(subentity.pincode, max_length=10),
                    "is_primary": True,
                    "isactive": bool(subentity.isactive),
                },
            )

        sub_contact_name = _to_clean(subentity.contact_person_name) or _to_clean(subentity.subentityname)
        sub_contact_mobile = _to_clean(subentity.mobile_primary) or _to_clean(subentity.phoneoffice)
        sub_contact_email = _to_clean(subentity.email_primary or subentity.email, lower=True)
        if sub_contact_name:
            SubEntityContact.objects.update_or_create(
                subentity_id=subentity.id,
                name=sub_contact_name,
                defaults={
                    "designation": _to_clean(subentity.contact_person_designation, max_length=100),
                    "mobile": _to_clean(sub_contact_mobile, max_length=20),
                    "email": sub_contact_email,
                    "is_primary": True,
                    "isactive": bool(subentity.isactive),
                },
            )

        sub_gstin = _to_clean(subentity.gstno, upper=True)
        if sub_gstin:
            sub_is_active = sub_gstin not in active_subentity_gstin
            if sub_is_active:
                active_subentity_gstin.add(sub_gstin)
            SubEntityGstRegistration.objects.update_or_create(
                subentity_id=subentity.id,
                gstin=sub_gstin,
                defaults={
                    "registration_type_id": subentity.GstRegitrationType_id,
                    "gst_status": getattr(subentity.entity, "gst_registration_status", None) or "registered",
                    "gst_effective_from": None,
                    "gst_cancelled_from": None,
                    "is_primary": sub_is_active,
                    "isactive": bool(subentity.isactive and sub_is_active),
                },
            )

        SubEntityCapability.objects.update_or_create(
            subentity_id=subentity.id,
            defaults={
                "can_sell": bool(subentity.can_sell),
                "can_purchase": bool(subentity.can_purchase),
                "can_stock": bool(subentity.can_stock),
                "can_bank": bool(subentity.can_bank),
                "isactive": bool(subentity.isactive),
            },
        )


def reverse_seed_normalized_profiles(apps, schema_editor):
    # Tables are dropped on reverse migration; no reverse data move required.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_remove_entityownership_ownershiptype_and_more'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityComplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('is_tds_applicable', models.BooleanField(default=False)),
                ('is_tcs_applicable', models.BooleanField(default=False)),
                ('is_einvoice_applicable', models.BooleanField(default=False)),
                ('is_ewaybill_applicable', models.BooleanField(default=False)),
                ('is_msme_registered', models.BooleanField(default=False)),
                ('msme_category', models.CharField(blank=True, choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium')], max_length=20, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profile', to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('pan', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('tan', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid TAN.', regex='^[A-Z]{4}[0-9]{5}[A-Z]$')])),
                ('cin_no', models.CharField(blank=True, max_length=21, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid CIN.', regex='^[A-Z0-9]{21}$')])),
                ('llpin_no', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid LLPIN.', regex='^[A-Z]{3}-[0-9]{4}$')])),
                ('iec_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IEC code.', regex='^[0-9A-Z]{10}$')])),
                ('udyam_no', models.CharField(blank=True, max_length=30, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('business_commencement_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubEntityCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('can_sell', models.BooleanField(default=True)),
                ('can_purchase', models.BooleanField(default=True)),
                ('can_stock', models.BooleanField(default=True)),
                ('can_bank', models.BooleanField(default=True)),
                ('subentity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capability', to='entity.subentity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('address_type', models.CharField(choices=[('registered', 'Registered'), ('principal', 'Principal Place'), ('correspondence', 'Correspondence')], default='registered', max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 6 digit pincode.', regex='^[0-9]{6}$')])),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.country')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.district')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entity.entity')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'address_type', 'isactive'], name='entity_enti_entity__5e2afb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True), ('isactive', True)), fields=('entity', 'address_type'), name='uq_entity_address_primary_type')],
            },
        ),
        migrations.CreateModel(
            name='EntityBankAccountV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(max_length=32)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings')], default='current', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts_v2', to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'ifsc_code', 'isactive'], name='entity_enti_entity__b44d5f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True), ('isactive', True)), fields=('entity',), name='uq_entity_bank_account_v2_primary')],
            },
        ),
        migrations.CreateModel(
            name='EntityConstitutionV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('constitution_code', models.CharField(max_length=20)),
                ('constitution_name', models.CharField(max_length=255)),
                ('shareholder', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitutions_v2', to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'constitution_code', 'isactive'], name='entity_enti_entity__c07245_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('contact_type', models.CharField(choices=[('owner', 'Owner'), ('accounts', 'Accounts'), ('support', 'Support'), ('compliance', 'Compliance'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'contact_type', 'isactive'], name='entity_enti_entity__9aaae0_idx'), models.Index(fields=['entity', 'email'], name='entity_enti_entity__8c8736_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityGstRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gstin', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')])),
                ('gst_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composition', 'Composition'), ('sez', 'SEZ'), ('tds', 'TDS Deductor'), ('tcs', 'TCS Collector'), ('uin', 'UIN Holder'), ('non_resident', 'Non Resident')], default='registered', max_length=20)),
                ('nature_of_business', models.CharField(blank=True, max_length=150, null=True)),
                ('gst_effective_from', models.DateField(blank=True, null=True)),
                ('gst_cancelled_from', models.DateField(blank=True, null=True)),
                ('credential_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_registrations', to='entity.entity')),
                ('registration_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.gstregistrationtype')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'is_primary', 'isactive'], name='entity_enti_entity__0e33fa_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('gstin',), name='uq_entity_gst_registration_active_gstin'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('isactive', True)), fields=('entity',), name='uq_entity_gst_registration_primary')],
            },
        ),
        migrations.CreateModel(
            name='EntityOwnershipV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('ownership_type', models.CharField(choices=[('proprietor', 'Proprietor'), ('partner', 'Partner'), ('director', 'Director'), ('shareholder', 'Shareholder'), ('trustee', 'Trustee'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')])),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capital_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships_v2', to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'ownership_type', 'isactive'], name='entity_enti_entity__bdb5ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubEntityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('address_type', models.CharField(choices=[('operations', 'Operations'), ('registered', 'Registered'), ('billing', 'Billing')], default='operations', max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 6 digit pincode.', regex='^[0-9]{6}$')])),
                ('is_primary', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state')),
                ('subentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entity.subentity')),
            ],
            options={
                'indexes': [models.Index(fields=['subentity', 'address_type', 'isactive'], name='entity_sube_subenti_846635_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubEntityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+() -]{8,20}$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('subentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entity.subentity')),
            ],
            options={
                'indexes': [models.Index(fields=['subentity', 'is_primary', 'isactive'], name='entity_sube_subenti_26a0ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubEntityGstRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gstin', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')])),
                ('gst_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composition', 'Composition'), ('sez', 'SEZ'), ('tds', 'TDS Deductor'), ('tcs', 'TCS Collector'), ('uin', 'UIN Holder'), ('non_resident', 'Non Resident')], default='registered', max_length=20)),
                ('gst_effective_from', models.DateField(blank=True, null=True)),
                ('gst_cancelled_from', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('registration_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.gstregistrationtype')),
                ('subentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_registrations', to='entity.subentity')),
            ],
            options={
                'indexes': [models.Index(fields=['subentity', 'is_primary', 'isactive'], name='entity_sube_subenti_f7c495_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isactive', True)), fields=('gstin',), name='uq_subentity_gst_registration_active_gstin')],
            },
        ),
        migrations.RunPython(
            seed_normalized_profiles,
            reverse_seed_normalized_profiles,
        ),
    ]
