# Generated by Django 5.2.1 on 2026-03-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_userentitycontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityconstitution',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='entityconstitution',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitydetail',
            name='entity',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='EntityConstitution',
        ),
        migrations.DeleteModel(
            name='EntityDetail',
        ),
    ]
