# Generated by Django 4.2.28 on 2026-03-26 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitygstregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='subentitygstregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$')]),
        ),
    ]
