# Generated by Django 5.2.1 on 2026-04-07 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_entitygstregistration_state_scope_and_primary_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('gstin_state_match_mode', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('off', 'Off')], default='hard', max_length=10)),
                ('require_subentity_mode', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('off', 'Off')], default='hard', max_length=10)),
                ('require_head_office_subentity_mode', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('off', 'Off')], default='hard', max_length=10)),
                ('require_entity_primary_gstin_mode', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('off', 'Off')], default='hard', max_length=10)),
                ('subentity_gstin_state_match_mode', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('off', 'Off')], default='hard', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='entity.entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
