# Generated by Django 5.2.1 on 2026-04-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_entitypolicy'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subentitygstregistration',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subentitygstregistration',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.state'),
        ),
        migrations.AddConstraint(
            model_name='subentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_head_office', True), ('isactive', True)), fields=('entity',), name='uq_subentity_single_head_office_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='subentitygstregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('isactive', True)), fields=('subentity',), name='uq_subentity_gst_registration_primary'),
        ),
        migrations.AddConstraint(
            model_name='subentitygstregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('isactive', True), ('state__isnull', False)), fields=('subentity', 'state'), name='uq_subentity_gst_registration_subentity_state_active'),
        ),
    ]
