# Generated by Django 5.2.1 on 2026-04-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_subentitygstregistration_nature_of_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='godowns', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='godown',
            name='subentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='godowns', to='entity.subentity'),
        ),
        migrations.AlterField(
            model_name='godown',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='godown',
            index=models.Index(fields=['entity', 'is_active'], name='entity_godo_entity__076766_idx'),
        ),
        migrations.AddIndex(
            model_name='godown',
            index=models.Index(fields=['entity', 'subentity', 'is_active'], name='entity_godo_entity__2bbddb_idx'),
        ),
        migrations.AddConstraint(
            model_name='godown',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='uq_godown_entity_code'),
        ),
        migrations.AddConstraint(
            model_name='godown',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='uq_godown_entity_name'),
        ),
    ]
