# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0017_godown_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityconstitutionv2",
            name="account_preference",
            field=models.CharField(
                choices=[
                    ("capital", "Capital"),
                    ("current", "Current"),
                    ("auto", "Auto"),
                ],
                default="capital",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entityconstitutionv2",
            name="agreement_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
