# Generated by Django 4.2.28 on 2026-04-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0019_entityownershipv2_account_preference_and_agreement_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='unitType',
        ),
    ]
