# Generated by Django 5.2.1 on 2026-04-19 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_remove_entity_unittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitygstregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='subentitygstregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$')]),
        ),
    ]
