# Generated by Django 5.2.1 on 2026-05-10 06:04

import entity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0023_one_active_entity_gst_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitygstregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, validators=[entity.models.gstin_validator]),
        ),
        migrations.AlterField(
            model_name='subentitygstregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, validators=[entity.models.gstin_validator]),
        ),
    ]
