# Generated by Django 5.2.1 on 2026-05-18 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entity', '0028_rename_entity_entit_entity__ecbab2_idx_entity_enti_entity__1a72b4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityapprovalpolicy',
            name='policy_key',
            field=models.CharField(choices=[('payroll_run', 'Payroll Run Approval'), ('payroll_adjustment', 'Payroll Adjustment Approval'), ('payroll_payment_handoff', 'Payroll Payment Handoff'), ('payroll_posting', 'Payroll Posting Approval'), ('payroll_payment_batch', 'Payroll Payment Batch Approval'), ('fnf_settlement', 'FnF Settlement Approval'), ('contract_tax_declaration', 'Contract Tax Declaration Approval'), ('leave_application', 'Leave Application Approval'), ('employment_change', 'Employment Change Approval')], max_length=40),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('object_id', models.CharField(max_length=64)),
                ('workflow_key', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approvals', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_approvals', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='contenttypes.contenttype')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='entity.entity')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_approvals', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='entity.subentity')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('step_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('approver_role', models.CharField(blank=True, default='', max_length=80)),
                ('approver_permission', models.CharField(blank=True, default='', max_length=120)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='entity.approvalrequest')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['approval_request_id', 'step_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ROUTED', 'Routed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('LOCKED', 'Locked'), ('STATUS_SYNC', 'Status Sync')], max_length=20)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_action_logs', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='entity.approvalrequest')),
                ('approval_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='entity.approvalstep')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity', 'status', 'workflow_key'], name='entity_appr_entity__de15d8_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='entity_appr_content_143a48_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity', 'subentity', 'status'], name='entity_appr_entity__ad180d_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approval_request', 'status'], name='entity_appr_approva_b0439e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver_user', 'status'], name='entity_appr_approve_cc9855_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalactionlog',
            index=models.Index(fields=['approval_request', 'created_at'], name='entity_appr_approva_d5dbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalactionlog',
            index=models.Index(fields=['action', 'created_at'], name='entity_appr_action_b8e2b7_idx'),
        ),
    ]
