# Generated by Django 5.2.1 on 2026-05-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("entity", "0029_alter_entityapprovalpolicy_policy_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("channel", models.CharField(choices=[("IN_APP", "In App"), ("EMAIL", "Email"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp")], default="IN_APP", max_length=20)),
                ("subject_template", models.CharField(blank=True, default="", max_length=255)),
                ("body_template", models.TextField(blank=True, default="")),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=True)),
                ("event_code", models.CharField(max_length=80)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("entity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notification_preferences", to="entity.entity")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["user_id", "entity_id", "event_code"]},
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=True)),
                ("object_id", models.CharField(max_length=64)),
                ("event_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField(blank=True, default="")),
                ("channel", models.CharField(choices=[("IN_APP", "In App"), ("EMAIL", "Email"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp")], default="IN_APP", max_length=20)),
                ("delivery_status", models.CharField(choices=[("PENDING", "Pending"), ("CREATED", "Created"), ("SKIPPED", "Skipped"), ("FAILED", "Failed")], default="CREATED", max_length=20)),
                ("target_url", models.CharField(blank=True, default="", max_length=255)),
                ("target_label", models.CharField(blank=True, default="", max_length=120)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="triggered_notification_events", to=settings.AUTH_USER_MODEL)),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_events", to="contenttypes.contenttype")),
                ("entity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_events", to="entity.entity")),
                ("subentity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notification_events", to="entity.subentity")),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="entity.notificationtemplate")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isactive", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("title_override", models.CharField(blank=True, default="", max_length=180)),
                ("message_override", models.TextField(blank=True, default="")),
                ("target_url_override", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_notifications", to="entity.notificationevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(fields=("user", "entity", "event_code"), name="uq_notification_pref_scope_event"),
        ),
        migrations.AddConstraint(
            model_name="usernotification",
            constraint=models.UniqueConstraint(fields=("event", "user"), name="uq_user_notification_event_user"),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(fields=["channel", "isactive"], name="ent_notif_tmpl_chan_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user", "entity", "event_code"], name="ent_notif_pref_user_evt_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["entity", "event_code", "created_at"], name="ent_notif_evt_entity_evt_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["content_type", "object_id"], name="ent_notif_evt_ct_obj_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["channel", "delivery_status", "created_at"], name="ent_notif_evt_chan_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(fields=["user", "is_read", "created_at"], name="ent_user_notif_user_read_idx"),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(fields=["event", "user"], name="ent_user_notif_event_user_idx"),
        ),
    ]
