# Generated by Django 5.2.1 on 2026-05-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0030_notificationevent_notificationpreference_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='entity_noti_entity__bd0b29_idx',
            old_name='ent_notif_evt_entity_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='entity_noti_content_42ec7e_idx',
            old_name='ent_notif_evt_ct_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='entity_noti_channel_e01b96_idx',
            old_name='ent_notif_evt_chan_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='entity_noti_user_id_0fd2af_idx',
            old_name='ent_notif_pref_user_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='entity_noti_channel_16e19d_idx',
            old_name='ent_notif_tmpl_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='entity_user_user_id_5e1c44_idx',
            old_name='ent_user_notif_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='entity_user_event_i_f03712_idx',
            old_name='ent_user_notif_event_user_idx',
        ),
    ]
