# Generated by Django 5.2.1 on 2026-06-19 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entity', '0034_entity_lookup_runtime_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['entity', 'isactive', 'workflow_key', 'status', 'updated_at'], name='ix_appr_req_entity_flow'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approval_request', 'status', 'step_order'], name='ix_appr_step_req_status'),
        ),
        migrations.AddIndex(
            model_name='entityapprovalpolicy',
            index=models.Index(fields=['entity', 'policy_key', 'status', 'subentity'], name='ix_ent_appr_pol_resolve'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['entity', 'subentity', 'created_at'], name='ix_notif_evt_scope_dt'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'event_code', 'entity'], name='ix_notif_pref_usr_evt'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'isactive', 'is_read', 'created_at'], name='ix_user_notif_active_rd'),
        ),
    ]
