# Generated by Django 5.2.1 on 2026-04-19 03:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_expiry_warning_days_and_more'),
        ('entity', '0020_remove_entity_unittype'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('bill_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HELD', 'Held'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('customer_email', models.CharField(blank=True, default='', max_length=120)),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=30)),
                ('address1', models.CharField(blank=True, default='', max_length=255)),
                ('address2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=20)),
                ('pincode', models.CharField(blank=True, default='', max_length=12)),
                ('narration', models.CharField(blank=True, default='', max_length=500)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('total_free_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('total_issue_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('gross_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('discount_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entityfinancialyear')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RetailTicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('line_source', models.CharField(choices=[('SCAN', 'Scan'), ('MANUAL', 'Manual')], default='SCAN', max_length=10)),
                ('scanned_barcode', models.CharField(blank=True, default='', max_length=50)),
                ('uom_code_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('pack_size_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('free_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('stock_issue_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('gross_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('promotion_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('promotion_code_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('gst_snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productbarcode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='retail.retailticket')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RetailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_mode', models.CharField(choices=[('invoice_per_ticket', 'Invoice Per Ticket'), ('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary'), ('manual_summary', 'Manual Summary')], default='invoice_per_ticket', max_length=30)),
                ('posting_mode', models.CharField(choices=[('real_time', 'Real Time'), ('on_close', 'On Close'), ('manual', 'Manual')], default='real_time', max_length=20)),
                ('customer_mode', models.CharField(choices=[('walk_in_only', 'Walk-In Only'), ('customer_optional', 'Customer Optional'), ('customer_required', 'Customer Required')], default='customer_optional', max_length=30)),
                ('walk_in_capture_mode', models.CharField(choices=[('none', 'None'), ('optional', 'Optional'), ('recommended', 'Recommended'), ('required_for_invoice', 'Required For Invoice')], default='optional', max_length=30)),
                ('auto_create_customer_mode', models.CharField(choices=[('never', 'Never'), ('manual_only', 'Manual Only'), ('when_mobile_present', 'When Mobile Present'), ('when_gstin_present', 'When GSTIN Present')], default='never', max_length=30)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('allow_hold_resume', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown')),
                ('default_walk_in_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_configs', to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_configs', to='entity.subentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity', 'subentity'), name='uq_retail_config_entity_subentity')],
            },
        ),
        migrations.AddIndex(
            model_name='retailticket',
            index=models.Index(fields=['entity', 'bill_date'], name='ix_retail_ticket_entity_date'),
        ),
        migrations.AddIndex(
            model_name='retailticket',
            index=models.Index(fields=['entity', 'ticket_no'], name='ix_retail_ticket_entity_no'),
        ),
        migrations.AddConstraint(
            model_name='retailticketline',
            constraint=models.UniqueConstraint(fields=('ticket', 'line_no'), name='uq_retail_ticket_line_no'),
        ),
    ]
