# Generated by Django 5.2.1 on 2026-04-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_retailticket_completed_at_retailticket_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailticket',
            name='billing_execution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('POSTED', 'Posted')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='retailticket',
            name='billing_mode_snapshot',
            field=models.CharField(choices=[('invoice_per_ticket', 'Invoice Per Ticket'), ('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary'), ('manual_summary', 'Manual Summary')], default='invoice_per_ticket', max_length=30),
        ),
        migrations.AddField(
            model_name='retailticket',
            name='billing_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='retailticket',
            name='posting_execution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('POSTED', 'Posted')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='retailticket',
            name='posting_mode_snapshot',
            field=models.CharField(choices=[('real_time', 'Real Time'), ('on_close', 'On Close'), ('manual', 'Manual')], default='real_time', max_length=20),
        ),
        migrations.AddField(
            model_name='retailticket',
            name='posting_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
