# Generated by Django 5.2.1 on 2026-04-19 05:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_remove_entity_unittype'),
        ('retail', '0004_retailsession_retailticket_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCloseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('trigger_mode', models.CharField(choices=[('SESSION_CLOSE', 'Session Close')], default='SESSION_CLOSE', max_length=20)),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('completed_ticket_count', models.PositiveIntegerField(default=0)),
                ('billing_ready_count', models.PositiveIntegerField(default=0)),
                ('billing_pending_count', models.PositiveIntegerField(default=0)),
                ('posting_ready_count', models.PositiveIntegerField(default=0)),
                ('posting_pending_count', models.PositiveIntegerField(default=0)),
                ('gross_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entity')),
                ('entityfin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.entityfinancialyear')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='close_batch', to='retail.retailsession')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.subentity')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RetailCloseBatchTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_status_snapshot', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('POSTED', 'Posted')], default='PENDING', max_length=20)),
                ('posting_status_snapshot', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('POSTED', 'Posted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='retail.retailclosebatch')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_batch_links', to='retail.retailticket')),
            ],
            options={
                'ordering': ['ticket_id'],
            },
        ),
        migrations.AddIndex(
            model_name='retailclosebatch',
            index=models.Index(fields=['entity', 'session_date'], name='ix_rtl_clsbch_ent_dt'),
        ),
        migrations.AddConstraint(
            model_name='retailclosebatchticket',
            constraint=models.UniqueConstraint(fields=('batch', 'ticket'), name='uq_retail_close_batch_ticket'),
        ),
    ]
