# Generated by Django 5.2.1 on 2026-06-19 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0034_entity_lookup_runtime_indexes'),
        ('financial', '0020_financial_master_runtime_indexes'),
        ('retail', '0006_retailticketline_snapshot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='retailclosebatch',
            index=models.Index(fields=['entity', 'subentity', 'location', 'created_at'], name='ix_rtl_clsbch_scope_ct'),
        ),
        migrations.AddIndex(
            model_name='retailsession',
            index=models.Index(fields=['entity', 'subentity', 'location', 'status', 'opened_at'], name='ix_rtl_sess_scope_stat_ot'),
        ),
        migrations.AddIndex(
            model_name='retailticket',
            index=models.Index(fields=['entity', 'subentity', 'bill_date'], name='ix_rtl_tkt_scope_dt'),
        ),
    ]
