from django.urls import path

from .views import (
    CfoBudgetLineUpsertAPIView,
    CfoBudgetVarianceReviewAPIView,
    CfoBudgetVsActualSummaryAPIView,
    CfoCashFlowAdjustmentCreateAPIView,
    CfoCashFlowAdjustmentDetailAPIView,
    CfoCashFlowForecastAPIView,
    CfoControlTowerSummaryAPIView,
    CfoEvidenceCenterAPIView,
    CfoEvidenceItemCreateAPIView,
    CfoEvidenceItemReviewAPIView,
    CfoInsightSignalReviewAPIView,
    CfoManagementPackAPIView,
    CfoManagementPackSnapshotCreateAPIView,
    CfoMonthCloseLockAPIView,
    CfoMonthCloseStatusAPIView,
    CfoMonthCloseTaskCompleteAPIView,
    CfoMonthCloseTaskReopenAPIView,
    CfoMonthCloseUnlockAPIView,
    CfoPayablesAgingAPIView,
    CfoPayablesWorklistAPIView,
    CfoPredictiveInsightsAPIView,
    CfoReceivablesAgingAPIView,
    CfoReceivablesWorklistAPIView,
    CfoRiskQueueAPIView,
    CfoRiskQueueReviewAPIView,
    CfoScenarioPlanCreateAPIView,
    CfoScenarioPlannerAPIView,
)


app_name = "cfo"

urlpatterns = [
    path("control-tower/summary/", CfoControlTowerSummaryAPIView.as_view(), name="control_tower_summary"),
    path("receivables/aging/", CfoReceivablesAgingAPIView.as_view(), name="receivables_aging"),
    path("receivables/worklist/", CfoReceivablesWorklistAPIView.as_view(), name="receivables_worklist"),
    path("payables/aging/", CfoPayablesAgingAPIView.as_view(), name="payables_aging"),
    path("payables/worklist/", CfoPayablesWorklistAPIView.as_view(), name="payables_worklist"),
    path("cash-flow/forecast/", CfoCashFlowForecastAPIView.as_view(), name="cash_flow_forecast"),
    path("cash-flow/adjustments/", CfoCashFlowAdjustmentCreateAPIView.as_view(), name="cash_flow_adjustments"),
    path("cash-flow/adjustments/<int:adjustment_id>/", CfoCashFlowAdjustmentDetailAPIView.as_view(), name="cash_flow_adjustment_detail"),
    path("budget-vs-actual/summary/", CfoBudgetVsActualSummaryAPIView.as_view(), name="budget_vs_actual_summary"),
    path("budget-vs-actual/budgets/", CfoBudgetLineUpsertAPIView.as_view(), name="budget_line_upsert"),
    path("budget-vs-actual/variances/<str:category>/review/", CfoBudgetVarianceReviewAPIView.as_view(), name="budget_variance_review"),
    path("risk-queue/", CfoRiskQueueAPIView.as_view(), name="risk_queue"),
    path("risk-queue/reviews/", CfoRiskQueueReviewAPIView.as_view(), name="risk_queue_review"),
    path("management-pack/summary/", CfoManagementPackAPIView.as_view(), name="management_pack_summary"),
    path("management-pack/snapshots/", CfoManagementPackSnapshotCreateAPIView.as_view(), name="management_pack_snapshots"),
    path("evidence-center/", CfoEvidenceCenterAPIView.as_view(), name="evidence_center"),
    path("evidence-center/items/", CfoEvidenceItemCreateAPIView.as_view(), name="evidence_items"),
    path("evidence-center/items/<int:item_id>/review/", CfoEvidenceItemReviewAPIView.as_view(), name="evidence_item_review"),
    path("insights/", CfoPredictiveInsightsAPIView.as_view(), name="predictive_insights"),
    path("insights/reviews/", CfoInsightSignalReviewAPIView.as_view(), name="insight_signal_review"),
    path("scenario-planner/", CfoScenarioPlannerAPIView.as_view(), name="scenario_planner"),
    path("scenario-planner/plans/", CfoScenarioPlanCreateAPIView.as_view(), name="scenario_plan_create"),
    path("month-close/status/", CfoMonthCloseStatusAPIView.as_view(), name="month_close_status"),
    path("month-close/tasks/<str:task_code>/mark-complete/", CfoMonthCloseTaskCompleteAPIView.as_view(), name="month_close_task_complete"),
    path("month-close/tasks/<str:task_code>/reopen/", CfoMonthCloseTaskReopenAPIView.as_view(), name="month_close_task_reopen"),
    path("month-close/lock-period/", CfoMonthCloseLockAPIView.as_view(), name="month_close_lock_period"),
    path("month-close/unlock-period/", CfoMonthCloseUnlockAPIView.as_view(), name="month_close_unlock_period"),
]
