# Generated by Django 4.2.28 on 2026-03-02 16:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityGstTdsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('250000.00'), max_digits=14)),
                ('enforce_pos_rule', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='GstTdsContractLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_ref', models.CharField(db_index=True, max_length=64)),
                ('cumulative_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cumulative_tds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entityfinid', 'vendor'], name='ix_gst_tds_ledger_vendor')],
            },
        ),
        migrations.AddConstraint(
            model_name='gsttdscontractledger',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity', 'entityfinid', 'vendor', 'contract_ref'), name='uq_gst_tds_contract_ledger'),
        ),
        migrations.AddConstraint(
            model_name='entitygsttdsconfig',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity'), name='uq_gst_tds_cfg_entity_sub'),
        ),
    ]
