# Generated by Django 5.2.1 on 2026-04-04 08:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_tds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstTdsMasterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default='GST_TDS_SEC_51', max_length=32, unique=True)),
                ('label', models.CharField(default='GST-TDS Section 51', max_length=128)),
                ('section_code', models.CharField(db_index=True, default='51', max_length=16)),
                ('total_rate', models.DecimalField(decimal_places=4, default=Decimal('2.0000'), max_digits=7)),
                ('cgst_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7)),
                ('sgst_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7)),
                ('igst_rate', models.DecimalField(decimal_places=4, default=Decimal('2.0000'), max_digits=7)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'effective_from'], name='ix_gst_tds_master_eff')],
            },
        ),
        migrations.AddField(
            model_name='entitygsttdsconfig',
            name='master_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gst_tds.gsttdsmasterrule'),
        ),
    ]
