# Generated by Django 5.2.1 on 2026-04-07 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('gst_tds', '0002_gsttdsmasterrule_entitygsttdsconfig_master_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsttdscontractledger',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account'),
        ),
    ]
