# Generated by Django 4.2.28 on 2026-02-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceShipToSnapshot',
            fields=[
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipto_snapshot', serialize=False, to='sales.salesinvoiceheader')),
                ('address1', models.CharField(blank=True, default='', max_length=255)),
                ('address2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=2)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'sales_invoice_shipto_snapshot',
            },
        ),
        migrations.RemoveField(
            model_name='salesinvoiceheader',
            name='ship_to_address1',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceheader',
            name='ship_to_address2',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceheader',
            name='ship_to_city',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceheader',
            name='ship_to_pincode',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceheader',
            name='ship_to_state_code',
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='shipping_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='financial.shippingdetails'),
        ),
    ]
