# Generated by Django 4.2.28 on 2026-02-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesinvoiceshiptosnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceshiptosnapshot',
            name='entity_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceshiptosnapshot',
            name='entityfinid_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceshiptosnapshot',
            name='subentity_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceheader',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesinvoiceheader',
            name='doc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceshiptosnapshot',
            index=models.Index(fields=['entity_id', 'entityfinid_id', 'subentity_id'], name='ix_sales_shipto_scope'),
        ),
    ]
