# Generated by Django 4.2.28 on 2026-02-27 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
        ('sales', '0003_salesinvoiceshiptosnapshot_entity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not Applicable'), (1, 'Pending'), (2, 'Generated'), (3, 'Cancelled'), (9, 'Failed')], db_index=True, default=1)),
                ('irn', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ack_no', models.CharField(blank=True, max_length=64, null=True)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('signed_invoice', models.TextField(blank=True, null=True)),
                ('signed_qr_code', models.TextField(blank=True, null=True)),
                ('ewb_no', models.CharField(blank=True, max_length=32, null=True)),
                ('ewb_date', models.DateTimeField(blank=True, null=True)),
                ('ewb_valid_upto', models.DateTimeField(blank=True, null=True)),
                ('last_request_json', models.JSONField(blank=True, null=True)),
                ('last_response_json', models.JSONField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_einvoice_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice_artifact', related_query_name='einvoice_artifact', to='sales.salesinvoiceheader')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_einvoice_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_einvoice',
            },
        ),
        migrations.CreateModel(
            name='SalesEWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not Applicable'), (1, 'Pending'), (2, 'Generated'), (3, 'Cancelled'), (9, 'Failed')], db_index=True, default=1)),
                ('ewb_no', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('ewb_date', models.DateTimeField(blank=True, null=True)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('transporter_id', models.CharField(blank=True, max_length=32, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=128, null=True)),
                ('transport_mode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=32, null=True)),
                ('vehicle_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=32, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('last_request_json', models.JSONField(blank=True, null=True)),
                ('last_response_json', models.JSONField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_eway_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eway_artifact', related_query_name='eway_artifact', to='sales.salesinvoiceheader')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_eway_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_ewaybill',
            },
        ),
        migrations.CreateModel(
            name='SalesEWayBillCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason_code', models.CharField(max_length=8)),
                ('cancel_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('portal_cancel_date', models.DateTimeField(blank=True, null=True)),
                ('last_request_json', models.JSONField(blank=True, null=True)),
                ('last_response_json', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_eway_cancel_created', to=settings.AUTH_USER_MODEL)),
                ('eway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='sales.salesewaybill')),
            ],
            options={
                'db_table': 'sales_ewaybill_cancel',
            },
        ),
        migrations.CreateModel(
            name='SalesEInvoiceCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reason_code', models.CharField(max_length=8)),
                ('cancel_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('irp_cancel_date', models.DateTimeField(blank=True, null=True)),
                ('last_request_json', models.JSONField(blank=True, null=True)),
                ('last_response_json', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_einvoice_cancel_created', to=settings.AUTH_USER_MODEL)),
                ('einvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='sales.saleseinvoice')),
            ],
            options={
                'db_table': 'sales_einvoice_cancel',
            },
        ),
        migrations.CreateModel(
            name='SalesNICCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.PositiveSmallIntegerField(choices=[(1, 'Sandbox'), (2, 'Production')], default=1)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.subentity')),
            ],
            options={
                'db_table': 'sales_nic_credential',
                'indexes': [models.Index(fields=['entity', 'subentity'], name='idx_sales_nic_scope'), models.Index(fields=['gstin'], name='idx_sales_nic_gstin'), models.Index(fields=['is_active'], name='idx_sales_nic_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='salesniccredential',
            constraint=models.UniqueConstraint(fields=('entity', 'subentity', 'environment'), name='uq_sales_nic_scope_env'),
        ),
        migrations.AddIndex(
            model_name='salesewaybillcancel',
            index=models.Index(fields=['cancelled_at'], name='idx_sales_eway_can_dt'),
        ),
        migrations.AddIndex(
            model_name='salesewaybillcancel',
            index=models.Index(fields=['eway'], name='idx_sales_eway_can_eway'),
        ),
        migrations.AddIndex(
            model_name='salesewaybill',
            index=models.Index(fields=['status'], name='idx_sales_eway_status'),
        ),
        migrations.AddIndex(
            model_name='salesewaybill',
            index=models.Index(fields=['ewb_no'], name='idx_sales_eway_no'),
        ),
        migrations.AddIndex(
            model_name='salesewaybill',
            index=models.Index(fields=['created_at'], name='idx_sales_eway_created'),
        ),
        migrations.AddConstraint(
            model_name='salesewaybill',
            constraint=models.UniqueConstraint(fields=('invoice',), name='uq_sales_eway_invoice'),
        ),
        migrations.AddIndex(
            model_name='saleseinvoicecancel',
            index=models.Index(fields=['cancelled_at'], name='idx_sales_einv_can_dt'),
        ),
        migrations.AddIndex(
            model_name='saleseinvoicecancel',
            index=models.Index(fields=['einvoice'], name='idx_sales_einv_can_einv'),
        ),
        migrations.AddIndex(
            model_name='saleseinvoice',
            index=models.Index(fields=['status'], name='idx_sales_einv_status'),
        ),
        migrations.AddIndex(
            model_name='saleseinvoice',
            index=models.Index(fields=['irn'], name='idx_sales_einv_irn'),
        ),
        migrations.AddIndex(
            model_name='saleseinvoice',
            index=models.Index(fields=['created_at'], name='idx_sales_einv_created'),
        ),
        migrations.AddConstraint(
            model_name='saleseinvoice',
            constraint=models.UniqueConstraint(fields=('invoice',), name='uq_sales_einv_invoice'),
        ),
    ]
