# Generated by Django 4.2.28 on 2026-02-27 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('sales', '0004_saleseinvoice_salesewaybill_salesewaybillcancel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMasterGSTCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.PositiveSmallIntegerField(choices=[(1, 'Sandbox'), (2, 'Production')], db_index=True, default=1)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('gst_username', models.CharField(max_length=128)),
                ('gst_password', models.CharField(max_length=256)),
                ('allow_all_ips', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'db_table': 'sales_mastergst_credential',
            },
        ),
        migrations.CreateModel(
            name='SalesMasterGSTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_auth_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_json', models.JSONField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='sales.salesmastergstcredential')),
            ],
            options={
                'db_table': 'sales_mastergst_token',
            },
        ),
        migrations.AddConstraint(
            model_name='salesmastergstcredential',
            constraint=models.UniqueConstraint(fields=('entity', 'environment'), name='uq_sales_mgst_entity_env'),
        ),
    ]
