# Generated by Django 4.2.28 on 2026-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesmastergstcredential_salesmastergsttoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmastergsttoken',
            name='gsp_client_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salesmastergsttoken',
            name='sek',
            field=models.TextField(blank=True, null=True),
        ),
    ]
