# Generated by Django 4.2.28 on 2026-02-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesmastergsttoken_gsp_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesewaybill',
            name='disp_dtls_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesewaybill',
            name='doc_type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='salesewaybill',
            name='exp_ship_dtls_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesewaybill',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
