# Generated by Django 4.2.28 on 2026-02-28 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesewaybill_disp_dtls_json_salesewaybill_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='tcs_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='tcs_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='tcs_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
