# Generated by Django 4.2.28 on 2026-02-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('withholding', '0001_initial'),
        ('sales', '0008_salesinvoiceheader_tcs_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='tcs_section',
            field=models.ForeignKey(blank=True, limit_choices_to={'tax_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_headers', to='withholding.withholdingsection'),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='withholding_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
