# Generated by Django 4.2.28 on 2026-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesinvoiceheader_tcs_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesewaybill',
            name='eway_source',
            field=models.CharField(choices=[('DIRECT', 'Direct (no IRN)'), ('IRN', 'From IRN (IRP)')], db_index=True, default='DIRECT', max_length=10),
        ),
    ]
