# Generated by Django 4.2.28 on 2026-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesewaybill_eway_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='place_of_supply_pincode',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
