# Generated by Django 4.2.28 on 2026-03-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_salesinvoiceheader_place_of_supply_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='productDesc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
