# Generated by Django 4.2.28 on 2026-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_salesinvoiceheader_place_of_supply_pincode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesmastergstcredential',
            name='uq_sales_mgst_entity_env',
        ),
        migrations.AddField(
            model_name='salesmastergstcredential',
            name='service_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'E-Invoice'), (2, 'E-Way')], db_index=True, default=1),
        ),
        migrations.AddConstraint(
            model_name='salesmastergstcredential',
            constraint=models.UniqueConstraint(fields=('entity', 'environment', 'service_scope'), name='uq_sales_mgst_entity_env_scope'),
        ),
    ]
