# Generated by Django 4.2.28 on 2026-03-02 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('sales', '0014_remove_salesmastergstcredential_uq_sales_mgst_entity_env_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmastergsttoken',
            name='eway_auth_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmastergsttoken',
            name='eway_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MasterGSTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('module', models.CharField(choices=[('EWB', 'E-Way'), ('EINV', 'E-Invoice')], db_index=True, max_length=8)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
    ]
