# Generated by Django 5.2.1 on 2026-03-04 14:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('sales', '0015_salesmastergsttoken_eway_auth_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChargeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('line_no', models.PositiveIntegerField()),
                ('charge_type', models.CharField(choices=[('FREIGHT', 'Freight'), ('PACKING', 'Packing'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('taxability', models.PositiveSmallIntegerField(choices=[(1, 'Taxable'), (2, 'Exempt'), (3, 'Nil-rated'), (4, 'Non-GST')], default=1)),
                ('is_service', models.BooleanField(default=True)),
                ('hsn_sac_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_rate_inclusive_of_tax', models.BooleanField(default=False)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='sales.salesinvoiceheader')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_charge_lines_revenue_accounts', to='financial.account')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_charge_line',
                'indexes': [models.Index(fields=['header'], name='ix_sales_charge_header'), models.Index(fields=['header', 'charge_type'], name='ix_sales_charge_hdr_type'), models.Index(fields=['header', 'taxability', 'gst_rate'], name='ix_sales_charge_hdr_tax')],
                'constraints': [models.UniqueConstraint(fields=('header', 'line_no'), name='uq_sales_charge_header_lineno'), models.CheckConstraint(check=models.Q(('taxable_value__gte', 0), ('gst_rate__gte', 0), ('gst_rate__lte', 100), ('cgst_amount__gte', 0), ('sgst_amount__gte', 0), ('igst_amount__gte', 0), ('total_value__gte', 0)), name='ck_sales_charge_nonneg'), models.CheckConstraint(check=models.Q(('gst_rate', 0), ('taxable_value', 0), models.Q(('hsn_sac_code', ''), _negated=True), _connector='OR'), name='ck_sales_charge_hsn_required_when_gst')],
            },
        ),
        migrations.CreateModel(
            name='SalesChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('base_category', models.CharField(choices=[('FREIGHT', 'Freight'), ('PACKING', 'Packing'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=True)),
                ('hsn_sac_code_default', models.CharField(blank=True, default='', max_length=20)),
                ('gst_rate_default', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_charge_types', to='entity.entity')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_charge_type_revenue_accounts', to='financial.account')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_charge_type',
                'indexes': [models.Index(fields=['entity', 'is_active'], name='ix_schtype_ent_active'), models.Index(fields=['entity', 'base_category'], name='ix_schtype_ent_cat')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'code'), name='uq_sales_charge_type_entity_code'), models.CheckConstraint(check=models.Q(('gst_rate_default__gte', 0), ('gst_rate_default__lte', 100)), name='ck_sales_charge_type_gst_rate_bounds')],
            },
        ),
    ]
