# Generated by Django 5.2.1 on 2026-03-04 16:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('sales', '0016_saleschargeline_saleschargetype'),
        ('withholding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='is_posting_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_documents', to='sales.salesinvoiceheader'),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='reverse_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='reversed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='settlement_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Partial'), (3, 'Settled')], default=1),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'original_invoice'], name='ix_sales_hdr_original'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceheader',
            index=models.Index(fields=['entity', 'entityfinid', 'subentity', 'settlement_status'], name='ix_sales_hdr_settle'),
        ),
    ]
