# Generated by Django 4.2.28 on 2026-03-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_compliance_error_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescomplianceactionlog',
            name='action_type',
            field=models.CharField(choices=[('IRN_GENERATE', 'IRN Generate'), ('IRN_FETCH', 'IRN Fetch'), ('IRN_CANCEL', 'IRN Cancel'), ('EWB_GENERATE', 'EWB Generate'), ('EWB_FETCH', 'EWB Fetch'), ('EWB_B2C_GENERATE', 'EWB B2C Generate'), ('EWB_CANCEL', 'EWB Cancel'), ('EWB_VEHICLE_UPDATE', 'EWB Vehicle Update'), ('EWB_TRANSPORTER_UPDATE', 'EWB Transporter Update'), ('EWB_EXTEND', 'EWB Validity Extend'), ('INVOICE_CANCEL_BLOCKED', 'Invoice Cancel Blocked')], db_index=True, max_length=32),
        ),
    ]
