# Generated by Django 5.2.1 on 2026-03-07 13:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_userrole_options'),
        ('financial', '0001_initial'),
        ('receipts', '0001_initial'),
        ('sales', '0021_alter_salescomplianceactionlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdvanceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('receipt_advance', 'Receipt Advance'), ('on_account', 'On Account'), ('manual', 'Manual')], db_index=True, default='receipt_advance', max_length=30)),
                ('credit_date', models.DateField(db_index=True)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding_amount', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('last_adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear')),
                ('receipt_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_advance_balance', to='receipts.receiptvoucherheader')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillOpenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.IntegerField(db_index=True)),
                ('bill_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tds_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_tds_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_receivable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding_amount', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('last_settled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear')),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ap_open_item', to='sales.salesinvoiceheader')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_type', models.CharField(choices=[('receipt', 'Receipt'), ('advance_adjustment', 'Advance Adjustment'), ('credit_note_adjustment', 'Credit Note Adjustment'), ('debit_note_adjustment', 'Debit Note Adjustment'), ('writeoff', 'Writeoff'), ('manual', 'Manual')], default='receipt', max_length=30)),
                ('settlement_date', models.DateField(db_index=True)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('external_voucher_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Posted'), (9, 'Cancelled')], db_index=True, default=1)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('advance_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='sales.customeradvancebalance')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.entityfinancialyear')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_customer_settlements', to=settings.AUTH_USER_MODEL)),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.subentity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('applied_amount_signed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('open_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='sales.customerbillopenitem')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.customersettlement')),
            ],
        ),
        migrations.AddIndex(
            model_name='customeradvancebalance',
            index=models.Index(fields=['entity', 'entityfinid', 'customer', 'is_open'], name='ix_sales_ar_adv_scope'),
        ),
        migrations.AddIndex(
            model_name='customeradvancebalance',
            index=models.Index(fields=['entity', 'entityfinid', 'credit_date'], name='ix_sales_ar_adv_creditdt'),
        ),
        migrations.AddIndex(
            model_name='customerbillopenitem',
            index=models.Index(fields=['entity', 'entityfinid', 'customer', 'is_open'], name='ix_sales_ar_open_scope'),
        ),
        migrations.AddIndex(
            model_name='customerbillopenitem',
            index=models.Index(fields=['entity', 'entityfinid', 'bill_date'], name='ix_sales_ar_open_billdt'),
        ),
        migrations.AddIndex(
            model_name='customerbillopenitem',
            index=models.Index(fields=['entity', 'entityfinid', 'due_date'], name='ix_sales_ar_open_duedt'),
        ),
        migrations.AddIndex(
            model_name='customersettlement',
            index=models.Index(fields=['entity', 'entityfinid', 'customer', 'status'], name='ix_sales_ar_settle_scope'),
        ),
        migrations.AddIndex(
            model_name='customersettlement',
            index=models.Index(fields=['entity', 'entityfinid', 'settlement_date'], name='ix_sales_ar_settle_date'),
        ),
        migrations.AddIndex(
            model_name='customersettlementline',
            index=models.Index(fields=['settlement'], name='ix_sales_stl_settle'),
        ),
        migrations.AddIndex(
            model_name='customersettlementline',
            index=models.Index(fields=['open_item'], name='ix_sales_stl_open'),
        ),
        migrations.AddConstraint(
            model_name='customersettlementline',
            constraint=models.UniqueConstraint(fields=('settlement', 'open_item'), name='uq_sales_ar_settleline_settlement_openitem'),
        ),
    ]
