# Generated by Django 4.2.28 on 2026-03-23 05:56

from django.db import migrations, models
import sales.models.sales_settings


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_salessettings_policy_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessettings',
            name='policy_controls',
            field=models.JSONField(blank=True, default=sales.models.sales_settings.default_policy_controls),
        ),
    ]
