# Generated by Django 5.2.1 on 2026-03-25 10:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0010_remove_account_address1_remove_account_address2_and_more'),
        ('sales', '0025_alter_salessettings_policy_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAdvanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voucher_date', models.DateField()),
                ('voucher_number', models.CharField(blank=True, default='', max_length=50)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('place_of_supply_state_code', models.CharField(blank=True, default='', max_length=2)),
                ('entry_type', models.CharField(choices=[('ADVANCE_RECEIPT', 'Advance Receipt'), ('ADVANCE_ADJUSTMENT', 'Advance Adjustment')], default='ADVANCE_RECEIPT', max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_amendment', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_advance_adjustments', to='financial.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_advance_adjustments', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_advance_adjustments', to='entity.entityfinancialyear')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_adjustments', to='sales.salesinvoiceheader')),
                ('original_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='sales.salesadvanceadjustment')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_advance_adjustments', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_advance_adjustment',
                'indexes': [models.Index(fields=['entity', 'entityfinid', 'subentity', 'voucher_date'], name='ix_sales_adv_scope_date'), models.Index(fields=['entity', 'entityfinid', 'is_amendment'], name='ix_sales_adv_scope_amd')],
                'constraints': [models.CheckConstraint(check=models.Q(('taxable_value__gte', 0), ('cgst_amount__gte', 0), ('sgst_amount__gte', 0), ('igst_amount__gte', 0), ('cess_amount__gte', 0)), name='ck_sales_adv_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='SalesEcommerceSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('operator_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('supplier_eco_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('supply_split', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], default='B2C', max_length=3)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_amendment', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_ecommerce_supplies', to='entity.entity')),
                ('entityfinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_ecommerce_supplies', to='entity.entityfinancialyear')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecommerce_rows', to='sales.salesinvoiceheader')),
                ('original_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='sales.salesecommercesupply')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_ecommerce_supplies', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_ecommerce_supply',
                'indexes': [models.Index(fields=['entity', 'entityfinid', 'subentity', 'operator_gstin'], name='ix_sales_eco_scope_op'), models.Index(fields=['entity', 'entityfinid', 'supplier_eco_gstin'], name='ix_sales_eco_scope_sup'), models.Index(fields=['entity', 'entityfinid', 'is_amendment'], name='ix_sales_eco_scope_amd')],
                'constraints': [models.CheckConstraint(check=models.Q(('taxable_value__gte', 0), ('cgst_amount__gte', 0), ('sgst_amount__gte', 0), ('igst_amount__gte', 0), ('cess_amount__gte', 0)), name='ck_sales_eco_nonneg')],
            },
        ),
    ]
