# Generated by Django 5.2.1 on 2026-03-25 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0010_remove_account_address1_remove_account_address2_and_more'),
        ('sales', '0026_salesadvanceadjustment_salesecommercesupply'),
        ('withholding', '0002_withholdingsection_law_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesinvoiceheader',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_no__isnull', False), ('subentity__isnull', True)), fields=('entity', 'entityfinid', 'doc_type', 'doc_code', 'doc_no'), name='uq_sales_hdr_root_docno'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceheader',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False), ('subentity__isnull', True), models.Q(('invoice_number', ''), _negated=True)), fields=('entity', 'entityfinid', 'doc_type', 'doc_code', 'invoice_number'), name='uq_sales_hdr_root_invoiceno'),
        ),
    ]
