# Generated by Django 5.2.1 on 2026-03-26 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_remove_entityconstitution_createdby_and_more'),
        ('financial', '0010_remove_account_address1_remove_account_address2_and_more'),
        ('sales', '0027_salesinvoiceheader_uq_sales_hdr_root_docno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesadvanceadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'ADVANCE_RECEIPT'), ('is_amendment', False)), fields=('entity', 'entityfinid', 'subentity', 'voucher_number', 'entry_type'), name='uq_sales_adv_receipt_active_per_voucher'),
        ),
        migrations.AddConstraint(
            model_name='salesadvanceadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'ADVANCE_ADJUSTMENT'), ('is_amendment', False), ('linked_invoice__isnull', False)), fields=('entity', 'entityfinid', 'subentity', 'voucher_number', 'entry_type', 'linked_invoice'), name='uq_sales_adv_adjust_active_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='salesadvanceadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'ADVANCE_ADJUSTMENT'), ('is_amendment', False), ('linked_invoice__isnull', True)), fields=('entity', 'entityfinid', 'subentity', 'voucher_number', 'entry_type'), name='uq_sales_adv_adjust_active_without_invoice'),
        ),
    ]
