# Generated by Django 5.2.1 on 2026-03-26 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_salesadvanceadjustment_uq_sales_adv_receipt_active_per_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='ecm_gstin',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='GSTIN must be 15 uppercase alphanumeric characters.', regex='^[0-9A-Z]{15}$')]),
        ),
    ]
