# Generated by Django 5.2.1 on 2026-03-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_catalog_pro_entity__73af6c_idx_catalog_pro_entity__dc0560_idx_and_more'),
        ('sales', '0030_salesinvoiceheader_custom_fields_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='catalog.unitofmeasure'),
        ),
    ]
