# Generated by Django 5.2.1 on 2026-04-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_godown_entity_godown_subentity_alter_godown_code_and_more'),
        ('sales', '0032_salesinvoiceheader_note_reason_and_affects_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entity.godown'),
        ),
    ]
