# Generated by Django 5.2.1 on 2026-04-13 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_expiry_warning_days_and_more'),
        ('entity', '0017_godown_is_default'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('sales', '0034_salesinvoiceheader_location_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['product', 'batch_number'], name='ix_sales_line_product_batch'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['product', 'expiry_date'], name='ix_sales_line_product_expiry'),
        ),
    ]
