# Generated by Django 5.2.1 on 2026-04-13 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_godown_is_default'),
        ('sales', '0035_salesinvoiceline_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStockPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scope_level', models.CharField(choices=[('ENTITY', 'Entity'), ('ENTITY_SUBENTITY', 'Entity + Branch'), ('ENTITY_FY', 'Entity + Financial Year'), ('ENTITY_SUBENTITY_FY', 'Entity + Branch + Financial Year')], db_index=True, max_length=32)),
                ('mode', models.CharField(choices=[('RELAXED', 'Relaxed'), ('CONTROLLED', 'Controlled'), ('STRICT', 'Strict')], db_index=True, default='RELAXED', max_length=20)),
                ('allow_negative_stock', models.BooleanField(default=True)),
                ('batch_required_for_sales', models.BooleanField(default=False)),
                ('expiry_validation_required', models.BooleanField(default=False)),
                ('fefo_required', models.BooleanField(default=False)),
                ('allow_manual_batch_override', models.BooleanField(default=True)),
                ('allow_oversell', models.BooleanField(default=False)),
                ('scope_key', models.CharField(db_index=True, editable=False, max_length=120, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_stock_policies', to='entity.entity')),
                ('entityfinid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_stock_policies', to='entity.entityfinancialyear')),
                ('subentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_stock_policies', to='entity.subentity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'scope_level'], name='ix_sales_stock_policy_scope'), models.Index(fields=['entity', 'entityfinid', 'subentity'], name='ix_sales_stock_policy_ids'), models.Index(fields=['entity', 'mode'], name='ix_sales_stock_policy_mode')],
                'constraints': [models.CheckConstraint(check=models.Q(('scope_level__isnull', False)), name='ck_sales_stock_policy_scope_level'), models.CheckConstraint(check=models.Q(('mode__isnull', False)), name='ck_sales_stock_policy_mode'), models.CheckConstraint(check=models.Q(('entity__isnull', False)), name='ck_sales_stock_policy_entity_nn')],
            },
        ),
    ]
