# Generated by Django 5.2.1 on 2026-04-23 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productbarcode_barcode_image_and_more'),
        ('entity', '0021_alter_entitygstregistration_gstin_and_more'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('sales', '0036_salesstockpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['header', 'is_service'], name='ix_sales_line_hdr_srv'),
        ),
    ]
