# Generated by Django 5.2.1 on 2026-05-14 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0024_alter_entitygstregistration_gstin_and_more'),
        ('financial', '0015_remove_account_ck_account_openingbcr_nonneg_and_more'),
        ('invoice_import', '0001_initial'),
        ('sales', '0039_salesinvoicetransportsnapshot'),
        ('withholding', '0015_tcsquarterlyreturn_restore_notes_original_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='is_legacy_imported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='legacy_behavior_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='legacy_import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_headers', to='invoice_import.importjob'),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='legacy_import_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='legacy_source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoiceheader',
            name='legacy_source_system',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceheader',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('legacy_source_system', ''), _negated=True), models.Q(('legacy_source_key', ''), _negated=True)), fields=('entity', 'legacy_source_system', 'legacy_source_key'), name='uq_sales_legacy_source_scope'),
        ),
    ]
