# Generated by Django 5.2.1 on 2026-06-24 09:12

from django.db import migrations, models


def backfill_sales_line_taxability(apps, schema_editor):
    SalesInvoiceLine = apps.get_model("sales", "SalesInvoiceLine")
    SalesInvoiceHeader = apps.get_model("sales", "SalesInvoiceHeader")

    for line in SalesInvoiceLine.objects.select_related("header").all():
        header_taxability = getattr(getattr(line, "header", None), "taxability", 1) or 1
        SalesInvoiceLine.objects.filter(pk=line.pk).update(taxability=header_taxability)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_salesattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='taxability',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Taxable'), (2, 'Exempt'), (3, 'Nil-rated'), (4, 'Non-GST')], default=1),
        ),
        migrations.RunPython(backfill_sales_line_taxability, migrations.RunPython.noop),
    ]
