from django.urls import path

from payroll.views import (
    ContractPayrollInputSnapshotListCreateAPIView,
    ContractPayrollInputSnapshotRetrieveUpdateAPIView,
    ContractPayrollProfileListCreateAPIView,
    ContractPayrollProfileRetrieveUpdateAPIView,
    ContractSalaryAssignmentListCreateAPIView,
    ContractSalaryAssignmentRetrieveUpdateAPIView,
    ContractStatutoryProfileListCreateAPIView,
    ContractStatutoryProfileRetrieveUpdateAPIView,
    ContractTaxDeclarationLineListCreateAPIView,
    ContractTaxDeclarationLineRetrieveUpdateAPIView,
    ContractTaxDeclarationApproveAPIView,
    ContractTaxDeclarationCancelAPIView,
    ContractTaxDeclarationListCreateAPIView,
    ContractTaxDeclarationRejectAPIView,
    ContractTaxDeclarationRetrieveUpdateAPIView,
    ContractTaxDeclarationSubmitAPIView,
    EntityPayrollPolicyListCreateAPIView,
    EntityPayrollPolicyRetrieveUpdateAPIView,
    EntityPayrollPolicySetDefaultAPIView,
    EntityStatutoryRegistrationListCreateAPIView,
    EntityStatutoryRegistrationRetrieveUpdateAPIView,
    GlobalPayrollComponentGroupListCreateAPIView,
    GlobalPayrollComponentGroupRetrieveUpdateAPIView,
    GlobalPayrollComponentListCreateAPIView,
    GlobalPayrollComponentRetrieveUpdateAPIView,
    GlobalSalaryTemplateAdoptAPIView,
    GlobalSalaryTemplateAdoptionPreviewAPIView,
    GlobalSalaryTemplateLineListCreateAPIView,
    GlobalSalaryTemplateLineRetrieveUpdateAPIView,
    GlobalSalaryTemplateListCreateAPIView,
    GlobalSalaryTemplateRetrieveUpdateAPIView,
    PayrollComponentListCreateAPIView,
    PayrollComponentRetrieveUpdateAPIView,
    PayrollDashboardSummaryAPIView,
    PayrollPolicyRuleListCreateAPIView,
    PayrollPolicyRuleRetrieveUpdateAPIView,
    PayrollPeriodActionAPIView,
    PayrollPeriodListCreateAPIView,
    PayrollPeriodRetrieveUpdateAPIView,
    PayrollPaymentBatchApproveAPIView,
    PayrollPaymentBatchCancelAPIView,
    PayrollPaymentBatchExportAPIView,
    PayrollPaymentBatchListCreateAPIView,
    PayrollPaymentBatchMarkFailedAPIView,
    PayrollPaymentBatchMarkPaidAPIView,
    PayrollPaymentBatchRetrieveAPIView,
    PayrollPaymentBatchValidateAPIView,
    PayrollRunPostingPreviewAPIView,
    PayrollRunPostingStatusAPIView,
    PayrollRunPostingValidateAPIView,
    PayrollPendingApprovalsAPIView,
    PayrollPendingFnFApprovalsAPIView,
    PayrollReadinessAPIView,
    PayrollReadinessDetailAPIView,
    PayrollRegisterReportAPIView,
    PayrollRegisterReportExportAPIView,
    PayrollExceptionsAPIView,
    PayrollProfileCompletenessAPIView,
    PayrollRuntimeReadinessPreviewAPIView,
    PFSummaryReportAPIView,
    PFSummaryReportExportAPIView,
    ESISummaryReportAPIView,
    ESISummaryReportExportAPIView,
    PTSummaryReportAPIView,
    PTSummaryReportExportAPIView,
    LWFSummaryReportAPIView,
    LWFSummaryReportExportAPIView,
    SalarySheetReportAPIView,
    SalarySheetReportExportAPIView,
    RecurringPayItemListCreateAPIView,
    RecurringPayItemRetrieveUpdateAPIView,
    OneTimePayItemListCreateAPIView,
    OneTimePayItemRetrieveUpdateAPIView,
    StatutoryRuleListCreateAPIView,
    StatutoryRuleRetrieveUpdateAPIView,
    StatutorySchemeListCreateAPIView,
    StatutorySchemeRetrieveUpdateAPIView,
    StatutorySlabListCreateAPIView,
    StatutorySlabRetrieveUpdateAPIView,
    PayrollRunApproveAPIView,
    PayrollRunCalculateAPIView,
    PayrollRunListCreateAPIView,
    PayrollRunPayslipAPIView,
    PayrollRunPayslipPdfAPIView,
    PayrollRunPaymentHandoffAPIView,
    PayrollRunPaymentReconcileAPIView,
    PayrollRunPostAPIView,
    PayrollRunReverseAPIView,
    PayrollRunRetrieveAPIView,
    PayrollRunComponentTraceDetailAPIView,
    PayrollRunEmployeeAttendanceTraceAPIView,
    PayrollRunEmployeeStatutoryTraceAPIView,
    PayrollRunSubmitAPIView,
    PayrollRunSummaryAPIView,
    SalaryStructureListCreateAPIView,
    SalaryStructureRetrieveUpdateAPIView,
    FnFSettlementListAPIView,
    FnFSettlementDetailAPIView,
    FnFSettlementCalculateAPIView,
    FnFSettlementRecalculateAPIView,
    FnFSettlementApproveAPIView,
    FnFSettlementPostingPreviewAPIView,
    FnFSettlementPostingStatusAPIView,
    FnFSettlementPostingValidateAPIView,
    FnFSettlementPostAPIView,
    FnFSettlementPaidAPIView,
    FnFSettlementCancelAPIView,
    FnFSettlementRegisterReportAPIView,
    FnFSettlementRegisterReportExportAPIView,
    FnFSettlementStatementPdfAPIView,
    EmployeePayslipListAPIView,
    EmployeePayslipDetailAPIView,
    EmployeePayslipPdfAPIView,
    EmployeeTaxDeclarationSummaryAPIView,
    EmployeeReimbursementPlaceholderAPIView,
    EmployeeAttendanceSummaryPlaceholderAPIView,
)

app_name = "payroll"

urlpatterns = [
    path("global/component-groups/", GlobalPayrollComponentGroupListCreateAPIView.as_view(), name="payroll-global-component-group-list-create"),
    path("global/component-groups/<uuid:pk>/", GlobalPayrollComponentGroupRetrieveUpdateAPIView.as_view(), name="payroll-global-component-group-detail"),
    path("global/components/", GlobalPayrollComponentListCreateAPIView.as_view(), name="payroll-global-component-list-create"),
    path("global/components/<uuid:pk>/", GlobalPayrollComponentRetrieveUpdateAPIView.as_view(), name="payroll-global-component-detail"),
    path("global/salary-templates/", GlobalSalaryTemplateListCreateAPIView.as_view(), name="payroll-global-template-list-create"),
    path("global/salary-templates/<uuid:pk>/", GlobalSalaryTemplateRetrieveUpdateAPIView.as_view(), name="payroll-global-template-detail"),
    path("global/salary-templates/<uuid:pk>/lines/", GlobalSalaryTemplateLineListCreateAPIView.as_view(), name="payroll-global-template-line-list-create"),
    path("global/salary-template-lines/<uuid:pk>/", GlobalSalaryTemplateLineRetrieveUpdateAPIView.as_view(), name="payroll-global-template-line-detail"),
    path("global/salary-templates/<uuid:pk>/adoption-preview/", GlobalSalaryTemplateAdoptionPreviewAPIView.as_view(), name="payroll-global-template-adoption-preview"),
    path("global/salary-templates/<uuid:pk>/adopt/", GlobalSalaryTemplateAdoptAPIView.as_view(), name="payroll-global-template-adopt"),
    path("periods/", PayrollPeriodListCreateAPIView.as_view(), name="payroll-period-list-create"),
    path("periods/<int:pk>/", PayrollPeriodRetrieveUpdateAPIView.as_view(), name="payroll-period-detail"),
    path("periods/<int:pk>/open/", PayrollPeriodActionAPIView.as_view(), {"action": "open"}, name="payroll-period-open"),
    path("periods/<int:pk>/close/", PayrollPeriodActionAPIView.as_view(), {"action": "close"}, name="payroll-period-close"),
    path("periods/<int:pk>/lock/", PayrollPeriodActionAPIView.as_view(), {"action": "lock"}, name="payroll-period-lock"),
    path("components/", PayrollComponentListCreateAPIView.as_view(), name="payroll-component-list-create"),
    path("components/<int:pk>/", PayrollComponentRetrieveUpdateAPIView.as_view(), name="payroll-component-detail"),
    path("structures/", SalaryStructureListCreateAPIView.as_view(), name="payroll-structure-list-create"),
    path("structures/<int:pk>/", SalaryStructureRetrieveUpdateAPIView.as_view(), name="payroll-structure-detail"),
    path("contract-profiles/", ContractPayrollProfileListCreateAPIView.as_view(), name="payroll-contract-profile-list-create"),
    path("contract-profiles/<uuid:pk>/", ContractPayrollProfileRetrieveUpdateAPIView.as_view(), name="payroll-contract-profile-detail"),
    path("contract-profiles/<uuid:pk>/salary-assignments/", ContractSalaryAssignmentListCreateAPIView.as_view(), name="payroll-contract-salary-assignment-list-create"),
    path("contract-salary-assignments/<uuid:pk>/", ContractSalaryAssignmentRetrieveUpdateAPIView.as_view(), name="payroll-contract-salary-assignment-detail"),
    path("contract-tax-declarations/", ContractTaxDeclarationListCreateAPIView.as_view(), name="payroll-contract-tax-declaration-list-create"),
    path("contract-tax-declarations/<uuid:pk>/", ContractTaxDeclarationRetrieveUpdateAPIView.as_view(), name="payroll-contract-tax-declaration-detail"),
    path("contract-tax-declarations/<uuid:pk>/submit/", ContractTaxDeclarationSubmitAPIView.as_view(), name="payroll-contract-tax-declaration-submit"),
    path("contract-tax-declarations/<uuid:pk>/approve/", ContractTaxDeclarationApproveAPIView.as_view(), name="payroll-contract-tax-declaration-approve"),
    path("contract-tax-declarations/<uuid:pk>/reject/", ContractTaxDeclarationRejectAPIView.as_view(), name="payroll-contract-tax-declaration-reject"),
    path("contract-tax-declarations/<uuid:pk>/cancel/", ContractTaxDeclarationCancelAPIView.as_view(), name="payroll-contract-tax-declaration-cancel"),
    path("contract-tax-declarations/<uuid:pk>/lines/", ContractTaxDeclarationLineListCreateAPIView.as_view(), name="payroll-contract-tax-declaration-line-list-create"),
    path("contract-tax-declaration-lines/<uuid:pk>/", ContractTaxDeclarationLineRetrieveUpdateAPIView.as_view(), name="payroll-contract-tax-declaration-line-detail"),
    path("contract-input-snapshots/", ContractPayrollInputSnapshotListCreateAPIView.as_view(), name="payroll-contract-input-snapshot-list-create"),
    path("contract-input-snapshots/<uuid:pk>/", ContractPayrollInputSnapshotRetrieveUpdateAPIView.as_view(), name="payroll-contract-input-snapshot-detail"),
    path("policies/", EntityPayrollPolicyListCreateAPIView.as_view(), name="payroll-policy-list-create"),
    path("policies/<uuid:pk>/", EntityPayrollPolicyRetrieveUpdateAPIView.as_view(), name="payroll-policy-detail"),
    path("policies/<uuid:pk>/set-default/", EntityPayrollPolicySetDefaultAPIView.as_view(), name="payroll-policy-set-default"),
    path("policies/<uuid:pk>/rules/", PayrollPolicyRuleListCreateAPIView.as_view(), name="payroll-policy-rule-list-create"),
    path("policy-rules/<uuid:pk>/", PayrollPolicyRuleRetrieveUpdateAPIView.as_view(), name="payroll-policy-rule-detail"),
    path("statutory/schemes/", StatutorySchemeListCreateAPIView.as_view(), name="payroll-statutory-scheme-list-create"),
    path("statutory/schemes/<uuid:pk>/", StatutorySchemeRetrieveUpdateAPIView.as_view(), name="payroll-statutory-scheme-detail"),
    path("statutory/rules/", StatutoryRuleListCreateAPIView.as_view(), name="payroll-statutory-rule-list-create"),
    path("statutory/rules/<uuid:pk>/", StatutoryRuleRetrieveUpdateAPIView.as_view(), name="payroll-statutory-rule-detail"),
    path("statutory/rules/<uuid:pk>/slabs/", StatutorySlabListCreateAPIView.as_view(), name="payroll-statutory-slab-list-create"),
    path("statutory/slabs/<uuid:pk>/", StatutorySlabRetrieveUpdateAPIView.as_view(), name="payroll-statutory-slab-detail"),
    path("statutory/registrations/", EntityStatutoryRegistrationListCreateAPIView.as_view(), name="payroll-statutory-registration-list-create"),
    path("statutory/registrations/<uuid:pk>/", EntityStatutoryRegistrationRetrieveUpdateAPIView.as_view(), name="payroll-statutory-registration-detail"),
    path("statutory/contract-profiles/", ContractStatutoryProfileListCreateAPIView.as_view(), name="payroll-statutory-contract-profile-list-create"),
    path("statutory/contract-profiles/<uuid:pk>/", ContractStatutoryProfileRetrieveUpdateAPIView.as_view(), name="payroll-statutory-contract-profile-detail"),
    path("recurring-pay-items/", RecurringPayItemListCreateAPIView.as_view(), name="payroll-recurring-pay-item-list-create"),
    path("recurring-pay-items/<uuid:pk>/", RecurringPayItemRetrieveUpdateAPIView.as_view(), name="payroll-recurring-pay-item-detail"),
    path("one-time-pay-items/", OneTimePayItemListCreateAPIView.as_view(), name="payroll-one-time-pay-item-list-create"),
    path("one-time-pay-items/<uuid:pk>/", OneTimePayItemRetrieveUpdateAPIView.as_view(), name="payroll-one-time-pay-item-detail"),
    path("dashboard/summary/", PayrollDashboardSummaryAPIView.as_view(), name="payroll-dashboard-summary"),
    path("reports/payroll-register/", PayrollRegisterReportAPIView.as_view(), name="payroll-report-payroll-register"),
    path("reports/payroll-register/export/", PayrollRegisterReportExportAPIView.as_view(), name="payroll-report-payroll-register-export"),
    path("reports/salary-sheet/", SalarySheetReportAPIView.as_view(), name="payroll-report-salary-sheet"),
    path("reports/salary-sheet/export/", SalarySheetReportExportAPIView.as_view(), name="payroll-report-salary-sheet-export"),
    path("reports/pf-summary/", PFSummaryReportAPIView.as_view(), name="payroll-report-pf-summary"),
    path("reports/pf-summary/export/", PFSummaryReportExportAPIView.as_view(), name="payroll-report-pf-summary-export"),
    path("reports/esi-summary/", ESISummaryReportAPIView.as_view(), name="payroll-report-esi-summary"),
    path("reports/esi-summary/export/", ESISummaryReportExportAPIView.as_view(), name="payroll-report-esi-summary-export"),
    path("reports/pt-summary/", PTSummaryReportAPIView.as_view(), name="payroll-report-pt-summary"),
    path("reports/pt-summary/export/", PTSummaryReportExportAPIView.as_view(), name="payroll-report-pt-summary-export"),
    path("reports/lwf-summary/", LWFSummaryReportAPIView.as_view(), name="payroll-report-lwf-summary"),
    path("reports/lwf-summary/export/", LWFSummaryReportExportAPIView.as_view(), name="payroll-report-lwf-summary-export"),
    path("reports/fnf-settlement-register/", FnFSettlementRegisterReportAPIView.as_view(), name="payroll-report-fnf-settlement-register"),
    path("reports/fnf-settlement-register/export/", FnFSettlementRegisterReportExportAPIView.as_view(), name="payroll-report-fnf-settlement-register-export"),
    path("readiness/", PayrollReadinessAPIView.as_view(), name="payroll-readiness"),
    path("runtime/readiness-preview/", PayrollRuntimeReadinessPreviewAPIView.as_view(), name="payroll-runtime-readiness-preview"),
    path("runtime/readiness-detail/", PayrollReadinessDetailAPIView.as_view(), name="payroll-runtime-readiness-detail"),
    path("workflows/pending-fnf-approvals/", PayrollPendingFnFApprovalsAPIView.as_view(), name="payroll-pending-fnf-approvals"),
    path("workflows/pending-payroll-approvals/", PayrollPendingApprovalsAPIView.as_view(), name="payroll-pending-payroll-approvals"),
    path("workflows/exceptions/", PayrollExceptionsAPIView.as_view(), name="payroll-exceptions"),
    path("workflows/profile-completeness/", PayrollProfileCompletenessAPIView.as_view(), name="payroll-profile-completeness"),
    path("fnf/", FnFSettlementListAPIView.as_view(), name="payroll-fnf-list"),
    path("fnf/calculate/", FnFSettlementCalculateAPIView.as_view(), name="payroll-fnf-calculate"),
    path("fnf/<int:pk>/", FnFSettlementDetailAPIView.as_view(), name="payroll-fnf-detail"),
    path("fnf/<int:pk>/recalculate/", FnFSettlementRecalculateAPIView.as_view(), name="payroll-fnf-recalculate"),
    path("fnf/<int:pk>/approve/", FnFSettlementApproveAPIView.as_view(), name="payroll-fnf-approve"),
    path("fnf/<int:pk>/posting-preview/", FnFSettlementPostingPreviewAPIView.as_view(), name="payroll-fnf-posting-preview"),
    path("fnf/<int:pk>/posting-validate/", FnFSettlementPostingValidateAPIView.as_view(), name="payroll-fnf-posting-validate"),
    path("fnf/<int:pk>/posting-status/", FnFSettlementPostingStatusAPIView.as_view(), name="payroll-fnf-posting-status"),
    path("fnf/<int:pk>/post/", FnFSettlementPostAPIView.as_view(), name="payroll-fnf-post"),
    path("fnf/<int:pk>/paid/", FnFSettlementPaidAPIView.as_view(), name="payroll-fnf-paid"),
    path("fnf/<int:pk>/cancel/", FnFSettlementCancelAPIView.as_view(), name="payroll-fnf-cancel"),
    path("fnf/<int:pk>/statement-pdf/", FnFSettlementStatementPdfAPIView.as_view(), name="payroll-fnf-statement-pdf"),
    path("ess/payslips/", EmployeePayslipListAPIView.as_view(), name="payroll-ess-payslip-list"),
    path("ess/payslips/<int:pk>/", EmployeePayslipDetailAPIView.as_view(), name="payroll-ess-payslip-detail"),
    path("ess/payslips/<int:pk>/pdf/", EmployeePayslipPdfAPIView.as_view(), name="payroll-ess-payslip-pdf"),
    path("ess/tax-declaration-summary/", EmployeeTaxDeclarationSummaryAPIView.as_view(), name="payroll-ess-tax-declaration-summary"),
    path("ess/reimbursements/placeholder/", EmployeeReimbursementPlaceholderAPIView.as_view(), name="payroll-ess-reimbursement-placeholder"),
    path("ess/attendance-summary/placeholder/", EmployeeAttendanceSummaryPlaceholderAPIView.as_view(), name="payroll-ess-attendance-summary-placeholder"),
    path("runs/", PayrollRunListCreateAPIView.as_view(), name="payroll-run-list-create"),
    path("runs/<int:pk>/", PayrollRunRetrieveAPIView.as_view(), name="payroll-run-detail"),
    path("runs/<int:pk>/calculate/", PayrollRunCalculateAPIView.as_view(), name="payroll-run-calculate"),
    path("runs/<int:pk>/submit/", PayrollRunSubmitAPIView.as_view(), name="payroll-run-submit"),
    path("runs/<int:pk>/approve/", PayrollRunApproveAPIView.as_view(), name="payroll-run-approve"),
    path("runs/<int:pk>/posting-preview/", PayrollRunPostingPreviewAPIView.as_view(), name="payroll-run-posting-preview"),
    path("runs/<int:pk>/posting-validate/", PayrollRunPostingValidateAPIView.as_view(), name="payroll-run-posting-validate"),
    path("runs/<int:pk>/posting-status/", PayrollRunPostingStatusAPIView.as_view(), name="payroll-run-posting-status"),
    path("runs/<int:pk>/post/", PayrollRunPostAPIView.as_view(), name="payroll-run-post"),
    path("runs/<int:pk>/reverse/", PayrollRunReverseAPIView.as_view(), name="payroll-run-reverse"),
    path("runs/<int:pk>/payment-handoff/", PayrollRunPaymentHandoffAPIView.as_view(), name="payroll-run-payment-handoff"),
    path("runs/<int:pk>/payment-reconcile/", PayrollRunPaymentReconcileAPIView.as_view(), name="payroll-run-payment-reconcile"),
    path("payment-batches/", PayrollPaymentBatchListCreateAPIView.as_view(), name="payroll-payment-batch-list-create"),
    path("payment-batches/<uuid:pk>/", PayrollPaymentBatchRetrieveAPIView.as_view(), name="payroll-payment-batch-detail"),
    path("payment-batches/<uuid:pk>/validate/", PayrollPaymentBatchValidateAPIView.as_view(), name="payroll-payment-batch-validate"),
    path("payment-batches/<uuid:pk>/approve/", PayrollPaymentBatchApproveAPIView.as_view(), name="payroll-payment-batch-approve"),
    path("payment-batches/<uuid:pk>/export/", PayrollPaymentBatchExportAPIView.as_view(), name="payroll-payment-batch-export"),
    path("payment-batches/<uuid:pk>/paid/", PayrollPaymentBatchMarkPaidAPIView.as_view(), name="payroll-payment-batch-paid"),
    path("payment-batches/<uuid:pk>/failed/", PayrollPaymentBatchMarkFailedAPIView.as_view(), name="payroll-payment-batch-failed"),
    path("payment-batches/<uuid:pk>/cancel/", PayrollPaymentBatchCancelAPIView.as_view(), name="payroll-payment-batch-cancel"),
    path("runs/<int:pk>/summary/", PayrollRunSummaryAPIView.as_view(), name="payroll-run-summary"),
    path("runs/<int:pk>/components/<int:component_id>/trace/", PayrollRunComponentTraceDetailAPIView.as_view(), name="payroll-run-component-trace"),
    path("runs/<int:pk>/employees/<int:employee_run_id>/attendance-trace/", PayrollRunEmployeeAttendanceTraceAPIView.as_view(), name="payroll-run-employee-attendance-trace"),
    path("runs/<int:pk>/employees/<int:employee_run_id>/statutory-trace/", PayrollRunEmployeeStatutoryTraceAPIView.as_view(), name="payroll-run-employee-statutory-trace"),
    path(
        "runs/<int:pk>/payslips/<int:employee_run_id>/",
        PayrollRunPayslipAPIView.as_view(),
        name="payroll-run-payslip",
    ),
    path(
        "runs/<int:pk>/payslips/<int:employee_run_id>/pdf/",
        PayrollRunPayslipPdfAPIView.as_view(),
        name="payroll-run-payslip-pdf",
    ),
]
