from django.urls import path

from payroll.views import (
    PayrollAdjustmentListCreateAPIView,
    PayrollAdjustmentRetrieveUpdateAPIView,
    PayrollComponentListCreateAPIView,
    PayrollComponentRetrieveUpdateAPIView,
    PayrollDashboardSummaryAPIView,
    PayrollPeriodActionAPIView,
    PayrollPeriodListCreateAPIView,
    PayrollPeriodRetrieveUpdateAPIView,
    PayrollProfileListCreateAPIView,
    PayrollProfileRetrieveUpdateAPIView,
    PayrollReadinessAPIView,
    PayrollRunApproveAPIView,
    PayrollRunCalculateAPIView,
    PayrollRunListCreateAPIView,
    PayrollRunPayslipAPIView,
    PayrollRunPaymentHandoffAPIView,
    PayrollRunPaymentReconcileAPIView,
    PayrollRunPostAPIView,
    PayrollRunReverseAPIView,
    PayrollRunRetrieveAPIView,
    PayrollRunSubmitAPIView,
    PayrollRunSummaryAPIView,
    SalaryStructureListCreateAPIView,
    SalaryStructureRetrieveUpdateAPIView,
)

app_name = "payroll"

urlpatterns = [
    path("periods/", PayrollPeriodListCreateAPIView.as_view(), name="payroll-period-list-create"),
    path("periods/<int:pk>/", PayrollPeriodRetrieveUpdateAPIView.as_view(), name="payroll-period-detail"),
    path("periods/<int:pk>/open/", PayrollPeriodActionAPIView.as_view(), {"action": "open"}, name="payroll-period-open"),
    path("periods/<int:pk>/close/", PayrollPeriodActionAPIView.as_view(), {"action": "close"}, name="payroll-period-close"),
    path("periods/<int:pk>/lock/", PayrollPeriodActionAPIView.as_view(), {"action": "lock"}, name="payroll-period-lock"),
    path("components/", PayrollComponentListCreateAPIView.as_view(), name="payroll-component-list-create"),
    path("components/<int:pk>/", PayrollComponentRetrieveUpdateAPIView.as_view(), name="payroll-component-detail"),
    path("structures/", SalaryStructureListCreateAPIView.as_view(), name="payroll-structure-list-create"),
    path("structures/<int:pk>/", SalaryStructureRetrieveUpdateAPIView.as_view(), name="payroll-structure-detail"),
    path("profiles/", PayrollProfileListCreateAPIView.as_view(), name="payroll-profile-list-create"),
    path("profiles/<int:pk>/", PayrollProfileRetrieveUpdateAPIView.as_view(), name="payroll-profile-detail"),
    path("adjustments/", PayrollAdjustmentListCreateAPIView.as_view(), name="payroll-adjustment-list-create"),
    path("adjustments/<int:pk>/", PayrollAdjustmentRetrieveUpdateAPIView.as_view(), name="payroll-adjustment-detail"),
    path("dashboard/summary/", PayrollDashboardSummaryAPIView.as_view(), name="payroll-dashboard-summary"),
    path("readiness/", PayrollReadinessAPIView.as_view(), name="payroll-readiness"),
    path("runs/", PayrollRunListCreateAPIView.as_view(), name="payroll-run-list-create"),
    path("runs/<int:pk>/", PayrollRunRetrieveAPIView.as_view(), name="payroll-run-detail"),
    path("runs/<int:pk>/calculate/", PayrollRunCalculateAPIView.as_view(), name="payroll-run-calculate"),
    path("runs/<int:pk>/submit/", PayrollRunSubmitAPIView.as_view(), name="payroll-run-submit"),
    path("runs/<int:pk>/approve/", PayrollRunApproveAPIView.as_view(), name="payroll-run-approve"),
    path("runs/<int:pk>/post/", PayrollRunPostAPIView.as_view(), name="payroll-run-post"),
    path("runs/<int:pk>/reverse/", PayrollRunReverseAPIView.as_view(), name="payroll-run-reverse"),
    path("runs/<int:pk>/payment-handoff/", PayrollRunPaymentHandoffAPIView.as_view(), name="payroll-run-payment-handoff"),
    path("runs/<int:pk>/payment-reconcile/", PayrollRunPaymentReconcileAPIView.as_view(), name="payroll-run-payment-reconcile"),
    path("runs/<int:pk>/summary/", PayrollRunSummaryAPIView.as_view(), name="payroll-run-summary"),
    path(
        "runs/<int:pk>/payslips/<int:employee_run_id>/",
        PayrollRunPayslipAPIView.as_view(),
        name="payroll-run-payslip",
    ),
]
